### ISSUE TITLE
util/linuxfw: TestNFTAddAndDelNetfilterBase fails on Fly CI

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#10003]
At 387a98fe2878cd2fa now, running `util/linuxfw` on the experiment Fly-based CI:

```
=== RUN   TestAddAndDeleteChains
--- PASS: TestAddAndDeleteChains (0.00s)
=== RUN   TestAddAndDeleteHooks
--- PASS: TestAddAndDeleteHooks (0.00s)
=== RUN   TestAddAndDeleteBase
--- PASS: TestAddAndDeleteBase (0.00s)
=== RUN   TestAddAndDelLoopbackRule
--- PASS: TestAddAndDelLoopbackRule (0.00s)
=== RUN   TestAddAndDelSNATRule
--- PASS: TestAddAndDelSNATRule (0.00s)
=== RUN   TestMaskof
--- PASS: TestMaskof (0.00s)
=== RUN   TestInsertHookRule
--- PASS: TestInsertHookRule (0.00s)
=== RUN   TestInsertLoopbackRule
--- PASS: TestInsertLoopbackRule (0.00s)
=== RUN   TestInsertLoopbackRuleV6
--- PASS: TestInsertLoopbackRuleV6 (0.00s)
=== RUN   TestAddReturnChromeOSVMRangeRule
--- PASS: TestAddReturnChromeOSVMRangeRule (0.00s)
=== RUN   TestAddDropCGNATRangeRule
--- PASS: TestAddDropCGNATRangeRule (0.00s)
=== RUN   TestAddSetSubnetRouteMarkRule
--- PASS: TestAddSetSubnetRouteMarkRule (0.00s)
=== RUN   TestAddDropOutgoingPacketFromCGNATRangeRuleWithTunname
--- PASS: TestAddDropOutgoingPacketFromCGNATRangeRuleWithTunname (0.00s)
=== RUN   TestAddAcceptOutgoingPacketRule
--- PASS: TestAddAcceptOutgoingPacketRule (0.00s)
=== RUN   TestAddAcceptIncomingPacketRule
--- PASS: TestAddAcceptIncomingPacketRule (0.00s)
=== RUN   TestAddMatchSubnetRouteMarkRuleMasq
--- PASS: TestAddMatchSubnetRouteMarkRuleMasq (0.00s)
=== RUN   TestAddMatchSubnetRouteMarkRuleAccept
--- PASS: TestAddMatchSubnetRouteMarkRuleAccept (0.00s)
=== RUN   TestAddAndDelNetfilterChains
    nftables_runner_test.go:532: conn.ListChainsOfTableFamily(2) failed: netlink receive: invalid argument
--- FAIL: TestAddAndDelNetfilterChains (0.02s)
=== RUN   TestNFTAddAndDelNetfilterBase
--- FAIL: TestNFTAddAndDelNetfilterBase (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x5a6caa]

goroutine 28 [running]:
testing.tRunner.func1.2({0x5e0440, 0x7c0e00})
	testing/testing.go:1545 +0x238
testing.tRunner.func1()
	testing/testing.go:1548 +0x397
panic({0x5e0440?, 0x7c0e00?})
	runtime/panic.go:914 +0x21f
tailscale.com/util/linuxfw.getChainFromTable(0x5eefa0?, 0x0, {0x61dbee, 0xa})
	tailscale.com/util/linuxfw/nftables_runner.go:389 +0x2a
tailscale.com/util/linuxfw.deleteChainIfExists(0xc0000547e0?, 0x0, {0x61dbee, 0xa})
	tailscale.com/util/linuxfw/nftables_runner.go:864 +0x34
tailscale.com/util/linuxfw.(*nftablesRunner).DelChains(0xc0000abf38)
	tailscale.com/util/linuxfw/nftables_runner.go:885 +0xbd
panic({0x5e0440?, 0x7c0e00?})
	runtime/panic.go:914 +0x21f
tailscale.com/util/linuxfw.getChainFromTable(0xc000076e78?, 0x0, {0x61d1bc, 0x8})
	tailscale.com/util/linuxfw/nftables_runner.go:389 +0x2a
tailscale.com/util/linuxfw.(*nftablesRunner).addBase4(0xc0000abf38, {0x61d1c4, 0x8})
	tailscale.com/util/linuxfw/nftables_runner.go:1316 +0x48
tailscale.com/util/linuxfw.(*nftablesRunner).AddBase(0xc0000abf38, {0x61d1c4, 0x8})
	tailscale.com/util/linuxfw/nftables_runner.go:1301 +0x26
tailscale.com/util/linuxfw.TestNFTAddAndDelNetfilterBase(0xc0000f0680)
	tailscale.com/util/linuxfw/nftables_runner_test.go:669 +0x105
testing.tRunner(0xc0000f0680, 0x647520)
	testing/testing.go:1595 +0xff
created by testing.(*T).Run in goroutine 1
	testing/testing.go:1648 +0x3ad
FAIL	tailscale.com/util/linuxfw	0.023s
```

/cc @raggi @maisem @catzkorn

**Comment by maisem** [comment]
After #10005 it fails with
```
=== RUN   TestAddAndDeleteChains
--- PASS: TestAddAndDeleteChains (0.00s)
=== RUN   TestAddAndDeleteHooks
--- PASS: TestAddAndDeleteHooks (0.00s)
=== RUN   TestAddAndDeleteBase
--- PASS: TestAddAndDeleteBase (0.00s)
=== RUN   TestAddAndDelLoopbackRule
--- PASS: TestAddAndDelLoopbackRule (0.00s)
=== RUN   TestAddAndDelSNATRule
--- PASS: TestAddAndDelSNATRule (0.00s)
=== RUN   TestMaskof
--- PASS: TestMaskof (0.00s)
=== RUN   TestInsertHookRule
--- PASS: TestInsertHookRule (0.00s)
=== RUN   TestInsertLoopbackRule
--- PASS: TestInsertLoopbackRule (0.00s)
=== RUN   TestInsertLoopbackRuleV6
--- PASS: TestInsertLoopbackRuleV6 (0.00s)
=== RUN   TestAddReturnChromeOSVMRangeRule
--- PASS: TestAddReturnChromeOSVMRangeRule (0.00s)
=== RUN   TestAddDropCGNATRangeRule
--- PASS: TestAddDropCGNATRangeRule (0.00s)
=== RUN   TestAddSetSubnetRouteMarkRule
--- PASS: TestAddSetSubnetRouteMarkRule (0.00s)
=== RUN   TestAddDropOutgoingPacketFromCGNATRangeRuleWithTunname
--- PASS: TestAddDropOutgoingPacketFromCGNATRangeRuleWithTunname (0.00s)
=== RUN   TestAddAcceptOutgoingPacketRule
--- PASS: TestAddAcceptOutgoingPacketRule (0.00s)
=== RUN   TestAddAcceptIncomingPacketRule
--- PASS: TestAddAcceptIncomingPacketRule (0.00s)
=== RUN   TestAddMatchSubnetRouteMarkRuleMasq
--- PASS: TestAddMatchSubnetRouteMarkRuleMasq (0.00s)
=== RUN   TestAddMatchSubnetRouteMarkRuleAccept
--- PASS: TestAddMatchSubnetRouteMarkRuleAccept (0.00s)
=== RUN   TestAddAndDelNetfilterChains
    nftables_runner_test.go:532: conn.ListChainsOfTableFamily(2) failed: netlink receive: invalid argument
--- FAIL: TestAddAndDelNetfilterChains (0.02s)
=== RUN   TestNFTAddAndDelNetfilterBase
    nftables_runner_test.go:670: AddChains() failed: create table: get table: get tables: netlink receive: invalid argument
--- FAIL: TestNFTAddAndDelNetfilterBase (0.00s)
=== RUN   TestNFTAddAndDelLoopbackRule
    nftables_runner_test.go:764: AddChains() failed: create table: get table: get tables: netlink receive: invalid argument
--- FAIL: TestNFTAddAndDelLoopbackRule (0.00s)
=== RUN   TestNFTAddAndDelHookRule
    nftables_runner_test.go:822: AddChains() failed: create table: get table: get tables: netlink receive: invalid argument
--- FAIL: TestNFTAddAndDelHookRule (0.00s)
=== RUN   TestCreateDummyPostroutingChains
    nftables_runner_test.go:873: createDummyPostroutingChains() failed: create nat table: get table: get tables: netlink receive: invalid argument
--- FAIL: TestCreateDummyPostroutingChains (0.00s)
=== RUN   TestPickFirewallModeFromInstalledRules
=== RUN   TestPickFirewallModeFromInstalledRules/using_iptables_legacy
    detector.go:82: nftables rule count: 0, iptables rule count: 1
    detector.go:89: iptables is currently in use
=== RUN   TestPickFirewallModeFromInstalledRules/using_nftables
    detector.go:82: nftables rule count: 1, iptables rule count: 0
    detector.go:85: nftables is currently in use
=== RUN   TestPickFirewallModeFromInstalledRules/using_both_iptables_and_nftables
    detector.go:82: nftables rule count: 2, iptables rule count: 2
    detector.go:95: nftables is available
=== RUN   TestPickFirewallModeFromInstalledRules/not_using_any_firewall,_both_available
    detector.go:82: nftables rule count: 0, iptables rule count: 0
    detector.go:95: nftables is available
=== RUN   TestPickFirewallModeFromInstalledRules/not_using_any_firewall,_iptables_available_only
    detector.go:79: detect nftables rule: nft error
    detector.go:82: nftables rule count: 0, iptables rule count: 1
    detector.go:89: iptables is currently in use
=== RUN   TestPickFirewallModeFromInstalledRules/not_using_any_firewall,_nftables_available_only
    detector.go:74: detect iptables rule: iptables error
    detector.go:82: nftables rule count: 1, iptables rule count: 0
    detector.go:85: nftables is currently in use
--- PASS: TestPickFirewallModeFromInstalledRules (0.00s)
    --- PASS: TestPickFirewallModeFromInstalledRules/using_iptables_legacy (0.00s)
    --- PASS: TestPickFirewallModeFromInstalledRules/using_nftables (0.00s)
    --- PASS: TestPickFirewallModeFromInstalledRules/using_both_iptables_and_nftables (0.00s)
    --- PASS: TestPickFirewallModeFromInstalledRules/not_using_any_firewall,_both_available (0.00s)
    --- PASS: TestPickFirewallModeFromInstalledRules/not_using_any_firewall,_iptables_available_only (0.00s)
    --- PASS: TestPickFirewallModeFromInstalledRules/not_using_any_firewall,_nftables_available_only (0.00s)
FAIL
FAIL	tailscale.com/util/linuxfw	0.030s
```
