### ISSUE TITLE
Containerboot as egress/ingress proxy always crashes once on startup

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#10398]
### What is the issue?

When an [ingress](https://tailscale.com/kb/1236/kubernetes-operator/#ingress-resource) or [egress](https://tailscale.com/kb/1236/kubernetes-operator/#cluster-egress) proxy is deployed it always crashes once on startup when it's installing DNAT rule:
```
...
2023/11/28 13:59:13 magicsock: 0 active derp conns
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x6c148a]

goroutine 1 [running]:
github.com/google/nftables.(*Conn).newRule(0xc00049e960, 0xc000427570, 0x1)
        github.com/google/nftables@v0.1.1-0.20230115205135-9aa6fdf5a28c/rule.go:123 +0x20a
github.com/google/nftables.(*Conn).InsertRule(0xc0003bd520?, 0xc000427660?)
        github.com/google/nftables@v0.1.1-0.20230115205135-9aa6fdf5a28c/rule.go:200 +0x2f
tailscale.com/util/linuxfw.(*nftablesRunner).AddDNATRule(0xc0003bd520, {{0xdd351bf834983a75?, 0x134ad6df3b7fd716?}, 0xc000118000?}, {{0xc000011c20?, 0x6f63e0?}, 0xc000118000?})
        tailscale.com/util/linuxfw/nftables_runner.go:139 +0x31f
main.installIngressForwardingRule({0xc00010e180?, 0x0?}, {0xc00001c023, 0xa}, {0xc0004f7500?, 0x2, 0x2}, {0x8065c8, 0xc0003bd520})
        tailscale.com/cmd/containerboot/main.go:822 +0x14f
main.main()
        tailscale.com/cmd/containerboot/main.go:408 +0x2157
```

Maybe because the device does not yet have a tailnet address.

### OS version

Any Kubernetes

**Comment by irbekrm** [comment]
Fixed in #10563, v1.56 and newer versions of `tailscale/tailscale` has this fix.
