### ISSUE TITLE
stun: index out of range

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#104]
```
Packet from [2604:a880:2:d1::c5:7001]:3478: "\x01\x01\x00H!\x12\xa4B\x06\xf5f\x85Ҋ\xf3\xe6\x9c\xe3A\xe2\x00\x01\x00\x14\x00\x02\x90\xce&\x02\x00Ѵ\xcf\xc1\x008\xb21\xff\xfe\xef\x96\xf6\x80+\x00\x14\x00\x02\r\x96&\x04\xa8\x80\x00\x02\x00\xd1\x00\x00\x00\x00\x00\xc5p\x01\x00 \x00\x14\x00\x02\xb1\xdc\a\x10\xa4\x93\xb2:\xa7\x85\xea8\xc2\x19b\f\xd7\x14"
panic: runtime error: index out of range [4] with length 4 
 
goroutine 12 [running]: 
tailscale.com/stun.xorMappedAddress(0xe6f38ad28566f506, 0xe241e39c, 0xc0001dc048, 0x14, 0xffb8, 0x4d46d1, 0xba7740, 0x85afc0, 0xc0002a2000, 0xc00004fd50, ...) 
        /home/bradfitz/src/tailscale.com/stun/stun.go:165 +0x27e 
tailscale.com/stun.ParseResponse(0xc0001dc000, 0x14, 0xffbc, 0xe6f38ad28566f506, 0xc0e241e39c, 0x3, 0xc00004fdd8, 0x4d46d1, 0x8, 0xc00004fd60, ...) 
        /home/bradfitz/src/tailscale.com/stun/stun.go:107 +0x462 
tailscale.com/stunner.(*Stunner).Receive(0xc000012780, 0xc0001dc000, 0x5c, 0x10000, 0xc00029e450) 
        /home/bradfitz/src/tailscale.com/stunner/stunner.go:54 +0x71 
tailscale.com/ipn.(*LocalBackend).populateNetworkConditions.func3(0xc000012780, 0x907160, 0xc0000100a0) 
        /home/bradfitz/src/tailscale.com/ipn/local.go:833 +0x1e9 
created by tailscale.com/ipn.(*LocalBackend).populateNetworkConditions 
        /home/bradfitz/src/tailscale.com/ipn/local.go:857 +0x9c3 
FAIL    tailscale.com/ipn       0.068s 
FAIL 
```

/cc @crawshaw but I can also figure this out if you're busy. I should learn STUN anyway.

**Comment by crawshaw** [comment]
Ah that's the ipv6 path. it's under-tested because I wrote that STUN code against public servers I could find, none of which returned interesting ipv6 data to me (because my ISP doesn't do it).

Probably easier for you to take this, as you have lots of ipv6.
