### ISSUE TITLE
net/nettest/pipe_test.go times out on Windows sometimes

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#1044]
Been seeing occasional failures of this test. Seemingly windows only, but there's no windows-specific code in here, so I suspect it's just that our Windows test box is loaded differently and triggers a timing based deadlock.

```
panic: test timed out after 10m0s

goroutine 25 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1618 +0xe6
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/time/sleep.go:167 +0x4b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000c0600, 0x510bda, 0xf, 0x51a410, 0x43d401)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc0000c0180)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1439 +0x7f
testing.tRunner(0xc0000c0180, 0xc0000b9de0)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1123 +0xef
testing.runTests(0xc00008a4a0, 0x5f8980, 0x3, 0x3, 0xbfefbc06b02a7288, 0x8bb3438779, 0x5fc700, 0x3be010)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1437 +0x310
testing.(*M).Run(0xc0000e8000, 0x0)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1345 +0x1f5
main.main()
	_testmain.go:47 +0x145

goroutine 20 [chan receive]:
testing.(*T).Run(0xc0000c0c00, 0x50fc76, 0xb, 0x51a400, 0x49f15ab701)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1169 +0x2da
tailscale.com/net/nettest.TestPipeTimeout(0xc0000c0600)
	D:/a/tailscale/tailscale/net/nettest/pipe_test.go:59 +0xb5
testing.tRunner(0xc0000c0600, 0x51a410)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1168 +0x2b3

goroutine 23 [chan receive]:
tailscale.com/net/nettest.(*Pipe).Write(0xc0000f21b0, 0xc00003bf37, 0x0, 0x0, 0x1, 0x0, 0x0)
	D:/a/tailscale/tailscale/net/nettest/pipe.go:122 +0x231
tailscale.com/net/nettest.TestPipeTimeout.func3(0xc0000c0c00)
	D:/a/tailscale/tailscale/net/nettest/pipe_test.go:68 +0x229
testing.tRunner(0xc0000c0c00, 0x51a400)
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.15.6/x64/src/testing/testing.go:1168 +0x2b3
FAIL	tailscale.com/net/nettest	600.053s
```

**Comment by danderson** [comment]
Focusing elsewhere for right now, but the issue seems to be that the write deadline fails to unblock Write, so the test times out while still blocked. On that basis, I'm thinking timing issues between the goroutine that writes to the wakeup channel and the main write routine, but haven't root-caused yet.

**Comment by bradfitz** [comment]
Dup of #873
