### ISSUE TITLE
SIGSEGV when using an authenticated http proxy

### ISSUE THREAD

**Issue by dvinella** [tailscale/tailscale#1047]
**Describe the bug**
Tailscale and netcheck fail with SIGSEGV with an authenticated http proxy

**To Reproduce**
1. Setup http_proxy and https_proxy in /etc/default/tailscale in "http_proxy=http://user:pass@proxy:port" form
2. Run tailscale netcheck
3. See error

```
2020/12/18 18:26:50 netcheck: probePortMapServices: me 10.0.2.15 -> gw 10.0.2.2
2020/12/18 18:26:50 netcheck: sent to 68.183.90.120:3478
2020/12/18 18:26:50 netcheck: sent to 159.89.225.99:3478
[..]
2020/12/18 18:26:51 netcheck: sent to 167.71.139.179:3478
2020/12/18 18:26:51 netcheck: sent to 103.43.75.49:3478
2020/12/18 18:26:54 netcheck: hairCheck done
2020/12/18 18:26:54 netcheck: portMap done
2020/12/18 18:26:54 netcheck: netcheck: UDP is blocked, trying HTTPS
2020/12/18 18:26:54 netcheck: derphttp: CONNECT dial to derp7.tailscale.com:443: 407 Proxy authentication required
2020/12/18 18:26:54 netcheck: netcheck: measuring HTTPS latency of tok (7): invalid response status from HTTP proxy http://user:pass@proxy:8080 on CONNECT to derp7.tailscale.com:443: 407 Proxy authentication required
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x71b47c]

goroutine 73 [running]:
tailscale.com/derp/derphttp.(*Client).dialNodeUsingProxy.func2(0xc000066a80, 0x8979c0, 0xc000062400, 0xc00002a200)
	tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:587 +0xdc
created by tailscale.com/derp/derphttp.(*Client).dialNodeUsingProxy
	tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:582 +0x3b9

```
4. Same for tailscaled daemon

**Expected behavior**
No sigsegv and a successful connection

**Version information:**
 - Device: virtual machine
 - OS: Arch linux
 - OS version: latest
 - Tailscale version:

```
1.2.10
  tailscale commit: e480f8ddf6f7334fda1b3d0dd1b500f2f01f961b
  other commit: 7b8c9553a1c6c4ceb525e9ce924d3ac5785f5ead
  go version: go1.15.4-tsf9db43b
```

**Comment by DentonGentry** [comment]
Quick browse of source around dialNode() -> c.dialNodeUsingProxy() doesn't show an obvious place where we might dereference nil.

**Comment by bradfitz** [comment]
Yeah, I spent a few minutes reading through https://github.com/tailscale/tailscale/blob/e480f8ddf6f7334fda1b3d0dd1b500f2f01f961b/derp/derphttp/derphttp_client.go again but don't see anything obviously wrong.

I haven't tried to reproduce, though.

**Comment by Xe** [comment]
I have been able to reproduce this with the following configuration:

```nix
{ config, pkgs, ... }: {
  services.squid = let
    pwFile = pkgs.writeTextFile {
      name = "htpasswd";
      # azurediamond:hunter2
      text = ''
        azurediamond:$apr1$ho3nk3Ew$oi2o/GX1RCoBmb7TV4Tto.
      '';
    };
  in {
    enable = true;
    proxyPort = squidPort;
    extraConfig = ''
      dns_nameservers 8.8.8.8

      auth_param basic program ${pkgs.squid}/libexec/basic_ncsa_auth ${pwFile}
      auth_param basic realm proxy
      acl authenticated proxy_auth REQUIRED
      http_access allow authenticated
    '';
  };

  services.tailscale.enable = true;
  systemd.services.tailscaled.serviceConfig.EnvironmentFile = pkgs.writeTextFile {
    name = "tailscale-proxy.env";
    text = ''
      http_proxy=http://azurediamond:hunter2@127.0.0.1:${toString squidPort}
      https_proxy=http://azurediamond:hunter2@127.0.0.1:${toString squidPort}
      HTTP_PROXY=http://azurediamond:hunter2@127.0.0.1:${toString squidPort}
      HTTPS_PROXY=http://azurediamond:hunter2@127.0.0.1:${toString squidPort}
    '';
  };
};
```

```
Feb 17 16:43:34 hexeta tailscaled[2936]: derphttp.Client.Connect: connecting to derp-1 (nyc)
Feb 17 16:43:34 hexeta tailscaled[2936]: Switching ipn state Starting -> Running (WantRunning=true)
Feb 17 16:43:34 hexeta tailscaled[2936]: derphttp: CONNECT dial to derp1.tailscale.com:443: 407 Proxy Authentication Required
Feb 17 16:43:34 hexeta tailscaled[2936]: derphttp: CONNECT dial to derp1b.tailscale.com:443: 407 Proxy Authentication Required
Feb 17 16:43:34 hexeta tailscaled[2936]: derphttp.Client.Recv: connecting to derp-1 (nyc)
Feb 17 16:43:34 hexeta tailscaled[2936]: derphttp: CONNECT dial to derp1.tailscale.com:443: 407 Proxy Authentication Required
Feb 17 16:43:34 hexeta tailscaled[2936]: derphttp: CONNECT dial to derp1b.tailscale.com:443: 407 Proxy Authentication Required
Feb 17 16:43:34 hexeta tailscaled[2936]: magicsock: [0xc000471980] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): invalid response status from HTTP proxy http://azurediamond:hunter2@127.0.0.1:38274 on CONNECT to derp1.tailscale.com:443: 407 Proxy Authentication Required
Feb 17 16:43:34 hexeta tailscaled[2936]: derp-1: backoff: 10 msec
Feb 17 16:43:34 hexeta tailscaled[2936]: panic: runtime error: invalid memory address or nil pointer dereference
Feb 17 16:43:34 hexeta tailscaled[2936]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8ca8dc]
Feb 17 16:43:34 hexeta tailscaled[2936]: goroutine 277 [running]:
Feb 17 16:43:34 hexeta tailscaled[2936]: tailscale.com/derp/derphttp.(*Client).dialNodeUsingProxy.func2(0xc00007bf80, 0xd3e8a0, 0xc00044e0c0, 0xc0004a4270)
Feb 17 16:43:34 hexeta tailscaled[2936]:         tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:587
+0xdc
Feb 17 16:43:34 hexeta tailscaled[2936]: created by tailscale.com/derp/derphttp.(*Client).dialNodeUsingProxy
Feb 17 16:43:34 hexeta tailscaled[2936]:         tailscale.com@v0.0.0-00010101000000-000000000000/derp/derphttp/derphttp_client.go:582
+0x3b9
Feb 17 16:43:34 hexeta systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by bradfitz** [comment]
@Xe, what tailscale version is that `derp/derphttp/derphttp_client.go:587` stack from?

**Comment by Xe** [comment]
@bradfitz it was from the latest unstable release, it seems that the NixOS packaging step I use for the tarballs strips off the information that would point to line numbers. I am going to see about disabling that if I can.

**Comment by bradfitz** [comment]
Does that mean 1.5.58? (relative references like "latest unstable release" don't age well in comments, or make things much harder to resolve later.)

1.5.58 was 11bbfbd8bb6f05e1891bf60f533dcc98b7254a77 so line 587 was:

https://github.com/tailscale/tailscale/blob/11bbfbd8bb6f05e1891bf60f533dcc98b7254a77/derp/derphttp/derphttp_client.go#L587

How can that variable ever be nil there? That's the big mystery for me.

**Comment by bradfitz** [comment]
@Xe, did you see my last question?

That's the more concerning part.

**Comment by dvinella** [comment]
I can confirm that the sigsegv is gone with the latest unstable (1.5.120) and the proxy basic auth works.
Thank you!

**Comment by DentonGentry** [comment]
There is a pending question of how the proxyConn could be nil.

**Comment by DentonGentry** [comment]
Closing during bug scrub.
