### ISSUE TITLE
Unable to setup Tailscale client: walk.NewNotifyIcon: Shell_NotifyIcon: This operation returned because the timeout perious expired.; windows: <nil>

### ISSUE THREAD

**Issue by amanjuman** [tailscale/tailscale#10545]
### What is the issue?

Having this annoying issue on Windows 11.
It works works fine If I reinstall.
![image](https://github.com/tailscale/tailscale/assets/19264857/b3a1561d-9a40-45a4-96c1-dd46e602b3dd)

### OS

Windows

### OS version

11

### Tailscale version

1.54.1

### Bug report

BUG-5db49de2d9b435a976e81d1f1754beaa8336c98d52b1fe9f7e0b9615d790dce7-20231211093654Z-094d45f08c1a584d

**Comment by eventsb** [comment]
I get the same error on Windows 10 and Tailscale 1.56.1
![Capture](https://github.com/tailscale/tailscale/assets/19614435/3eb7f905-5959-4577-9de0-ce53e726e16d)

**Comment by redactedscribe** [comment]
Same here, but with specific error (version 1.58.2). Installed Tailscale for the first time moments ago, can't run it.

```
---------------------------
Tailscale Error
---------------------------
Unable to setup Tailscale client:

walk.NewNotifyIcon: Shell_NotifyIcon

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x5e
github.com/tailscale/walk.newErr(...)
	github.com/tailscale/walk@v0.0.0-20240108184108-6a278000867c/error.go:81
github.com/tailscale/walk.newError({0xdd7847, 0x10})
	github.com/tailscale/walk@v0.0.0-20240108184108-6a278000867c/error.go:85 +0x25
github.com/tailscale/walk.(*niCmd).execute(0xc000081400)
	github.com/tailscale/walk@v0.0.0-20240108184108-6a278000867c/notifyicon.go:443 +0xf7
github.com/tailscale/walk.newShellNotificationIcon(0xc0001a2250)
	github.com/tailscale/walk@v0.0.0-20240108184108-6a278000867c/notifyicon.go:280 +0x112
github.com/tailscale/walk.newNotifyIcon(0x0?)
	github.com/tailscale/walk@v0.0.0-20240108184108-6a278000867c/notifyicon.go:496 +0x17
github.com/tailscale/walk.NewNotifyIconWithGUID({0xfbed1924, 0xf0e, 0x4ae6, {0x87, 0xd3, 0x24, 0x6d, 0xcd, 0x41, 0xee, ...}})
	github.com/tailscale/walk@v0.0.0-20240108184108-6a278000867c/notifyicon.go:492 +0x57
tailscale.io/win/ui.(*app).populateTray(0xc00014a580)
	tailscale.io/win/ui/ui.go:376 +0x65
tailscale.io/win/ui.RunUI({0xc00001ee80, 0x40})
	tailscale.io/win/ui/ui.go:1561 +0x1bd
tailscale.io/win/ui.Main()
	tailscale.io/win/ui/main.go:109 +0x8a5
main.main()
	tailscale.io/win/gui/main.go:13 +0xf
; windows: <nil>
---------------------------
OK   
---------------------------
```

Windows 11

**Comment by miquelfire** [comment]
Just got this myself on Windows 10, Tailscale 1.64.0

![image](https://github.com/tailscale/tailscale/assets/417966/0f7a5c83-d723-434e-a8fe-b00bd1eb30fc)

**Comment by aaronzgh** [comment]
> Just got this myself on Windows 10, Tailscale 1.64.0
> 
> ![image](https://private-user-images.githubusercontent.com/417966/325591180-0f7a5c83-d723-434e-a8fe-b00bd1eb30fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTYyMTIsIm5iZiI6MTcxNzg1NTkxMiwicGF0aCI6Ii80MTc5NjYvMzI1NTkxMTgwLTBmN2E1YzgzLWQ3MjMtNDM0ZS1hOGZlLWIwMGJkMWViMzBmYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNDExNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzRiNzA4NDkzZjk4ZmFhN2U4ZTdmM2I1YzVhODE0YTlmNzU4OGVlMjAwMjk4N2IyNjQwOTEwOWJhMWM1YTRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CgOwu44qnjRHgFbPIAIB9YsiVTmk8MHy6BPkgJJQHMU)

the same error with 1.66.4 installation.

**Comment by dblohm7** [comment]
I was going to dup this to another issue, but those have all been closed for various reasons. This bug has been around for a while and it's still unclear why it's happening, but we're still keeping an eye on it.

**Comment by JanickGers85** [comment]
Experiencing this issue with `1.78.1` too
Windows 11 Pro 23H2 (build: 22631.4602)
![image](https://github.com/user-attachments/assets/0079c77f-5d64-464c-a30b-7db2b0c851a1)

**Comment by dblohm7** [comment]
@JanickGers85 fixing this by running the GUI as administrator suggests to me that the failure was happening because `explorer.exe` is running as an Administrator but `tailscale-ipn.exe` was not. Can you confirm?

**Comment by JanickGers85** [comment]
@dblohm7 Not sure about that, but my user is an administrator.
Adding another detail: to make this workaround I have to kill the `tailscaled.exe` and `tailscale-ipn.exe` too, then run the guid as an administrator.
I've seen that the deamon run as a Windows service.

P.S.: I've just upgraded to to `1.80.0`, I'll keep you updated if the issue is still there.

**Comment by prenaux** [comment]
Same problem here on a Windows 10 VM, it auto updated to 1.82.5 and crashed on startup with the same NewNotifyIcon issue (https://github.com/tailscale/tailscale/issues/10545#issuecomment-2537219889).

I tried to run as Admin and uinstall/reinstall (clearing the LocalAppData folder with configs I could find), that didnt fix it.

The only fix I found is to download a full installer of 1.76.3 and install that. I used that version because that's what I installed initially so I know it works. I disabled auto-updates for now :(

**Comment by al-dubois** [comment]
Same issue here. tailscale-setup-1.84.0

![Image](https://github.com/user-attachments/assets/e16f73a3-7ffd-40dd-94b4-b02771d25296)

Windows Server 2019 1809

![Image](https://github.com/user-attachments/assets/47eecc39-876a-42ef-943d-a3e2ba47f98c)

**Comment by grichecth** [comment]
I'm also getting this issue on Windows Server 2019, the 1.76.3 Full version did not work for me. I did however discover that if I killed Explorer with Task Manager, and then ran the executable (or shortcut) for Tailscale as admin via the Task Manager it would open fine. I would then relaunch explorer via Task Manager. The tray icon does not appear after relaunching explorer, but it is running in the background.

**Comment by aivanis** [comment]
> I'm also getting this issue on Windows Server 2019, the 1.76.3 Full version did not work for me. I did however discover that if I killed Explorer with Task Manager, and then ran the executable (or shortcut) for Tailscale as admin via the Task Manager it would open fine. I would then relaunch explorer via Task Manager. The tray icon does not appear after relaunching explorer, but it is running in the background.

Killing Explorer with task manager did the trick, thank you so much.
