### ISSUE TITLE
Tailscale's context menu crashes Tailscale when ran under classic theme on Windows

### ISSUE THREAD

**Issue by Cynosphere** [tailscale/tailscale#11013]
### What is the issue?

Tailscale's context menu crashes Tailscale when ran under classic theme, most likely due to classic theme context menus being unable to render the account avatars.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xd7f5c0]

goroutine 1 [running, locked to thread]:
github.com/tailscale/walk.(*menuSharedMetrics).DPI(0x0?)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/menuownerdraw.go:139
github.com/tailscale/walk/dpicache.InstanceForDPI[...](0x0, 0x60)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/dpicache/dpicache.go:42 +0x72
github.com/tailscale/walk.(*WindowBase).menuSharedMetrics(0xc000454000)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/window.go:2377 +0x8a
github.com/tailscale/walk.(*Menu).updateItemsForWindow(0xc000450060, {0x12f2340, 0xc000454000})
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/menu.go:166 +0x198
github.com/tailscale/walk.(*Menu).onInitPopup(0xc000450060, {0x12f2340, 0xc000454000})
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/menu.go:140 +0x85
github.com/tailscale/walk.(*WindowBase).WndProc(0xc000454000, 0xc0000e0be8?, 0x117, 0xb0acd, 0x0)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/window.go:2552 +0xd4c
github.com/tailscale/walk.(*notifyIconWindow).WndProc(0xc000454000, 0xc000152a50?, 0x117, 0xc0000e0f50?, 0x0)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/notifyicon.go:71 +0x12d
github.com/tailscale/walk.defaultWndProc(0xbc8f05?, 0x0?, 0xc0000e0d38?, 0xc0000e0ca0?)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/window.go:2207 +0xa5
syscall.SyscallN(0xc000408030?, {0xc0000e1300?, 0x10?, 0x0?})
        runtime/syscall_windows.go:544 +0x107
syscall.Syscall6(0xc000152690?, 0x0?, 0x0?, 0xc0000e13a0?, 0xce43ae?, 0xc000152300?, 0x0?, 0x0?)
        runtime/syscall_windows.go:488 +0x4a
github.com/tailscale/win.TrackPopupMenuEx(0xc00041a1c0?, 0x4100, 0x8b2, 0x5e, 0xc0000e13f0?, 0xbb0229?)
        github.com/tailscale/win@v0.0.0-20230710211752-84569fd814a9/user32.go:3476 +0x87
github.com/tailscale/walk.(*NotifyIcon).wndProc(0xc00041a140, 0x294?, 0x5a00?, 0x5e08b2)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/notifyicon.go:112 +0x10c
github.com/tailscale/walk.(*notifyIconWindow).WndProc(0x1139b20?, 0xc000152a50?, 0xb0a6c?, 0xc0000e17a0?, 0x7b)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/notifyicon.go:60 +0x77
github.com/tailscale/walk.defaultWndProc(0xc0000e1578?, 0xe14e0?, 0x0?, 0xc0000e17d0?)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/window.go:2207 +0xa5
syscall.SyscallN(0x0?, {0xc0000e1b50?, 0x175cd80?, 0x1248a68?})
        runtime/syscall_windows.go:544 +0x107
syscall.Syscall6(0x0?, 0xc0000e1be8?, 0xce3395?, 0xce1d0b?, 0xc000151170?, 0x30300000780?, 0xc000121c01?, 0xc000121c40?)
        runtime/syscall_windows.go:488 +0x4a
github.com/tailscale/win.GetMessage(0x0?, 0x780?, 0x0, 0x0)
        github.com/tailscale/win@v0.0.0-20230710211752-84569fd814a9/user32.go:2669 +0x6b
github.com/tailscale/walk.(*FormBase).mainLoop(0xc000071000)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/mainloop_default.go:21 +0x8b
github.com/tailscale/walk.(*FormBase).Run(0xc000071000)
        github.com/tailscale/walk@v0.0.0-20230719224259-a3cf94ed774a/form.go:373 +0x1f5
tailscale.io/win/ui.(*app).Run(0xc000424500)
        tailscale.io/win/ui/ui.go:1530 +0xe9
tailscale.io/win/ui.RunUI({0xc000022780, 0x40})
        tailscale.io/win/ui/ui.go:1520 +0x2cf
tailscale.io/win/ui.Main()
        tailscale.io/win/ui/main.go:99 +0x805
main.main()
        tailscale.io/win/gui/main.go:13 +0xf
```

### Steps to reproduce

1. Use a classic theme enabler (e.g. [ClassicThemeTray](https://github.com/spitfirex86/ClassicThemeTray))
2. Run Tailscale
3. Try to open the context menu

### OS

Windows

### OS version

Windows 10 22H2 (19045.3996

### Tailscale version

v1.48.2-ta6bcfd691-g62c580b04

### Other software

ClassicThemeTray

### Bug report

BUG-51fe6f875c96c989797b1ec9e4f8be1de7b6d22e28521ab1799a1c1c534f51ca-20240201231833Z-43aca55eb024c13b

**Comment by bradfitz** [comment]
Talking to coworkers, it sounds like the classic theme is no longer officially supported in Windows. In terms of prioritization, supporting this configuration that Microsoft itself no longer supports is thus probably pretty low on our list.
