### ISSUE TITLE
ipnlocal: panic due to missing health.Tracker when migrating prefs

### ISSUE THREAD

**Issue by andrew-d** [tailscale/tailscale#11986]
Observed here: https://github.com/tailscale/tailscale/actions/runs/8940541217/job/24558866819?pr=11985
```
## WARNING: (non-fatal) nil health.Tracker (being strict in CI):
goroutine 25 [running]:
tailscale.com/health.(*Tracker).nil(0x0)
	tailscale.com/health/health.go:185 +0x79
tailscale.com/health.(*Tracker).SetCheckForUpdates(0x0, 0x1)
	tailscale.com/health/health.go:571 +0x33
tailscale.com/ipn/ipnlocal.(*profileManager).updateHealth(...)
	tailscale.com/ipn/ipnlocal/profiles.go:450
tailscale.com/ipn/ipnlocal.(*profileManager).NewProfile(0x9e54060)
	tailscale.com/ipn/ipnlocal/profiles.go:459 +0x82
tailscale.com/ipn/ipnlocal.(*profileManager).migrateFromLegacyPrefs(0x9e54060)
	tailscale.com/ipn/ipnlocal/profiles.go:592 +0x50
tailscale.com/ipn/ipnlocal.newProfileManagerWithGOOS({0x8d59f88, 0x9e54030}, 0x9dbd1a0, {0x9c44223, 0x5})
	tailscale.com/ipn/ipnlocal/profiles.go:580 +0x1c9
tailscale.com/ipn/ipnlocal.NewLocalBackend(0x9dbd1a0, {0xb3, 0xfa, 0x9, 0x58, 0xa6, 0x77, 0x17, 0x4, 0x7a, ...}, ...)
	tailscale.com/ipn/ipnlocal/local.go:367 +0x154
main.getLocalBackend({0x8d5dec0, 0x9e54210}, 0x9dbd1a0, {0xb3, 0xfa, 0x9, 0x58, 0xa6, 0x77, 0x17, ...}, ...)
	tailscale.com/cmd/tailscaled
```

**Comment by andrew-d** [comment]
cc @bradfitz
