### ISSUE TITLE
Install produces errors and wont start up at all

### ISSUE THREAD

**Issue by paulsybrandy** [tailscale/tailscale#12472]
I did go through the FAQ and Troubleshooting pages and sections but alas I could not find any information that can help me. I also sent an email to support and thus far have not hear back. So I am hoping someone can tell me what all these errors are that popped up or let me know what other information you need. I have attached a screenshot of the errors but will also paste the text of the error below as well as my PC information. If other info is needed please let me know. Thanks.

## PC Info
**OS**: Windows 11 (Pro) x86_64
**Kernel**: 10.0.22635.3720 (23H2)
**Display (LG FULL HD)**: 1920x1080 @ 60Hz [External] *
**Display (S39C)**: 1920x1080 @ 60Hz [External]
**CPU**: AMD Ryzen 7 5800H (16) @ 4.45 GHz
**GPU**: AMD Radeon(TM) Graphics (2.98 GiB) [Discrete]
**Memory**: 28.92 GiB
**Swap**: 26.00 GiB

### _(screenshot attached)_
```
Unable to setup Tailscale client:
walk.NewNotifylcon: Shell_Notifylcon
Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack
runtime/debug/stack.go:24 +0x5e
github.com/tailscale/walk.newErr(...)
github.com/tailscale/walk@v0.0.0-20240411225155-0fe267360
a54/error.go:81
github.com/tailscale/walk.newError({0x1144dcc, 0x10}}
github.com/tailscale/walk@v0.0.0-20240411225155-0fe267360
a54/error.go:85 +0x25
github.com/tailscale/walk.(*niCmd).execute(0xc0001b7630)
github.com/tailscale/walk@v0.0.0-20240411225155-0fe267360
a54/notifyicon.go:445 +0xf7
github.com/tailscale/walk.(*niCmd).execute(0xc00026a408)
github.com/tailscale/walk@v0.0.0-20240411225155-0fe267360
a54/notifyicon.go:462 +0xd0
github.com/tailscale/walk.newShell Notificationlcon (0xc000120
280)
github.com/tailscale/walk@v0.0.0-20240411225155-0fe267360
a54/notifyicon.go:282 +0x113
github.com/tailscale/walk.newNotifylcon(0x0?)
github.com/tailscale/walk@v0.0.0-20240411225155-0fe267360
a54/notifyicon.go:498 +0x17
github.com/tailscale/walk.NewNotifylconWithGUID({0xfbed19
24, Oxf0e, Ox4ae6, {0x87, 0xd3, 0x24, 0x6d, Oxcd, Ox41, Oxee, ...}}}
github.com/tailscale/walk@v0.0.0-20240411225155-0fe267360
a54/notifyicon.go:494 +0x57
tailscale.io/win/ui.(*app).populate Tray(0xc00012a708)
tailscale.io/win/ui/ui.go:358 +0x65
tailscale.io/win/ui.runUl({0xc00010a280, 0x40})
tailscale.io/win/ui/ui.go:1574 +0x1fd
tailscale.io/win/ui.RunUI (0xc00010a280?, 0xc00010a240?})
tailscale.io/win/ui.Main
tailscale.io/win/ui/ui.go:1533 +0x18
tailscale.io/win/ui/main.go:92 +0x82a
main.main(
tailscale.io/win/gui/main.go:13 +0xf
; windows: <nil>

```

![tailscale-ipn_glWKA2TDRc](https://github.com/tailscale/tailscale/assets/83975391/3b5915bc-d8e9-446c-80b0-d3bc56d21abf)

Need anymore info? Just ask! Thanks.

**Comment by dblohm7** [comment]
While this is not the first time we've seen errors out of `Shell_NotifyIcon`, this one is interesting:

When adding a new icon, we need to call `Shell_NotifyIcon` twice; the first time to add the icon, and the second time to inform the system that we want to use a newer revision of the API contract. In this case, it failed during the _second_ call! The first call succeeded, but the second one did not!

**Comment by dblohm7** [comment]
But also: I think we should try to make the installer more robust to stupid GUI errors like this. Failing to auto-start the GUI is not a fatal installation error.

**Comment by paulsybrandy** [comment]
So, is there anything I can about it, to make it successful?

**Comment by dblohm7** [comment]
@paulsybrandy I'm putting together some changes for logging some additional diagnostic information in a future unstable build. I'll let you know when it's ready so that you can try installing that and letting us know what additional information is shown.

**Comment by paulsybrandy** [comment]
Sounds good. I will patiently await further info. Thanks. 



 

 
 

 


Paul Sybrandy

Technophile                          *+1 (570) 335-0105*

**Comment by dblohm7** [comment]
OK @paulsybrandy, please to go https://pkgs.tailscale.com/unstable/#windows and download the same type of package that you're using right now (if you're using MSI, please download an MSI, if you're using the .exe, please download that).

I expect this version to fail as well, but the error message will include additional information. If you could please post that output to this issue, it would be really helpful! Thanks!

**Comment by paulsybrandy** [comment]
Okay @dblohm7, installed and failed as anticipated. I have attached a screenshot of the error (which is considerably larger than earlier) so hopefully it provides the info you are looking for. Let me know.


![tailscale-ipn_vYSC2jF5Jb](https://github.com/tailscale/tailscale/assets/83975391/16652966-d340-4078-98a0-4080a676531e)

**Comment by paulsybrandy** [comment]
Any update on what is going on with my system or internally by chance?
