### ISSUE TITLE
derp/derphttp: TestBreakWatcherConn test flake

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#12706]
### What is the issue?

[`TestBreakWatcherConn` DERP test](https://github.com/tailscale/tailscale/blob/v1.68.2/derp/derphttp/derphttp_test.go#L268) flaked on an unrelated PR
https://github.com/tailscale/tailscale/actions/runs/9797960947/job/27055581527?pr=12274#step:8:307

```
=== RUN   TestBreakWatcherConn
    derphttp_client.go:419: RunWatchConnectionLoop: connecting to http://127.0.0.1:41955
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    derphttp_client.go:419: derphttp.Client.ForwardPacket: connecting to http://127.0.0.1:41955
    mesh_client.go:67: reconnected; clearing 1 forwarding mappings
    derphttp_test.go:380: remove: [jqHy6]
    derphttp_test.go:373: add: [jqHy6]
    mesh_client.go:79: connected; 0 peers
panic: test timed out after 10m0s
running tests:
	TestBreakWatcherConn (10m0s)

goroutine 270 [running]:
testing.(*M).startAlarm.func1()
	testing/testing.go:2366 +0x265
created by time.goFunc
	time/sleep.go:177 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc000132820, {0xadaed4, 0x14}, 0xb0efe0)
	testing/testing.go:1750 +0x851
testing.runTests.func1(0xc000132820)
	testing/testing.go:2161 +0x86
testing.tRunner(0xc000132820, 0xc00011bb10)
	testing/testing.go:1689 +0x21f
testing.runTests(0xc0000121c8, {0xe77920, 0x7, 0x7}, {0xc00011bbb8?, 0xc00011bc00?, 0xe7fc00?})
	testing/testing.go:2159 +0x8bf
testing.(*M).Run(0xc00010b220)
	testing/testing.go:2027 +0xf18
main.main()
	_testmain.go:59 +0x2be

goroutine 139 [semacquire]:
sync.runtime_Semacquire(0xc0002af028?)
	runtime/sema.go:62 +0x25
sync.(*WaitGroup).Wait(0xc0002af020)
	sync/waitgroup.go:116 +0xa5
tailscale.com/derp/derphttp.TestBreakWatcherConn(0xc000133380)
	tailscale.com/derp/derphttp/derphttp_test.go:407 +0x9ef
testing.tRunner(0xc000133380, 0xb0efe0)
	testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 1
	testing/testing.go:1742 +0x826

goroutine 8 [IO wait]:
internal/poll.runtime_pollWait(0x7fc[307](https://github.com/tailscale/tailscale/actions/runs/9797960947/job/27055581527?pr=12274#step:8:308)b73820, 0x72)
	runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00010b9c0, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00010b9a0)
	internal/poll/fd_unix.go:611 +0x507
net.(*netFD).accept(0xc00010b9a0)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000046720)
	net/tcpsock_posix.go:159 +0x3e
net.(*TCPListener).Accept(0xc000046720)
	net/tcpsock.go:327 +0x65
net/http.(*Server).Serve(0xc0001560f0, {0xba4c00, 0xc000046720})
	net/http/server.go:3260 +0x672
tailscale.com/derp/derphttp.TestSendRecv.func1()
	tailscale.com/derp/derphttp/derphttp_test.go:53 +0x4b
created by tailscale.com/derp/derphttp.TestSendRecv in goroutine 6
	tailscale.com/derp/derphttp/derphttp_test.go:52 +0x7af

goroutine 141 [IO wait]:
internal/poll.runtime_pollWait(0x7fc307b73538, 0x72)
	runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00026cde0, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00026cdc0)
	internal/poll/fd_unix.go:611 +0x507
net.(*netFD).accept(0xc00026cdc0)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0001948e0)
	net/tcpsock_posix.go:159 +0x3e
net.(*TCPListener).Accept(0xc0001948e0)
	net/tcpsock.go:327 +0x65
net/http.(*Server).Serve(0xc0001564b0, {0xba4c00, 0xc0001948e0})
	net/http/server.go:3260 +0x672
tailscale.com/derp/derphttp.newTestServer.func1()
	tailscale.com/derp/derphttp/derphttp_test.go:230 +0x59
created by tailscale.com/derp/derphttp.newTestServer in goroutine 139
	tailscale.com/derp/derphttp/derphttp_test.go:229 +0x439

goroutine 71 [IO wait]:
internal/poll.runtime_pollWait(0x7fc307b73630, 0x72)
	runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc0000acc00, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0000acbe0)
	internal/poll/fd_unix.go:611 +0x507
net.(*netFD).accept(0xc0000acbe0)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0000470a0)
	net/tcpsock_posix.go:159 +0x3e
net.(*TCPListener).Accept(0xc0000470a0)
	net/tcpsock.go:327 +0x65
net/http.(*Server).Serve(0xc0001563c0, {0xba4c00, 0xc0000470a0})
	net/http/server.go:3260 +0x672
tailscale.com/derp/derphttp.newTestServer.func1()
	tailscale.com/derp/derphttp/derphttp_test.go:230 +0x59
created by tailscale.com/derp/derphttp.newTestServer in goroutine 67
	tailscale.com/derp/derphttp/derphttp_test.go:229 +0x439

goroutine 31 [IO wait]:
internal/poll.runtime_pollWait(0x7fc307b7[325](https://github.com/tailscale/tailscale/actions/runs/9797960947/job/27055581527?pr=12274#step:8:326)0, 0x72)
	runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00010bec0, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00010bea0)
	internal/poll/fd_unix.go:611 +0x507
net.(*netFD).accept(0xc00010bea0)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000046bc0)
	net/tcpsock_posix.go:159 +0x3e
net.(*TCPListener).Accept(0xc000046bc0)
	net/tcpsock.go:327 +0x65
net/http.(*Server).Serve(0xc0001561e0, {0xba4c00, 0xc000046bc0})
	net/http/server.go:[326](https://github.com/tailscale/tailscale/actions/runs/9797960947/job/27055581527?pr=12274#step:8:327)0 +0x672
tailscale.com/derp/derphttp.TestPing.func1()
	tailscale.com/derp/derphttp/derphttp_test.go:181 +0x4b
created by tailscale.com/derp/derphttp.TestPing in goroutine 29
	tailscale.com/derp/derphttp/derphttp_test.go:180 +0x545

goroutine 69 [IO wait]:
internal/poll.runtime_pollWait(0x7fc307b73348, 0x72)
	runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00026c2a0, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00026c280)
	internal/poll/fd_unix.go:611 +0x507
net.(*netFD).accept(0xc00026c280)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc000294260)
	net/tcpsock_posix.go:159 +0x3e
net.(*TCPListener).Accept(0xc000294260)
	net/tcpsock.go:[327](https://github.com/tailscale/tailscale/actions/runs/9797960947/job/27055581527?pr=12274#step:8:328) +0x65
net/http.(*Server).Serve(0xc0001562d0, {0xba4c00, 0xc000294260})
	net/http/server.go:3260 +0x672
tailscale.com/derp/derphttp.newTestServer.func1()
	tailscale.com/derp/derphttp/derphttp_test.go:230 +0x59
created by tailscale.com/derp/derphttp.newTestServer in goroutine 67
	tailscale.com/derp/derphttp/derphttp_test.go:229 +0x439

goroutine 143 [IO wait]:
internal/poll.runtime_pollWait(0x7fc307b73440, 0x72)
	runtime/netpoll.go:345 +0x85
internal/poll.(*pollDesc).wait(0xc00018c700, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00018c6e0)
	internal/poll/fd_unix.go:611 +0x507
net.(*netFD).accept(0xc00018c6e0)
	net/fd_unix.go:172 +0x45
net.(*TCPListener).accept(0xc0000b0680)
	net/tcpsock_posix.go:159 +0x3e
net.(*TCPListener).Accept(0xc0000b0680)
	net/tcpsock.go:327 +0x65
net/http.(*Server).Serve(0xc0001565a0, {0xba4c00, 0xc0000b0680})
	net/http/server.go:3260 +0x672
tailscale.com/derp/derphttp.newTestServer.func1()
	tailscale.com/derp/derphttp/derphttp_test.go:230 +0x59
created by tailscale.com/derp/derphttp.newTestServer in goroutine 139
	tailscale.com/derp/derphttp/derphttp_test.go:229 +0x439

goroutine 144 [chan receive]:
tailscale.com/derp/derphttp.TestBreakWatcherConn.func2.1({{{0x8e, 0xa1, 0xf2, 0xea, 0xc6, 0xd3, 0xa1, 0x3b, 0x24, 0x2a, ...}}, ...})
	tailscale.com/derp/derphttp/derphttp_test.go:378 +0x151
tailscale.com/derp/derphttp.(*Client).RunWatchConnectionLoop(0xc00014f180, {0xba5530, 0xc0000ed2c0}, {{0x8e, 0xa1, 0xf2, 0xea, 0xc6, 0xd3, 0xa1, ...}}, ...)
	tailscale.com/derp/derphttp/mesh_client.go:149 +0xca7
tailscale.com/derp/derphttp.TestBreakWatcherConn.func2()
	tailscale.com/derp/derphttp/derphttp_test.go:382 +0x[345](https://github.com/tailscale/tailscale/actions/runs/9797960947/job/27055581527?pr=12274#step:8:346)
created by tailscale.com/derp/derphttp.TestBreakWatcherConn in goroutine 139
	tailscale.com/derp/derphttp/derphttp_test.go:369 +0x66c
FAIL	tailscale.com/derp/derphttp
```

**Comment by hiSandog** [comment]
The repeated add/remove sequence suggests the test is observing reconnect churn rather than waiting on a single well-defined transition. Replacing timing assumptions with a channel/barrier that confirms the watcher has installed its forwarding mapping before the connection is broken would make the intended order deterministic. A bounded failure path that dumps the watcher state would also make future flakes diagnosable instead of leaving only the reconnect log.
