### ISSUE TITLE
Tailscale now panics in containers

### ISSUE THREAD

**Issue by irbekrm** [tailscale/tailscale#12968]
### What is the issue?

Since https://github.com/tailscale/tailscale/pull/12888, containerboot now panics:

```
...
$ k logs ts-kuard1-dbqbm-0 -n tailscale 
Defaulted container "tailscale" out of: tailscale, sysctler (init)
boot: 2024/07/30 11:55:11 skipping file "..data" in tailscaled config directory "/etc/tsconfig": input does not match format
boot: 2024/07/30 11:55:11 Using tailscaled config file '_' for capability version 'g'
boot: 2024/07/30 11:55:11 Starting tailscaled
boot: 2024/07/30 11:55:11 Waiting for tailscaled socket
2024/07/30 11:55:11 logtail started
2024/07/30 11:55:11 Program starting: v1.71.38-t1b6496132, Go 1.22.5: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=kube:ts-kuard1-dbqbm-0", "--statedir=/tmp", "--config=/etc/tsconfig/cap-95.hujson"}
2024/07/30 11:55:11 LogID: 160e3e0ce627cce547182ba0363234065969b3f3a73978a7226289c46e40e5ee
2024/07/30 11:55:11 logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
2024/07/30 11:55:11 dns: [rc=unknown ret=direct]
2024/07/30 11:55:11 dns: using "direct" mode
2024/07/30 11:55:11 flushing log.
2024/07/30 11:55:11 logger closing down
panic: nil health

goroutine 1 [running]:
tailscale.com/net/dns/resolver.New(0x803540?, {0x0?, 0x0?}, 0xc00025dc60?, 0xc00025dcc8?, 0xad170e?)
        tailscale.com/net/dns/resolver/tsdns.go:235 +0x24a
tailscale.com/net/dns.NewManager(0xc00003e190, {0x1321240, 0xc0000c4180}, 0x0, 0xc0000ca000, {0x0, 0x0}, 0x0, {0x113502a, 0x5})
        tailscale.com/net/dns/manager.go:85 +0x13f
tailscale.com/net/dns.CleanUp(0xc00003e190, 0xc00017ca80, {0x11391cc?, 0x64?})
        tailscale.com/net/dns/manager.go:549 +0x154
main.run()
        tailscale.com/cmd/tailscaled/tailscaled.go:397 +0x4d3
main.main()
        tailscale.com/cmd/tailscaled/tailscaled.go:240 +0x92f
...
```

### Steps to reproduce

1. Build a local tailscale container image

`REPO=local.io/tailscale PLATFORM=local TAGS="v0.0.1panic" make publishdevimage`

2. Run it and observe panic:
```
docker run -it local.io/tailscale:v0.0.1panic
boot: 2024/07/30 12:32:59 Starting tailscaled
boot: 2024/07/30 12:32:59 Waiting for tailscaled socket
logtail started
Program starting: v1.71.38-t1b6496132, Go 1.22.5: []string{"tailscaled", "--socket=/tmp/tailscaled.sock", "--state=mem:", "--statedir=/tmp", "--tun=userspace-networking"}
LogID: 4705b0112fddb9cd7c117af707467dc720ed913df64d33ab40a0bba3b0f151d5
logpolicy: using system state directory "/var/lib/tailscale"
logpolicy.ConfigFromFile /var/lib/tailscale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
logpolicy.Config.Validate for /var/lib/tailscale/tailscaled.log.conf: config is nil
dns: [rc=unknown ret=direct]
dns: using "direct" mode
flushing log.
logger closing down
panic: nil health
...
```
cc @barnstar 

(long term, we should add a CI test that builds and runs container images)

**Comment by KTamas** [comment]
Whew. I was trying to set up `tailscaled` on macOS and tearing my hair out with the same issue
