### ISSUE TITLE
net/dns: panic in github.com/illarion/gonotify/v2 file watcher

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#13359]
I saw this panic in a natlab test run:

```
panic: runtime error: slice bounds out of range [:1735355411] with capacity 32768

goroutine 15 [running]:
github.com/illarion/gonotify/v2.(*Inotify).ReadDeadline(0xc0001cc680, {0xc1ab1c3737733670?, 0xa3e3c171?, 0x1afd240?})
	/Users/bradfitz/go/pkg/mod/github.com/illarion/gonotify/v2@v2.0.2/inotify.go:242 +0x7d9
github.com/illarion/gonotify/v2.(*Inotify).Read(0xc0001cc680)
	/Users/bradfitz/go/pkg/mod/github.com/illarion/gonotify/v2@v2.0.2/inotify.go:171 +0x39
tailscale.com/net/dns.(*directManager).runFileWatcher(0xc0001b3600)
	/Users/bradfitz/src/tailscale.com/net/dns/direct_linux.go:37 +0x1c5
created by tailscale.com/net/dns.newDirectManagerOnFS in goroutine 1
	/Users/bradfitz/src/tailscale.com/net/dns/direct.go:158 +0x10f
```

@illarion's 0cb7eb9b758cf995a40604614d333dad9f56615c updated to using `illarion/gonotify/v2` so this might be a regression. I haven't read the diff from v1.0.1 to v2.0.2.

**Comment by illarion** [comment]
This part of code was not changed since 2018, so this bug is potentially present in all versions. It looks like for some reason syscall.Read have returned corrupted buffer, instead of real inotify events, giant offset (1735355411) hints that. I will investigate and get back to you later.

**Comment by bradfitz** [comment]
Thanks!

**Comment by illarion** [comment]
I was able to reproduce the issue under pressure - lot of events with long file names. Fixed in the v2.0.3, please review and check if it panics in natlab. Thank you!

**Comment by bradfitz** [comment]
(To save others some clicks, the change was: https://github.com/illarion/gonotify/commit/31f003af64019ba62568fbf8fc406390e2826a24)
