### ISSUE TITLE
wireguard-go/tun: NativeTun.Close isn't idempotent

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1363]
Can't double-close NativeTun:

```
panic: close of closed channel

goroutine 1 [running]:
github.com/tailscale/wireguard-go/tun.(*NativeTun).Close(0xc000212080, 0xd50e80, 0xc000212080)
        /home/bradfitz/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20210210202228-3cc76ed5f222/tun/tun_linux.go:376 +0xce
tailscale.com/wgengine.NewUserspaceEngine(0xc89e60, 0xc58bac, 0xa, 0x7ffd49db0000, 0x5, 0x5007f765471c1f8, 0xc000167d50, 0xfdedc17f3c1e4d)
        /home/bradfitz/src/tailscale.com/wgengine/userspace.go:199 +0x32a
main.run(0x0, 0x0)
        /home/bradfitz/src/tailscale.com/cmd/tailscaled/tailscaled.go:201 +0x865
main.main()
        /home/bradfitz/src/tailscale.com/cmd/tailscaled/tailscaled.go:144 +0x4e5
```

/cc @josharian

**Comment by bradfitz** [comment]
sent https://git.zx2c4.com/wireguard-go/commit/?h=bf/tun_close/for-jason&id=4704acd7091f2bd02bcb78109cfa038ad61a3c47

**Comment by bradfitz** [comment]
That wireguard-go patch is upstream but I found other problems in wgengine where the various error paths aren't consistent about when/when they close things.
