### ISSUE TITLE
netcheck: panic in makeProbePlanInitial

### ISSUE THREAD

**Issue by andrew-d** [tailscale/tailscale#13728]
```
goroutine 129 [running]:
tailscale.com/net/netcheck.makeProbePlanInitial(0xc00033e948, 0xc000306050)
tailscale.com@v1.60.1/net/netcheck/netcheck.go:481 +0x2b0
tailscale.com/net/netcheck.makeProbePlan(0xc000074000?, 0xc0000301e0?, 0x1197118?)
tailscale.com@v1.60.1/net/netcheck/netcheck.go:396 +0x12d
tailscale.com/net/netcheck.(*Client).GetReport(0xc000095220, {0x1197188, 0xc0000f0070}, 0xc00033e948, 0xc000506000)
tailscale.com@v1.60.1/net/netcheck/netcheck.go:896 +0xb0d
tailscale.com/wgengine/magicsock.(*Conn).updateNetInfo(0xc00040c008, {0x1197118, 0xc0000fa6e0})
tailscale.com@v1.60.1/wgengine/magicsock/magicsock.go:635 +0x18a
tailscale.com/wgengine/magicsock.(*Conn).determineEndpoints(0xc00040c008, {0x1197118, 0xc0000fa6e0})
tailscale.com@v1.60.1/wgengine/magicsock/magicsock.go:836 +0x7e
tailscale.com/wgengine/magicsock.(*Conn).updateEndpoints(0xc00040c008, {0xff8e5c, 0xf})
tailscale.com@v1.60.1/wgengine/magicsock/magicsock.go:552 +0x229
created by tailscale.com/wgengine/magicsock.(*Conn).ReSTUN in goroutine 232
tailscale.com@v1.60.1/wgengine/magicsock/magicsock.go:2314 +0x3d9
```

**Comment by bradfitz** [comment]
Not clear what else remains here, so closing.
