### ISSUE TITLE
Android intent not reliable

### ISSUE THREAD

**Issue by maxhac03** [tailscale/tailscale#14148]
### What is the issue?

Using MacroDroid to automatically execute `com.tailscale.ipn.CONNECT_VPN` when disconnecting from some WiFi networks.
Since around 1 month Tailscale is not executing the intent command (Since 1.74 ?)

Sometimes it simply do nothing and sometimes get this notification:
![Screenshot_20241112-160706](https://github.com/user-attachments/assets/913e6b22-943e-4964-a222-4ebbc390125a)

Before, the phone could be locked and Tailscale would connect without any interactions.

With the bug report provided, the app simply did nothing after MacroDroid used the intent.

### Steps to reproduce

Programming MacroDroid to use an intent to connect Tailscale when disconnecting from specifics Wifi networks.
Tailscale does not start.

### OS

Android

### OS version

Pixel 8 Pro with Android 15 (AP3A.241105.007)

### Tailscale version

1.76.6

### Bug report

BUG-9758175d83a79bc497d8c5ca6de0544a5841b3a7c0464452b674d9c93d7f0d8e-20241119002026Z-23de8a64a154745f

**Comment by mkaltner** [comment]
Instead of relying on intents, I think there should be an option to auto connect/disconnect when connected to a configured wifi SSID.  I don't need Tailscale to be connected when I'm home and I'm currently using tasker to do exactly this.

Side request, auto start the app when the phone reboots...

**Comment by maxhac03** [comment]
I reinstalled 1.72.0 yesterday after posting this and it worked perfectly as intended since.

> Instead of relying on intents, I think there should be an option to auto connect/disconnect when connected to a configured wifi SSID. I don't need Tailscale to be connected when I'm home and I'm currently using tasker to do exactly this.

Exact same opinion and situation. Using Tailscale to keep my phone connected remotely when out of the home as i do have a few things in my homelab. Love the seamless transitions compared to OpenVPN.

**Comment by maxhac03** [comment]
Can confirm that 1.78.0 still has the issue.

**Comment by timtailscale** [comment]
Additional report from a user who wrote into support whose comment is not showing up here properly:

> Having a similar issue with the same use case and intent methodology, just sent via Tasker instead of Macrodroid. Intents sent to _dis_connect usually work, but connections are incredibly unreliable. Both tailscale and tasker have been allowed all relevant background usage / unrestricted battery / exclude from optimisation permissions.
> 
> Currently on 1.78.3 and a Pixel 7 Pro.
> 
> Behaviour Scenarios
> 
> When tailscale has been recently opened and I immediately switch over to tasker to send the intent (leaving tailscale open as a background app) it works as expected.
> 
> When tailscale is left open as a background app and the intent is sent a while later (i.e. returned to home screen without making any special effort to "close" tailscale), it becomes unreliable, but is usually fine up to ~10 mins or so after leaving the app.
> 
> At some duration of not opening tailscale between ~10mins and "overnight", it stops working again. It never works after being left overnight, and almost always works up to ~10 mins as above. Between those times, I've had mixed and inconsistent results. I haven't been able to establish any obvious discernable pattern of time/dozing/charging/phone usage/phone idle etc., but nor have I spent the time rigorously and systematically searching for one.
> 
> The only thing I have established for certain is that if a conscious effort is made to "close" tailscale, (either through "force stop" or "swiping" away the app from the app switcher) tailscale will immediately cease responding to intents. It won't respond again until the app has been re-opened / foregrounded.
> 
> Out of curiousity, I also tried sending intents through methods other than tasker, and have observed the same behaviour regardless of how the intent is sent. The presence/absence of tailscales "Not connected" notification also seems to have no obvious impact on outcome.
> 
> My assumption is that it's something to do with either how tailscale handles notifications/intents when not an active foregrounded (or recently foregrounded) app.
> 
> In case it helps, included link to the tailscale bug report. The process to generate this bug report was:
> 
> Open tailscale
> Swipe up to access the multitasking app menu, and swipe tailscale closed.
> Open to tasker.
> Send intent (no response from tailscale)
> Open tailscale, immediately copy the bug report ID.
> 
> BUG-36527c4785633c4b8cf2f698222bb5baf84ca2985e34f2488d4ab138510ec752-20250103171643Z-dc41055a8dd181b1

**Comment by maxhac03** [comment]
Any updates on this? Second time the intents got broken since the feature has been released. 
Would like to try the new 1.82.x branch but still no APK or updates on the Play Store.

**Comment by maxhac03** [comment]
@kelivel Any updates in this?

**Comment by arjenanker** [comment]
Still seeing this same behaviour too. As a workaround I've got tasker open Tailscale, wait 2 seconds and then connect. Works but is annoying cause it's supposed to work seamlessly in the background and having Tailscale pop up while I've just opened my navigation or something is just a nuisance.

**Comment by maxhac03** [comment]
Considering at this point to cancel my subscription and stay on the free tier as i was initially using this to keep my phone connected to reach my home lab but not keeping Tailscale active 24/7.  It is an official feature (It has been announced in the change logs) and they keep ignoring the issue. They add new features instead of fixing the existing ones.

@kelivel
@timtailscale

**Comment by bakoff44** [comment]
It's still an issue today. 
Is this abandoned as the tag need-triage is now removed ?

**Comment by mattcd216** [comment]
Using this intent with Automate app (f-droid). The **disconnect** flow seems to work ok. The **connect** consistently does nothing.

**Comment by yochaigal** [comment]
> Using this intent with Automate app (f-droid). The **disconnect** flow seems to work ok. The **connect** consistently does nothing.

I have the same issue (but using Macrodroid). I can only get a consistent disconnect/connect flow if I the intent is triggered by the hidden tailscale notification.

**Comment by mattcd216** [comment]
> > Using this intent with Automate app (f-droid). The **disconnect** flow seems to work ok. The **connect** consistently does nothing.
> 
> I have the same issue (but using Macrodroid). I can only get a consistent disconnect/connect flow if I the intent is triggered by the hidden tailscale notification.

Have you got to a good place with macrodroid? Mind sharing the config?

**Comment by yochaigal** [comment]
> > > Using this intent with Automate app (f-droid). The **disconnect** flow seems to work ok. The **connect** consistently does nothing.
> > 
> > 
> > I have the same issue (but using Macrodroid). I can only get a consistent disconnect/connect flow if I the intent is triggered by the hidden tailscale notification.
> 
> Have you got to a good place with macrodroid? Mind sharing the config?

Yep, here is a write-up:
https://www.reddit.com/r/Tailscale/comments/1nad8qg/tailscale_android_macrodroid_howto/

Note: if you swipe away the notification, it won't auto-connect/disconnect. This happens to me a lot.

**Comment by lmagyar** [comment]
Me and my wife have identical phones, identical app versions, and I've spent hours checking that all the settings are identical.

On my phone `com.tailscale.ipn.CONNECT_VPN` works flawlessly from Automate, on my wife's phone only when the screen is unlocked. It's a joke...

UPDATE: I went through the settings again, Tailscale's battery optimizations somehow got reenabled, so went through again on https://dontkillmyapp.com/ (disable batt. optimization for both Automate and Tailscale again) and it works again.

**Comment by yochaigal** [comment]
> Me and my wife have identical phones, identical app versions, and I've spent hours checking that all the settings are identical.
> 
> On my phone `com.tailscale.ipn.CONNECT_VPN` works flawlessly from Automate, on my wife's phone only when the screen is unlocked. It's a joke...
> 
> UPDATE: I went through the settings again, Tailscale's battery optimizations somehow got reenabled, so went through again on https://dontkillmyapp.com/ (disable batt. optimization for both Automate and Tailscale again) and it works again.

I had the same issue, even with the battery optimization turned off. I suppose I can try again....

**Comment by arjenanker** [comment]
I don't know what's going on but not only is this issue still not resolved (I don't think there's even been any comment on it?) it's gotten so much worse for me.

I have a 2 tasked automations that run when I disconnect from or connect to my home network. The disconnect automation works fine. The connect one though.... I "fixed" the issue by just opening tailscale first, waiting a few seconds and then running the intent. Means tailscale pops up whenever I leave the house which is annoying as hell, but at least my traffic is automatically routed through my home connection whenever I'm away. 

But now.... Now most of them time tailscale opens and I get a log in button. That does nothing. I have to force close and re-open the app (after which I'm logged in as you'd expect). 

I use tailscale for 2 reasons, to access my home network and to protect my traffic when I'm not at home. Tailscale has become completely unreliable for that. Now I *have* to get my phone out of my pocket and check every single time I leave the house which completely defeats the purpose of automation. In fact, it now takes way longer cause the whole force closing is just a chore. 

I'm going to have to find a replacement for tailscale because this just doesn't work and clearly tailscale has no interest in fixing this.

Edit: I just found out what's somehow causing the unresponsive login screen. As soon as my tailscale gets disconnected by the intent, I'm "not logged in". Next time I disconnect from my home network, it won't work. So now BOTH intents are failing on me.

**Comment by steviator** [comment]
What a shame that tailscale can't be trusted, their service is very convenient.

As this is a serious security issue, I will be removing tailscale from all my devices and advising my employer to end all commercial dealings with tailscale immediately. Would recommend all users tell their employers to switch providers immediately to a service that doesn't ignore their users requests to not have data funneled through remote servers.

**Comment by maxhac03** [comment]
I've been using again the intents for a while with Macrodroid and it seems to be stable again.

That said, the Tailscale dev team is slow and doesn't seem to care at all.
I opened a support request on November 26th and only got a reply on December 8th.

Their response:

> For this issue, I can at least confirm our team is aware of this behavior not working as intended. Beyond that however, I can’t currently provide an ETA on when a fix for this will be implemented. I’ll be more than happy to reiterate to our team that this is causing frustration, but where this falls within our Android team’s roadmap will ultimately be up to their current priorities.
> 
> If/when we do make any progress on this, we will share updates in that Github issue accordingly. If there are any more questions I can help answer for now, please let me know.

That's after this issue has been open for a **year**.

I cancelled my paid subscription. Didn't need the extra features as i only wanted to support the project and connect to my home to reach my homelab.

They keep adding new features, they don't fix the bugs and the service is getting more unstable. They did post on their blog that growing is not easy (https://tailscale.com/blog/hypergrowth-isnt-always-easy) so i guess they think they get a free pass?

My feedback to Tailscale: Fix the bugs THEN add new features.

**Comment by lmagyar** [comment]
> But now.... Now most of them time tailscale opens and I get a log in button. That does nothing. I have to force close and re-open the app (after which I'm logged in as you'd expect).

Exact same experience.
1.92.3
Android 9

Broadcast CONNECT_VPN works, then a few seconds later not. Manually bring up the app, there is a Login button, that doesn't work, force stop, then everything works. But god knows how long it works.

TS is just another project that adds new features until it become totally disfunctional.

**Comment by kari-ts** [comment]
I made some changes that should hopefully improve this experience. I'd really appreciate it if you could try out our new unstable [here](https://pkgs.tailscale.com/unstable/#android) and let us know if you are still experiencing the issue. Thanks!

**Comment by autumntulloch** [comment]
Just tried this unstable version.

I only very occasionally had the issue with the app getting stuck before logging in. It hasn't happened since i've tried this version but that's not unusual for me.

I've seen no increase of the reliability of the intent, my tasker script still requires an app launch, a 3 second wait with the UI open and then sending the intent. Any sooner and I get the connection failed notification.

**Comment by wabolabs** [comment]
I think I found a deterministic root cause for the "intent sometimes does nothing" behavior
here: the `IPNReceiver` broadcast handlers can crash the `com.tailscale.ipn` process, so
the requested action (connect / disconnect / use-exit-node) never completes and looks like
a no-op.

Each of the automation intents enqueues a WorkManager job marked
`.setExpedited(OutOfQuotaPolicy.RUN_AS_NON_EXPEDITED_WORK_REQUEST)`, but none of the workers
override `getForegroundInfo()` / `getForegroundInfoAsync()`. When WorkManager invokes the
foreground-info path for these expedited requests, the default implementation throws
`IllegalStateException: Not implemented`, which is uncaught and kills the process. Android
then restarts the process specifically to re-run the pending job, which crashes again — a
crash-loop until the "has crashed too many times: killing!" backoff stops it.

Observed on an Android 14 (API 34) device, Tailscale 1.98.8,
`androidx.work:work-runtime:2.9.1`, from `USE_EXIT_NODE` (`UseExitNodeWorker`, a
`CoroutineWorker`):

```
FATAL EXCEPTION: DefaultDispatcher-worker-N
Process: com.tailscale.ipn
java.lang.IllegalStateException: Not implemented
    at androidx.work.CoroutineWorker.getForegroundInfo$suspendImpl(CoroutineWorker.kt:100)
    at androidx.work.CoroutineWorker.getForegroundInfo(Unknown Source:0)
    at androidx.work.CoroutineWorker$getForegroundInfoAsync$1.invokeSuspend(CoroutineWorker.kt:134)
```

All four workers enqueued by `IPNReceiver` use `setExpedited` and none override
`getForegroundInfo()`:

| Intent | Worker | Base class | Reachable in release? |
|---|---|---|---|
| `com.tailscale.ipn.CONNECT_VPN` | `StartVPNWorker` | `Worker` | yes (exported) |
| `com.tailscale.ipn.DISCONNECT_VPN` | `StopVPNWorker` | `Worker` | yes (exported) |
| `com.tailscale.ipn.USE_EXIT_NODE` | `UseExitNodeWorker` | `CoroutineWorker` | yes (exported) |
| `com.tailscale.ipn.integration.LOGIN` | `IntegrationLoginWorker` | `CoroutineWorker` | `BuildConfig.DEBUG` only |

The `setExpedited(...)` calls were added in `tailscale/tailscale-android#736` (which cited
"Updates #14148") and are still on `main`. That timing lines up with the "since ~1.74 the
intent stopped working reliably" report here.

Repro:

```
adb shell am broadcast -a com.tailscale.ipn.CONNECT_VPN    -n com.tailscale.ipn/.IPNReceiver
adb shell am broadcast -a com.tailscale.ipn.DISCONNECT_VPN -n com.tailscale.ipn/.IPNReceiver
```

Triggering these repeatedly reproduces the crash + auto-restart loop in `logcat`.
(I haven't pinned down the precise WorkManager condition that invokes the foreground-info
path on API 31+ — quota exhaustion vs. an OEM variance vs. other — the stack trace is the
observed proximate cause.) This may also explain the more generic reports in #14031.

Two fix directions, with a real trade-off:

1. **Implement `getForegroundInfo()` on the workers** — keeps `setExpedited` (preserves
   #736's intent of not delaying/losing backgrounded tasks) and fixes the crash per the
   WorkManager contract. Needs care around `targetSdk 35` foreground-service-type rules
   when a job is actually promoted to a foreground service.
2. **Drop `setExpedited`** from these enqueues — simpler, but reintroduces the
   delay/loss of backgrounded tasks that #736 set out to fix.

One more wrinkle either way: stale expedited work persisted in WorkManager's job DB
survives in-place app updates and can replay/crash on the next cold start before any new
intent arrives, so a one-time cancel of the affected unique-work names on startup is worth
including.

Happy to send a PR in whichever direction you'd prefer.

**Comment by kari-ts** [comment]
Thanks @wabolabs ! I've merged a similar PR implementing `getForegroundInfo`. This is in the latest unstable, which can be found at https://pkgs.tailscale.com/unstable/. If you're able to test this out, please report back if this resolves your issue. Thanks!
