### ISSUE TITLE
Windows 11 Client - Connectivity Issues to Control Plane

### ISSUE THREAD

**Issue by jimmybrancaccio** [tailscale/tailscale#14161]
### What is the issue?

This issue was generated from a customer support ticket (TSS-48066).

When attempting to login to a tailnet nothing seems to happen. While a bug report may be generated it's not able to be sent to Tailscale for review. When running the command `tailscale debug ts2021` the following output is given:

```console
Fetching keys from https://controlplane.tailscale.com/key?v=106 ...
panic: netns.NewDialer called with nil netMon

        runtime/debug.Stack()
                runtime/debug/stack.go:26 +0x5e
        tailscale.com/util/singleflight.newPanicError({0xfac7a0, 0x11b7b70})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:49 +0x25
        tailscale.com/util/singleflight.(*Group[...]).doCall.func2.1()
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:290 +0x34
        panic({0xfac7a0?, 0x11b7b70?})
                runtime/panic.go:785 +0x132
        tailscale.com/net/netns.NewDialer(...)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/netns/netns.go:75
        tailscale.com/net/dnsfallback.bootstrapDNSMap({0x11bf500?, 0xc00032a150?}, {0xc000324318?, 0x1?}, {{0x0?, 0x0?}, {0xc0001943a8?}}, {0xc000144dc0?, 0x0?}, 0xc000166410, ...)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnsfallback/dnsfallback.go:282 +0x645
        tailscale.com/net/dnsfallback.lookup({0x11bf500, 0xc00032a0e0}, {0xc000144dc0, 0x1a}, 0xc000166410, 0x0, 0x0)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnsfallback/dnsfallback.go:260 +0x93d
        tailscale.com/net/dnsfallback.(*fallbackResolver).Lookup(0xc00015ab10, {0x11bf500, 0xc00032a0e0}, {0xc000144dc0, 0x1a})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnsfallback/dnsfallback.go:84 +0x48c
        tailscale.com/net/dnscache.(*Resolver).lookupIP(0xc000154cb0, {0x11bf490, 0xc000178550}, {0xc000144dc0, 0x1a})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnscache/dnscache.go:301 +0x434
        tailscale.com/net/dnscache.(*Resolver).LookupIP.func1({0x11bf490?, 0xc000178550?})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnscache/dnscache.go:217 +0x5f
        tailscale.com/util/singleflight.(*Group[...]).DoChanContext.func1()
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:195 +0x49
        tailscale.com/util/singleflight.(*Group[...]).doCall.func2(0xc000168140, 0x0, 0x0?)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:295 +0x6e
        tailscale.com/util/singleflight.(*Group[...]).doCall(0xc000160300?, 0x0?, {0xc000144dc0?, 0x0?}, 0x0?)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:297 +0xa5
        created by tailscale.com/util/singleflight.(*Group[...]).DoChanContext in goroutine 44
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:194 +0x45f


goroutine 52 [running]:
tailscale.com/util/singleflight.(*Group[...]).doCall.func1.gowrap2()
        tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:264 +0x25
created by tailscale.com/util/singleflight.(*Group[...]).doCall.func1 in goroutine 45
        tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:264 +0x2d3
panic: netns.NewDialer called with nil netMon

        runtime/debug.Stack()
                runtime/debug/stack.go:26 +0x5e
        tailscale.com/util/singleflight.newPanicError({0xfac7a0, 0x11b7b70})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:49 +0x25
        tailscale.com/util/singleflight.(*Group[...]).doCall.func2.1()
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:290 +0x34
        panic({0xfac7a0?, 0x11b7b70?})
                runtime/panic.go:785 +0x132
        tailscale.com/net/netns.NewDialer(...)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/netns/netns.go:75
        tailscale.com/net/dnsfallback.bootstrapDNSMap({0x11bf500?, 0xc0000880e0?}, {0xc000022258?, 0x1e3572eaba8?}, {{0xc00002c150?, 0xaac89c?}, {0xc0001943a8?}}, {0xc000144860?, 0xc00026d7f8?}, 0xc000166070, ...)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnsfallback/dnsfallback.go:282 +0x645
        tailscale.com/net/dnsfallback.lookup({0x11bf500, 0xc000088070}, {0xc000144860, 0x1a}, 0xc000166070, 0x0, 0x0)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnsfallback/dnsfallback.go:260 +0x93d
        tailscale.com/net/dnsfallback.(*fallbackResolver).Lookup(0xc00015a390, {0x11bf500, 0xc000088070}, {0xc000144860, 0x1a})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnsfallback/dnsfallback.go:84 +0x48c
        tailscale.com/net/dnscache.(*Resolver).lookupIP(0xc0001544d0, {0x11bf490, 0xc000178230}, {0xc000144860, 0x1a})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnscache/dnscache.go:301 +0x434
        tailscale.com/net/dnscache.(*Resolver).LookupIP.func1({0x11bf490?, 0xc000178230?})
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/net/dnscache/dnscache.go:217 +0x5f
        tailscale.com/util/singleflight.(*Group[...]).DoChanContext.func1()
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:195 +0x49
        tailscale.com/util/singleflight.(*Group[...]).doCall.func2(0xc0001680a0, 0xc000144460, 0x1e?)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:295 +0x6e
        tailscale.com/util/singleflight.(*Group[...]).doCall(0xc00026dfd0?, 0xa1329b?, {0xc000144860?, 0x1e?}, 0x0?)
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:297 +0xa5
        created by tailscale.com/util/singleflight.(*Group[...]).DoChanContext in goroutine 37
                tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:194 +0x45f


goroutine 8 [running]:
tailscale.com/util/singleflight.(*Group[...]).doCall.func1.gowrap2()
        tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:264 +0x25
created by tailscale.com/util/singleflight.(*Group[...]).doCall.func1 in goroutine 38
        tailscale.com@v1.76.4-0.20241104200736-1edcf9d466ce/util/singleflight/singleflight.go:264 +0x2d3
```

### Steps to reproduce

1. Install Tailscale 1.76.6 on Windows 11.
2. Attempt to login to your tailnet.
3. Observe nothing happens.
4. Open the Command Prompt application.
5. Run the command - `tailscale debug ts2021`.
6. Observe the panic and stack trace.

### Are there any recent changes that introduced the issue?

N/A, it does not seem like this device has ever been able to connect to a tailnet.

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.76.6

**Comment by croakerbcts** [comment]
Hi @jimmybrancaccio , could you let us know if you're still seeing this issue in the latest version of Tailscale?
