### ISSUE TITLE
macOS panic in ParseRIB

### ISSUE THREAD

**Issue by raggi** [tailscale/tailscale#14201]
```
2024-11-22T19:46:58Z	panic: runtime error: slice bounds out of range [8:0]
2024-11-22T19:46:58Z	
2024-11-22T19:46:58Z	goroutine 75 [running]:
2024-11-22T19:46:58Z	golang.org/x/net/route.parseInetAddr(0x14000582dc8?, {0x1400024e090, 0x14000f38480?, 0x788})
2024-11-22T19:46:58Z	golang.org/x/net@v0.30.0/route/address.go:203 +0x280
2024-11-22T19:46:58Z	golang.org/x/net/route.parseAddrs(0x15, 0x1033fb958, {0x1400024e074, 0x34, 0x7a4})
2024-11-22T19:46:58Z	golang.org/x/net@v0.30.0/route/address.go:408 +0xd8
2024-11-22T19:46:58Z	golang.org/x/net/route.(*wireFormat).parseRouteMessage(0x1400012a018, 0x140003f8008?, {0x1400024e018, 0x90, 0x800})
2024-11-22T19:46:58Z	golang.org/x/net@v0.30.0/route/route_classic.go:70 +0x2b8
2024-11-22T19:46:58Z	golang.org/x/net/route.ParseRIB(0x1, {0x1400024e018?, 0x14000f38380?, 0x140001105b0?})
2024-11-22T19:46:58Z	golang.org/x/net@v0.30.0/route/message.go:55 +0x194
2024-11-22T19:46:58Z	tailscale.com/net/netmon.(*darwinRouteMon).Receive(0x1400024e008)
2024-11-22T19:46:58Z	tailscale.com@v1.77.0-pre.0.20241121205641-e3c6ca43d3e3/net/netmon/netmon_darwin.go:59 +0x60
2024-11-22T19:46:58Z	tailscale.com/net/netmon.(*Monitor).pump(0x140001821c0)
2024-11-22T19:46:58Z	tailscale.com@v1.77.0-pre.0.20241121205641-e3c6ca43d3e3/net/netmon/netmon.go:346 +0x78
2024-11-22T19:46:58Z	created by tailscale.com/net/netmon.(*Monitor).Start in goroutine 17
2024-11-22T19:46:58Z	tailscale.com@v1.77.0-pre.0.20241121205641-e3c6ca43d3e3/net/netmon/netmon.go:265 +0x1b8
```

x/net bug: https://github.com/golang/go/issues/70528

**Comment by raggi** [comment]
A new case has been observed:

```
2025-02-03T08:09:41Z	panic: runtime error: slice bounds out of range [8:2]
2025-02-03T08:09:41Z	
2025-02-03T08:09:41Z	goroutine 93 [running]:
2025-02-03T08:09:41Z	golang.org/x/net/route.parseInetAddr(0x14000428dc8?, {0x140002e3290, 0x14000d0e700?, 0x788})
2025-02-03T08:09:41Z	golang.org/x/net@v0.34.0/route/address.go:203 +0x290
2025-02-03T08:09:41Z	golang.org/x/net/route.parseAddrs(0x15, 0x103810768, {0x140002e3274, 0x34, 0x7a4})
2025-02-03T08:09:41Z	golang.org/x/net@v0.34.0/route/address.go:411 +0xfc
2025-02-03T08:09:41Z	golang.org/x/net/route.(*wireFormat).parseRouteMessage(0x1400000e030, 0x14000100008?, {0x140002e3218, 0x90, 0x800})
2025-02-03T08:09:41Z	golang.org/x/net@v0.34.0/route/route_classic.go:70 +0x2b8
2025-02-03T08:09:41Z	golang.org/x/net/route.ParseRIB(0x1, {0x140002e3218?, 0x14000d0e600?, 0x800?})
2025-02-03T08:09:41Z	golang.org/x/net@v0.34.0/route/message.go:55 +0x194
2025-02-03T08:09:41Z	tailscale.com/net/netmon.(*darwinRouteMon).Receive(0x140002e3208)
2025-02-03T08:09:41Z	tailscale.com@v1.80.0/net/netmon/netmon_darwin.go:59 +0x60
2025-02-03T08:09:41Z	tailscale.com/net/netmon.(*Monitor).pump(0x140002c2000)
2025-02-03T08:09:41Z	tailscale.com@v1.80.0/net/netmon/netmon.go:346 +0x78
2025-02-03T08:09:41Z	created by tailscale.com/net/netmon.(*Monitor).Start in goroutine 17
2025-02-03T08:09:41Z	tailscale.com@v1.80.0/net/netmon/netmon.go:265 +0x1b8
```

We should permanently leave the panic guard in place at this point.

New upstreams: https://github.com/golang/go/issues/71064 (looks slightly different).
