### ISSUE TITLE
Segmentation fault on container start with `tailscale/tailscale:latest` (1.78.1)

### ISSUE THREAD

**Issue by endigma** [tailscale/tailscale#14364]
### What is the issue?

segmentation fault under docker

```
ts-plex-1  | panic: runtime error: invalid memory address or nil pointer dereference
ts-plex-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa72e81]
ts-plex-1  |
ts-plex-1  | goroutine 1 [running]:
ts-plex-1  | main.(*kubeClient).storeHTTPSEndpoint(...)
ts-plex-1  |    tailscale.com/cmd/containerboot/kube.go:88
ts-plex-1  | main.main()
ts-plex-1  |    tailscale.com/cmd/containerboot/main.go:334 +0x14e1
```

### Steps to reproduce

just using the tailscale dockerhub image for network_mode service

### Are there any recent changes that introduced the issue?

Issue is in 1.78.X not in 1.76.X

### OS

Linux

### OS version

Docker image

### Tailscale version

1.78.1

### Other software

Stock docker container image, can't get bug report ID as the container won't start, and using entrypoint=`ash` doesn't start tailscaled.

**Comment by joedeboom** [comment]
I am having the same issues, none of my tailscale sidecars are functional after updating this morning.

**Comment by jclement** [comment]
For what it's worth, I'm having this issue for any of my containers using `ts-serve.json`.

```
tailscale-1  | 2024/12/11 15:11:34 health(warnable=warming-up): ok
tailscale-1  | 2024/12/11 15:11:34 health(warnable=no-derp-connection): ok
tailscale-1  | 2024/12/11 15:11:34 health(warnable=no-derp-connection): ok
tailscale-1  | boot: 2024/12/11 15:11:34 Running 'tailscale set'
tailscale-1  | boot: 2024/12/11 15:11:34 serve proxy: unsetting previous config
tailscale-1  | 2024/12/11 15:11:34 tailscaled got signal terminated; shutting down
tailscale-1  | 2024/12/11 15:11:34 canceling captive portal context
tailscale-1  | 2024/12/11 15:11:34 control: client.Shutdown ...
tailscale-1  | 2024/12/11 15:11:34 control: authRoutine: exiting
tailscale-1  | 2024/12/11 15:11:34 control: updateRoutine: exiting
tailscale-1  | 2024/12/11 15:11:34 control: mapRoutine: exiting
tailscale-1  | 2024/12/11 15:11:34 control: Client.Shutdown done.
tailscale-1  | 2024/12/11 15:11:34 magicsock: closing connection to derp-10 (conn-close), age 0s
tailscale-1  | 2024/12/11 15:11:34 magicsock: 0 active derp conns
tailscale-1  | panic: runtime error: invalid memory address or nil pointer dereference
tailscale-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa72e81]
tailscale-1  |
tailscale-1  | goroutine 1 [running]:
tailscale-1  | main.(*kubeClient).storeHTTPSEndpoint(...)
tailscale-1  | 	tailscale.com/cmd/containerboot/kube.go:88
tailscale-1  | main.main()
tailscale-1  | 	tailscale.com/cmd/containerboot/main.go:334 +0x14e1
```

**Comment by irbekrm** [comment]
Hi, this is a duplicate of https://github.com/tailscale/tailscale/issues/14354
There is an unstable version with a fix and we'll be releasing a stable soon https://github.com/tailscale/tailscale/issues/14354#issuecomment-2535542763

**Comment by A4alli** [comment]
same here. Tailscale container restarting again and again.
specially when using serve.json

**Comment by crypt0rr** [comment]
Same issue here, sidecars broke. For now back to `tailscale/tailscale:v1.76.6` which works fine.

**Comment by irbekrm** [comment]
The 1.78.3 that we published earlier has a fix for this.
Please let us know if there are further issues.

**Comment by A4alli** [comment]
V1.78.3 solve the problem. Just test it.
