### ISSUE TITLE
iOS: latest TestFlight build 1.5.179 appears to OOM overnight

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#1462]
Woke up to find my iPhone disconnected from Tailscale. Last uploaded log line was:

```
2021-03-06 14:05:51.77015 +0000 UTC: ^0.3M control: mapRoutine: netmap received: state:synchronized
2021-03-06 14:05:51.770205 +0000 UTC: ^0.3M control: sendStatus: mapRoutine-got-netmap: state:synchronized
2021-03-06 14:05:51.770448 +0000 UTC: ^0.3M netmap diff: (none)
```

Restarting it:

```
2021-03-06 16:25:51.298298 +0000 UTC: ^9.9M goSetupLogs: success (started with 10.0M); version 1.5.179-t061422aff-g7530f5406, go1.16-tsc76071c
2021-03-06 16:25:51.303774 +0000 UTC: ^9.5M up=1615047951+0 Sys=5.5M HeapAlloc=0.2M HeapSys=3.3M HeapIdle=2.5M HeapInuse=0.9M HeapReleased=2.5M StackInuse=0.7M StackSys=0.7M MSpanInuse=0.0M MSpanSys=0.0M BuckHashSys=0.0M GCSys=0.8M OtherSys=0.7M NumGC=0 goroutines=4
...
2021-03-06 17:44:42.253916 +0000 UTC: ^2.7M netmap diff: (none)
```

Much tighter memory reporting than before. Binary size growth?

**Comment by bradfitz** [comment]
I wonder if it's from leaking Magic DNS goroutines. I have 33 of these:

```
goroutine 85 [sync.Cond.Wait, 3000 minutes]:
sync.runtime_notifyListWait(0xc000030b10, 0x0)
	runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000030b00)
	sync/cond.go:56 +0x99
tailscale.com/wgengine/tsdns.(*fwdConn).read(0xc000030ac0, 0xc000392200, 0x200, 0x200, 0x0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:403 +0x296
tailscale.com/wgengine/tsdns.(*forwarder).recv(0xc0001d4930, 0xc000030ac0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:189 +0xeb
created by tailscale.com/wgengine/tsdns.(*forwarder).Start
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:143 +0x76

goroutine 86 [sync.Cond.Wait, 3000 minutes]:
sync.runtime_notifyListWait(0xc000030b90, 0xc000000000)
	runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000030b80)
	sync/cond.go:56 +0x99
tailscale.com/wgengine/tsdns.(*fwdConn).read(0xc000030b40, 0xc000422000, 0x200, 0x200, 0x0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:403 +0x296
tailscale.com/wgengine/tsdns.(*forwarder).recv(0xc0001d4930, 0xc000030b40)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:189 +0xeb
created by tailscale.com/wgengine/tsdns.(*forwarder).Start
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:143 +0x76

goroutine 87 [sync.Cond.Wait, 3000 minutes]:
sync.runtime_notifyListWait(0xc000030c10, 0x0)
	runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000030c00)
	sync/cond.go:56 +0x99
tailscale.com/wgengine/tsdns.(*fwdConn).read(0xc000030bc0, 0xc000392600, 0x200, 0x200, 0x0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:403 +0x296
tailscale.com/wgengine/tsdns.(*forwarder).recv(0xc0001d4930, 0xc000030bc0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:189 +0xeb
created by tailscale.com/wgengine/tsdns.(*forwarder).Start
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:143 +0x76

goroutine 88 [sync.Cond.Wait, 3000 minutes]:
sync.runtime_notifyListWait(0xc000030c90, 0x0)
	runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000030c80)
	sync/cond.go:56 +0x99
tailscale.com/wgengine/tsdns.(*fwdConn).read(0xc000030c40, 0xc000494800, 0x200, 0x200, 0x0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:403 +0x296
tailscale.com/wgengine/tsdns.(*forwarder).recv(0xc0001d4930, 0xc000030c40)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:189 +0xeb
created by tailscale.com/wgengine/tsdns.(*forwarder).Start
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/tsdns/forwarder.go:143 +0x76
```

**Comment by bradfitz** [comment]
Oh, the code actually starts 33 of those up:

```go
// connCount is the number of UDP connections to use for forwarding.                                                                                                                                         
const connCount = 32
...
func (f *forwarder) Start() error {
        f.wg.Add(connCount + 1)
        for idx := range f.conns {
                f.conns[idx] = newFwdConn(f.logf, idx)
                go f.recv(f.conns[idx])
        }
        go f.cleanMap()
```

So not necessarily efficient (minimal 132 KB of memory, likely double that), but not a leak.

**Comment by bradfitz** [comment]
@crawshaw, you said the latest build did better, right?

**Comment by crawshaw** [comment]
Yes, it survived last night too. We're definitely using more RAM than the last time we looked at this, but we recovered enough to stay connected to tailscale.com.

**Comment by bradfitz** [comment]
I would **love** to be able to see a heap profile with `runtime.MemProfileRate=1` on iOS but we don't have the memory for the hash table.

But I just had a crazy thought: we could hack up the Go runtime to keep that mprof hash table in a file-backed mmap memory segment, so iOS wouldn't count it against our memory usage (being pageable memory). Just might work?

**Comment by crawshaw** [comment]
It might! But I think we do pay for pagable memory when it's paged in. Do you expect most of the hash table to be unused?

**Comment by bradfitz** [comment]
> But I think we do pay for pagable memory when it's paged in. 

I'm not sure that's true. I thought it actually wasn't from previous debugging sessions on this.

**Comment by DentonGentry** [comment]
In the next bug scrub if this issue is in the same state, I plan to close it as being two releases ago. We can open a fresh bug if we need to investigate memory footprint.

**Comment by apenwarr** [comment]
Closing, probably obsolete.
