### ISSUE TITLE
tailscale up --login-server=.... regression

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#1840]
The integration tests sometimes fail with...

```
    integration_test.go:92: Running up --login-server=http://127.0.0.1:36271 ...
2021/05/03 12:07:11 Error: unexpected HTTP proxy via proxy: CONNECT login.tailscale.com:443 HTTP/1.1
Host: login.tailscale.com:443
User-Agent: Go-http-client/1.1

    logger.go:31: derp client 127.0.0.1:51092/acecc2231aa7440b3334d7b2a604f1a34761e5e1e786a068283e2f93a4fbde3c: adding connection
    integration_test.go:110: Got IP: 100.64.0.1
    logger.go:31: derp client 127.0.0.1:51092/acecc2231aa7440b3334d7b2a604f1a34761e5e1e786a068283e2f93a4fbde3c: read EOF
    logger.go:31: derp client 127.0.0.1:51092/acecc2231aa7440b3334d7b2a604f1a34761e5e1e786a068283e2f93a4fbde3c: removing connection
    integration_test.go:122: number of HTTP logcatcher requests: 47
    integration_test.go:124: unexpected HTTP proxy via proxy: CONNECT login.tailscale.com:443 HTTP/1.1
        Host: login.tailscale.com:443
        User-Agent: Go-http-client/1.1


    integration_test.go:125: logs: magicsock: closing connection to derp-1 (conn-close), age 0s
        magicsock: 0 active derp conns
        netcheck: report: udp=true v6=false mapvarydest= hair=true portmap=MC v4a=127.0.0.1:45348 derp=1 derpdist=1v4:0s
        Routine: receive incoming v4 - failed to receive packet: read udp4 0.0.0.0:45348: use of closed network connection
        Routine: receive incoming v4 - stopped
        magicsock: netInfo update: NetInfo{varies= hairpin=true ipv6=false udp=true derp=#1 portmap=MC link=""}
        magicsock: endpoints changed: 127.0.0.1:45348 (stun), 10.0.0.52:45348 (local), 172.17.0.1:45348 (local), 172.19.0.1:45348 (local), [2602:d1:b4cf:c100:f4fb:4ff:fe1a:4148]:45348 (local)
        wgengine status error: engine closing; no status
        Routine: receive incoming v6 - failed to receive packet: read udp6 [::]:58630: use of closed network connection
        Routine: receive incoming v6 - stopped
        control: NetInfo: NetInfo{varies= hairpin=true ipv6=false udp=true derp=#1 portmap=MC link=""}
        control: cancelMapSafely: synced=false
        [RATELIMIT] format("control: cancelMapSafely: synced=%v")
        control: cancelMapSafely: wrote to channel
        warning: fakeRouter.Close: not implemented.
        Device closing
        Routine: receive incoming receiveDERP - failed to receive packet: use of closed network connection
        Routine: receive incoming receiveDERP - stopped
        Device closed
        flushing log.
        logger closing down
        reading ringbuffer: bufio.Scanner: token too long
        logtail started
        Program starting: vdate.20210427, Go 1.16.2: []string{"/tmp/TestIntegration4212726024/001/tailscaled", "--tun=userspace-networking", "--state=/tmp/TestIntegration4212726024/002/tailscale.state", "--socket=/tmp/TestIntegration4212726024/002/tailscale.sock"}
        LogID: bc54295ee7961f06f4bb7e82353bb78e2c87044253604ae2a46a58d6b9993806
        logpolicy: using system state directory "/home/bradfitz/.local/share/tailscale"
        wgengine.NewUserspaceEngine(tun "userspace-networking") ...
        using fake (no-op) tun device
        using fake (no-op) OS network configurator
        using fake (no-op) DNS configurator
        dns: using dns.noopManager
        link state: interfaces.State{defaultRoute=ens18 ifs={br-e36bfa9018c5:[172.19.0.1/16] docker0:[172.17.0.1/16] ens18:[10.0.0.52/16 2602:d1:b4cf:c100:f4fb:4ff:fe1a:4148/64] tailscale0:[100.74.70.3/32 fd7a:115c:a1e0:ab12:4843:cd96:624a:4603/128]} httpproxy=http://127.0.0.1:46319 v4=true v6global=true}
        logtail: dialed "127.0.0.1:40529" in 2ms
        Creating wireguard device...
        Bringing wireguard device up...
        UDP bind has been updated
        Interface state was Down, requested Up, now Up
        Bringing router up...
        warning: fakeRouter.Up: not implemented.
        Clearing router settings...
        Routine: receive incoming receiveDERP - started
        Routine: receive incoming v4 - started
        Routine: receive incoming v6 - started
        warning: fakeRouter.Set: not implemented.
        Starting link monitor...
        Starting magicsock...
        Engine created.
        magicsock: starting endpoint update (initial)
        Listening on /tmp/TestIntegration4212726024/002/tailscale.sock
        magicsock: ignoring pre-DERP map, STUN-less endpoint update: [{209.180.207.193:39898 portmap} {10.0.0.52:39898 local} {172.17.0.1:39898 local} {172.19.0.1:39898 local} {[2602:d1:b4cf:c100:f4fb:4ff:fe1a:4148]:39898 local}]
        netmap packet filter: (not ready yet)
        Start
        using backend prefs
        created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
        got initial portlist info in 0s
        magicsock: disco key = d:47649e322408b702
        control: HostInfo: {"IPNVersion":"date.20210427","BackendLogID":"bc54295ee7961f06f4bb7e82353bb78e2c87044253604ae2a46a58d6b9993806","OS":"linux","OSVersion":"Debian 10.9 (buster); kernel=4.19.0-16-amd64","Hostname":"tsdev","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22},{"Proto":"tcp","Port":139},{"Proto":"tcp","Port":445},{"Proto":"tcp","Port":3389},{"Proto":"tcp","Port":59453}]}
        Backend: logs: be:bc54295ee7961f06f4bb7e82353bb78e2c87044253604ae2a46a58d6b9993806 fe:
        control: authRoutine: state:new; goal=nil paused=false
        control: mapRoutine: state:new
        Switching ipn state NoState -> NeedsLogin (WantRunning=false)
        blockEngineUpdates(true)
        health("overall"): error: state=NeedsLogin, wantRunning=false
        wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
        wgengine: Reconfig: configuring router
        warning: fakeRouter.Set: not implemented.
        wgengine: Reconfig: configuring DNS
        dns: Set: {DefaultResolvers:[] Routes:map[] SearchDomains:[] Hosts:map[] AuthoritativeSuffixes:[]}
        dns: Resolvercfg: {Routes:map[] Hosts:map[] LocalDomains:[]}
        dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
        wgengine: Reconfig done
        ipnserver: conn1: incoming control connection
        ipnserver: conn1: connection from userid 1001; connection from non-root user matching daemon has access
        ipnserver: conn1: ReadMsg: EOF
        ipnserver: conn4: incoming control connection
        ipnserver: conn4: connection from userid 1001; connection from non-root user matching daemon has access
        SetPrefs: Prefs{ra=false dns=true want=true routes=[] nf=on url="http://127.0.0.1:36271" Persist=nil}
        netmap packet filter: (not ready yet)
        transitioning to running; doing Login...
        control: client.Login(false, 0)
        control: authRoutine: context done.
        control: authRoutine: state:new; wantLoggedIn=true
        control: direct.TryLogin(token=false, flags=0)
        Start
        generating new machine key
        machine key written to store
        control: doLogin(regen=false, hasUrl=false)
        control: client.Shutdown()
        control: client.Shutdown: inSendStatus=0
        control: TryLogin: fetch control key: Get "https://login.tailscale.com/key": http: server gave HTTP response to HTTPS client
        control: authRoutine: state:authenticating; wantLoggedIn=true
        control: authRoutine: quit
        control: mapRoutine: context done.
        control: mapRoutine: state:authenticating
        control: mapRoutine: quit
        control: Client.Shutdown done.
```

**Comment by bradfitz** [comment]
Pretty reliable repro as of 3237e140c417c2f0bb7530bd4459511455507cba:

```
$ TS_POST_UP_SLEEP=500ms go test -count=10 -failfast -v ./tstest/integration/
```

**Comment by bradfitz** [comment]
@apenwarr, if I `git rebase -i a07a504b1633ee537964cc34d6a1d390ecf28b5f^` and remove all your recent changes (and the follow-up LoggedOut prefs fix), I can't get this test to fail even after 40 runs.

I pushed that altered tree to `bradfitz/issue_1849_rebased_tree`.

Want to have a look?

**Comment by bradfitz** [comment]
Easier repro:

```patch
diff --git a/control/controlclient/direct.go b/control/controlclient/direct.go
index 5e522ed9..0567fb1e 100644
--- a/control/controlclient/direct.go
+++ b/control/controlclient/direct.go
@@ -975,6 +975,9 @@ func encode(v interface{}, serverKey *wgkey.Key, mkey *wgkey.Private) ([]byte, e
 }
 
 func loadServerKey(ctx context.Context, httpc *http.Client, serverURL string) (wgkey.Key, error) {
+       if strings.Contains(serverURL, "login.tailscale.com") {
+               panic("nope")
+       }
        req, err := http.NewRequest("GET", serverURL+"/key", nil)
        if err != nil {
                return wgkey.Key{}, fmt.Errorf("create control key request: %v", err)
diff --git a/tstest/integration/integration_test.go b/tstest/integration/integration_test.go
index 922d6db3..eacb47be 100644
--- a/tstest/integration/integration_test.go
+++ b/tstest/integration/integration_test.go
@@ -231,6 +231,7 @@ func (n *testNode) StartDaemon(t testing.TB) *exec.Cmd {
                "HTTP_PROXY="+n.env.TrafficTrapServer.URL,
                "HTTPS_PROXY="+n.env.TrafficTrapServer.URL,
        )
+       cmd.Stderr = os.Stderr
        if err := cmd.Start(); err != nil {
                t.Fatalf("starting tailscaled: %v", err)
        }
```

Then:

```
bradfitz@tsdev:~/src/tailscale.com$ go test -v ./tstest/integration/
=== RUN   TestIntegration
    integration_test.go:295: using go binary /home/bradfitz/sdk/go1.16.2/bin/go
    integration_test.go:295: using go binary /home/bradfitz/sdk/go1.16.2/bin/go
2021/05/03 14:35:37 You have enabled a non-default log target. Doing without being told to by Tailscale staff or your network administrator will make getting support difficult.
...
2021/05/03 14:35:37 Switching ipn state NoState -> NeedsLogin (WantRunning=false)
2021/05/03 14:35:37 blockEngineUpdates(true)
2021/05/03 14:35:37 health("overall"): error: state=NeedsLogin, wantRunning=false
2021/05/03 14:35:37 wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
2021/05/03 14:35:37 wgengine: Reconfig: configuring router
2021/05/03 14:35:37 wgengine: Reconfig: configuring DNS
2021/05/03 14:35:37 dns: Set: {DefaultResolvers:[] Routes:map[] SearchDomains:[] Hosts:map[] AuthoritativeSuffixes:[]}
2021/05/03 14:35:37 dns: Resolvercfg: {Routes:map[] Hosts:map[] LocalDomains:[]}
2021/05/03 14:35:37 dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
2021/05/03 14:35:37 ipnserver: conn1: connection from userid 1001; connection from non-root user matching daemon has access
    integration_test.go:78: Status: NeedsLogin
    integration_test.go:90: Running up --login-server=http://127.0.0.1:36767 ...
2021/05/03 14:35:37 ipnserver: conn4: connection from userid 1001; connection from non-root user matching daemon has access
2021/05/03 14:35:37 SetPrefs: Prefs{ra=false dns=true want=true routes=[] nf=on url="http://127.0.0.1:36767" Persist=nil}
2021/05/03 14:35:37 netmap packet filter: (not ready yet)
2021/05/03 14:35:37 transitioning to running; doing Login...
2021/05/03 14:35:37 control: client.Login(false, 0)
2021/05/03 14:35:37 Start
2021/05/03 14:35:37 control: authRoutine: state:new; wantLoggedIn=true
2021/05/03 14:35:37 control: direct.TryLogin(token=false, flags=0)
2021/05/03 14:35:37 control: client.Shutdown()
2021/05/03 14:35:37 control: client.Shutdown: inSendStatus=0
2021/05/03 14:35:37 generating new machine key
2021/05/03 14:35:37 machine key written to store
2021/05/03 14:35:37 control: doLogin(regen=false, hasUrl=false)
panic: nope

goroutine 115 [running]:
tailscale.com/control/controlclient.loadServerKey(0xc23278, 0xc000460080, 0xc000262ab0, 0xb4e154, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/bradfitz/src/tailscale.com/control/controlclient/direct.go:979 +0x9b2
tailscale.com/control/controlclient.(*Direct).doLogin(0xc000354000, 0xc23278, 0xc000460080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2, ...)
        /home/bradfitz/src/tailscale.com/control/controlclient/direct.go:337 +0x2488
tailscale.com/control/controlclient.(*Direct).doLoginOrRegen(0xc000354000, 0xc23278, 0xc000460080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xb715a0, ...)
        /home/bradfitz/src/tailscale.com/control/controlclient/direct.go:281 +0x73
tailscale.com/control/controlclient.(*Direct).TryLogin(0xc000354000, 0xc23278, 0xc000460080, 0x0, 0x0, 0x6465726168, 0x71652e2e65707974, 0x616e7265746e692e, 0x656c676e69732f6c)
        /home/bradfitz/src/tailscale.com/control/controlclient/direct.go:269 +0x177
tailscale.com/control/controlclient.(*Auto).authRoutine(0xc00012e2d0)
        /home/bradfitz/src/tailscale.com/control/controlclient/auto.go:334 +0x7b5
created by tailscale.com/control/controlclient.(*Auto).Start
        /home/bradfitz/src/tailscale.com/control/controlclient/auto.go:150 +0x3f

^CFAIL  tailscale.com/tstest/integration        3.443s
```

**Comment by bradfitz** [comment]
Looks like `setPrefsLockedOnEntry` shouldn't use `b.cc` (the LocalBackend controlclient.Auto) that was created with different prefs, at least when the new pref's LoginURL differs.

**Comment by bradfitz** [comment]
Regression from https://github.com/tailscale/tailscale/commit/4f3315f3da8ed73034924d09d1ca97b677f61f1e which introduced the use of `b.cc` within `setPrefsLockedOnEntry`.
