### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by uhthomas** [tailscale/tailscale#1888]
Hi! I'm playing with Magic DNS. I added a search domain `.tailscale.starjunk.net` and then ran
```
ssh e7b79f2078.tailscale.starjunk.net
```

It fails with
```
ssh: Could not resolve hostname e7b79f2078.tailscale.starjunk.net: Temporary failure in name resolution
```

# Stack trace (tailscaled)
```
panic: runtime error: slice bounds out of range [:-1]

goroutine 765 [running]:
tailscale.com/util/dnsname.FQDN.WithoutTrailingDot(...)
        tailscale.com@v0.0.0-00010101000000-000000000000/util/dnsname/dnsname.go:71
tailscale.com/net/dns.writeResolvConf(0xc17820, 0xc0004916b0, 0xc0004da828, 0x1, 0x1, 0xc000144660, 0x2, 0x2)
        tailscale.com@v0.0.0-00010101000000-000000000000/net/dns/direct.go:43 +0x2f4
tailscale.com/net/dns.directManager.SetDNS(0xc0004da828, 0x1, 0x1, 0xc000144660, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc00053c204, ...)
        tailscale.com@v0.0.0-00010101000000-000000000000/net/dns/direct.go:249 +0x131
tailscale.com/net/dns.(*Manager).Set(0xc000456180, 0xc0000f2580, 0x2, 0x2, 0x0, 0xc000144660, 0x2, 0x2, 0xc000491170, 0xc000563000, ...)
        tailscale.com@v0.0.0-00010101000000-000000000000/net/dns/manager.go:69 +0x522
tailscale.com/wgengine.(*userspaceEngine).Reconfig(0xc000416200, 0xc000456000, 0xc00019e310, 0xc00048c300, 0x0, 0x0)
        tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/userspace.go:1018 +0xf78
tailscale.com/wgengine.(*watchdogEngine).Reconfig.func1(0xd6469ffcf19ab9c6, 0x3fdfee8e705aa645)
        tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:78 +0x4d
tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func1(0xc00066a420, 0xc0004911a0)
        tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:54 +0x27
created by tailscale.com/wgengine.(*watchdogEngine).watchdogErr
        tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:53 +0x77
```

**Comment by uhthomas** [comment]
Maybe it's my fault for giving it a bad search domain as per this log

```
[unexpected] non-FQDN search domain ".tailscale.starjunk.net"
```

However the UI does make it a bit confusing as the required search domain is prefixed with a `.`

![](https://kipp.6f.io/jR26K9RhJMpj.png)

**Comment by danderson** [comment]
Regardless, we shouldn't be crashing. Thanks for the report, we probably have some inconsistent normalization somewhere, I'll track it down on Monday.
