### ISSUE TITLE
windows/arm64: 1.8.0 panic at service startup

### ISSUE THREAD

**Issue by sailorfrag** [tailscale/tailscale#1898]
![image](https://user-images.githubusercontent.com/70300501/117701977-e3801e80-b195-11eb-8c9e-74147ab183b5.png)

A user reported a problem running the Tailscale 1.8.0 client on a Surface Pro X that it is unable to connect to the service. Immediately after installing 1.8.0 there's a panic:
```
2021-05-10 13:35:37.9310887 -0400 EDT: panic: unaligned 64-bit atomic operation
2021-05-10 13:35:37.9310887 -0400 EDT: goroutine 22 [running]:
2021-05-10 13:35:37.9320905 -0400 EDT: runtime/internal/atomic.panicUnaligned()
2021-05-10 13:35:37.9330863 -0400 EDT: 	runtime/internal/atomic/unaligned.go:8 +0x2d
2021-05-10 13:35:37.9330863 -0400 EDT: runtime/internal/atomic.Load64(0x1918558c, 0x50f57, 0x1919ad00)
2021-05-10 13:35:37.9330863 -0400 EDT: 	runtime/internal/atomic/asm_386.s:201 +0x10
2021-05-10 13:35:37.9330863 -0400 EDT: github.com/tailscale/wireguard-go/tun.(*NativeTun).Read(0x19185560, 0x19234028, 0x7e0, 0x7e0, 0x10, 0x0, 0x0, 0x0)
2021-05-10 13:35:37.9330863 -0400 EDT: 	github.com/tailscale/wireguard-go@v0.0.0-20210429195722-6cd106ab1339/tun/tun_windows.go:164 +0x14b
2021-05-10 13:35:37.9330863 -0400 EDT: tailscale.com/net/tstun.(*Wrapper).poll(0x19234000)
2021-05-10 13:35:37.9330863 -0400 EDT: 	tailscale.com@v0.0.0-00010101000000-000000000000/net/tstun/wrap.go:248 +0xed
2021-05-10 13:35:37.9330863 -0400 EDT: created by tailscale.com/net/tstun.Wrap
2021-05-10 13:35:37.9330863 -0400 EDT: 	tailscale.com@v0.0.0-00010101000000-000000000000/net/tstun/wrap.go:144 +0x199
2021-05-10 13:35:37.9526868 -0400 EDT: subprocess exited: exit status 2
```

**Comment by josharian** [comment]
Merged into HEAD via https://github.com/tailscale/tailscale/pull/1899. Cherry-picked to release-branch/1.8 in https://github.com/tailscale/tailscale/commit/b8bd18b0537070b99bdc34892c50c61dedd747bc.
