### ISSUE TITLE
Linux/NixOS: `tailscale up` failing on 1.8.x

### ISSUE THREAD

**Issue by epk** [tailscale/tailscale#1914]
## Problem

On NixOS I run the latest/unstable version with the following config:
```nix
{ config, lib, pkgs, ... }:

let

  baseconfig = { allowUnfree = true; };
  unstable = import <nixos-unstable> { config = baseconfig; };

in {

  imports =
    [ <nixos-unstable/nixos/modules/services/networking/tailscale.nix> ];
  disabledModules = [ "services/networking/tailscale.nix" ];

  nixpkgs.config = baseconfig // {
    packageOverrides = pkgs: { tailscale = unstable.tailscale; };
  };

  services.tailscale.enable = true;

}
```

After upgrading to the latest version (1.8.0) by running `sudo nix-channel --update` and `sudo nixos-rebuild switch --upgrade`, the server went offline on the tailscale network. 

However I was able to ssh directly and stumbled upon the following: 

```
adi@servnerr  ~  tailscale status                                        
Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
 
✘ adi@servnerr  ~  tailscale status
unexpected state: NoState

✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale bugreport                                
BUG-827d75fed582e0ff636f182d9253822a8714a034eb7a001cc3306ec82b4d13d1-20210512060256Z-31657defefd31e5f
 
adi@servnerr  /etc/nixos   master ●  sudo tailscale bugreport
Post "http://local-tailscaled.sock/localapi/v0/bugreport?note=": dial unix /var/run/tailscale/tailscaled.sock: connect: connection refused

✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale bugreport
Post "http://local-tailscaled.sock/localapi/v0/bugreport?note=": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale bugreport
Post "http://local-tailscaled.sock/localapi/v0/bugreport?note=": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
```

Attempts to `sudo tailscale up` yielded similar errors:
```
✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale up                     
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale up
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: connection refused

✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale up
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale up

adi@servnerr  /etc/nixos   master ●  sudo tailscale up
can't fetch status from tailscaled: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
 
✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale status
unexpected state: NoState
 
✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale status
Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory
 
✘ adi@servnerr  /etc/nixos   master ●  sudo tailscale status
unexpected state: NoState

✘  sudo tailscale bugreport
BUG-827d75fed582e0ff636f182d9253822a8714a034eb7a001cc3306ec82b4d13d1-20210512060454Z-2f1aa80632abaaa8
```

**Comment by epk** [comment]
This behaviour is also persistent on a fresh GCP VM running Debian Buster. I was unable to `sudo tailscale up` on the latest version. 

Installing/Rolling back to 1.6.0 fixed the issues on either systems fixed the issues

## Caveats 

- I have IPv6 with my ISP 
- MagicDNS on with both IPv4 + IPv6 DNS servers

**Comment by DentonGentry** [comment]
/var/run/tailscale/tailscaled.sock being missing means that tailscaled is not running. Does `systemctl status tailscaled` show anything about what went wrong?

**Comment by epk** [comment]
On NixOS: 

```
 ✘ adi@servnerr  ~  systemctl status tailscaled
● tailscaled.service - Tailscale node agent
     Loaded: loaded (/nix/store/qvgkp87yd4gr643r26wnc29c06nqn9px-tailscale-1.8.0/lib/systemd/system/tailscaled.service; enabled; vendor preset: enabled)
    Drop-In: /nix/store/k2pgcws68id1231wdv5njpgh1h93p085-system-units/tailscaled.service.d
             └─overrides.conf
     Active: deactivating (stop-post) (Result: exit-code) since Wed 2021-05-12 07:56:09 PDT; 303ms ago
       Docs: https://tailscale.com/kb/
    Process: 19811 ExecStartPre=/nix/store/qvgkp87yd4gr643r26wnc29c06nqn9px-tailscale-1.8.0/bin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
    Process: 19825 ExecStart=/nix/store/qvgkp87yd4gr643r26wnc29c06nqn9px-tailscale-1.8.0/bin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port $PORT $FLAGS (code=exited, status=2)
   Main PID: 19825 (code=exited, status=2); Control PID: 19922 (.tailscaled-wra)
         IP: 0B in, 0B out
      Tasks: 8 (limit: 4915)
     Memory: 11.0M
        CPU: 808ms
     CGroup: /system.slice/tailscaled.service
             └─19922 /nix/store/qvgkp87yd4gr643r26wnc29c06nqn9px-tailscale-1.8.0/bin/tailscaled --cleanup

May 12 07:56:09 servnerr tailscaled[19825]:         tailscale.com/wgengine/watchdog.go:53 +0x77
May 12 07:56:09 servnerr systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 12 07:56:09 servnerr tailscaled[19922]: logtail started
May 12 07:56:09 servnerr tailscaled[19922]: Program starting: v1.8.0, Go 1.16.3: []string{"/nix/store/qvgkp87yd4gr643r26wnc29c06nqn9px-tailscale-1.8.0/bin/tailscaled", "--cleanup"}
May 12 07:56:09 servnerr tailscaled[19922]: LogID: 827d75fed582e0ff636f182d9253822a8714a034eb7a001cc3306ec82b4d13d1
May 12 07:56:09 servnerr tailscaled[19922]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
May 12 07:56:09 servnerr tailscaled[19922]: dns: [rc=resolvconf src-is-nm=no resolvconf=yes ret=dns.openresolvManager]
May 12 07:56:09 servnerr tailscaled[19922]: dns: using dns.openresolvManager
May 12 07:56:09 servnerr tailscaled[19922]: flushing log.
May 12 07:56:09 servnerr tailscaled[19922]: logger closing down
```

I tried to replicate on Debian but the release v1.8.3 seems be working again

**Comment by danderson** [comment]
Can you send the output of `sudo journalctl -u tailscaled --since="5 minutes ago"` ? I see something failing to start up in the log snippet provided by systemd, but the important error is just barely out of shot. If you'd prefer to keep the logs private, you can email them to me at danderson@tailscale.com and I'll post a personal-information-free update with my findings.

**Comment by epk** [comment]
> Can you send the output of `sudo journalctl -u tailscaled --since="5 minutes ago"` ? I see something failing to start up in the log snippet provided by systemd, but the important error is just barely out of shot. If you'd prefer to keep the logs private, you can email them to me at [danderson@tailscale.com](mailto:danderson@tailscale.com) and I'll post a personal-information-free update with my findings.

Emailed you the full logs, but the relevant bits are:
```
May 12 10:40:39 servnerr tailscaled[3991]: dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[adi.run.beta.tailscale.net. ] MatchDomains:[]}
May 12 10:40:39 servnerr tailscaled[3991]: panic: runtime error: slice bounds out of range [:-1]
May 12 10:40:39 servnerr tailscaled[3991]: goroutine 156 [running]:
May 12 10:40:39 servnerr tailscaled[3991]: tailscale.com/util/dnsname.FQDN.WithoutTrailingDot(...)
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/util/dnsname/dnsname.go:71
May 12 10:40:39 servnerr tailscaled[3991]: tailscale.com/net/dns.writeResolvConf(0xc10440, 0xc0004d6900, 0xc000608378, 0x1, 0x1, 0xc00041a380, 0x2, 0x2)
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/net/dns/direct.go:43 +0x2f4
May 12 10:40:39 servnerr tailscaled[3991]: tailscale.com/net/dns.openresolvManager.SetDNS(0xc000608378, 0x1, 0x1, 0xc00041a380, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc0000fc0e4, ...)
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/net/dns/openresolv.go:39 +0x116
May 12 10:40:39 servnerr tailscaled[3991]: tailscale.com/net/dns.(*Manager).Set(0xc0000ea300, 0xc0000ee600, 0x8, 0x8, 0x0, 0xc00041a380, 0x2, 0x2, 0xc0004e29f0, 0xc000760000, ...)
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/net/dns/manager.go:69 +0x522
May 12 10:40:39 servnerr tailscaled[3991]: tailscale.com/wgengine.(*userspaceEngine).Reconfig(0xc000124000, 0xc0004d2580, 0xc0001840e0, 0xc000126ba0, 0x0, 0x0)
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/wgengine/userspace.go:1018 +0xf78
May 12 10:40:39 servnerr tailscaled[3991]: tailscale.com/wgengine.(*watchdogEngine).Reconfig.func1(0xc000136900, 0xc0000597b0)
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/wgengine/watchdog.go:78 +0x4d
May 12 10:40:39 servnerr tailscaled[3991]: tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func1(0xc000365380, 0xc0004e2a20)
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/wgengine/watchdog.go:54 +0x27
May 12 10:40:39 servnerr tailscaled[3991]: created by tailscale.com/wgengine.(*watchdogEngine).watchdogErr
May 12 10:40:39 servnerr tailscaled[3991]:         tailscale.com/wgengine/watchdog.go:53 +0x77
May 12 10:40:39 servnerr systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by danderson** [comment]
Aha, okay, that's a bug I fixed in 1.8.3 related to how you specified search domains in the admin panel (not your fault, we failed at validation). To mitigate until 1.8.3 shows up in nixos, remove the leading dot from your search domains in the admin panel.

**Comment by epk** [comment]
> Aha, okay, that's a bug I fixed in 1.8.3 related to how you specified search domains in the admin panel (not your fault, we failed at validation). To mitigate until 1.8.3 shows up in nixos, remove the leading dot from your search domains in the admin panel.

Thanks!
That did the trick, however in the panel the domain did not have a trailing dot (I just removed it all together)

**Comment by danderson** [comment]
Hmm, did the search domain have a leading dot? (as in, `.blah.com`) ? I may be conflating a couple of different bugs, but I'm fairly sure that panic was induced by missing FQDN normalization on search domains.

**Comment by epk** [comment]
> Hmm, did the search domain have a leading dot? (as in, .blah.com) ?

I am not sure, it might have. Anyway thanks a lot for your help @DentonGentry & @danderson 🍻
