### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by x-cubed** [tailscale/tailscale#1963]
After upgrading to 1.8.4 on a Windows 10 machine, the Tailscale service is not responding. Manually running tailscaled from the command line results in the following error:

```
panic: assignment to entry in nil map

goroutine 177 [running]:
tailscale.com/ipn/ipnlocal.(*LocalBackend).authReconfig(0xc00024e000)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:1788 +0xa32
tailscale.com/ipn/ipnlocal.(*LocalBackend).enterState(0xc00024e000, 0x5)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:2175 +0x66a
tailscale.com/ipn/ipnlocal.(*LocalBackend).stateMachine(0xc00024e000)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:2276 +0x45
tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus(0xc00024e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00017ac80, 0x5, 0xc00060ce00, ...)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:539 +0x518
tailscale.com/control/controlclient.(*Auto).sendStatus(0xc00023a5a0, 0x147468e, 0x15, 0x0, 0x0, 0x0, 0x0, 0xc00017ac80)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:607 +0x355
tailscale.com/control/controlclient.(*Auto).mapRoutine.func2(0xc00017ac80)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:494 +0x1f3
tailscale.com/control/controlclient.(*Direct).sendMapRequest(0xc000252700, 0x1557bd8, 0xc00008c340, 0xffffffffffffffff, 0xc000507f10, 0x0, 0x0)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:862 +0x1e1c
tailscale.com/control/controlclient.(*Direct).PollNetMap(...)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:556
tailscale.com/control/controlclient.(*Auto).mapRoutine(0xc00023a5a0)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:464 +0x575
created by tailscale.com/control/controlclient.(*Auto).Start
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:151 +0x68
```

<details>
  <summary>Redacted tailscaled log output</summary>

```
Program starting: v1.8.4-t33ff4a25b-g5ed85f6bc, Go 1.16.4-ts1b677aa: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe"}
LogID: 55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040
logpolicy: using system state directory "C:\\Users\\bishopc\\AppData\\Local\\Tailscale"
wgengine.NewUserspaceEngine(tun "Tailscale") ...
logtail: dialed "log.tailscale.io:443" in 215ms
[Wintun] CreateAdapter: Creating adapter
[Wintun] CreateAdapter: Requested GUID {37217669-42DA-4657-A55B-0D995D328250} has leftover residue
[Wintun] SelectDriver: Using existing driver 0.10
waitInterfaceUp: TUN interface already up; no need to wait
dns: using dns.windowsManager
link state: interfaces.State ****
Creating wireguard device...
Bringing wireguard device up...
Bringing router up...
router: firewall: marking for removal
router: firewall: starting netsh goroutine
router: firewall: clearing Tailscale-In firewall rules...
router: monitorDefaultRoutes done after 64ms
Clearing router settings...
router: firewall: marking for removal
Starting link monitor...
Starting magicsock...
Engine created.
monitor: got windows change event after 0s: evt=addr
monitor: got windows change event after 0s: evt=addr
monitor: got windows change event after 0s: evt=route
monitor: got windows change event after 0s: evt=route
monitor: got windows change event after 0s: evt=route
[RATELIMIT] format("monitor: got windows change event after %v: evt=%s")
Listening on 127.0.0.1:41112
router: firewall: cleared Tailscale-In firewall rules in 325ms
router: firewall: deleting any prior Tailscale-Process rule...
router: firewall: removed old Tailscale-Process rule in 164ms
router: firewall: adding Tailscale-Process rule to allow UDP for "C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe" ...
router: firewall: added Tailscale-Process rule in 192ms
router: firewall: ending netsh goroutine
netmap packet filter: (not ready yet)
Start
using backend prefs
created empty state for "_daemon": Prefs{ra=true dns=true want=false Persist=nil}
Start: serverMode=false
got initial portlist info in 0s
magicsock: disco key = d:a32b801a71316e10
control: HostInfo: {"IPNVersion":"1.8.4-t33ff4a25b-g5ed85f6bc","BackendLogID":"55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040","OS":"windows","OSVersion":"10.0.19043.985","Hostname":"***","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd"},{"Proto":"tcp","Port":3389,"Description":"TermService"}]}
Backend: logs: be:55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040 fe:
Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
blockEngineUpdates(true)
wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
wgengine: Reconfig: configuring router
router: firewall: marking for removal
router: firewall: starting netsh goroutine
control: mapRoutine: state:new
control: authRoutine: state:new; goal=nil paused=false
health("overall"): error: state=NeedsLogin, wantRunning=false
router: firewall: ending netsh goroutine
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:map[] SearchDomains:[] Hosts:map[] AuthoritativeSuffixes:[]}
dns: Resolvercfg: {Routes:map[] Hosts:map[] LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
running ipconfig /registerdns ...
netmap packet filter: (not ready yet)
Start: Prefs{ra=true dns=true want=true Persist{lm=[tjDUO], o=, n=[V7OX8] u="***@gmail.com"}}
control: client.Shutdown()
control: client.Shutdown: inSendStatus=0
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: context done.
control: mapRoutine: state:new
control: mapRoutine: quit
control: Client.Shutdown done.
using frontend prefs: Prefs{ra=true dns=true want=true Persist{lm=[tjDUO], o=, n=[V7OX8] u="***@gmail.com"}}
using frontend-provided legacy machine key
machine key written to store
Start: serverMode=false
netmap packet filter: (not ready yet)
control: HostInfo: {"IPNVersion":"1.8.4-t33ff4a25b-g5ed85f6bc","FrontendLogID":"55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040","BackendLogID":"55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040","OS":"windows","OSVersion":"10.0.19043.985","Hostname":"***","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd"},{"Proto":"tcp","Port":3389,"Description":"TermService"}]}
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
Backend: logs: be:55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040 fe:55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040
control: client.Login(false, 0)
control: authRoutine: state:new; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode=[AAAAA] node=[V7OX8] fup=false
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
control: No AuthURL
blockEngineUpdates(false)
authReconfig: netmap not yet valid. Skipping.
authReconfig: netmap not yet valid. Skipping.
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
Backend: logs: be:55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040 fe:55cfbc43eecb753d15c501573b41254b767b117d34c0149b8c1ca62b8e449040
control: client.Login(false, 0)
control: authRoutine: state:new; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
control: RegisterReq: onode=[AAAAA] node=[V7OX8] fup=false
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
control: No AuthURL
blockEngineUpdates(false)
authReconfig: netmap not yet valid. Skipping.
authReconfig: netmap not yet valid. Skipping.
control: authRoutine: state:authenticated; goal=nil paused=false
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:authenticated
active login: ***@gmail.com
netmap packet filter: [[TCP UDP ICMPv4 ICMPv6][0.0.0.0/0,::/0]=>[0.0.0.0/0:22,::/0:22,0.0.0.0/0:53,::/0:53,0.0.0.0/0:80,::/0:80,0.0.0.0/0:443,::/0:443,0.0.0.0/0:3389,::/0:3389,192.168.2.251/32:*,192.168.2.15/32:5004]]
Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
panic: assignment to entry in nil map

goroutine 177 [running]:
tailscale.com/ipn/ipnlocal.(*LocalBackend).authReconfig(0xc00024e000)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:1788 +0xa32
tailscale.com/ipn/ipnlocal.(*LocalBackend).enterState(0xc00024e000, 0x5)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:2175 +0x66a
tailscale.com/ipn/ipnlocal.(*LocalBackend).stateMachine(0xc00024e000)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:2276 +0x45
tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus(0xc00024e000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc00017ac80, 0x5, 0xc00060ce00, ...)
        tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:539 +0x518
tailscale.com/control/controlclient.(*Auto).sendStatus(0xc00023a5a0, 0x147468e, 0x15, 0x0, 0x0, 0x0, 0x0, 0xc00017ac80)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:607 +0x355
tailscale.com/control/controlclient.(*Auto).mapRoutine.func2(0xc00017ac80)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:494 +0x1f3
tailscale.com/control/controlclient.(*Direct).sendMapRequest(0xc000252700, 0x1557bd8, 0xc00008c340, 0xffffffffffffffff, 0xc000507f10, 0x0, 0x0)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:862 +0x1e1c
tailscale.com/control/controlclient.(*Direct).PollNetMap(...)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:556
tailscale.com/control/controlclient.(*Auto).mapRoutine(0xc00023a5a0)
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:464 +0x575
created by tailscale.com/control/controlclient.(*Auto).Start
        tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:151 +0x68
```
</details>

**Comment by arsfeld** [comment]
Same for me on Ubuntu 20.04:

```
May 21 01:59:39 gcp tailscaled[2251]: panic: assignment to entry in nil map
May 21 01:59:39 gcp tailscaled[2251]: goroutine 113 [running]:
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/ipn/ipnlocal.(*LocalBackend).authReconfig(0xc0000a0fc0)
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:1788 +0xa1b
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/ipn/ipnlocal.(*LocalBackend).enterState(0xc0000a0fc0, 0x5)
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:2175 +0x79a
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/ipn/ipnlocal.(*LocalBackend).stateMachine(0xc0000a0fc0)
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:2276 +0x39
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus(0xc0000a0fc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0>
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/ipn/ipnlocal/local.go:539 +0x514
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/control/controlclient.(*Auto).sendStatus(0xc0004181e0, 0xb4b0c7, 0x15, 0x0, 0x0, 0x0, 0x0, 0x>
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:607 +0x335
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/control/controlclient.(*Auto).mapRoutine.func2(0xc00040aa00)
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:494 +0x1e5
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/control/controlclient.(*Direct).sendMapRequest(0xc000428000, 0xc24d18, 0xc0003de180, 0xffffff>
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:862 +0x1e7c
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/control/controlclient.(*Direct).PollNetMap(...)
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:556
May 21 01:59:39 gcp tailscaled[2251]: tailscale.com/control/controlclient.(*Auto).mapRoutine(0xc0004181e0)
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:464 +0x571
May 21 01:59:39 gcp tailscaled[2251]: created by tailscale.com/control/controlclient.(*Auto).Start
May 21 01:59:39 gcp tailscaled[2251]:         tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:151 +0x65
May 21 01:59:39 gcp systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

```
> uname -a
Linux gcp 5.4.0-1043-gcp #46-Ubuntu SMP Mon Apr 19 19:17:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by DentonGentry** [comment]
Regarding the initial comment on Windows 10: ipn/ipnlocal/local/go:1788 is https://github.com/tailscale/tailscale/blob/33ff4a25b20a19e12ad00dec4f4ed06f3482879f/ipn/ipnlocal/local.go#L1788

```
		if nm.DNS.Proxied { // actually means "enable MagicDNS"
			for _, dom := range dcfg.AuthoritativeSuffixes {
-->				dcfg.Routes[dom] = []netaddr.IPPort{netaddr.IPPort{IP: tsaddr.TailscaleServiceIP(), Port: 53}}
			}
		}
```

which implies that dcfg.Routes is nil.

**Comment by DentonGentry** [comment]
I think this can happen if on line 1762, if len(nm.DNS.Routes) == 0 https://github.com/tailscale/tailscale/blob/33ff4a25b20a19e12ad00dec4f4ed06f3482879f/ipn/ipnlocal/local.go#L1762 

```
		if len(nm.DNS.Routes) > 0 {
			dcfg.Routes = map[dnsname.FQDN][]netaddr.IPPort{}
		}
```

dcfg.Routes will not be allocated.

On line 1788, dcfg.Routes can be dereferenced even if len(nm.DNS.Routes) was 0 on line 1762. https://github.com/tailscale/tailscale/blob/33ff4a25b20a19e12ad00dec4f4ed06f3482879f/ipn/ipnlocal/local.go#L1788

```
		if nm.DNS.Proxied { // actually means "enable MagicDNS"
			for _, dom := range dcfg.AuthoritativeSuffixes {	
				dcfg.Routes[dom] = []netaddr.IPPort{netaddr.IPPort{IP: tsaddr.TailscaleServiceIP(), Port: 53}}
			}
		}
```

This would result in a panic due to nil dererence.

**Comment by danderson** [comment]
Keeping open until backport is finished and 1.8.5 released.

**Comment by DentonGentry** [comment]
We are building 1.8.5 now.

The panic in 1.8.4 happens if:
- there are no split DNS entries in https://login.tailscale.com/admin/dns
- there are global resolvers configured in https://login.tailscale.com/admin/dns
- Magic DNS is enabled

A quick way to avoid the issue would be to add a nameserver for a specific but nonexistent domain, some combination of random letters and numbers would do. You can point it at 1.1.1.1 or any other DNS server, the mere existence of the Split DNS entry would avoid the code path that results in the problem.

**Comment by x-cubed** [comment]
@DentonGentry I'm not sure I meet those requirements, as I have a split DNS entry defined, a global resolver and Magic DNS enabled:

<img src="https://user-images.githubusercontent.com/11729/119082348-fb875600-ba51-11eb-863f-72b32c52c9fa.png" width=250 alt="Tailscale DNS settings" />

**Comment by DentonGentry** [comment]
Odd. We'll have to look at the conditions that would hit this code path again.

Ok: if you can live without Magic DNS for a while, disabling it for now would also likely avoid the problem. I expect 1.8.5 to be released tomorrow with a fix for this (and only this).

**Comment by danderson** [comment]
1.8.5 is released with the fix for the crash. Thanks for reporting!

@x-cubed depending on whether you changed your DNS config recently, you're likely getting a config that's been massaged through one of the control server's legacy codepaths, which would have also triggered the broken codepath. The actual condition is that the DNS config you receive in your client netmap doesn't contain any DNS routes, which legacy compat configs never do.

**Comment by x-cubed** [comment]
I can confirm that 1.8.5 works, thanks!
