### ISSUE TITLE
1.8.3 32-bit ARM segfault due to unaligned atomic access

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2129]
From https://github.com/tailscale/tailscale-synology/issues/66

**Description**
Tailscale segfaults on 32-bit ARM, due to unaligned atomic access in inet.af/netstack. Seems to have been fixed upstream in https://github.com/google/gvisor/issues/5692; I've tested a manual build with the fixes included and it does seem to work fine.

**Steps to reproduce**
Install Tailscale package, do `tailscale up`

**Expected behavior**
Tailscale should not segfault

**Synology NAS model**
DS218j

**Comment by bogsen** [comment]
I've started over with a clean install and couldn't reproduce the segfault immediately (it's a memory alignment issue so it may just be down to luck), but then advertising a subnet from the NAS and enabling it from the admin UI was enough to trigger a segfault:

```
2021/06/16 01:18:43 [RATELIMIT] format("acceptUDP: could not create endpoint: %v")
2021/06/16 01:18:46 Accept: ICMPv4{100.88.16.31:0 > 100.78.170.88:0} 84 icmp ok
panic: unaligned 64-bit atomic operation

goroutine 720 [running]:
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x14adf1c, 0x100000, 0x0)
	runtime/internal/atomic/asm_arm.s:278 +0x14
inet.af/netstack/tcpip.(*SocketOptions).SetSendBufferSize(0x14adeb0, 0x100000, 0x0, 0x8d17ff00)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/socketops.go:607 +0x17c
inet.af/netstack/tcpip/transport/tcp.newEndpoint(0x147a380, 0x800, 0x16ee020, 0x4)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/endpoint.go:892 +0x1d0
inet.af/netstack/tcpip/transport/tcp.(*listenContext).createConnectingEndpoint(0x14ba000, 0x14a2b40, 0x32a5f721, 0xb8b111c7, 0x14c3eb4, 0x16ee020, 0xbc5d8d6e, 0x32a5f721, 0x40)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:216 +0xac
inet.af/netstack/tcpip/transport/tcp.(*listenContext).startHandshake(0x14ba000, 0x14a2b40, 0x14c3eb4, 0x16ee020, 0x0, 0x0, 0x20, 0x20, 0x78)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:251 +0x84
inet.af/netstack/tcpip/transport/tcp.(*listenContext).performHandshake(0x14ba000, 0x14a2b40, 0x14c3eb4, 0x16ee020, 0x0, 0x0, 0x20, 0x76f012e0, 0x20)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:319 +0x48
inet.af/netstack/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0x1462180, 0x16ee020, 0x0, 0x0, 0x0, 0x0)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/forwarder.go:155 +0xe8
tailscale.com/wgengine/netstack.(*Impl).acceptTCP(0x18120c0, 0x1462180)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/netstack/netstack.go:439 +0x114
created by inet.af/netstack/tcpip/transport/tcp.(*Forwarder).HandlePacket
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/forwarder.go:94 +0x204
panic: unaligned 64-bit atomic operation

goroutine 737 [running]:
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0x19fe41c, 0x100000, 0x0)
	runtime/internal/atomic/asm_arm.s:278 +0x14
inet.af/netstack/tcpip.(*SocketOptions).SetSendBufferSize(0x19fe3b0, 0x100000, 0x0, 0x8d17f000)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/socketops.go:607 +0x17c
inet.af/netstack/tcpip/transport/tcp.newEndpoint(0x147a380, 0x800, 0x1928160, 0x4)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/endpoint.go:892 +0x1d0
inet.af/netstack/tcpip/transport/tcp.(*listenContext).createConnectingEndpoint(0x14ba000, 0x14a2c80, 0x551be624, 0xaa06662d, 0x1849eb4, 0x1928160, 0xbc5d8d6e, 0x551be624, 0xffff)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:216 +0xac
inet.af/netstack/tcpip/transport/tcp.(*listenContext).startHandshake(0x14ba000, 0x14a2c80, 0x1849eb4, 0x1928160, 0x0, 0x0, 0x30f16062, 0x10, 0x9ae230)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:251 +0x84
inet.af/netstack/tcpip/transport/tcp.(*listenContext).performHandshake(0x14ba000, 0x14a2c80, 0x1849eb4, 0x1928160, 0x0, 0x0, 0x20, 0x76f01088, 0x20)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:319 +0x48
inet.af/netstack/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0x14621e0, 0x1928160, 0x0, 0x0, 0x0, 0x0)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/forwarder.go:155 +0xe8
tailscale.com/wgengine/netstack.(*Impl).acceptTCP(0x18120c0, 0x14621e0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/netstack/netstack.go:439 +0x114
created by inet.af/netstack/tcpip/transport/tcp.(*Forwarder).HandlePacket
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/forwarder.go:94 +0x204
```

**Comment by compliment** [comment]
Different version, different arch 
```
panic: unaligned 64-bit atomic operation

goroutine 193 [running]:
runtime/internal/atomic.panicUnaligned(...)
        runtime/internal/atomic/unaligned.go:8
runtime/internal/atomic.lockAndCheck(...)
        runtime/internal/atomic/atomic_mipsx.go:38
runtime/internal/atomic.Store64(0x214a56c, 0x8000)
        runtime/internal/atomic/atomic_mipsx.go:104 +0x94
inet.af/netstack/atomicbitops.(*AlignedAtomicInt64).Store(...)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/atomicbitops/aligned_64bit.go:39
inet.af/netstack/tcpip.(*SocketOptions).SetReceiveBufferSize(0x214a4f4, 0x8000, 0x0)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/socketops.go:663 +0x1c8
inet.af/netstack/tcpip/transport/udp.newEndpoint(0x2098000, 0x800, 0x20daba0)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/transport/udp/endpoint.go:187 +0x270
inet.af/netstack/tcpip/transport/udp.(*ForwarderRequest).CreateEndpoint(0x20dab80, 0x20daba0)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/transport/udp/forwarder.go:79 +0x11c
tailscale.com/wgengine/netstack.(*Impl).acceptUDP(0x20d3b00, 0x20dab80)
        tailscale.com@v1.16.2/wgengine/netstack/netstack.go:597 +0xb4
inet.af/netstack/tcpip/transport/udp.(*Forwarder).HandlePacket(...)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/transport/udp/forwarder.go:47
tailscale.com/wgengine/netstack.(*Impl).wrapProtoHandler.func1({0x35, {0x236fbcc, 0x4}, 0x9cfa, {0x236fbc8, 0x4}}, 0x206b950)
        tailscale.com@v1.16.2/wgengine/netstack/netstack.go:153 +0x1b8
inet.af/netstack/tcpip/stack.(*nic).DeliverTransportPacket(0x20641e0, 0x11, 0x206b950)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/stack/nic.go:826 +0x370
inet.af/netstack/tcpip/network/ipv4.(*endpoint).handleValidatedPacket(0x20c0800, {0x23bb580, 0x14, 0x40}, 0x206b950, {0x0, 0x0})
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/network/ipv4/ipv4.go:1046 +0x102c
inet.af/netstack/tcpip/network/ipv4.(*endpoint).HandlePacket(0x20c0800, 0x206b950)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/network/ipv4/ipv4.go:836 +0x394
inet.af/netstack/tcpip/stack.(*nic).DeliverNetworkPacket(0x20641e0, {0x0, 0x0}, {0x0, 0x0}, 0x800, 0x206b950)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/stack/nic.go:749 +0x2dc
inet.af/netstack/tcpip/link/channel.(*Endpoint).InjectLinkAddr(...)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/link/channel/channel.go:193
inet.af/netstack/tcpip/link/channel.(*Endpoint).InjectInbound(...)
        inet.af/netstack@v0.0.0-20210622165351-29b14ebc044e/tcpip/link/channel/channel.go:188
tailscale.com/wgengine/netstack.(*Impl).injectInbound(0x20d3b00, 0x2390e60, 0x20ea000)
        tailscale.com@v1.16.2/wgengine/netstack/netstack.go:470 +0x260
tailscale.com/net/tstun.(*Wrapper).filterIn(0x20ea000, {0x251e010, 0x3e, 0xffef})
        tailscale.com@v1.16.2/net/tstun/wrap.go:587 +0xa24
tailscale.com/net/tstun.(*Wrapper).Write(0x20ea000, {0x251e000, 0x4e, 0xffff}, 0x10)
        tailscale.com@v1.16.2/net/tstun/wrap.go:599 +0x94
golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialReceiver(0x217b080)
        golang.zx2c4.com/wireguard@v0.0.0-20210905140043-2ef39d47540c/device/receive.go:477 +0x644
created by golang.zx2c4.com/wireguard/device.(*Peer).Start
        golang.zx2c4.com/wireguard@v0.0.0-20210905140043-2ef39d47540c/device/peer.go:202 +0x3b8
```
```
1.16.2
  tailscale commit: f449111792f662c8552514cf3691c3c1bd7f38e4
  other commit: 3853a3b920c7ec33da2b8ba8454e9ca8b3772774
  go version: go1.17.1-ts097d1284f9
```
MIPS. I was just testing doesn't actually affect anyone.

**Comment by DentonGentry** [comment]
Moved into a new bug report #3233
