### ISSUE TITLE
Windows7-64 bit is failing on exitnode.

### ISSUE THREAD

**Issue by darshinimashar** [tailscale/tailscale#2149]
When you enable exitnode it makes the Tailscale service failed to start. (related to https://github.com/tailscale/tailscale/issues/2133) 

![image (3)](https://user-images.githubusercontent.com/75628398/122267308-ba476200-cea8-11eb-8caf-60beed48c4c6.png)
[1_9_177_windows failure.zip](https://github.com/tailscale/tailscale/files/6664844/1_9_177_windows.failure.zip)
![image (4)](https://user-images.githubusercontent.com/75628398/122268836-8ec57700-ceaa-11eb-8710-89b8fed44796.png)

Tailscale version : 1.9.177 (Unstable)
OS version : Windows 7 - 64 bit
logID : 2f40059955ea4332990d4527c49fcbe24fd4dd93113572626b84aadcd984b7f4

**Comment by crawshaw** [comment]
Does it show the exit node as selected in the UI?

Does it show the -> in the tasbar icon?

Do the logs show any crashes?

If you restart the service from the services menu, does it start?

**Comment by darshinimashar** [comment]
Does it show the exit node as selected in the UI? No , it only shows "Restart windows service.." , About and connect (which is gray out)

Does it show the -> in the tasbar icon? Yes

Do the logs show any crashes? Not in the log, but if I keep checking the status of the tailscale, it goes to stopped -> nostate -> stopped and so on. Also, it keeps creating a new tunnel interface and deleting previous same as restarting tailscale.

If you restart the service from the services menu, does it start? After we manually restart windows services it still stays in the same state sometimes and sometimes it gets stable, but going back to none exit node and reselecting exit node make it fail again.

more info in the attached screen capture.

**Comment by DentonGentry** [comment]
We'll need to check if a new build containing the fix for #2133 also fixes this.

**Comment by DentonGentry** [comment]
Nevermind, 1.9.177 should contain the #2133 fix.

**Comment by DentonGentry** [comment]
I've installed 1.9.177 in a Win7 32 bit VM, the Microsoft IE8 test VM, and do not see this issue.

**Comment by darshinimashar** [comment]
Yes issue is not reproducible on Win7 32 bit. All looks good with win 7 32 bit env.I tested it too

**Comment by darshinimashar** [comment]
2021-06-16 13:20:33.7344627 -0700 -0700: 2021/06/16 13:20:33 magicsock: endpoints changed: 97.108.50.244:60593 (stun), 192.168.18.143:41641 (local)
2021-06-16 13:20:33.7393452 -0700 -0700: panic: LocalBackend.assertClient: b.cc == nil
2021-06-16 13:20:33.7393452 -0700 -0700: goroutine 286 [running]:
2021-06-16 13:20:33.7393452 -0700 -0700: tailscale.com/ipn/ipnlocal.(*LocalBackend).assertClientLocked(...)
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/ipn/ipnlocal/local.go:2393
2021-06-16 13:20:33.7393452 -0700 -0700: tailscale.com/ipn/ipnlocal.(*LocalBackend).nextState(0xc0000b0480, 0x2)
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/ipn/ipnlocal/local.go:2220 +0x535
2021-06-16 13:20:33.7393452 -0700 -0700: tailscale.com/ipn/ipnlocal.(*LocalBackend).stateMachine(0xc0000b0480)
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/ipn/ipnlocal/local.go:2293 +0x32
2021-06-16 13:20:33.7393452 -0700 -0700: tailscale.com/ipn/ipnlocal.(*LocalBackend).setWgengineStatus(0xc0000b0480, 0xc00041d040, 0x0, 0x0)
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/ipn/ipnlocal/local.go:609 +0x232
2021-06-16 13:20:33.7393452 -0700 -0700: tailscale.com/wgengine.(*userspaceEngine).RequestStatus(0xc000028400)
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/wgengine/userspace.go:1002 +0xf1
2021-06-16 13:20:33.7393452 -0700 -0700: tailscale.com/wgengine.NewUserspaceEngine.func2(0xc00041f1d0, 0x2, 0x2)
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/wgengine/userspace.go:272 +0xf5
2021-06-16 13:20:33.7393452 -0700 -0700: tailscale.com/wgengine/magicsock.(*Conn).updateEndpoints(0xc0000b3340, 0x9be0c2, 0xe)
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/wgengine/magicsock/magicsock.go:588 +0x31e
2021-06-16 13:20:33.7393452 -0700 -0700: created by tailscale.com/wgengine/magicsock.(*Conn).updateEndpoints.func1
2021-06-16 13:20:33.7393452 -0700 -0700: 	tailscale.com@v1.1.1-0.20210616035303-93378260115b/wgengine/magicsock/magicsock.go:546 +0x3a6
2021-06-16 13:20:33.8155122 -0700 -0700: subprocess exited: exit status 2
2021-06-16 13:20:33.8155122 -0700 -0700: BabysitProc: backoff: 905 msec
2021-06-16 13:20:34.7353923 -0700 -0700: exec: "C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe" [/subproc 2f40059955ea4332990d4527c49fcbe24fd4dd93113572626b84aadcd984b7f4]
2021-06-16 13:20:34.7373453 -0700 -0700: 2021/06/16 13:20:34 Program starting: v1.9.177-t933782601-g71ce4c657: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe", "/subproc", "2f40059955ea4332990d4527c49fcbe24fd4dd93113572626b84aadcd984b7f4"}
2021-06-16 13:20:34.7373453 -0700 -0700: 2021/06/16 13:20:34 subproc mode: logid=2f40059955ea4332990d4527c49fcbe24fd4dd93113572626b84aadcd984b7f4
2021-06-16 13:20:34.7373453 -0700 -0700: 2021/06/16 13:20:34 Listening on 127.0.0.1:41112
2021-06-16 13:20:34.7373453 -0700 -0700: 2021/06/16 13:20:34 tailscaled: getting engine... (try 1)
2021-06-16 13:20:35.0361597 -0700 -0700: 2021/06/16 13:20:35 [Wintun] CreateAdapter: Creating adapter
2021-06-16 13:20:35.1181872 -0700 -0700: 2021/06/16 13:20:35 [Wintun] SelectDriver: Using existing driver 0.10
2021-06-16 13:20:35.5478544 -0700 -0700: 2021/06/16 13:20:35 waitInterfaceUp: TUN interface already up; no need to wait
2021-06-16 13:20:35.6503869 -0700 -0700: 2021/06/16 13:20:35 winhttp: Open: The parameter is incorrect.
2021-06-16 13:20:35.6503869 -0700 -0700: 2021/06/16 13:20:35 tshttpproxy: winhttp: GetProxyForURL("https://login.tailscale.com/"): ERROR_INVALID_PARAMETER [unexpected]

**Comment by DentonGentry** [comment]
I downloaded the image Darshini used and tried to set it up to boot, but within the VM set up in Proxmox it just says, "Booting from Hard Disk..." and hangs forever. Will debug tomorrow.

**Comment by crawshaw** [comment]
@darshinimashar could you please repeat the exit node test with 1.8.7 on win7 64-bit? If this isn't a regression we shouldn't block 1.10 on it.

Looking at the panic logs you pasted, it's some sort of state machine bug. Somehow magicsock is up and getting its endpoints updated (presumably from a netlink change), but the ipn package hasn't started up a controlclient yet. That means something, somewhere is being initialized too early.

**Comment by DentonGentry** [comment]
I've had no luck getting Win7 x64 installed:
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ IE11 Win7 VMWare is the one Darshini used, and even after downloading it afresh, after converting to qcow2 it doesn't boot at all in Proxmox.
The VirtualBox and Hyper-V versions install in Proxmox as 32 bit after converting to qcow2.

**Comment by Xe** [comment]
I'm seeing this on my Windows 7 VM too. Having tailscale running at all breaks DNS entirely as far as I have observed, even if you tell tailscale to not manipulate DNS settings. It also breaks DNS in Firefox.

**Comment by DentonGentry** [comment]
@Xe : when you have an exit node enabled, you see a different set of symptoms with Win7 x64 than Darshini did? Darshini's system wouldn't start the frontend. Your system can start the frontend, but DNS is broken?

**Comment by DentonGentry** [comment]
I think we've determined that we see the same behaviors on Win7 x64 with Tailscale 1.8.7.

**Comment by crawshaw** [comment]
As it's not a regression with 1.10, removing from the 1.10.0 blockers.

**Comment by wizzard0** [comment]
fyi: utm.app is 32bit only

**Comment by DentonGentry** [comment]
So far as I can tell, Win7-64 now works with an exit node enabled.
Barring further comment, we'll expect to close this during the next bug scrub.

**Comment by DentonGentry** [comment]
ETIMEDOUT
