### ISSUE TITLE
Exit node usage broken on NixOS unstable

### ISSUE THREAD

**Issue by Xe** [tailscale/tailscale#2184]
```[root@bandetto:~]# cat /etc/os-release
NAME=NixOS
ID=nixos
VERSION="21.11pre296557.33d42ad7cf2 (Porcupine)"
VERSION_CODENAME=porcupine
VERSION_ID="21.11pre296557.33d42ad7cf2"
PRETTY_NAME="NixOS 21.11 (Porcupine)"
LOGO="nix-snowflake"
HOME_URL="https://nixos.org/"
DOCUMENTATION_URL="https://nixos.org/learn.html"
SUPPORT_URL="https://nixos.org/community.html"
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
```

With the following config options:

```nix
# bandetto.nix
{ config, pkgs, modulesPath, ... }:
let
  fetchKeys = username:
    (builtins.fetchurl "https://github.com/${username}.keys");
in {
  imports = [ (modulesPath + "/profiles/qemu-guest.nix") ];

  services.openssh.enable = true;

  boot.initrd.availableKernelModules =
    [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/vda";

  nixpkgs.config.allowUnfree = true;

  fileSystems."/" = {
    device = "/dev/vda1";
    fsType = "ext4";
  };

  users.users.root.openssh.authorizedKeys.keyFiles = [ (fetchKeys "Xe") ];

  services.qemuGuest.enable = true;

  networking.hostName = "bandetto";
  services.tailscale.enable = true;
}
```

And an exit node that works on my iPhone (100.89.21.74), networking to the outside world breaks on NixOS unstable. Attempting to reset tailscaled breaks things horribly:

```Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: quit
Jun 21 20:35:42 bandetto tailscaled[794]: control: Client.Shutdown done.
Jun 21 20:35:42 bandetto tailscaled[794]: using backend prefs
Jun 21 20:35:42 bandetto tailscaled[794]: backend prefs for "_daemon": Prefs{ra=false dns=true want=true exit=100.103.44.76 lan=true routes=[] nf=on Persist{lm=, o=, n=[FTLHS] u="Xe
(cetacean)"}}
Jun 21 20:35:42 bandetto tailscaled[794]: active login:
Jun 21 20:35:42 bandetto tailscaled[794]: netmap packet filter: (not ready yet)
Jun 21 20:35:42 bandetto tailscaled[794]: control: HostInfo: {"IPNVersion":"1.8.7","BackendLogID":"7ca8576e9b3a6bc91fa1ef20897d6cc9d9bf42a8e84a83435add361039c9ff61","OS":"linux","OS
Version":"NixOS 21.11 (Porcupine); kernel=5.10.44","Hostname":"bandetto","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd_config [listener] 0 of 10-100 star
tups"},{"Proto":"tcp","Port":35796,"Description":"tailscaled"}],"NetInfo":{"MappingVariesByDestIP":null,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":false,"UPnP":false,"PMP"
:false,"PCP":false,"PreferredDERP":1}}
Jun 21 20:35:42 bandetto tailscaled[794]: control: client.newEndpoints(0, [10.77.131.212:41641])
Jun 21 20:35:42 bandetto tailscaled[794]: Backend: logs: be:7ca8576e9b3a6bc91fa1ef20897d6cc9d9bf42a8e84a83435add361039c9ff61 fe:
Jun 21 20:35:42 bandetto tailscaled[794]: control: client.Login(false, 0)
Jun 21 20:35:42 bandetto tailscaled[794]: [RATELIMIT] format("control: authRoutine: %s; wantLoggedIn=%v") (7 dropped)
Jun 21 20:35:42 bandetto tailscaled[794]: control: authRoutine: state:new; wantLoggedIn=true
Jun 21 20:35:42 bandetto tailscaled[794]: [RATELIMIT] format("control: direct.TryLogin(token=%v, flags=%v)") (7 dropped)
Jun 21 20:35:42 bandetto tailscaled[794]: control: direct.TryLogin(token=false, flags=0)
Jun 21 20:35:42 bandetto tailscaled[794]: [RATELIMIT] format("control: doLogin(regen=%v, hasUrl=%v)") (7 dropped)
Jun 21 20:35:42 bandetto tailscaled[794]: control: doLogin(regen=false, hasUrl=false)
Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: state:authenticating
Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: new map needed while idle.
Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: state:authenticating
Jun 21 20:35:42 bandetto tailscaled[794]: control: HostInfo: {"IPNVersion":"1.8.7","BackendLogID":"7ca8576e9b3a6bc91fa1ef20897d6cc9d9bf42a8e84a83435add361039c9ff61","OS":"linux","OS
Version":"NixOS 21.11 (Porcupine); kernel=5.10.44","Hostname":"bandetto","GoArch":"amd64","Services":[{"Proto":"peerapi4","Port":35796},{"Proto":"peerapi6","Port":35796}],"NetInfo":
{"MappingVariesByDestIP":null,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":false,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":1}}
Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: new map needed while idle.
Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: state:authenticating
Jun 21 20:35:42 bandetto tailscaled[794]: control: HostInfo: {"IPNVersion":"1.8.7","BackendLogID":"7ca8576e9b3a6bc91fa1ef20897d6cc9d9bf42a8e84a83435add361039c9ff61","OS":"linux","OS
Version":"NixOS 21.11 (Porcupine); kernel=5.10.44","Hostname":"bandetto","GoArch":"amd64","Services":[{"Proto":"peerapi4","Port":35796},{"Proto":"peerapi6","Port":35796}],"NetInfo":
{"MappingVariesByDestIP":null,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":false,"UPnP":false,"PMP":false,"PCP":false,"PreferredDERP":1}}
Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: new map needed while idle.
Jun 21 20:35:42 bandetto tailscaled[794]: control: mapRoutine: state:authenticating
Jun 21 20:35:44 bandetto tailscaled[794]: logtail: dial "log.tailscale.io:443" failed: dial tcp 34.210.105.16:443: i/o timeout (in 30.001s)
Jun 21 20:35:44 bandetto tailscaled[794]: logtail: upload: log upload of 769 bytes compressed failed: Post "https://log.tailscale.io/c/tailnode.log.tailscale.io/e0206fe5463a42de33b2
b3c0f1ec099de09b85224d0ea4f22ce757ed93311c63": dial tcp 34.210.105.16:443: i/o timeout
Jun 21 20:35:44 bandetto tailscaled[794]: logtail: backoff: 4304 msec
Jun 21 20:35:45 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): dial tcp6 [2604:a880:400:d1::828:b001]:443: connect: ne
twork is unreachable
Jun 21 20:35:45 bandetto tailscaled[794]: derphttp.Client.Send: connecting to derp-1 (nyc)
Jun 21 20:35:48 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): context deadline exceeded
Jun 21 20:35:48 bandetto tailscaled[794]: derphttp.Client.Send: connecting to derp-1 (nyc)
Jun 21 20:35:48 bandetto tailscaled[794]: [RATELIMIT] format("%s: connecting to derp-%d (%v)")
Jun 21 20:35:51 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): context deadline exceeded
Jun 21 20:35:54 bandetto tailscaled[794]: magicsock: [0xc0000e80c0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): dial tcp6 [2604:a880:400:d1::828:b001]:443: co
nnect: network is unreachable
Jun 21 20:35:54 bandetto tailscaled[794]: derp-1: backoff: 3162 msec
Jun 21 20:35:57 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): context deadline exceeded
Jun 21 20:35:57 bandetto tailscaled[794]: [RATELIMIT] format("%s: connecting to derp-%d (%v)") (2 dropped)
Jun 21 20:35:57 bandetto tailscaled[794]: derphttp.Client.Send: connecting to derp-1 (nyc)
Jun 21 20:36:00 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): dial tcp6 [2604:a880:400:d1::828:b001]:443: connect: ne
twork is unreachable
Jun 21 20:36:00 bandetto tailscaled[794]: derphttp.Client.Recv: connecting to derp-1 (nyc)
Jun 21 20:36:03 bandetto tailscaled[794]: magicsock: [0xc0000e80c0] derp.Recv(derp-1): derphttp.Client.Recv connect to region 1 (nyc): context deadline exceeded
Jun 21 20:36:03 bandetto tailscaled[794]: derp-1: backoff: 6264 msec
Jun 21 20:36:03 bandetto tailscaled[794]: derphttp.Client.Send: connecting to derp-1 (nyc)
Jun 21 20:36:03 bandetto tailscaled[794]: [RATELIMIT] format("%s: connecting to derp-%d (%v)")
Jun 21 20:36:06 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): context deadline exceeded
Jun 21 20:36:09 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): context deadline exceeded
Jun 21 20:36:12 bandetto tailscaled[794]: magicsock: derp.Send(127.3.3.40:1): derphttp.Client.Send connect to region 1 (nyc): dial tcp6 [2604:a880:400:d1::828:b001]:443: connect: network is unreachable
```

While tailscale is in this state, tailscale status reports an unexpected state:

```[root@bandetto:~]# tailscale status
unexpected state: NoState
```

`tailscale up` also hangs infinitely and if you SIGQUIT it, you get this stacktrace:

```
[root@bandetto:~]# tailscale up --reset
^\SIGQUIT: quit
PC=0x46eae1 m=0 sigcode=128
goroutine 26 [syscall]:
runtime.notetsleepg(0xb92a20, 0xffffffffffffffff, 0x0)
        runtime/lock_futex.go:235 +0x34 fp=0xc000042798 sp=0xc000042768 pc=0x40c3f4
os/signal.signal_recv(0x0)
        runtime/sigqueue.go:168 +0xa5 fp=0xc0000427c0 sp=0xc000042798 pc=0x4699a5
os/signal.loop()
        os/signal/signal_unix.go:23 +0x25 fp=0xc0000427e0 sp=0xc0000427c0 pc=0x7500a5
runtime.goexit()
        runtime/asm_amd64.s:1371 +0x1 fp=0xc0000427e8 sp=0xc0000427e0 pc=0x46ccc1
created by os/signal.Notify.func1.1
        os/signal/signal.go:151 +0x45
goroutine 1 [select]:
tailscale.com/cmd/tailscale/cli.runUp(0x928eb0, 0xc0000a6010, 0xc00008e170, 0x0, 0x0, 0x0, 0x0)
        tailscale.com/cmd/tailscale/cli/up.go:455 +0xa5e
github.com/peterbourgon/ff/v2/ffcli.(*Command).Run(0xb59020, 0x928eb0, 0xc0000a6010, 0x0, 0x0)
        github.com/peterbourgon/ff/v2@v2.0.0/ffcli/command.go:139 +0x1a2
github.com/peterbourgon/ff/v2/ffcli.(*Command).Run(0xc0000d4580, 0x928eb0, 0xc0000a6010, 0x0, 0x0)
        github.com/peterbourgon/ff/v2@v2.0.0/ffcli/command.go:143 +0x113
tailscale.com/cmd/tailscale/cli.Run(0xc00008e160, 0x2, 0x2, 0x0, 0x0)
        tailscale.com/cmd/tailscale/cli/cli.go:130 +0x505
main.main()
        tailscale.com/cmd/tailscale/tailscale.go:23 +0xcf
goroutine 23 [select]:
tailscale.com/cmd/tailscale/cli.connect.func2(0x928e78, 0xc0000b1b80, 0x92c1f0, 0xc0000aa2d0, 0xc00008d960)
        tailscale.com/cmd/tailscale/cli/cli.go:165 +0x131
created by tailscale.com/cmd/tailscale/cli.connect
        tailscale.com/cmd/tailscale/cli/cli.go:162 +0x17f
goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x7f58692166a0, 0x72, 0xffffffffffffffff)
        runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc000110518, 0x72, 0x0, 0x4, 0xffffffffffffffff)
        internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000110500, 0xc00001813c, 0x4, 0x4, 0x0, 0x0, 0x0)
        internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc000110500, 0xc00001813c, 0x4, 0x4, 0x0, 0x0, 0x0)
        net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0000aa2d0, 0xc00001813c, 0x4, 0x4, 0x0, 0x0, 0x0)
        net/net.go:183 +0x91
io.ReadAtLeast(0x9227e0, 0xc0000aa2d0, 0xc00001813c, 0x4, 0x4, 0x4, 0x881de0, 0x9227e0, 0x0)
        io/io.go:328 +0x87
io.ReadFull(...)
        io/io.go:347
tailscale.com/ipn.ReadMsg(0x9227e0, 0xc0000aa2d0, 0xc0000aa2d0, 0x9227e0, 0xc0000aa2d0, 0x0, 0x0)
        tailscale.com/ipn/message.go:334 +0x9a
tailscale.com/cmd/tailscale/cli.pump(0x928e78, 0xc0000b1b80, 0xc0000c45e0, 0x92c1f0, 0xc0000aa2d0, 0x0, 0x0)
        tailscale.com/cmd/tailscale/cli/cli.go:185 +0xed
tailscale.com/cmd/tailscale/cli.runUp.func3(0xc0000ad440, 0x928e78, 0xc0000b1b80, 0xc0000c45e0, 0x92c1f0, 0xc0000aa2d0)
        tailscale.com/cmd/tailscale/cli/up.go:352 +0x5a
created by tailscale.com/cmd/tailscale/cli.runUp
        tailscale.com/cmd/tailscale/cli/up.go:352 +0x6d1
rax    0xca
rbx    0xb64400
rcx    0x46eae3
rdx    0x0
rdi    0xb92a20
rsi    0x80
rbp    0xc000042720
rsp    0xc0000426d8
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0xf1
r13    0x0
r14    0x9175ec
r15    0x0
rip    0x46eae1
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

Here are the contents of `/etc/resolv.conf`:

```[root@bandetto:~]# cat /etc/resolv.conf
# Generated by resolvconf
search cetacean.org.github.beta.tailscale.net akua.xeserv.us
nameserver 100.100.100.100
options edns0
```

My VM is using `/nix/store/h1bga03hy7gpfq8ka7i63rh6hvswfq8d-tailscale-1.8.7/bin/tailscaled` as its tailscaled install.

**Comment by alarsyo** [comment]
Can confirm I'm seeing similar behavior here, on a NixOS 21.05 stable machine.

Exit node is also a NixOS 21.05 machine, but I've verified the exit node itself wasn't a problem by using it from an Android phone as well as from an Archlinux laptop.

**Comment by pimeys** [comment]
I'm also facing this issue with Tailscale version 1.10.2 on NixOS unstable.

**Comment by DentonGentry** [comment]
I don't have a way to test this on current nixOS unstable, but will note that there have been no recent reports.

**Comment by alarsyo** [comment]
I've tried this again without luck about a month ago, I can try again tomorrow and provide more info if needed

**Comment by DentonGentry** [comment]
I don't have a way to test this on current nixOS unstable, but will note that there have been no recent reports. As this is the second time we've noted the lack of recent reports, I'm closing this.

**Comment by alarsyo** [comment]
> I can try again tomorrow and provide more info if needed

Sorry haha, I apparently completely forgot to come back and report my findings.

It looks like it got fixed at some point indeed, I can use an exit node just fine from nixos-unstable now. Thanks!
