### ISSUE TITLE
magicsock: test flake

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2228]
On macOS at HEAD.

```
panic: please use tailscale.com/logger.Logf instead of the log package (tried to log: "2021/06/23 06:21:41 netns: DefaultRouteInterfaceIndex: route.FetchRIB: sysctl: cannot allocate memory\n")

goroutine 1590 [running]:
tailscale.com/tstest.panicLogWriter.Write(0xc00008a000, 0x66, 0x70, 0x60d33565, 0xc00008a000, 0xc00008a000)
	/Users/crawshaw/repo/corp/gohack/tailscale.com/tstest/log.go:49 +0x17f
log.(*Logger).Output(0xc000096050, 0x2, 0xc00063e060, 0x51, 0x0, 0x0)
	/Users/crawshaw/repo/goroot/src/log/log.go:184 +0x284
log.Printf(0x15a2cb2, 0x25, 0xc000f178e8, 0x1, 0x1)
	/Users/crawshaw/repo/goroot/src/log/log.go:323 +0x85
tailscale.com/net/netns.control(0x1591f98, 0x4, 0xc000cdbe75, 0xb, 0x1633d80, 0xc001102080, 0xc0006f7400, 0xffff)
	/Users/crawshaw/repo/corp/gohack/tailscale.com/net/netns/netns_darwin_tailscaled.go:30 +0xf3
net.(*netFD).listenDatagram(0xc0006f7400, 0x1636768, 0xc0006dbbc0, 0x15b6ff8, 0x0, 0x0)
	/Users/crawshaw/repo/goroot/src/net/sock_posix.go:241 +0x3e8
net.socket(0x1634af0, 0xc00002a070, 0x1591f98, 0x4, 0x1e, 0x2, 0x0, 0x1, 0x1636768, 0xc0006dbbc0, ...)
	/Users/crawshaw/repo/goroot/src/net/sock_posix.go:63 +0x377
net.internetSocket(0x1634af0, 0xc00002a070, 0x1591f98, 0x4, 0x1636768, 0xc0006dbbc0, 0x0, 0x0, 0x2, 0x0, ...)
	/Users/crawshaw/repo/goroot/src/net/ipsock_posix.go:141 +0x145
net.(*sysListener).listenUDP(0xc000f17c78, 0x1634af0, 0xc00002a070, 0xc0006dbbc0, 0x162f5e8, 0xc0006dbbc0, 0x4)
	/Users/crawshaw/repo/goroot/src/net/udpsock_posix.go:106 +0xb7
net.(*ListenConfig).ListenPacket(0xc000f17d38, 0x1634af0, 0xc00002a070, 0x1591f98, 0x4, 0xc000cdbe50, 0xb, 0xc000cdbe46, 0x5, 0xc000cdbe50, ...)
	/Users/crawshaw/repo/goroot/src/net/dial.go:666 +0x5d9
tailscale.com/wgengine/magicsock.(*Conn).listenPacket(0xc0004db8c0, 0x1591f98, 0x4, 0x0, 0x1, 0xc00000e108, 0xf1d7, 0x4, 0xc001102078, 0x0, ...)
	/Users/crawshaw/repo/corp/gohack/tailscale.com/wgengine/magicsock/magicsock.go:2630 +0x272
tailscale.com/wgengine/magicsock.(*Conn).bindSocket(0xc0004db8c0, 0xc0004db928, 0x1591f98, 0x4, 0x0, 0x0, 0x0)
	/Users/crawshaw/repo/corp/gohack/tailscale.com/wgengine/magicsock/magicsock.go:2685 +0x2fa
tailscale.com/wgengine/magicsock.(*Conn).rebind(0xc0004db8c0, 0xc000f17f00, 0x20, 0x1)
	/Users/crawshaw/repo/corp/gohack/tailscale.com/wgengine/magicsock/magicsock.go:2714 +0x145
tailscale.com/wgengine/magicsock.(*Conn).Rebind(0xc0004db8c0)
	/Users/crawshaw/repo/corp/gohack/tailscale.com/wgengine/magicsock/magicsock.go:2723 +0x45
tailscale.com/wgengine/magicsock.TestRebindStress.func4(0xc000487060, 0xc0004db8c0)
	/Users/crawshaw/repo/corp/gohack/tailscale.com/wgengine/magicsock/magicsock_test.go:1537 +0x65
created by tailscale.com/wgengine/magicsock.TestRebindStress
	/Users/crawshaw/repo/corp/gohack/tailscale.com/wgengine/magicsock/magicsock_test.go:1534 +0x252
FAIL	tailscale.com/wgengine/magicsock	12.639s
ok  	tailscale.com/wgengine/monitor	(cached)
?   	tailscale.com/wgengine/netstack	[no test files]
?   	tailscale.com/wgengine/router	[no test files]
ok  	tailscale.com/wgengine/wgcfg	(cached)
?   	tailscale.com/wgengine/wgcfg/nmcfg	[no test files]
ok  	tailscale.com/wgengine/wglog	(cached)
FAIL
```

**Comment by DentonGentry** [comment]
This has not been seen in over a year.
