### ISSUE TITLE
net/dns/resolver: TestDelegate/hugetxt fails on macOS

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2229]
I guess we don't run tailscale/tailscale repo's CI on macOS. This is failing at HEAD, currently ece138ffc3335f49eaff85b71f5cc753f57bbdca, on macOS 11.2.3 (20D91).

```
crow5k:tailscale.com $ go test -count=1 -v ./net/dns/resolver
=== RUN   TestRDNSNameToIPv4
=== RUN   TestRDNSNameToIPv4/valid
=== RUN   TestRDNSNameToIPv4/double_dot
=== RUN   TestRDNSNameToIPv4/overflow
=== RUN   TestRDNSNameToIPv4/not_ip
--- PASS: TestRDNSNameToIPv4 (0.00s)
    --- PASS: TestRDNSNameToIPv4/valid (0.00s)
    --- PASS: TestRDNSNameToIPv4/double_dot (0.00s)
    --- PASS: TestRDNSNameToIPv4/overflow (0.00s)
    --- PASS: TestRDNSNameToIPv4/not_ip (0.00s)
=== RUN   TestRDNSNameToIPv6
=== RUN   TestRDNSNameToIPv6/valid
=== RUN   TestRDNSNameToIPv6/double_dot
=== RUN   TestRDNSNameToIPv6/double_hex
=== RUN   TestRDNSNameToIPv6/not_hex
--- PASS: TestRDNSNameToIPv6 (0.00s)
    --- PASS: TestRDNSNameToIPv6/valid (0.00s)
    --- PASS: TestRDNSNameToIPv6/double_dot (0.00s)
    --- PASS: TestRDNSNameToIPv6/double_hex (0.00s)
    --- PASS: TestRDNSNameToIPv6/not_hex (0.00s)
=== RUN   TestResolveLocal
=== RUN   TestResolveLocal/ipv4
=== RUN   TestResolveLocal/ipv6
=== RUN   TestResolveLocal/no-ipv6
=== RUN   TestResolveLocal/nxdomain
=== RUN   TestResolveLocal/foreign_domain
=== RUN   TestResolveLocal/all
=== RUN   TestResolveLocal/mx-ipv4
=== RUN   TestResolveLocal/mx-ipv6
=== RUN   TestResolveLocal/mx-nxdomain
=== RUN   TestResolveLocal/ns-nxdomain
=== RUN   TestResolveLocal/onion-domain
--- PASS: TestResolveLocal (0.00s)
    --- PASS: TestResolveLocal/ipv4 (0.00s)
    --- PASS: TestResolveLocal/ipv6 (0.00s)
    --- PASS: TestResolveLocal/no-ipv6 (0.00s)
    --- PASS: TestResolveLocal/nxdomain (0.00s)
    --- PASS: TestResolveLocal/foreign_domain (0.00s)
    --- PASS: TestResolveLocal/all (0.00s)
    --- PASS: TestResolveLocal/mx-ipv4 (0.00s)
    --- PASS: TestResolveLocal/mx-ipv6 (0.00s)
    --- PASS: TestResolveLocal/mx-nxdomain (0.00s)
    --- PASS: TestResolveLocal/ns-nxdomain (0.00s)
    --- PASS: TestResolveLocal/onion-domain (0.00s)
=== RUN   TestResolveLocalReverse
=== RUN   TestResolveLocalReverse/ipv4
=== RUN   TestResolveLocalReverse/ipv6
=== RUN   TestResolveLocalReverse/nxdomain
--- PASS: TestResolveLocalReverse (0.00s)
    --- PASS: TestResolveLocalReverse/ipv4 (0.00s)
    --- PASS: TestResolveLocalReverse/ipv6 (0.00s)
    --- PASS: TestResolveLocalReverse/nxdomain (0.00s)
=== RUN   TestDelegate
=== RUN   TestDelegate/ipv4
=== RUN   TestDelegate/ipv6
=== RUN   TestDelegate/ns
=== RUN   TestDelegate/nxdomain
=== RUN   TestDelegate/smalltxt
=== RUN   TestDelegate/medtxt
=== RUN   TestDelegate/largetxt
=== RUN   TestDelegate/xlargetxt
=== RUN   TestDelegate/hugetxt
panic: write udp 127.0.0.1:52706->127.0.0.1:51798: sendmsg: message too long

goroutine 172 [running]:
tailscale.com/net/dns/resolver.resolveToTXT.func1(0x14b0f10, 0xc0001ac600, 0xc00013eab0)
        /Users/bradfitz/src/tailscale.com/net/dns/resolver/tsdns_server_test.go:97 +0x32e
github.com/miekg/dns.HandlerFunc.ServeDNS(0xc0002ba0c0, 0x14b0f10, 0xc0001ac600, 0xc00013eab0)
        /Users/bradfitz/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:37 +0x44
github.com/miekg/dns.(*ServeMux).ServeDNS(0xc0002ba0e0, 0x14b0f10, 0xc0001ac600, 0xc00013eab0)
        /Users/bradfitz/pkg/mod/github.com/miekg/dns@v1.1.42/serve_mux.go:103 +0x5d
github.com/miekg/dns.(*Server).serveDNS(0xc000412120, 0xc000346200, 0x1a, 0x200, 0xc0001ac600)
        /Users/bradfitz/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:651 +0x2fd
github.com/miekg/dns.(*Server).serveUDPPacket(0xc000412120, 0xc00029a264, 0xc000346200, 0x1a, 0x200, 0x14af0a8, 0xc0002ce010, 0xc00006efa0, 0x0, 0x0)
        /Users/bradfitz/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:591 +0xed
created by github.com/miekg/dns.(*Server).serveUDP
        /Users/bradfitz/pkg/mod/github.com/miekg/dns@v1.1.42/server.go:521 +0x395
FAIL    tailscale.com/net/dns/resolver  0.017s
FAIL
```

**Comment by bradfitz** [comment]
Ah, the internets suggest this is due to:

```
$ sysctl net.inet.udp.maxdgram
net.inet.udp.maxdgram: 9216
```

**Comment by bradfitz** [comment]
Binary searching for the largest `N` for `hugeTXT := generateTXT(N, randSource)`, I find that

```go
        hugeTXT := generateTXT(9068, randSource)
```

... makes the test hang.

I'm just going to skip this test on macOS for now.

**Comment by MikaelUrankar** [comment]
It also fails on FreeBSD, according to truss, net.inet.udp.maxdgram should be at least 64580 
```
 8058: sendmsg(7,{{ AF_INET6 [::1]:51454 },28,[{"\0\0\M^@\0\0\^A\0\^A\0\0\0\0\^Dh"...,64580}],1,{{level=IPPROTO_IPV6,type=IPV6_PKTINFO,data={0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00}}},40,0},0) ERR#40 'Message too long'
```
