### ISSUE TITLE
Tailscale v1.8.3 used as Exit Node on Synology DiskStation process panic

### ISSUE THREAD

**Issue by saturnism** [tailscale/tailscale#2260]
I was running Tailscale on Synology DS212j (arm 32bit) with Tailscale v1.6.0. I had it configured as exit node and used it successfully from another device.

I upgraded to v1.8.3, and discovered that when another device used it as an exit node, the traffic was not flowing through. I was able to observe the Tailscale log with the following messages as the device attempts to open a connection.

I downgraded the package to v1.6.0 and exit node works again (w/o other non-related issues).

```
2021/06/26 20:01:14 magicsock: got disco message from idle peer, starting lazy conf for [33CFp], d:53f86acdbdd6e9a0
2021/06/26 20:01:14 wgengine: idle peer d:53f86acdbdd6e9a0 now active, reconfiguring wireguard
2021/06/26 20:01:14 wgengine: Reconfig: configuring userspace wireguard config (with 2/2 peers)
2021/06/26 20:01:14 magicsock: ParseEndpoint: key=[33CFp]: 53f86acdbdd6e9a0ea257f819b31b03e6375b8b1a8b631af6cd82fe6018e640a.disco.tailscale:12345
2021/06/26 20:01:14 magicsock: lazy endpoint created via disco message for [33CFp], d:53f86acdbdd6e9a0
2021/06/26 20:01:14 monitor: RTM_NEWROUTE: src=, dst=fd22:4e39:e630:1:184e:becf:2217:2f69/128, gw=fd22:4e39:e630:1:184e:becf:2217:2f69, outif=2, table=254
2021/06/26 20:01:14 magicsock: disco: node [33CFp] d:53f86acdbdd6e9a0 now using 192.168.1.2:41641
2021/06/26 20:01:14 acceptUDP: could not create endpoint: no route
2021/06/26 20:01:14 acceptUDP: could not create endpoint: no route
2021/06/26 20:01:14 acceptUDP: could not create endpoint: no route
2021/06/26 20:01:16 monitor: RTM_NEWROUTE: src=, dst=ff02::1:fff3:a01e/128, gw=ff02::1:fff3:a01e, outif=2, table=255
2021/06/26 20:01:16 acceptUDP: could not create endpoint: no route
2021/06/26 20:01:16 acceptUDP: could not create endpoint: no route
2021/06/26 20:01:16 [RATELIMIT] format("acceptUDP: could not create endpoint: %v")
2021/06/26 20:01:24 Accept: TCP{100.76.244.44:60222 > 100.119.196.40:5001} 137 tcp non-syn
2021/06/26 20:01:28 [RATELIMIT] format("acceptUDP: could not create endpoint: %v") (4 dropped)
2021/06/26 20:01:28 acceptUDP: could not create endpoint: no route
2021/06/26 20:01:28 acceptUDP: could not create endpoint: no route
2021/06/26 20:01:28 [RATELIMIT] format("acceptUDP: could not create endpoint: %v")
2021/06/26 20:01:34 monitor: RTM_DELROUTE: src=, dst=fe80::1e6e:42ff:fe2a:e1c2/128, gw=fe80::1e6e:42ff:fe2a:e1c2, outif=2, table=3
2021/06/26 20:01:34 monitor: RTM_DELROUTE: src=, dst=ff02::1:ff0f:b694/128, gw=ff02::1:ff0f:b694, outif=2, table=255
2021/06/26 20:01:37 Drop: ICMPv4{100.102.175.66:0 > 100.100.100.100:0} 56 destination not allowed
2021/06/26 20:01:37 Drop: ICMPv4{100.102.175.66:0 > 100.100.100.100:0} 56 destination not allowed
2021/06/26 20:01:37 Drop: ICMPv4{100.102.175.66:0 > 100.100.100.100:0} 56 destination not allowed
2021/06/26 20:01:37 Drop: ICMPv4{100.102.175.66:0 > 100.100.100.100:0} 56 destination not allowed
2021/06/26 20:01:37 Drop: ICMPv4{100.102.175.66:0 > 100.100.100.100:0} 56 destination not allowed
2021/06/26 20:01:37 [RATELIMIT] format("%s: %s %d %s\n%s")
panic: unaligned 64-bit atomic operation

goroutine 1102 [running]:
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Store64(0xf79f1c, 0x100000, 0x0)
	runtime/internal/atomic/asm_arm.s:278 +0x14
inet.af/netstack/tcpip.(*SocketOptions).SetSendBufferSize(0xf79eb0, 0x100000, 0x0, 0x728c7400)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/socketops.go:607 +0x17c
inet.af/netstack/tcpip/transport/tcp.newEndpoint(0xc70380, 0x800, 0xfbb000, 0x4)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/endpoint.go:892 +0x1d0
inet.af/netstack/tcpip/transport/tcp.(*listenContext).createConnectingEndpoint(0xcb2180, 0xc9b180, 0x287fa9f0, 0x64c9280e, 0x1001eb4, 0xfbb000, 0x92d46db8, 0x287fa9f0, 0x0)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:216 +0xac
inet.af/netstack/tcpip/transport/tcp.(*listenContext).startHandshake(0xcb2180, 0xc9b180, 0x1001eb4, 0xfbb000, 0x0, 0x0, 0x3523c0, 0x569e90, 0x0)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:251 +0x84
inet.af/netstack/tcpip/transport/tcp.(*listenContext).performHandshake(0xcb2180, 0xc9b180, 0x1001eb4, 0xfbb000, 0x0, 0x0, 0x20, 0x40000088, 0x20)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/accept.go:319 +0x48
inet.af/netstack/tcpip/transport/tcp.(*ForwarderRequest).CreateEndpoint(0xcfe7e0, 0xfbb000, 0x0, 0x0, 0x0, 0x0)
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/forwarder.go:155 +0xe8
tailscale.com/wgengine/netstack.(*Impl).acceptTCP(0xf85740, 0xcfe7e0)
	tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/netstack/netstack.go:439 +0x114
created by inet.af/netstack/tcpip/transport/tcp.(*Forwarder).HandlePacket
	inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/forwarder.go:94 +0x204
```

**Comment by bradfitz** [comment]
This was fixed in 1.10. We might need to roll new Synology packages.

**Comment by alex88** [comment]
@saturnism how did you configure the synology package to run as an exit node?

**Comment by saturnism** [comment]
> @saturnism how did you configure the synology package to run as an exit node? I'm on DSM 7

A couple of steps in general:
1. Tailscale up with  advertise exit node, but also turn netfilter-mode off explicitly with v1.6.0.
2. configure iptable rules manually

This thread helped me understand the netfilter issue: https://github.com/tailscale/tailscale/issues/451

These threads helped me understand more on where Synology keeps a modules list, and handy examples:
 https://galaxysd.github.io/linux/20170804/2017-08-04-iptables-on-Synology-DSM-6
https://community.synology.com/enu/forum/1/post/123676

**Comment by saturnism** [comment]
Just noticed this issue seems to be a duplicate of https://github.com/tailscale/tailscale/issues/2129.
Also, Tailscale 1.10 package now available: https://github.com/tailscale/tailscale-synology/releases/tag/v1.10.0

For the model I'm using, I'll follow https://github.com/tailscale/tailscale/issues/2319
