### ISSUE TITLE
Log in goroutine after TestTwoDevicePing has completed

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#228]
Seen at 2d48f92a8250d1c84d7aec76189f58c64e1eadb1

```
PASS
panic: Log in goroutine after TestTwoDevicePing has completed

goroutine 226 [running]:
testing.(*common).logDepth(0xc00026e200, 0xc0000320f0, 0x47, 0x3)
        /home/bradfitz/sdk/go1.13.8/src/testing/testing.go:678 +0x406
testing.(*common).log(...)
        /home/bradfitz/sdk/go1.13.8/src/testing/testing.go:658
testing.(*common).Logf(0xc00026e200, 0xc00059a560, 0x1b, 0xc0001a2020, 0x2, 0x2)
        /home/bradfitz/sdk/go1.13.8/src/testing/testing.go:693 +0x7e
tailscale.com/types/logger.WithPrefix.func1(0x90b388, 0x14, 0xc0001a2020, 0x2, 0x2)
        /home/bradfitz/src/tailscale.com/types/logger/logger.go:21 +0x98
tailscale.com/derp/derphttp.(*Client).connect(0xc000306080, 0x9aa520, 0xc0000240c0, 0x90b66c, 0x14, 0x0, 0x0, 0x0)
        /home/bradfitz/src/tailscale.com/derp/derphttp/derphttp_client.go:108 +0x185
tailscale.com/derp/derphttp.(*Client).Recv(0xc000306080, 0xc00016c000, 0x10000, 0x10000, 0x0, 0x0, 0x0, 0x0)
        /home/bradfitz/src/tailscale.com/derp/derphttp/derphttp_client.go:268 +0x5c
tailscale.com/wgengine/magicsock.(*Conn).runDerpReader(0xc0002fab00, 0x9aa4e0, 0xc000308040, 0xc0002b8e40, 0xc000306080, 0xc00006e7a0, 0xc00009a0c0)
        /home/bradfitz/src/tailscale.com/wgengine/magicsock/magicsock.go:962 +0x2f4
created by tailscale.com/wgengine/magicsock.(*Conn).derpWriteChanOfAddr
        /home/bradfitz/src/tailscale.com/wgengine/magicsock/magicsock.go:874 +0xc26
FAIL    tailscale.com/wgengine/magicsock        0.085s
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1171685499906294/1171686708745683) by [Unito](https://www.unito.io/learn-more)

**Comment by danderson** [comment]
Unable to repro at head, with 1000 iterations with and without race detector. Based on backtrace, looks like it was a shutdown race for derp client, which I think we no longer have.
