### ISSUE TITLE
CentOS 8 Installation - Missing "iptables" command

### ISSUE THREAD

**Issue by morgangallant** [tailscale/tailscale#233]
**Describe the bug**
When installing Tailscale on a new CentOS 8 machine (following the [website docs](https://tailscale.com/kb/1051/install-centos-8)), if `iptables` isn't installed, `tailscaled` will enter an infinite systemd restart loop. This occurred when configuring a reverse proxy instance via DigitalOcean, who doesn't install `iptables` with the default CentOS 8.1 image.

**To Reproduce**
1. Configure a CentOS 8.1 server and do not install `iptables`.
2. `sudo dnf config-manager --add-repo https://pkgs.tailscale.com/stable/centos/8/tailscale.repo`
3. `sudo dnf install tailscale`
4. `sudo systemctl enable --now tailscaled`
5. At this point, a `sudo systemctl status tailscaled` will show an infinite loop, and `sudo tailscale up` will fail with a missing socket error.

**Expected behavior**
I'd expect that the `iptables-services` package be installed as a dependency of `tailscale` when performing `sudo dnf install tailscale`. I manually did this after seeing this error, and everything worked great.

**Error Message**
Note that `rvpc-gateway` is the hostname of my VPS.
```
Mar 27 20:31:56 rvpc-gateway systemd[1]: Stopped Tailscale node agent.
Mar 27 20:31:56 rvpc-gateway systemd[1]: Started Tailscale node agent.
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 logtail started
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 Program starting: v0.97-45-g02c73501: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.stat>
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 LogID: d9ee8daee29f91aec1b0659eb7b98e168678fe71ab6c9db2d7325780c7de15cc
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 6.1M/26.1M Starting userspace wireguard engine.
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 6.1M/26.1M external packet routing via --tun=tailscale0 enabled
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 6.1M/26.1M CreateTUN ok.
Mar 27 20:31:56 rvpc-gateway NetworkManager[730]: <info>  [1585341116.4792] manager: (tailscale0): new Tun device (/org/freedesktop/NetworkManager/Devices/141)
Mar 27 20:31:56 rvpc-gateway systemd-udevd[3195]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 6.4M/26.1M Routine: event worker - started
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 magicsock.Conn: starting endpoint update (initial)
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 11.3M/30.1M Device closing
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 11.5M/30.1M Failed to load updated MTU of device: failed to get MTU of TUN device: no such device
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 11.5M/30.1M Interface set up
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 11.5M/30.1M Routine: event worker - stopped
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 11.5M/30.1M Interface closed
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: 2020/03/27 20:31:56 11.5M/30.1M NewUserspaceEngineAdv: exec: "iptables": executable file not found in $PATH
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: panic: close of closed channel
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: goroutine 1 [running]:
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: github.com/tailscale/wireguard-go/tun.(*NativeTun).Close(0xc0000ba400, 0x1a, 0xc000055ea0)
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]:         /home/bradfitz/src/tailscale.io/wireguard-go/tun/tun_linux.go:377 +0xcb
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: tailscale.com/wgengine.NewUserspaceEngine(0xc000055750, 0xa05b6a, 0xa, 0xa2a9, 0x6, 0x73, 0xc0000f1ed0, 0x1)
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]:         /home/bradfitz/src/tailscale.io/oss/wgengine/userspace.go:88 +0x34f
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]: main.main()
Mar 27 20:31:56 rvpc-gateway tailscaled[3190]:         /home/bradfitz/src/tailscale.io/oss/cmd/tailscaled/tailscaled.go:73 +0x885
Mar 27 20:31:56 rvpc-gateway systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 27 20:31:56 rvpc-gateway systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Mar 27 20:31:56 rvpc-gateway systemd[1]: tailscaled.service: Service RestartSec=100ms expired, scheduling restart.
Mar 27 20:31:56 rvpc-gateway systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 139.
Mar 27 20:31:56 rvpc-gateway systemd[1]: Stopped Tailscale node agent.
Mar 27 20:31:56 rvpc-gateway systemd[1]: Started Tailscale node agent.
```

**Comment by danderson** [comment]
Fixed in https://pkgs.tailscale.com/unstable, the packages now have correct dependencies. Stable track will be fixed next time we do a stable release (some time next week, most likely)
