### ISSUE TITLE
TestVMIntegrationEndToEnd flake

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2362]
I got a test flake on one of my changes: https://github.com/tailscale/tailscale/runs/3022215087

```
=== RUN   TestVMIntegrationEndToEnd/do/oracle-linux-7/incoming-ssh-ipv4
panic: test timed out after 10m0s

goroutine 1790 [running]:
testing.(*M).startAlarm.func1()
	/nix/store/ybmznqd9958gmksnwfdqnvzax0il5hxz-go-1.16.5/share/go/src/testing/testing.go:1700 +0xe5
created by time.goFunc
	/nix/store/ybmznqd9958gmksnwfdqnvzax0il5hxz-go-1.16.5/share/go/src/time/sleep.go:180 +0x45

goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000102780, 0xd939d3, 0x19, 0xdbe510, 0x496701)
	/nix/store/ybmznqd9958gmksnwfdqnvzax0il5hxz-go-1.16.5/share/go/src/testing/testing.go:1239 +0x2da
testing.runTests.func1(0xc000102c00)
	/nix/store/ybmznqd9958gmksnwfdqnvzax0il5hxz-go-1.16.5/share/go/src/testing/testing.go:1511 +0x78
testing.tRunner(0xc000102c00, 0xc00021fde0)
	/nix/store/ybmznqd9958gmksnwfdqnvzax0il5hxz-go-1.16.5/share/go/src/testing/testing.go:1193 +0xef
testing.runTests(0xc00013c660, 0x137f6a0, 0x4, 0x4, 0xc031efde33457bd9, 0x8bb2f6504c, 0x13898c0, 0xd8a0cc)
	/nix/store/ybmznqd9958gmksnwfdqnvzax0il5hxz-go-1.16.5/share/go/src/testing/testing.go:1509 +0x2fe
testing.(*M).Run(0xc000192280, 0x0)
	/nix/store/ybmznqd9958gmksnwfdqnvzax0il5hxz-go-1.16.5/share/go/src/testing/testing.go:1417 +0x1eb
main.main()
	_testmain.go:49 +0x138
```

**Comment by DentonGentry** [comment]
This iteration of the VM integration test is no longer active.
