### ISSUE TITLE
SIGSEGV on Android 1.11.106 in SetDisableUPnP

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#2444]
We released an Open Testing Android build, and saw a SIGSEGV (yes, really) in control/controlclient/direct.go:803

```
2021-07-16 19:58:19.89380079 +0000 UTC: 5.2M/119.4M control: authRoutine: state:authenticated; goal=nil paused=false
2021-07-16 19:58:19.89390381 +0000 UTC: 5.2M/119.4M control: mapRoutine: new map needed while idle.
2021-07-16 19:58:19.893960373 +0000 UTC: 5.2M/119.4M control: mapRoutine: state:authenticated
2021-07-16 19:58:19.89400829 +0000 UTC: 5.2M/119.4M control: PollNetMap: stream=true :0 ep=[]
2021-07-16 20:21:05.723883978 +0000 UTC: panic: runtime error: invalid memory address or nil pointer dereference
2021-07-16 20:21:05.723883978 +0000 UTC: [signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x7428a1fdb0]
2021-07-16 20:21:05.723883978 +0000 UTC: goroutine 111 [running]:
2021-07-16 20:21:05.723883978 +0000 UTC: tailscale.com/control/controlclient.(*Direct).sendMapRequest(0x40001b4000, 0x7428dbdc98, 0x4000022300, 0xffffffffffffffff, 0x40002b9f10, 0x0, 0x0)
2021-07-16 20:21:05.723883978 +0000 UTC: 	/home/dgentry/go/pkg/mod/tailscale.com@v1.1.1-0.20210715222212-1bb6abc604c1/control/controlclient/direct.go:803 +0x1370
2021-07-16 20:21:05.723883978 +0000 UTC: tailscale.com/control/controlclient.(*Direct).PollNetMap(...)
2021-07-16 20:21:05.723883978 +0000 UTC: 	/home/dgentry/go/pkg/mod/tailscale.com@v1.1.1-0.20210715222212-1bb6abc604c1/control/controlclient/direct.go:574
2021-07-16 20:21:05.723883978 +0000 UTC: tailscale.com/control/controlclient.(*Auto).mapRoutine(0x40006462d0)
2021-07-16 20:21:05.723883978 +0000 UTC: 	/home/dgentry/go/pkg/mod/tailscale.com@v1.1.1-0.20210715222212-1bb6abc604c1/control/controlclient/auto.go:464 +0x4bc
2021-07-16 20:21:05.723883978 +0000 UTC: created by tailscale.com/control/controlclient.(*Auto).Start
2021-07-16 20:21:05.723883978 +0000 UTC: 	/home/dgentry/go/pkg/mod/tailscale.com@v1.1.1-0.20210715222212-1bb6abc604c1/control/controlclient/auto.go:151 +0x54
```

https://github.com/tailscale/tailscale/blob/798b0da4703d66beed9ea4a2c7272f8a4bfe6476/control/controlclient/direct.go#L803
```
                hasDebug := resp.Debug != nil
                // being conservative here, if Debug not present set to False
                controlknobs.SetDisableUPnP(hasDebug && resp.Debug.DisableUPnP.EqualBool(true))
```

Seen at ea6ba6e4f0d170a6e68978a6b0c36bd75656eb672a952f65085d579b639178d2

**Comment by bradfitz** [comment]
You linked to the wrong line number. The version from the logs is `1.11.106-1bb6abc604c-g2c1f35d5607` so the line number is:

https://github.com/tailscale/tailscale/blob/1bb6abc604c/control/controlclient/direct.go#L803

Which I fixed in 171ec9f8f4e4b4751b5f07dbed6f01514597c1a0.

/cc @JulianKnodt
