### ISSUE TITLE
Develop test case for EDNS packet killing tailscaled

### ISSUE THREAD

**Issue by jc00ke** [tailscale/tailscale#2533]
I _just_ upgraded from 1.10.2 and this is what I'm seeing when I run the command repeatedly:

```
  ➜ sudo tailscale status
  unexpected state: Starting

  ❯ sudo tailscale status
  100.93.208.38   jimmie               jesse@       linux   -
  100.101.102.103 ("hello")            services@    linux   -
  100.96.127.98   igor                 jesse@       linux   -
  100.125.42.13   tailscale-relay-9c2da37 pat@         linux   -

  ➜ sudo tailscale status
  unexpected state: NoState

  ❯ sudo tailscale status
  100.93.208.38   jimmie               jesse@       linux   -
  100.101.102.103 ("hello")            services@    linux   -
  100.96.127.98   igor                 jesse@       linux   -

  ➜ sudo tailscale status
  unexpected state: NoState
```

**Comment by DentonGentry** [comment]
You may be hitting #2321. Could you:
1. `tailscale status down`
2. `tailscale status up` (with the same arguments it had before)

**Comment by bradfitz** [comment]
I don't think it's #2321. It'd be different symptoms if it were.

Looking at logs (cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62) I see the process restarting a lot, with no obvious crash in the logs for the previous generation:

```
2021-07-27 15:57:26.991721774 -0700 PDT: health("overall"): ok
2021-07-27 15:57:27.054284 -0700 PDT: LinkChange: minor
2021-07-27 15:57:27.05431515 -0700 PDT: magicsock: ReSTUN: endpoint update active, need another later ("link-change-minor")
2021-07-27 15:57:27.131133386 -0700 PDT: control: mapRoutine: netmap received: state:synchronized
2021-07-27 15:57:27.131163826 -0700 PDT: control: sendStatus: mapRoutine-got-netmap: state:synchronized
2021-07-27 15:57:27.131184696 -0700 PDT: netmap diff: (none)
2021-07-27 15:57:27.131374426 -0700 PDT: wgcfg: skipped unselected default routes from: "tailscale-relay-9c2da37" ([O2sn8])
2021-07-27 15:57:27.216271597 -0700 PDT: netcheck: report: udp=true v6=false mapvarydest=false hair=false portmap= v4a=52.129.39.162:41641 derp=10 derpdist=2v4:29ms,9v4:59ms,10v4:8ms
2021-07-27 15:57:27.468788047 -0700 PDT: netcheck: report: udp=true v6=false mapvarydest=false hair=false portmap= v4a=52.129.39.162:41641 derp=10 derpdist=2v4:30ms,9v4:59ms,10v4:7ms
2021-07-27 15:57:27.554920855 -0700 PDT: logtail started
2021-07-27 15:57:27.555015614 -0700 PDT: Program starting: v1.12.0-t359baa842-ge1013695a, Go 1.16.6-ts6fa85e8: []string{"/usr/sbin/tailscaled", "--cleanup"}
2021-07-27 15:57:27.555029764 -0700 PDT: LogID: cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62
2021-07-27 15:57:27.555035704 -0700 PDT: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
2021-07-27 15:57:27.557374108 -0700 PDT: dns: [rc=resolved nm=yes nm-resolved=yes nm-safe=no ret=*dns.resolvedManager]
2021-07-27 15:57:27.557416817 -0700 PDT: creating dns cleanup: route ip+net: no such network interface
2021-07-27 15:57:27.557427867 -0700 PDT: flushing log.
2021-07-27 15:57:27.557438917 -0700 PDT: logger closing down
2021-07-27 15:57:27.584641218 -0700 PDT: logtail: dialed "log.tailscale.io:443" in 29ms
2021-07-27 15:57:27.876012723 -0700 PDT: logtail started
2021-07-27 15:57:27.876087523 -0700 PDT: Program starting: v1.12.0-t359baa842-ge1013695a, Go 1.16.6-ts6fa85e8: []string{"/usr/sbin/tailscaled", "--cleanup"}
2021-07-27 15:57:27.876098493 -0700 PDT: LogID: cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62
2021-07-27 15:57:27.876103963 -0700 PDT: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
2021-07-27 15:57:27.878175457 -0700 PDT: dns: [rc=resolved nm=yes nm-resolved=yes nm-safe=no ret=*dns.resolvedManager]
2021-07-27 15:57:27.878368837 -0700 PDT: creating dns cleanup: route ip+net: no such network interface
2021-07-27 15:57:27.878413476 -0700 PDT: flushing log.
2021-07-27 15:57:27.878427036 -0700 PDT: logger closing down
2021-07-27 15:57:27.895315197 -0700 PDT: logtail: dialed "log.tailscale.io:443" in 18ms
2021-07-27 15:57:27.970173578 -0700 PDT: logtail started
2021-07-27 15:57:27.970230588 -0700 PDT: Program starting: v1.12.0-t359baa842-ge1013695a, Go 1.16.6-ts6fa85e8: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "416
41"}
```

**Comment by jc00ke** [comment]
@DentonGentry it worked for a hot sec, then I ran `tailscale down` and then `tailscale up --accept-routes` and I still see

```
➜ sudo tailscale down                                                                                                                                         
~                                                                                                                                                             
➜ sudo tailscale up --accept-routes                                                                                                                           
Success.                                                                                                                                                      
~                                                                                                                                                             
➜ sudo tailscale status                                                                                                                                       
unexpected state: NoState                                                                                                                                     
~                                                                                                                                                             
❯ sudo tailscale status                                                                                                                                       
100.93.208.38   jimmie               jesse@       linux   -                                                                                                   
100.101.102.103 ("hello")            services@    linux   active; relay "fra", tx 148 rx 0                                                                    
100.96.127.98   igor                 jesse@       linux   -
~                                                                                                                                                             
➜ sudo tailscale status                                                                                                                                       
failed to connect to local tailscaled (which appears to be running). Got error: Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/run/tail
scale/tailscaled.sock: connect: no such file or directory                                                                                                     
~                                                                                                                                                             
❯ sudo tailscale status                                                                                                                                       
unexpected state: Starting                                                                                                                                    
~                                                                                                                                                             
❯ sudo tailscale status                                                                                                                                       
100.93.208.38   jimmie               jesse@       linux   -                                                                                                   
100.101.102.103 ("hello")            services@    linux   -                                                                                                   
100.96.127.98   igor                 jesse@       linux   -                                                                                             
~                                                                                                                                                             
➜ sudo tailscale status                                                                                                                                       
100.93.208.38   jimmie               jesse@       linux   -                                                                                                   
100.101.102.103 ("hello")            services@    linux   -                                                                                                   
100.96.127.98   igor                 jesse@       linux   -                                                                           
~                                                                                                                                                             
➜ sudo tailscale status                                                                                                                                       
unexpected state: NoState                                                                                                                                     
```

**Comment by bradfitz** [comment]
Can you `systemctl stop tailscaled` and then run `tailscaled` in the foreground, like:

```
$ sudo /usr/sbin/tailscaled --cleanup
$ sudo /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41641
```

And then in another window, while that second `tailscaled` is running, then try to check its status, etc?

It seems like `tailscaled` is crashing but its crash logs aren't getting uploaded.

**Comment by jc00ke** [comment]
```
panic: runtime error: slice bounds out of range [:12] with capacity 11

goroutine 556 [running]:
tailscale.com/net/dns/resolver.clampEDNSSize(0xc000a0a980, 0x40, 0x40, 0xc000150fff)
	tailscale.com@v1.12.0/net/dns/resolver/forwarder.go:145 +0x125
tailscale.com/net/dns/resolver.(*forwarder).forward(0xc00018c070, 0xc000a0a980, 0x40, 0x40, 0x0, 0xffff645dd026, 0xc0001340a8, 0xaa93, 0x0, 0x0)
	tailscale.com@v1.12.0/net/dns/resolver/forwarder.go:536 +0xca
tailscale.com/net/dns/resolver.(*Resolver).handleQuery(0xc00045e500, 0xc000a0a980, 0x40, 0x40, 0x0, 0xffff645dd026, 0xc0001340a8, 0xaa93)
	tailscale.com@v1.12.0/net/dns/resolver/tsdns.go:365 +0x3a5
created by tailscale.com/net/dns/resolver.(*Resolver).EnqueueRequest
	tailscale.com@v1.12.0/net/dns/resolver/tsdns.go:256 +0x169
```

**Comment by jc00ke** [comment]
```
➜ sudo /usr/sbin/tailscaled --cleanup
logtail started
Program starting: v1.12.0-t359baa842-ge1013695a, Go 1.16.6-ts6fa85e8: []string{"/usr/sbin/tailscaled", "--cleanup"}
LogID: cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62
logpolicy: using system state directory "/var/lib/tailscale"
dns: [rc=resolved nm=yes nm-resolved=yes nm-safe=no ret=*dns.resolvedManager]
creating dns cleanup: route ip+net: no such network interface
flushing log.
logger closing down
logtail: dialed "log.tailscale.io:443" in 41ms

➜ sudo /usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=41641
logtail started
Program starting: v1.12.0-t359baa842-ge1013695a, Go 1.16.6-ts6fa85e8: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port=41641"}
LogID: cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
router: v6nat = true
dns: [rc=resolved nm=yes nm-resolved=yes nm-safe=no ret=*dns.resolvedManager]
dns: using *dns.resolvedManager
link state: interfaces.State{defaultRoute=enp39s0 ifs={docker0:[172.17.0.1/16] enp39s0:[10.50.103.153/22]} v4=true v6=false}
Creating wireguard device...
Bringing wireguard device up...
Bringing router up...
external route: up
logtail: dialed "log.tailscale.io:443" in 17ms
Clearing router settings...
Starting link monitor...
Starting magicsock...
Engine created.
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:254 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5210 Table:254 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:253 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5230 Table:253 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
Listening on /run/tailscale/tailscaled.sock
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:0 Scope:0 Type:7 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5250 Table:0 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:52 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5270 Table:52 Mark:0 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: RTM_NEWROUTE: src=, dst=ff00::/8, gw=, outif=443, table=255
monitor: RTM_NEWROUTE: src=, dst=fe80::/64, gw=, outif=443, table=254
monitor: RTM_NEWROUTE: src=, dst=fe80::3c3f:b718:66ef:16c0/128, gw=, outif=443, table=255
netmap packet filter: (not ready yet)
Start
using backend prefs
backend prefs for "_daemon": Prefs{ra=true dns=true want=true routes=[] nf=on Persist{lm=[FKcR3], o=, n=[EVKD1] u="jesse@ratiopbc.com"}}
got initial portlist info in 0s
magicsock: disco key = d:30cf38ba38d45ce1
control: HostInfo: {"IPNVersion":"1.12.0-t359baa842-ge1013695a","BackendLogID":"cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62","OS":"linux","OSVersion":"Ubuntu 21.04 (Hirsute Hippo); kernel=5.11.0-25-generic","Hostname":"jimmie","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd -D [listener] 0 of 10-100 startups"},{"Proto":"tcp","Port":53,"Description":"systemd-resolved"}]}
Backend: logs: be:cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62 fe:
control: client.Login(false, 0)
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
control: authRoutine: state:new; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=0)
control: doLogin(regen=false, hasUrl=false)
router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's
netmap packet filter: (not ready yet)
control: control server key 9e5156a4c65121306dd2d8ed8f92cb8d738e2533011344b522c5d28409bc4970 from https://controlplane.tailscale.com
control: RegisterReq: onode=[AAAAA] node=[EVKD1] fup=false
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
control: No AuthURL
authReconfig: netmap not yet valid. Skipping.
control: authRoutine: state:authenticated; goal=nil paused=false
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:authenticated
active login: jesse@ratiopbc.com
netmap packet filter: [[TCP UDP ICMPv4 ICMPv6][0.0.0.0/0,::/0]=>[0.0.0.0/0:*,::/0:*]]
Switching ipn state NoState -> Starting (WantRunning=true, nm=true)
health("overall"): error: state=Starting, wantRunning=true
magicsock: SetPrivateKey called (init)
wgengine: Reconfig: configuring userspace wireguard config (with 2/9 peers)
magicsock: ParseEndpoint: key=[O2sn8]: disco=d:8b105dd09fbbf920 ipps=
magicsock: ParseEndpoint: key=[Z0VJp]: disco=d:ea94b484c46b7a27 ipps=
wgengine: Reconfig: configuring router
monitor: RTM_NEWROUTE: src=, dst=10.95.0.0/16, gw=, outif=443, table=52
monitor: RTM_NEWROUTE: src=, dst=10.96.0.0/16, gw=, outif=443, table=52
[RATELIMIT] format("monitor: %s: src=%v, dst=%v, gw=%v, outif=%v, table=%v")
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[8.8.8.8:53 8.8.4.4:53] Routes:{internal.ratiopbc.com.:[169.254.169.254:53]} SearchDomains:[internal.ratiopbc.com.] Hosts:9}
dns: Resolvercfg: {Routes:{.:[8.8.8.8:53 8.8.4.4:53] internal.ratiopbc.com.:[169.254.169.254:53]} Hosts:9 LocalDomains:[]}
dns: OScfg: {Nameservers:[100.100.100.100] SearchDomains:[internal.ratiopbc.com.] MatchDomains:[]}
peerapi: serving on http://100.93.208.38:42003
peerapi: serving on http://[fd7a:115c:a1e0:ab12:4843:cd96:625d:d026]:42003
control: HostInfo: {"IPNVersion":"1.12.0-t359baa842-ge1013695a","BackendLogID":"cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62","OS":"linux","OSVersion":"Ubuntu 21.04 (Hirsute Hippo); kernel=5.11.0-25-generic","Hostname":"jimmie","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd -D [listener] 0 of 10-100 startups"},{"Proto":"tcp","Port":53,"Description":"systemd-resolved"},{"Proto":"peerapi4","Port":42003},{"Proto":"peerapi6","Port":42003}]}
Received error: PollNetMap: EOF
control: mapRoutine: backoff: 13 msec
control: mapRoutine: state:authenticated
control: HostInfo: {"IPNVersion":"1.12.0-t359baa842-ge1013695a","BackendLogID":"cd78e299c5ef11ecf4946362945b020ef28f0a423d872c47941eb0ccee3e3c62","OS":"linux","OSVersion":"Ubuntu 21.04 (Hirsute Hippo); kernel=5.11.0-25-generic","Hostname":"jimmie","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd -D [listener] 0 of 10-100 startups"},{"Proto":"tcp","Port":53,"Description":"systemd-resolved"},{"Proto":"tcp","Port":42003,"Description":"tailscaled"},{"Proto":"peerapi4","Port":42003},{"Proto":"peerapi6","Port":42003}]}
control: mapRoutine: state:authenticated
magicsock: home is now derp-10 (sea)
magicsock: adding connection to derp-10 for home-keep-alive
control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false udp=true derp=#10 portmap= link=""}
magicsock: 1 active derp conns: derp-10=cr0s,wr0s
derphttp.Client.Connect: connecting to derp-10 (sea)
Switching ipn state Starting -> Running (WantRunning=true, nm=true)
magicsock: endpoints changed: 52.129.39.162:41641 (stun), 10.50.103.153:41641 (local), 172.17.0.1:41641 (local)
control: client.newEndpoints(0, [52.129.39.162:41641 10.50.103.153:41641 172.17.0.1:41641])
magicsock: derp-10 connected; connGen=1
health("overall"): ok
control: mapRoutine: state:authenticated
[RATELIMIT] format("control: mapRoutine: %s")
panic: runtime error: slice bounds out of range [:12] with capacity 11

goroutine 818 [running]:
tailscale.com/net/dns/resolver.clampEDNSSize(0xc000900000, 0x40, 0x40, 0xc0007f0fff)
	tailscale.com@v1.12.0/net/dns/resolver/forwarder.go:145 +0x125
tailscale.com/net/dns/resolver.(*forwarder).forward(0xc000192150, 0xc000900000, 0x40, 0x40, 0x0, 0xffff645dd026, 0xc00000c0c0, 0xde46, 0x0, 0x0)
	tailscale.com@v1.12.0/net/dns/resolver/forwarder.go:536 +0xca
tailscale.com/net/dns/resolver.(*Resolver).handleQuery(0xc0001b2580, 0xc000900000, 0x40, 0x40, 0x0, 0xffff645dd026, 0xc00000c0c0, 0xde46)
	tailscale.com@v1.12.0/net/dns/resolver/tsdns.go:365 +0x3a5
created by tailscale.com/net/dns/resolver.(*Resolver).EnqueueRequest
	tailscale.com@v1.12.0/net/dns/resolver/tsdns.go:256 +0x169
```

**Comment by DentonGentry** [comment]
We have quite a few people looking at this right now.

If you need to, you can downgrade back to the previous release using: `sudo apt install tailscale=1.10.2`

**Comment by DentonGentry** [comment]
Would you be willing

**Comment by DentonGentry** [comment]
Could you try a build from the unstable track?
https://pkgs.tailscale.com/unstable/#ubuntu-groovy

We are pretty sure it will fix the crash. We need to do more work to characterize what happened in the first place, and get a packet to trigger the problem in a test case.

**Comment by jc00ke** [comment]
Sure, lemme give it a try now. I'll use https://pkgs.tailscale.com/unstable/#ubuntu-hirsute

**Comment by jc00ke** [comment]
:tada: I'm connected and `tailscale status` is not showing the same behavior as it did on 1.12.0.

**Comment by DentonGentry** [comment]
Fixed for keepsies in 1.12.1.

It should be fine to switch back to the stable track https://pkgs.tailscale.com/stable/#ubuntu-hirsute, if you'd prefer.

**Comment by jc00ke** [comment]
I switched back. Thanks for getting a quick fix out!

**Comment by DentonGentry** [comment]
Reopening and repurposing this bug to make sure we develop a unit test to exercise the problem and ensure we don't reintroduce it or a problem like it.
