### ISSUE TITLE
logtail: panics lost on linux

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2544]
In https://github.com/tailscale/tailscale/issues/2533, a user reported a tailscaled crash on Ubuntu that, by eventually running the command directly, they discovered was a Go panic. But the logs for their log ID did not show any panic, suggesting something in filch/logtail was either failing to write the crash to disk, or after writing it, failed to upload it.

Inserting a panic into `--cleanup` suggests that some change to filch (or the Go runtime?) means we no longer capture the panic:

```
diff --git a/cmd/tailscaled/tailscaled.go b/cmd/tailscaled/tailscaled.go
index 4d3651a2..25e19a95 100644
--- a/cmd/tailscaled/tailscaled.go
+++ b/cmd/tailscaled/tailscaled.go
@@ -210,6 +210,8 @@ func run() error {
        logf = logger.RateLimitedFn(logf, 5*time.Second, 5, 100)

        if args.cleanup {
+               time.Sleep(1)
+               panic("test panic")
                dns.Cleanup(logf, args.tunname)
                router.Cleanup(logf, args.tunname)
                return nil
```

Running this shows the panic:

```
$ go run ./cmd/tailscaled -cleanup
logtail started
Program starting: vdate.20210727, Go devel go1.17-ab4085ce84 Fri Jul 9 18:00:16 2021 +0000: []string{"/tmp/go-build1572353434/b001/exe/tailscaled", "-cleanup"}
LogID: 5e918fe8a26bc7ed7af848670e27929f351bc3c239619520260b3652037a3aa8
logpolicy: using system state directory "/home/crawshaw/.local/share/tailscale"
flushing log.
logger closing down
logtail: dialed "log.tailscale.io:443" in 31ms
panic: test panic

goroutine 1 [running]:
main.run()
        /home/crawshaw/repo/corp/gohack/tailscale.com/cmd/tailscaled/tailscaled.go:214 +0xd27
main.main()
        /home/crawshaw/repo/corp/gohack/tailscale.com/cmd/tailscaled/tailscaled.go:151 +0x605
exit status 2
```

But in the disk logs we don't see the panic:

```
$ ls -al ~/.local/share/tailscale/
total 40
drwx------   3 crawshaw crawshaw  4096 Jun  2 12:38 .
drwx------   4 crawshaw crawshaw  4096 Jun  2 12:38 ..
drwx------ 391 crawshaw crawshaw 20480 Jul 26 06:43 files
-rw-------   1 crawshaw crawshaw   209 Jun  2 12:38 tailscaled.log.conf
-rw-------   1 crawshaw crawshaw     0 Jul 28 13:30 tailscaled.log1.txt
-rw-------   1 crawshaw crawshaw   968 Jul 28 13:30 tailscaled.log2.txt
$ cat ~/.local/share/tailscale/tailscaled.log2.txt
{"logtail": {"client_time": "2021-07-28T13:30:56.4116773-07:00"}, "text": "logtail started"}
{"logtail": {"client_time": "2021-07-28T13:30:56.4120828-07:00"}, "text": "Program starting: vdate.20210727, Go devel go1.17-ab4085ce84 Fri Jul 9 18:00:16 2021 +0000: []string{\"/tmp/go-build1572353434/b001/exe/tailscaled\", \"-cleanup\"}\n"}
{"logtail": {"client_time": "2021-07-28T13:30:56.4121014-07:00"}, "text": "LogID: 5e918fe8a26bc7ed7af848670e27929f351bc3c239619520260b3652037a3aa8\n"}
{"logtail": {"client_time": "2021-07-28T13:30:56.4121121-07:00"}, "text": "logpolicy: using system state directory \"/home/crawshaw/.local/share/tailscale\"\n"}
{"logtail": {"client_time": "2021-07-28T13:30:56.4122828-07:00"}, "text": "flushing log.\n"}
{"logtail": {"client_time": "2021-07-28T13:30:56.4123112-07:00"}, "text": "logger closing down\n"}
{"logtail": {"client_time": "2021-07-28T13:30:56.4439093-07:00"}, "text": "logtail: dialed \"log.tailscale.io:443\" in 31ms\n"}
```

**Comment by crawshaw** [comment]
Did a quick survey of the Go runtime, nothing has changed. Panics are still written directly to fd 2.

**Comment by crawshaw** [comment]
Josh and I found the problem. But noting a second potential problem:

Does `tailscaled` followed by `tailscaled --cleanup` happen fast enough that we truncate the logs without uploading them? May need some kind of feedback mechanism between logtail and filch so we don't truncate the file until the upload has succeeded.

**Comment by DentonGentry** [comment]
Nevermind the change in title, https://github.com/tailscale/tailscale/issues/2547 was filed to cover the second part.

Fixed by https://github.com/tailscale/tailscale/pull/2546
