### ISSUE TITLE
Synology exit-node crashes whole tailscaled

### ISSUE THREAD

**Issue by andrej-zirko** [tailscale/tailscale#2658]
I installed Tailscale from the official Synology package manager on my Synology DS118. The default configuration seems to work. I tried to enable exit node on the Synology and it works for a little while. I confirmed this using whatsmyip on the other client. The traffic is routed through the Synology. However in the few moments it stops working.

Status after it stops working
`sudo /var/packages/Tailscale/target/bin/tailscale status 

Get "http://local-tailscaled.sock/localapi/v0/status": dial unix /var/packages/Tailscale/var/tailscaled.sock: connect: connection refused 
 `

Here is how I enable the exit node - using the Synology task setup after the boot up
`sleep 60 

/var/packages/Tailscale/target/bin/tailscale up --reset --advertise-exit-node 
`

Here are the hopefully relevant logs
`acceptUDP: could not create endpoint: no route 

acceptUDP: could not create endpoint: no route 

acceptUDP: could not create endpoint: no route 

acceptUDP: could not create endpoint: no route 

acceptUDP: could not create endpoint: no route 

[RATELIMIT] format("acceptUDP: could not create endpoint: %v") 

netstack: could not connect to local server at [2600:1901:0:c584::]:443: dial tcp [2600:1901:0:c584::]:443: connect: network is unreachable 

netstack: could not connect to local server at [2600:1901:0:c584::]:443: dial tcp [2600:1901:0:c584::]:443: connect: network is unreachable 

[RATELIMIT] format("acceptUDP: could not create endpoint: %v") (11 dropped) 

acceptUDP: could not create endpoint: no route 

acceptUDP: could not create endpoint: no route 

netstack: could not connect to local server at obfuscated:8080: operation was canceled 

netstack: could not connect to local server at obfuscated:8080: operation was canceled 

netstack: could not connect to local server at obfuscated:8080: operation was canceled 

netstack: could not connect to local server at obfuscated:8080: operation was canceled 

[RATELIMIT] format("netstack: could not connect to local server at %s: %v") 

panic: interface conversion: net.Addr is nil, not *net.TCPAddr 

  

goroutine 1123 [running]: 

tailscale.com/wgengine/netstack.(*Impl).forwardTCP(0x400017a3f0, 0x4000073c80, 0x40001a0510, 0x400069e21c, 0x4, 0x1f90) 

    tailscale.com@v1.1.1-0.20210610140605-f944614c5c0a/wgengine/netstack/netstack.go:491 +0xa18 

tailscale.com/wgengine/netstack.(*Impl).acceptTCP(0x400017a3f0, 0x4000016e80) 

    tailscale.com@v1.1.1-0.20210610140605-f944614c5c0a/wgengine/netstack/netstack.go:459 +0x278 

created by inet.af/netstack/tcpip/transport/tcp.(*Forwarder).HandlePacket 

    inet.af/netstack@v0.0.0-20210317161235-a1bf4e56ef22/tcpip/transport/tcp/forwarder.go:94 +0x288 
`

**Comment by DentonGentry** [comment]
Could I ask for the Tailscale IP address of the Synology device, to be able to look at errors it is reporting? Also is it DSM6 or DSM7? You can send it to support@tailscale.com if you're not comfortable pasting it here.

The version in the Synology Package Center is 1.9.156, and didn't expose an exit node setting in the Web UI though as you note it is possible to activate it using the CLI. If you're going to make heavy use of the exit node feature it might be better to sideload the 1.12.1 version: https://github.com/tailscale/tailscale-synology

We get an opportunity at the beginning of each month to update the version in the Synology package center, right now I'd expect to update it to 1.12.x at the start of September.

**Comment by andrej-zirko** [comment]
Thank you for your response. 

I'm using DSM 7. I sideloaded the latest version as you proposed. Unfortunately with the same result. I can browse few pages successfully, then I run a speed test, and then it fails. I provided the IP address to support@tailscale.com

**Comment by DentonGentry** [comment]
```
panic: interface conversion: net.Addr is nil, not *net.TCPAddr
goroutine 1123 [running]:
tailscale.com/wgengine/netstack.(*Impl).forwardTCP(0x400017a3f0, 0x4000073c80, 0x40001a0510, 0x400069e21c, 0x4, 0x1f90)
tailscale.com@v1.1.1-0.20210610140605-f944614c5c0a/wgengine/netstack/netstack.go:491 +0xa18 
```

I think I've got the commit correct for the 1.9.156 version in the Package Center:
https://github.com/tailscale/tailscale/blob/f944614c5c0a6fa9ef917dada05e1ca3e4478ac0/wgengine/netstack/netstack.go#L491

```
	backendLocalAddr := server.LocalAddr().(*net.TCPAddr)
	backendLocalIPPort, _ := netaddr.FromStdAddr(backendLocalAddr.IP, backendLocalAddr.Port, backendLocalAddr.Zone)
	clientRemoteIP, _ := netaddr.FromStdIP(client.RemoteAddr().(*net.TCPAddr).IP)         <-- HERE
	ns.e.RegisterIPPortIdentity(backendLocalIPPort, clientRemoteIP)
	defer ns.e.UnregisterIPPortIdentity(backendLocalIPPort)
```

That specific line in the current tree is https://github.com/tailscale/tailscale/blob/39610aeb09098142fdfd93a472a339ec33b24671/wgengine/netstack/netstack.go#L533, and there have been no changes in forwardTCP. There have been other changes elsewhere which might impact the issue since 1.9.156.
