### ISSUE TITLE
Android on ChromeOS: Crashes when sending files with taildrop from an external device

### ISSUE THREAD

**Issue by dbaynard** [tailscale/tailscale#2720]
I tried to send a file from an SD card, which caused the tailscale app to filcker briefly and then crash.

I could send the same file if I copied it to the internal disk (Downloads folder). I haven’t tested any other devices.

**Comment by eliasnaur** [comment]
Can anyone provide an `adb logcat` of the crashes?

**Comment by dbaynard** [comment]
> Can anyone provide an `adb logcat` of the crashes?

@eliasnaur 

I’ve sanitized the volume UUID and filepath. I have a few more crashes in the logcat history; let me know what you need (I’m new to logcat so please excuse any errors).

<details>
<summary>adb logcat</summary>

```
08-30 15:40:26.816   737  1424 E WebApkValidator: no application info, or metaData retrieved.
08-30 15:40:32.643   123  4010 I ActivityManager: START u0 {act=android.intent.action.SEND typ=application/pdf flg=0x10000003 cmp=com.tailscale.ipn/.IPNActivity clip={application/pdf U:content://org.chromium.arc.volumeprovider/${VOLUME_UUID?}/${FILEPATH?}} (has extras)} from uid 10051
08-30 15:40:32.656   123  4516 D ActivityManagerInjectorArc: taskOcclusionChanged: taskId=77 does not support PIP
08-30 15:40:32.658   123  3052 I ActivityManager: Killing 21894:com.google.process.gapps/u0a0 (adj 904): empty #17
08-30 15:40:32.658   123  3052 I ActivityManager: Killing 21948:android.process.acore/u0a34 (adj 904): empty #18
08-30 15:40:26.823   737  1424 I chatty  : uid=10058(org.chromium.arc.intent_helper) identical 8 lines
08-30 15:40:26.824   737  1424 E WebApkValidator: no application info, or metaData retrieved.
08-30 15:40:32.658   123   220 W libprocessgroup: kill(-21894, 9) failed: No such process
08-30 15:40:32.662   528   528 D ArcAppTaskTracker: Calculating task stack diff.
08-30 15:40:32.662   750 31967 D ArcMediaControllerManager: onTaskMovedToFront: 77
08-30 15:40:32.662   528   528 D ArcAppTaskTracker: Active task: 77.
08-30 15:40:32.664   750 31967 I ArcMediaControllerManager: onAppBecameActive: com.tailscale.ipn
08-30 15:40:32.666   123   219 I ActivityManager: Start proc 22979:org.chromium.arc.volumeprovider/u0a37 for content provider org.chromium.arc.volumeprovider/.VolumeProvider
08-30 15:40:32.669 22979 22979 E .volumeprovide: Not starting debugger since process cannot load the jdwp agent.
08-30 15:40:32.681    49    49 I Zygote  : Process 21894 exited due to signal (9)
08-30 15:40:32.688   123   827 D CountryDetector: No listener is left
08-30 15:40:32.690    49    49 I Zygote  : Process 21948 exited due to signal (9)
08-30 15:40:32.692 22979 22979 I .volumeprovide: The ClassLoaderContext is a special shared library.
08-30 15:40:32.693 22979 22979 W .volumeprovide: JIT profile information will not be recorded: profile file does not exits.
08-30 15:40:32.694 22979 22979 W .volumeprovide: Couldn't clamp region space as there are regions in use beyond growth limit.
08-30 15:40:32.697 18663 18663 D AndroidRuntime: Shutting down VM
08-30 15:40:32.697 18663 18663 E AndroidRuntime: FATAL EXCEPTION: main
08-30 15:40:32.697 18663 18663 E AndroidRuntime: Process: com.tailscale.ipn, PID: 18663
08-30 15:40:32.697 18663 18663 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int android.database.Cursor.getColumnIndex(java.lang.String)' on a null object reference
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at com.tailscale.ipn.IPNActivity.handleIntent(IPNActivity.java:72)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at com.tailscale.ipn.IPNActivity.onNewIntent(IPNActivity.java:33)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.Activity.performNewIntent(Activity.java:7286)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1382)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1394)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3231)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.ActivityThread.performNewIntents(ActivityThread.java:3250)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3267)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:49)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1883)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6971)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-30 15:40:32.697 18663 18663 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:865)
08-30 15:40:32.699   123  4516 W ActivityManager:   Force finishing activity com.tailscale.ipn/.IPNActivity
08-30 15:40:32.700   123  4516 E TaskRecordArc: updateSnapshotVisibility: no activity in task record 77
08-30 15:40:32.701   123  4024 E ActivityManagerInjectorArc: taskOcclusionChanged: taskId not found:77
08-30 15:40:32.702   123   220 W libprocessgroup: kill(-21894, 9) failed: No such process
08-30 15:40:32.702   123   220 I libprocessgroup: Successfully killed process cgroup uid 10000 pid 21894 in 44ms
08-30 15:40:32.703   123   220 W libprocessgroup: kill(-21948, 9) failed: No such process
08-30 15:40:32.703   123   220 I libprocessgroup: Successfully killed process cgroup uid 10034 pid 21948 in 0ms
08-30 15:40:32.706   123  4516 E ActivityManagerInjectorArc: taskOcclusionChanged: taskId not found:77
08-30 15:40:32.706 18663 18663 I Process : Sending signal. PID: 18663 SIG: 9
08-30 15:40:32.714   123   217 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
08-30 15:40:32.714   123   217 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
08-30 15:40:32.730   614 21432 I ArcCrashDumpStreamer: Streamed 368 B for data_app_crash dump.
08-30 15:40:32.730   123   283 W InputDispatcher: channel '5271df0 com.tailscale.ipn/com.tailscale.ipn.IPNActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-30 15:40:32.730   123   283 E InputDispatcher: channel '5271df0 com.tailscale.ipn/com.tailscale.ipn.IPNActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-30 15:40:32.753   120   191 D NetlinkEvent: Unknown ifindex 26 in RTM_DELADDR
08-30 15:40:32.757   120   191 D NetlinkEvent: Unknown ifindex 26 in RTM_DELADDR
08-30 15:40:32.758   123  4516 I WindowManager: WIN DEATH: Window{5271df0 u0 com.tailscale.ipn/com.tailscale.ipn.IPNActivity}
08-30 15:40:32.758   123  4516 W InputDispatcher: Attempted to unregister already unregistered input channel '5271df0 com.tailscale.ipn/com.tailscale.ipn.IPNActivity (server)'
08-30 15:40:32.764    49    49 I Zygote  : Process 18663 exited due to signal (9)
08-30 15:40:32.768   123   827 I ActivityManager: Process com.tailscale.ipn (pid 18663) has died: vis  TOP 
08-30 15:40:32.768   123   220 W libprocessgroup: kill(-18663, 9) failed: No such process
08-30 15:40:32.768   123   220 I libprocessgroup: Successfully killed process cgroup uid 10079 pid 18663 in 0ms
08-30 15:40:32.768   120   191 D NetlinkEvent: Unknown ifindex 26 in RTM_DELADDR
08-30 15:40:32.783   123   827 W ActivityManager: Scheduling restart of crashed service com.tailscale.ipn/.IPNService in 1000ms
```

(Timestamps are in BST.)

</summary>

**Comment by eliasnaur** [comment]
@dbaynard I failed to reproduce the crash when sharing a file from an SD-card on my ChromeOS (93.0.4577.85), but I've added a change that ignores files we don't have permission for instead of crashing. The second change implements proper taildrop receive support on ChromeOS (and other Android < 10 devices).
