### ISSUE TITLE
magicsock: panic: call to ReSTUN before Start

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#2733]
Seen at b49d9bc74ded7d17b1bedad47b4beac4e4ba3d67 in the CI VM test running on Ubuntu 20.04:

```
logtail started
Program starting: vdate.20210823, Go 1.17: []string{"/usr/sbin/tailscaled", "--cleanup"}
LogID: 333d9c9a1e8cbdeba58720e2e47eecf61dfec4db66da75565ce0a2fcd55f6bdd
logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
ale/tailscaled.log.conf: open /var/lib/tailscale/tailscaled.log.conf: no such file or directory
dns: [rc=resolved nm=no ret=*dns.resolvedManager]
creating dns cleanup: route ip+net: no such network interface
flushing log.
logger closing down
logtail: dialed "143.198.143.59:40025" in 16ms
logtail started
Program starting: vdate.20210823, Go 1.17: []string{"/usr/sbin/tailscaled", "--state=/var/lib/tailscale/tailscaled.state", "--socket=/run/tailscale/tailscaled.sock", "--port", "41641"}
LogID: 333d9c9a1e8cbdeba58720e2e47eecf61dfec4db66da75565ce0a2fcd55f6bdd
logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
logtail: dialed "143.198.143.59:40025" in 9ms
router: v6nat = true
dns: [rc=resolved nm=no ret=*dns.resolvedManager]
dns: using *dns.resolvedManager
link state: interfaces.State{defaultRoute=enp0s2 ifs={enp0s2:[10.0.2.15/24 fec0::8828:5cff:fe30:1f25/64]} v4=true v6=false}
Creating wireguard device...
Bringing wireguard device up...
UDP bind has been updated
Interface state was Down, requested Up, now Up
Bringing router up...
Routine: receive incoming v4 - started
Routine: receive incoming v6 - started
external route: up
Routine: receive incoming receiveDERP - started
Clearing router settings...
Starting link monitor...
Starting magicsock...
monitor: RTM_NEWROUTE: src=, dst=ff00::/8, gw=, outif=3, table=255
monitor: RTM_NEWROUTE: src=, dst=fe80::/64, gw=, outif=3, table=254
monitor: RTM_NEWROUTE: src=, dst=fe80::3a08:25bf:f69e:21c1/128, gw=, outif=3, table=255
LinkChange: minor
panic: call to ReSTUN before Start

goroutine 19 [running]:
tailscale.com/wgengine/magicsock.(*Conn).ReSTUN(0xc000128840, {0xab442d, 0x0})
    /root/repo/tailscale/wgengine/magicsock/magicsock.go:2547 +0x3dc
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc000122900, 0x0, 0xc000094050)
    /root/repo/tailscale/wgengine/userspace.go:1129 +0x3a8
tailscale.com/wgengine.NewUserspaceEngine.func1(0xd, 0xc00016e000)
    /root/repo/tailscale/wgengine/userspace.go:282 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
    /root/repo/tailscale/wgengine/monitor/monitor.go:328 +0x565
```

Not particularly easy to reproduce, one of hundreds of runs over many hours.

cc @danderson @bradfitz

**Comment by bradfitz** [comment]
For the record, the second small window is if you call NewUserspaceEngine with `conf.LinkMonitor != nil` with an already-running link monitor. In that case the: 

```
        unregisterMonWatch := e.linkMon.RegisterChangeCallback(func(changed bool, st *interfaces.State) {
                tshttpproxy.InvalidateCache()
                e.linkChange(changed, st)
        })
```

... is also before the magicConn.Start.

**Comment by herbygillot** [comment]
This is happening pretty consistently on a Synology Diskstation.

**Tailscale version:** 1.14.3
**Diskstation Version:** DSM 6.2.4-25556 Update 2
**Linux kernel version:** 3.10.105

Steps to reproduce:
1. Install Tailscale 1.14.3 into Diskstation using [tailscale-synology](https://github.com/tailscale/tailscale-synology)
2. Start Tailscale service
3. In the Package Center, click the Open button on the Tailscale app to visit the local Tailscale status page

Result:
The Tailscale service immediately stops with the following panic internally:
```
root@diskstation:/var/packages/Tailscale/etc# tail -f tailscaled.stdout.log
2021/09/17 00:51:57 magicsock: 1 active derp conns: derp-1=cr0s,wr0s
2021/09/17 00:51:57 derphttp.Client.Connect: connecting to derp-1 (nyc)
2021/09/17 00:51:57 control: NetInfo: NetInfo{varies=false hairpin=false ipv6=false udp=true derp=#1 portmap=active-M link=""}
2021/09/17 00:51:57 control: client.newEndpoints(0, [...<REDACTED>...])
2021/09/17 00:51:57 Switching ipn state Starting -> Running (WantRunning=true, nm=true)
2021/09/17 00:51:57 magicsock: derp-1 connected; connGen=1
2021/09/17 00:51:57 health("overall"): ok
2021/09/17 00:51:57 control: mapRoutine: state:authenticated
2021/09/17 00:51:57 [RATELIMIT] format("control: mapRoutine: %s")
2021/09/17 00:51:57 control: HostInfo: {"IPNVersion":"1.14.3-t3a762776e-g75eaf27e5","BackendLogID":"<REDACTED>","OS":"linux","OSVersion":"Synology 6.2.4; kernel=3.10.105","Hostname":"diskstation","GoArch":"amd64","Services":[{"Proto":"tcp","Port":22,"Description":"sshd"},{"Proto":"tcp","Port":80,"Description":"nginx: worker process"},{"Proto":"tcp","Port":111,"Description":"rpcbind"},{"Proto":"tcp","Port":139,"Description":"smbd"},{"Proto":"tcp","Port":443,"Description":"nginx: worker process"},{"Proto":"tcp","Port":445,"Description":"smbd"},{"Proto":"tcp","Port":548,"Description":"afpd"},{"Proto":"tcp","Port":892,"Description":"mountd"},{"Proto":"tcp","Port":2049},{"Proto":"tcp","Port":3261},{"Proto":"tcp","Port":3262,"Description":"iscsi_snapshot_comm_core"},{"Proto":"tcp","Port":3263},{"Proto":"tcp","Port":3264},{"Proto":"tcp","Port":3265,"Description":"scsi_plugin_server"},{"Proto":"tcp","Port":3493,"Description":"upsd"},{"Proto":"tcp","Port":5000,"Description":"nginx: worker process"},{"Proto":"tcp","Port":5001,"Description":"nginx: worker process"},{"Proto":"tcp","Port":5566,"Description":"ReplicationService-synobtrfsreplicad"},{"Proto":"tcp","Port":16881,"Description":"transmissiond"},{"Proto":"tcp","Port":37170},{"Proto":"tcp","Port":48043},{"Proto":"tcp","Port":53398,"Description":"statd"},{"Proto":"tcp","Port":55336,"Description":"statd"},{"Proto":"tcp","Port":64755,"Description":"tailscaled"},{"Proto":"peerapi4","Port":64755},{"Proto":"peerapi6","Port":64755}],"NetInfo":{"MappingVariesByDestIP":false,"HairPinning":false,"WorkingIPv6":false,"WorkingUDP":true,"HavePortMap":true,"UPnP":false,"PMP":true,"PCP":false,"PreferredDERP":1,"DERPLatency":{"1-v4":0.004754056,"10-v4":0.064472899,"11-v4":0.129896262,"12-v4":0.022338299,"2-v4":0.067301603,"3-v4":0.232591291,"4-v4":0.096922845,"5-v4":0.232679393,"6-v4":0.226902234,"7-v4":0.1600529,"8-v4":0.083890006,"9-v4":0.042587457}}}



2021/09/17 00:53:24 monitor: RTM_DELROUTE: src=, dst=ff02::1/128, gw=, outif=5, table=255
panic: call to ReSTUN before Start

goroutine 304 [running]:
tailscale.com/wgengine/magicsock.(*Conn).ReSTUN(0xc0000d2dc0, {0xac006e, 0x0})
	tailscale.com@v1.14.3/wgengine/magicsock/magicsock.go:2547 +0x3dc
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc0000cd440, 0x0, 0xc00009a870)
	tailscale.com@v1.14.3/wgengine/userspace.go:1129 +0x3a8
tailscale.com/wgengine.NewUserspaceEngine.func1(0x0, 0x0)
	tailscale.com@v1.14.3/wgengine/userspace.go:282 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
	tailscale.com@v1.14.3/wgengine/monitor/monitor.go:328 +0x565
```

**Comment by bradfitz** [comment]
@herbygillot, the fix isn't in a release yet. Cherry-picking that one into 1.14.x might've been possible but we didn't. It was probably borderline too invasive with dependent commits. You can build from main.

Are you getting that Synology crash with userspace mode or TUN mode?

**Comment by DentonGentry** [comment]
The fix in #2739 isn't in the 1.14.3 release, it was scheduled to appear in 1.16. I've added it to the 1.14 branch, if we build a 1.14.4 the fix will be in it.

**Comment by herbygillot** [comment]
> @herbygillot, the fix isn't in a release yet. Cherry-picking that one into 1.14.x might've been possible but we didn't. It was probably borderline too invasive with dependent commits. You can build from main.
> 
> Are you getting that Synology crash with userspace mode or TUN mode?

Looks like tun mode; here's the output with `verbose=1`:
```
-socket=/var/packages/Tailscale/etc/tailscaled.sock --verbose=1 --port=41641
2021/09/17 02:24:52 logtail started
2021/09/17 02:24:52 Program starting: v1.14.3-t3a762776e-g75eaf27e5, Go 1.17-tsdd6b269c77: []string{"/volume2/@appstore/Tailscale/bin/tailscaled", "
--state=/var/packages/Tailscale/etc/tailscaled.state", "--socket=/var/packages/Tailscale/etc/tailscaled.sock", "--verbose=1", "--port=41641"}
2021/09/17 02:24:52 LogID: <REDACTED>
2021/09/17 02:24:52 logpolicy: using $STATE_DIRECTORY, "/var/packages/Tailscale/etc"
2021/09/17 02:24:52 wgengine.NewUserspaceEngine(tun "tailscale0") ...
2021/09/17 02:24:52 router: v6nat = false
2021/09/17 02:24:52 dns: [rc=unknown ret=dns.directManager]
2021/09/17 02:24:52 dns: using dns.directManager
2021/09/17 02:24:52 link state: interfaces.State{defaultRoute=bond0 ifs={bond0:[192.168.1.156/24] docker0:[172.17.0.1/16]} v4=true v6=false}
2021/09/17 02:24:52 Creating wireguard device...
2021/09/17 02:24:52 Bringing wireguard device up...
2021/09/17 02:24:52 Bringing router up...
2021/09/17 02:24:52 external route: up
2021/09/17 02:24:52 router: failed to delete legacy rule, continuing anyway: checking for [-m comment --comment tailscale -i tailscale0 -j ACCEPT] i
n filter/FORWARD: running [/sbin/iptables -t filter -C FORWARD -m comment --comment tailscale -i tailscale0 -j ACCEPT --wait]: exit status 2: iptabl
es v1.6.0: Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
2021/09/17 02:24:52 router: failed to delete legacy rule, continuing anyway: checking for [-m comment --comment tailscale -o eth0 -j MASQUERADE] in
nat/POSTROUTING: running [/sbin/iptables -t nat -C POSTROUTING -m comment --comment tailscale -o eth0 -j MASQUERADE --wait]: exit status 2: iptables
 v1.6.0: Couldn't load match `comment':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
2021/09/17 02:24:52 wgengine.NewUserspaceEngine(tun "tailscale0") error: running "ip link set dev tailscale0 up" failed: fork/exec /sbin/ip: invalid
 argument
2021/09/17 02:24:52 wgengine.NewUserspaceEngine(tun "userspace-networking") ...
2021/09/17 02:24:52 using fake (no-op) tun device
2021/09/17 02:24:52 using fake (no-op) OS network configurator
2021/09/17 02:24:52 using fake (no-op) DNS configurator
2021/09/17 02:24:52 dns: using dns.noopManager
2021/09/17 02:24:52 link state: interfaces.State{defaultRoute=bond0 ifs={bond0:[192.168.1.156/24] docker0:[172.17.0.1/16]} v4=true v6=false}
2021/09/17 02:24:52 magicsock: unable to bind udp4 port 41641: listen udp4 :41641: bind: address already in use
2021/09/17 02:24:52 magicsock: unable to bind udp6 port 41641: listen udp6 :41641: bind: address already in use
2021/09/17 02:24:52 Creating wireguard device...
2021/09/17 02:24:52 Bringing wireguard device up...
2021/09/17 02:24:52 Bringing router up...
2021/09/17 02:24:52 warning: fakeRouter.Up: not implemented.
```

**Comment by herbygillot** [comment]
Thank you very much @bradfitz - I just installed `1.14.4` on my Synology, and it's confirmed that Tailscale is now running on there stable.

Thank you and team for Tailscale.

And unrelated, but Tailscale's port in [MacPorts](https://www.macports.org) has also been updated: https://ports.macports.org/port/tailscale/
