### ISSUE TITLE
wgengine/magicsock: crash

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#2801]
My `tailscaled` crashed after the recent magicsock refactoring work.

I can't figure out exactly which commit it was, but something recent.  /cc @danderson 

```
magicsock: created endpoint key=[8xcuW]: disco=d:bf4e3f302e6ea487; derp=2(sfo) aip=100.86.113.101 aip=fd7a:115c:a1e0:ab12:4843:cd96:6256:7165 ep=24.4.62.176:56232 ep=135.180.175.246:39811 ep=[2602:248:7b4a:ff60:6080:26b:f34f:6a30]:50828 ep=10.1.10.240:56232 ep=[2602:248:7b4a:ff60::1111]:56232 ep=[2602:248:7b4a:ff60:18b6:4f2c:c627:a466]:56232 ep=[2602:248:7b4a:ff60:6080:26b:f34f:6a30]:56232
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x8600c2]

goroutine 141824 [running]:
tailscale.com/wgengine/magicsock.(*peerMap).deleteDiscoEndpoint(0xc0001315e8, 0xc000312480)
        /home/bradfitz/src/tailscale.com/wgengine/magicsock/magicsock.go:195 +0xc2
tailscale.com/wgengine/magicsock.(*Conn).SetNetworkMap.func2(0xc000312480)
        /home/bradfitz/src/tailscale.com/wgengine/magicsock/magicsock.go:2147 +0x71
tailscale.com/wgengine/magicsock.(*peerMap).forEachDiscoEndpoint(0x9e6f80, 0xc000603e10)
        /home/bradfitz/src/tailscale.com/wgengine/magicsock/magicsock.go:149 +0x98
tailscale.com/wgengine/magicsock.(*Conn).SetNetworkMap(0xc000131400, 0xc0007002c0)
        /home/bradfitz/src/tailscale.com/wgengine/magicsock/magicsock.go:2145 +0x10fb
tailscale.com/wgengine.(*userspaceEngine).SetNetworkMap(0xc000130500, 0xc0007002c0)
        /home/bradfitz/src/tailscale.com/wgengine/userspace.go:1210 +0x45
tailscale.com/wgengine.(*watchdogEngine).SetNetworkMap.func1()
        /home/bradfitz/src/tailscale.com/wgengine/watchdog.go:108 +0x2c
tailscale.com/wgengine.(*watchdogEngine).watchdog.func1()
        /home/bradfitz/src/tailscale.com/wgengine/watchdog.go:72 +0x1b
tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func1()
        /home/bradfitz/src/tailscale.com/wgengine/watchdog.go:54 +0x29
created by tailscale.com/wgengine.(*watchdogEngine).watchdogErr
        /home/bradfitz/src/tailscale.com/wgengine/watchdog.go:53 +0xb8
```

**Comment by bradfitz** [comment]
Crash is when `pi` is nil and ranging over `pi.ipPorts`...

```go
func (m *peerMap) deleteDiscoEndpoint(ep *endpoint) {
        if ep == nil {
                return
        }
        ep.stopAndReset()
        pi := m.byDiscoKey[ep.discoKey]
        delete(m.byDiscoKey, ep.discoKey)
        delete(m.byNodeKey, ep.publicKey)
        for ip := range pi.ipPorts {
                delete(m.byIPPort, ip)
        }
}
```

**Comment by danderson** [comment]
Hm. Walking back up the trace, we delete an endpoint that was handed to us by forEachDiscoEndpoint. As of one of the recent changes, it should not be possible to have a pi without it being linked to a discokey.

The obvious fix is one more nil check, but this is pointing to an inconsistency somewhere in state tracking, so I want to work that out first.

**Comment by danderson** [comment]
... never mind, of course you can have an endpoint sans discokey, that's what asia-relay is. We should be executing this lookup by node key instead. Fixing.

**Comment by bradfitz** [comment]
Another, this time on my Mac, running `1.15.80-t980acc38b-g4ad0fc915`

```
2021-09-08 07:35:07.39318 -0700 PDT: netmap packet filter: 3 filters
2021-09-08 07:35:07.393473 -0700 PDT: magicsock: got updated network map; 104 peers
2021-09-08 07:35:07.393705 -0700 PDT: magicsock: 1 DERP-only peers (no discokey)
2021-09-08 07:35:07.393771 -0700 PDT: magicsock: created endpoint key=[oOrfh]: disco=d:2c3406ef93fa45e0; derp=12(ord) aip=100.108.150.50 aip=fd7a:115c:a1e0:ab12:4843:cd96:626c:9632 ep=72.140.1
33.70:50858 ep=192.168.0.13:50858
2021-09-08 07:35:07.393849 -0700 PDT: magicsock: doing cleanup for discovery key c833bd802f53872e1d095f3a6743e75120ee1cc550296fd7feca6b9f29ae3450
2021-09-08 07:35:07.393857 -0700 PDT: magicsock: doing cleanup for discovery key 0000000000000000000000000000000000000000000000000000000000000000
2021-09-08 15:05:44.573836184 +0000 UTC: panic: runtime error: invalid memory address or nil pointer dereference
2021-09-08 15:05:44.573836184 +0000 UTC: [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10e6de342]
2021-09-08 15:05:44.573836184 +0000 UTC: goroutine 93 [running]:
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/wgengine/magicsock.(*peerMap).deleteDiscoEndpoint(0xc0000b7368, 0xc00032d680)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/wgengine/magicsock/magicsock.go:195 +0xc2
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/wgengine/magicsock.(*Conn).SetNetworkMap.func2(0xc00032d680)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/wgengine/magicsock/magicsock.go:2147 +0x71
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/wgengine/magicsock.(*peerMap).forEachDiscoEndpoint(0x10e8e2140, 0xc0006111e0)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/wgengine/magicsock/magicsock.go:149 +0x98
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/wgengine/magicsock.(*Conn).SetNetworkMap(0xc0000b7180, 0xc00095b080)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/wgengine/magicsock/magicsock.go:2145 +0x10fb
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/wgengine.(*userspaceEngine).SetNetworkMap(0xc0000b6f00, 0xc00095b080)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/wgengine/userspace.go:1210 +0x45
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus(0xc0002b6900, {{}, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0xc00095b080, 0x5, ...})
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/ipn/ipnlocal/local.go:551 +0xbc6
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/control/controlclient.(*Auto).sendStatus(0xc0002ea1e0, {0x10e7b19a4, 0x15}, {0x0, 0x0}, {0x0, 0x0}, 0xc00095b080)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/control/controlclient/auto.go:607 +0x3f5
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/control/controlclient.(*Auto).mapRoutine.func2(0xc00095b080)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/control/controlclient/auto.go:494 +0x1b4
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/control/controlclient.(*Direct).sendMapRequest(0xc00000c1e0, {0x10e981ab8, 0xc000539f00}, 0xffffffffffffffff, 0xc000611ef8)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/control/controlclient/direct.go:825 +0x22ce
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/control/controlclient.(*Direct).PollNetMap(...)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/control/controlclient/direct.go:539
2021-09-08 15:05:44.573836184 +0000 UTC: tailscale.com/control/controlclient.(*Auto).mapRoutine(0xc0002ea1e0)
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/control/controlclient/auto.go:464 +0x4c5
2021-09-08 15:05:44.573836184 +0000 UTC: created by tailscale.com/control/controlclient.(*Auto).Start
2021-09-08 15:05:44.573836184 +0000 UTC:        tailscale.com@v1.1.1-0.20210903201746-980acc38bad2/control/controlclient/auto.go:151 +0xa5
```
