### ISSUE TITLE
ipn/ipnlocal: test flake panic: Log in goroutine after TestStateMachine has completed

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3441]
At 6e584ffa33a8c2b4c11aeddf75cbbe79f4cbb523 + unrelated change.

```
panic: Log in goroutine after TestStateMachine has completed: 
(ignored) Notify{wg={0 0 0 0 map[]}}



goroutine 204 [running]:
testing.(*common).logDepth(0xc00043c680, {0xc000415650, 0x27}, 0x3)
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:779 +0x6d4
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:761
testing.(*common).Logf(0x43e105, {0xef43dc, 0xf}, {0xc0002965b0, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:807 +0x6f
tailscale.com/ipn/ipnlocal.TestStateMachine.func2({{}, {0xc00003c210, 0x14}, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002592f0, 0x0, ...})
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/state_test.go:315 +0x25b
tailscale.com/ipn/ipnlocal.(*LocalBackend).send(0xc0000c1900, {{}, {0xc00003c210, 0x14}, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0002592f0, ...})
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/local.go:1267 +0x155
tailscale.com/ipn/ipnlocal.(*LocalBackend).setWgengineStatus(0xc0000c1900, 0xc000186d00, {0x0, 0x0})
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/local.go:662 +0x4ad
tailscale.com/wgengine.(*userspaceEngine).RequestStatus(0xc0000c0500)
	/home/runner/work/tailscale/tailscale/wgengine/userspace.go:1122 +0xc2
created by tailscale.com/ipn/ipnlocal.(*LocalBackend).requestEngineStatusAndWait
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/local.go:2541 +0x105
exit status 2
FAIL	tailscale.com/ipn/ipnlocal	0.872s
```

**Comment by bradfitz** [comment]
Dup of #3020
