### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#3726]
Tailscale is hung on one of my machines, running a build from a week ago or so (v1.1.1-0.20220107005935-1b426cc232c0, 1b426cc232c0)

Full goroutine dump from `tailscale debug goroutines` (which fortunately still works): [goroutines.txt](https://github.com/tailscale/tailscale/files/7865353/goroutines.txt)

A subset of that file:

```
goroutine 17 [semacquire, 228 minutes, locked to thread]:
sync.runtime_SemacquireMutex(0xc00039d958, 0x50, 0x1041bfde6)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).DERPs(0xc0008bf258)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2568 +0x65
tailscale.com/wgengine.(*userspaceEngine).getStatus(0xc00020b400)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:994 +0x52
tailscale.com/wgengine.(*userspaceEngine).RequestStatus(0xc00020b400)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:1148 +0x53
tailscale.com/ipn/ipnlocal.(*LocalBackend).RequestEngineStatus(0x1041b185e)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/ipn/ipnlocal/local.go:2558 +0x22
tailscale.com/ipn.(*BackendServer).GotCommand(0xc0002909f0, {0x1049d4ff0, 0xc000040068}, 0xc00038c000)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/ipn/message.go:176 +0x5b2
main.sendCmd(0xc00039d5e0)
        tailscale.io/xcode/ipn-go-bridge/ipn.go:259 +0x73
main.send({0xc00039d5e0, 0x45, 0x45})
        tailscale.io/xcode/ipn-go-bridge/ipn.go:242 +0xa6
main.sendAndRecv({0xc00039d5e0, 0x45, 0x45})
        tailscale.io/xcode/ipn-go-bridge/ipn.go:287 +0x71
main.SendBackendMsg(0xc000182000, 0x0, 0x104006cf0)
        tailscale.io/xcode/ipn-go-bridge/ipn.go:233 +0xa6
main.goSendBackendMsg(...)
        tailscale.io/xcode/ipn-go-bridge/export_cgo.go:55

goroutine 71 [semacquire, 228 minutes]:
sync.runtime_SemacquireMutex(0x10445a2a9, 0xd0, 0x1040f85e9)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).handleDiscoMessage(0xc0001238c0, {0xc0007a6000, 0x7c, 0xffff}, {{{0xa2a9, 0x0}, 0xc00000e138}, 0x7c}, {{0x0, 0x0, ...}})
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1854 +0x1a7
tailscale.com/wgengine/magicsock.(*Conn).receiveIP(0xc0001238c0, {0xc0007a6000, 0xffff, 0xffff}, {{{0xc0008c5df8, 0x104092107}, 0xc00000e138}, 0xc060}, 0xc000123960)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1669 +0x12b
tailscale.com/wgengine/magicsock.(*Conn).receiveIPv4(0xc0001238c0, {0xc0007a6000, 0xffff, 0xffff})
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1653 +0x151
golang.zx2c4.com/wireguard/device.(*Device).RoutineReceiveIncoming(0xc00020b680, 0xc0001968c0)
        golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/receive.go:94 +0x18f
created by golang.zx2c4.com/wireguard/device.(*Device).BindUpdate
        golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/device.go:513 +0x439

goroutine 378873 [semacquire, 12 minutes]:
sync.runtime_SemacquireMutex(0x133, 0x72, 0xc0703b7275063030)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).SetNetworkUp(0xc0001238c0, 0x1)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2136 +0x5e
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc00020b400, 0x1, 0xc0008c7e00)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:1213 +0x158
tailscale.com/wgengine.NewUserspaceEngine.func1(0xad, 0xc00023cb40)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:332 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/monitor/monitor.go:330 +0x565

goroutine 378908 [semacquire, 12 minutes]:
sync.runtime_SemacquireMutex(0x16, 0xe2, 0xc0703b7d27616008)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).SetNetworkUp(0xc0001238c0, 0x1)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2136 +0x5e
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc00020b400, 0x0, 0xc000610000)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:1213 +0x158
tailscale.com/wgengine.NewUserspaceEngine.func1(0xad, 0xc00023cb40)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:332 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/monitor/monitor.go:330 +0x565

goroutine 375620 [semacquire, 116 minutes]:
sync.runtime_SemacquireMutex(0x198, 0x77, 0xc07035194590aec0)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).SetNetworkUp(0xc0001238c0, 0x1)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2136 +0x5e
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc00020b400, 0x1, 0xc0006feaa0)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:1213 +0x158
tailscale.com/wgengine.NewUserspaceEngine.func1(0xa6, 0xc00023cb40)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:332 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/monitor/monitor.go:330 +0x565

goroutine 371384 [semacquire, 228 minutes]:
sync.runtime_SemacquireMutex(0xc00011aab0, 0x8, 0x1040ee4a7)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).sendDiscoMessage(0xc0001238c0, {{{0xc0004ff260, 0x104e9a620}, 0xc00000e138}, 0x0}, {{0x51, 0x33, 0x7e, 0x37, 0xf, ...}}, ...)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1770 +0xaa
tailscale.com/wgengine/magicsock.(*endpoint).sendDiscoPing(0xc000448640, {{{0x5f5e100, 0xc0002e9c38}, 0xc00000e138}, 0x4401}, {{0xb3, 0xcf, 0xd8, 0xc2, 0x3c, ...}}, ...)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:3617 +0x1e5
created by tailscale.com/wgengine/magicsock.(*endpoint).startPingLocked
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:3673 +0x515

goroutine 371518 [semacquire, 227 minutes]:
sync.runtime_SemacquireMutex(0x1d000001052413c8, 0x40, 0x1049d1378)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).enqueueCallMeMaybe(0xc0001238c0, {{{0x30, 0x0}, 0xc00000e138}, 0xe138}, 0xc000448640)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2088 +0xa5
created by tailscale.com/wgengine/magicsock.(*endpoint).sendPingsLocked
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:3707 +0x53a

goroutine 372370 [semacquire, 214 minutes]:
sync.runtime_SemacquireMutex(0x11d, 0x42, 0xc0702189812f1da8)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).SetNetworkUp(0xc0001238c0, 0x1)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2136 +0x5e
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc00020b400, 0x1, 0xc0008c63c0)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:1213 +0x158
tailscale.com/wgengine.NewUserspaceEngine.func1(0xad, 0x104ecaa80)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:332 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/monitor/monitor.go:330 +0x565

goroutine 370653 [semacquire, 228 minutes]:
sync.runtime_SemacquireMutex(0x0, 0x5a, 0x1040a8d85)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).sendDiscoMessage(0xc0001238c0, {{{0xc0000aa400, 0x10000c0004ede38}, 0xc00000e138}, 0x3}, {{0x39, 0xf0, 0xd5, 0x92, 0x42, ...}}, ...)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1770 +0xaa
tailscale.com/wgengine/magicsock.(*endpoint).sendDiscoPing(0xc0004acb40, {{{0x50, 0x0}, 0xc00000e138}, 0xe138}, {{0x64, 0xb8, 0x4c, 0x95, 0xbb, ...}}, ...)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:3617 +0x1e5
created by tailscale.com/wgengine/magicsock.(*endpoint).startPingLocked
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:3673 +0x515
```

**Comment by bradfitz** [comment]
Here's the only goroutine in semacquire lockSlow that has a unique address:

```
goroutine 371226 [semacquire, 228 minutes]:
sync.runtime_SemacquireMutex(0x0, 0x0, 0xc0008dfda8)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0000cc160)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/derp/derphttp.(*Client).LocalAddr(0xc0000d6000)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/derp/derphttp/derphttp_client.go:780 +0x47
tailscale.com/wgengine/magicsock.(*Conn).maybeCloseDERPsOnRebind(0xc0001238c0, {0xc000148e80, 0x4, 0x4})
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2426 +0x16b
tailscale.com/wgengine/magicsock.(*Conn).Rebind(0xc0001238c0)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:2912 +0x14b
tailscale.com/wgengine.(*userspaceEngine).linkChange(0xc00020b400, 0x1, 0xc0007b6410)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:1240 +0x17b
tailscale.com/wgengine.NewUserspaceEngine.func1(0x0, 0xc0000d6301)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/userspace.go:332 +0x3f
created by tailscale.com/wgengine/monitor.(*Mon).debounce
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/monitor/monitor.go:330 +0x565
```

**Comment by bradfitz** [comment]
(and `maybeCloseDERPsOnRebind` is new code)

/cc @DentonGentry

**Comment by bradfitz** [comment]
Which is:

```
func (c *Client) LocalAddr() (netaddr.IPPort, error) {
        c.mu.Lock()
        closed, client := c.closed, c.client
        c.mu.Unlock()
```

Apparently a lock ordering problem between magicsock.Conn.mu and derphttp.Client.mu.

**Comment by bradfitz** [comment]
Maybe:

```
goroutine 371103 [semacquire, 228 minutes]:
sync.runtime_SemacquireMutex(0xc0005e15f0, 0xb4, 0x105240a68)
        runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc0001239ec)
        sync/mutex.go:138 +0x165
sync.(*Mutex).Lock(...)
        sync/mutex.go:81
tailscale.com/wgengine/magicsock.(*Conn).derpWriteChanOfAddr.func1()
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1361 +0x89
tailscale.com/derp/derphttp.(*Client).connect(0xc0000cc0e0, {0x1049d4ff0, 0xc000040068}, {0x104728660, 0x14})
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/derp/derphttp/derphttp_client.go:230 +0x242
tailscale.com/derp/derphttp.(*Client).Send(0xc00048ac66, {{0x39, 0xf0, 0xd5, 0x92, 0x42, 0x56, 0xd3, 0xae, 0x7c, ...}}, ...)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/derp/derphttp/derphttp_client.go:693 +0x57
tailscale.com/wgengine/magicsock.(*Conn).runDerpWriter(0xc0001238c0, {0x1049d4fb8, 0xc00038bbc0}, 0xc0002e9837, 0xc000269680, 0x1300, 0xc00053a3c0)
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1617 +0x24e
created by tailscale.com/wgengine/magicsock.(*Conn).derpWriteChanOfAddr
        tailscale.com@v1.1.1-0.20220107005935-1b426cc232c0/wgengine/magicsock/magicsock.go:1410 +0xfd3
```

**Comment by bradfitz** [comment]
To summarize, it's a lock ordering bug between magicsock.Conn.mu and derphttp.Client.mu.

The two stacks: (or at least one possible set of two stacks)

1) `derphttp.Client.connect` (derp mutex first at top of `connect`, then calls its `getRegion` func callback which is defined in magicsock as in my earlier comment to call `c.mu.Lock()`).  So that's the derp then magicsock order.
2) `magicsock.Conn.maybeCloseDERPsOnRebind`: magicsock mutex at top of `maybeCloseDERPsOnRebind`, then `ad.c.LocalAddr()` a few lines later, acquiring the `derphttp.Client.mu`

That (2) path is new in 1.19.x.

So I guess the official lock ordering is derp then magicsock.

**Comment by bradfitz** [comment]
But no, there are existing paths prior to the `maybeCloseDERPsOnRebind` that acquire in the other order:

* magicsock `derpWriteChanOfAddr` acquires magicsock mutex, then calls `derphttp.Client.SetCanAckPings` and `derphttp.Client.NotePreferred`, both of which acquire derp mutex.

**Comment by bradfitz** [comment]
As magicsock.Conn has references to derphttp.Clients but not vice-versa, I'm inclined to say that the lock ordering rules *should* be magicsock first, then derphttp.Client.

In that case, there's only one possible way to violate it: the `getRegion` callback.

If we instead make the getRegion lock-free (using an atomic.Value for the derpMap), ...

``` go
dc := derphttp.NewRegionClient(c.privateKey, c.logf, func() *tailcfg.DERPRegion {
....
        c.mu.Lock()   // <---- replace this with derpMapAtomic
        defer c.mu.Unlock()
        if c.derpMap == nil {
                return nil
        }
        return c.derpMap.Regions[regionID]
```

.... then there should be no way for derphttp to ever acquire magicsock.Conn.mu afterwards.
