### ISSUE TITLE
`slice bounds out of range [4:0]` in netstack tcpip/header/udp.go:79

### ISSUE THREAD

**Issue by DentonGentry** [tailscale/tailscale#3880]
### What is the issue?

A user has compiled Tailscaled-for-macOS, and has one system where tailscaled is crashing with
`panic: runtime error: slice bounds out of range [4:0]`.

```
2022/02/01 14:00:26 proxy connection closed with error: read tcp 10.0.6.101:62554->10.0.6.101:6881: read: connection reset by peer
2022/02/01 14:00:26 proxy connection closed with error: read tcp 10.0.6.100:62559->10.0.6.100:6881: read: connection reset by peer
2022/02/01 14:00:26 proxy connection closed with error: read tcp 10.0.6.100:62553->10.0.6.100:6881: read: connection reset by peer
panic: runtime error: slice bounds out of range [4:0]

goroutine 238 [running]:
inet.af/netstack/tcpip/header.UDP.Length(...)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/header/udp.go:79
inet.af/netstack/tcpip/transport/udp.(*endpoint).HandlePacket(0xc003ef8300, {0x1ae1, {0xc00068f4a8, 0x4}, 0x1ae3, {0xc00068f4a4, 0x4}}, 0xc0037687e0)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/transport/udp/endpoint.go:872 +0x6c9
inet.af/netstack/tcpip/stack.(*endpointsByNIC).handlePacket(0xc0010a0570, {0x1ae1, {0xc00068f4a8, 0x4}, 0x1ae3, {0xc00068f4a4, 0x4}}, 0xc0037687e0)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/stack/transport_demuxer.go:185 +0x27f
inet.af/netstack/tcpip/stack.(*transportDemuxer).deliverPacket(0xc0001f6360, 0x11, 0xc0037687e0, {0x1ae1, {0xc00068f4a8, 0x4}, 0x1ae3, {0xc00068f4a4, 0x4}})
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/stack/transport_demuxer.go:595 +0x3b0
inet.af/netstack/tcpip/stack.(*nic).DeliverTransportPacket(0xc00019e000, 0x11, 0xc0037687e0)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/stack/nic.go:872 +0x1f7
inet.af/netstack/tcpip/network/ipv4.(*endpoint).handleValidatedPacket(0xc000361800, {0xc0028f5810, 0x14, 0xb0}, 0xc003768900, {0x0, 0x0})
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/network/ipv4/ipv4.go:1068 +0xfd6
inet.af/netstack/tcpip/network/ipv4.(*endpoint).HandlePacket(0xc000361800, 0x14d6935)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/network/ipv4/ipv4.go:854 +0x2b0
inet.af/netstack/tcpip/stack.(*nic).DeliverNetworkPacket(0xc00019e000, {0xc00372bbf0, 0x1}, {0x0, 0x0}, 0x800, 0xc003768900)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/stack/nic.go:788 +0x2d6
inet.af/netstack/tcpip/link/channel.(*Endpoint).InjectLinkAddr(...)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/link/channel/channel.go:207
inet.af/netstack/tcpip/link/channel.(*Endpoint).InjectInbound(...)
	/Users/mb/Developer/go/pkg/mod/inet.af/netstack@v0.0.0-20211120045802-8aa80cf23d3c/tcpip/link/channel/channel.go:202
tailscale.com/wgengine/netstack.(*Impl).injectInbound(0xc000126480, 0xc0033b8200, 0xc003882ae0)
	/Users/mb/Developer/go/src/github.com/tailscale/tailscale/wgengine/netstack/netstack.go:523 +0x744
tailscale.com/net/tstun.(*Wrapper).filterIn(0xc0000ee000, {0xc003b0e010, 0xae, 0xffef})
	/Users/mb/Developer/go/src/github.com/tailscale/tailscale/net/tstun/wrap.go:615 +0x78d
tailscale.com/net/tstun.(*Wrapper).Write(0xc0000ee000, {0xc003b0e000, 0xc00043f180, 0x1}, 0x10)
	/Users/mb/Developer/go/src/github.com/tailscale/tailscale/net/tstun/wrap.go:628 +0x7c
golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialReceiver(0xc000860000)
	/Users/mb/Developer/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/receive.go:477 +0x4d1
created by golang.zx2c4.com/wireguard/device.(*Peer).Start
	/Users/mb/Developer/go/pkg/mod/golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/peer.go:199 +0x295
tailscale-startup - TCPIP is available
tailscale-startup established on utun9
```

HEAD in their OSS tree is:
```
commit d6fb86020684dd5436b96ab1956935f02d5995b1
Author: Maisem Ali 
Date:   Thu Feb 3 10:25:41 2022 -0800

    chirp: remove regex dependency
    
    Signed-off-by: Maisem Ali 
    (cherry picked from commit e64cecac8e7ecbba5df50d0e2229bb11d00c5686)
```

Which means they are building from the HEAD of release-branch/1.20 with the changes that have been cherry-picked for 1.20.4 (which has not been built yet).

The user says the problem was also happening when their build said it was 1.20.2, so the problem is not related to the most recent changes in the branch. It has been there for a while.

**Comment by DentonGentry** [comment]
https://github.com/inetaf/netstack/blob/8aa80cf23d3cced44d45a31a5d8b841fae949dcf/tcpip/transport/udp/endpoint.go#L869
```
func (e *endpoint) HandlePacket(id stack.TransportEndpointID, pkt *stack.PacketBuffer) {
	// Get the header then trim it from the view.
	hdr := header.UDP(pkt.TransportHeader().View())
	if int(hdr.Length()) > pkt.Data().Size()+header.UDPMinimumSize {
		// Malformed packet.
```

is called from https://github.com/inetaf/netstack/blob/8aa80cf23d3cced44d45a31a5d8b841fae949dcf/tcpip/stack/transport_demuxer.go#L159.

I don't see a length check anywhere prior to the one in transport/udp/endpoint.go, which makes the assumption that the packet is long enough to have the first few bytes of a UDP header. If we receive a bare 20 byte IPv4 packet where the protocol field is set to 17 for UDP, I think we get this crash. It is trying to look up a UDP header that isn't there.

**Comment by DentonGentry** [comment]
[#4222](https://github.com/tailscale/tailscale/pull/4222) updated to the latest gvisor

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/pull/5253 updated gvisor again. We haven't seen this issue since the initial occurrence.
