### ISSUE TITLE
Use custom derper server,got error when add OmitDefaultRegions=true in ACL

### ISSUE THREAD

**Issue by mwcodefun** [tailscale/tailscale#3896]
### What is the issue?

My network:

Openwrt router running tailscale and tailscale derper ip:192.168.11.1
One win10 system in home network ip:192.168.11.123
one Office system with remote ip

When I add OmitDefaultRegions = "true" to acl
openwrt tailsclae and win10 tailscale is down
Log on openwrt tailscale:

```
root@OpenWrt:~# tailscaled
logtail started
Program starting: v1.20.2-t312750ddd-g2c164d9c7, Go 1.17.6-tse44d304e54: []string{"/tmp/tailscaled"}
LogID: 06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d
logpolicy: using system state directory "/var/lib/tailscale"
wgengine.NewUserspaceEngine(tun "tailscale0") ...
logtail: dialed "log.tailscale.io:443" in 3ms
router: v6nat = true
dns: [rc=unknown ret=direct]
dns: using *dns.directManager
link state: interfaces.State{defaultRoute=pppoe-wan ifs={br-lan:[192.168.11.1/24] docker0:[172.17.0.1/16] pppoe-wan:[mywanip/32 wanipv6:fdff/64]} v4=true v6=true}
magicsock: disco key = d:0f994e83dda7451a
Creating wireguard device...
Bringing wireguard device up...
external route: up
Bringing router up...
Clearing router settings...
Starting link monitor...
Engine created.
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:254 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5210 Table:254 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:253 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5230 Table:253 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:0 Protocol:0 Scope:0 Type:7 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5250 Table:0 Mark:4294967295 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: ip rule deleted: {Family:2 DstLength:0 SrcLength:0 Tos:0 Table:52 Protocol:0 Scope:0 Type:1 Flags:0 Attributes:{Dst:<nil> Src:<nil> Gateway:<nil> OutIface:0 Priority:5270 Table:52 Mark:0 Expires:<nil> Metrics:<nil> Multipath:[]}}
monitor: RTM_NEWROUTE: src=, dst=ff00::/8, gw=, outif=30, table=255
monitor: RTM_NEWROUTE: src=, dst=fe80::/64, gw=, outif=30, table=254
monitor: RTM_NEWROUTE: src=, dst=fe80::81:eb8b:ab6f:f2b2/128, gw=, outif=30, table=255
monitor: RTM_NEWROUTE: src=, dst=fe80::/128, gw=, outif=30, table=255
netmap packet filter: (not ready yet)
Start
using backend prefs
created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
got initial portlist info in 0s
control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d","OS":"linux","OSVersion":"OpenWrt GDQ; kernel=5.4.132","Hostname":"OpenWrt","GoArch":"amd64","Services":[{"Proto":"tcp","Port":21,"Description":"vsftpd"},{"Proto":"tcp","Port":22,"Description":"dropbear"},{"Proto":"tcp","Port":53,"Description":"dnsmasq"},{"Proto":"tcp","Port":80,"Description":"uhttpd"},{"Proto":"tcp","Port":111,"Description":"rpcbind"},{"Proto":"tcp","Port":139,"Description":"smbd"},{"Proto":"tcp","Port":443,"Description":"uhttpd"},{"Proto":"tcp","Port":445,"Description":"smbd"},{"Proto":"tcp","Port":1041,"Description":"v2ray"},{"Proto":"tcp","Port":1688,"Description":"vlmcsd"},{"Proto":"tcp","Port":2049},{"Proto":"tcp","Port":3000,"Description":"koolproxy"},{"Proto":"tcp","Port":3702,"Description":"wsdd2"},{"Proto":"tcp","Port":4443,"Description":"ocserv-main"},{"Proto":"tcp","Port":5200,"Description":"UnblockNeteaseMusic"},{"Proto":"tcp","Port":5201,"Description":"UnblockNeteaseMusic"},{"Proto":"tcp","Port":5355,"Description":"wsdd2"},{"Proto":"tcp","Port":7681,"Description":"ttyd"},{"Proto":"tcp","Port":8888,"Description":"derper"},{"Proto":"tcp","Port":8897,"Description":"linkease"},{"Proto":"tcp","Port":19999,"Description":"netdata"},{"Proto":"tcp","Port":32777},{"Proto":"tcp","Port":32778,"Description":"rpc.statd"},{"Proto":"tcp","Port":32780,"Description":"rpc.mountd"}]}
Backend: logs: be:06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d fe:
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
blockEngineUpdates(true)
health("overall"): error: state=NeedsLogin, wantRunning=false
wgengine: Reconfig: configuring userspace wireguard config (with 0/0 peers)
wgengine: Reconfig: configuring router
wgengine: Reconfig: configuring DNS
dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
dns: OScfg: {Nameservers:[] SearchDomains:[] MatchDomains:[]}
router: somebody (likely systemd-networkd) deleted ip rules; restoring Tailscale's
netmap packet filter: (not ready yet)
control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d","OS":"linux","OSVersion":"OpenWrt GDQ; kernel=5.4.132","Hostname":"OpenWrt","GoArch":"amd64","Services":[{"Proto":"peerapi-dns-proxy","Port":1}]}
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:new
ipnserver: conn2: connection from userid 0; root has access
Start
control: client.Shutdown()
control: client.Shutdown: inSendStatus=0
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: context done.
control: mapRoutine: state:new
control: mapRoutine: quit
control: Client.Shutdown done.
using backend prefs
created empty state for "_daemon": Prefs{ra=true dns=true want=false routes=[] nf=on Persist=nil}
generating new machine key
machine key written to store
netmap packet filter: (not ready yet)
control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d","OS":"linux","OSVersion":"OpenWrt GDQ; kernel=5.4.132","Hostname":"OpenWrt","GoArch":"amd64","RoutableIPs":["0.0.0.0/0","::/0","192.168.11.0/24"],"Services":[{"Proto":"tcp","Port":21,"Description":"vsftpd"},{"Proto":"tcp","Port":22,"Description":"dropbear"},{"Proto":"tcp","Port":53,"Description":"dnsmasq"},{"Proto":"tcp","Port":80,"Description":"uhttpd"},{"Proto":"tcp","Port":111,"Description":"rpcbind"},{"Proto":"tcp","Port":139,"Description":"smbd"},{"Proto":"tcp","Port":443,"Description":"uhttpd"},{"Proto":"tcp","Port":445,"Description":"smbd"},{"Proto":"tcp","Port":1041,"Description":"v2ray"},{"Proto":"tcp","Port":1688,"Description":"vlmcsd"},{"Proto":"tcp","Port":2049},{"Proto":"tcp","Port":3000,"Description":"koolproxy"},{"Proto":"tcp","Port":3702,"Description":"wsdd2"},{"Proto":"tcp","Port":4443,"Description":"ocserv-main"},{"Proto":"tcp","Port":5200,"Description":"UnblockNeteaseMusic"},{"Proto":"tcp","Port":5201,"Description":"UnblockNeteaseMusic"},{"Proto":"tcp","Port":5355,"Description":"wsdd2"},{"Proto":"tcp","Port":7681,"Description":"ttyd"},{"Proto":"tcp","Port":8888,"Description":"derper"},{"Proto":"tcp","Port":8897,"Description":"linkease"},{"Proto":"tcp","Port":19999,"Description":"netdata"},{"Proto":"tcp","Port":32777},{"Proto":"tcp","Port":32778,"Description":"rpc.statd"},{"Proto":"tcp","Port":32780,"Description":"rpc.mountd"}]}
Backend: logs: be:06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d fe:
control: authRoutine: state:new; goal=nil paused=false
control: mapRoutine: state:new
Switching ipn state NoState -> NeedsLogin (WantRunning=true, nm=false)
blockEngineUpdates(true)
StartLoginInteractive: url=false
control: client.Login(false, 2)
control: authRoutine: state:new; wantLoggedIn=true
control: direct.TryLogin(token=false, flags=2)
control: LoginInteractive -> regen=true
control: doLogin(regen=true, hasUrl=false)
control: control server key [nlFWp] from https://controlplane.tailscale.com
control: Generating a new nodekey.
control: RegisterReq: onode= node=[pYNOY] fup=false
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=false; authURL=true
control: AuthURL is https://login.tailscale.com/a/de778d5587f1
Received auth URL: https://login.tailsc...
popBrowserAuthNow: url=true
blockEngineUpdates(true)
stopEngineAndWait...
requestEngineStatusAndWait
requestEngineStatusAndWait: waiting...
requestEngineStatusAndWait: got status update.
stopEngineAndWait: done.
authReconfig: blocked, skipping.
control: authRoutine: state:url-visit-required; wantLoggedIn=true
control: direct.WaitLoginURL
control: doLogin(regen=false, hasUrl=true)
control: RegisterReq: onode= node=[pYNOY] fup=true
control: HostInfo: {"IPNVersion":"1.20.2-t312750ddd-g2c164d9c7","BackendLogID":"06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d","OS":"linux","OSVersion":"OpenWrt GDQ; kernel=5.4.132","Hostname":"OpenWrt","GoArch":"amd64","RoutableIPs":["0.0.0.0/0","::/0","192.168.11.0/24"],"Services":[{"Proto":"peerapi-dns-proxy","Port":1}]}
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:url-visit-required
control: RegisterReq: got response; nodeKeyExpired=false, machineAuthorized=true; authURL=false
control: No AuthURL
blockEngineUpdates(false)
authReconfig: netmap not yet valid. Skipping.
authReconfig: netmap not yet valid. Skipping.
control: authRoutine: state:authenticated; goal=nil paused=false
control: mapRoutine: new map needed while idle.
control: mapRoutine: state:authenticated
active login: mawerss1@gmail.com
netmap packet filter: 1 filters
Switching ipn state NeedsLogin -> Starting (WantRunning=true, nm=true)
magicsock: SetPrivateKey called (init)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8f374b]

goroutine 166 [running]:
tailscale.com/net/netcheck.makeProbePlanInitial(0xc0002030f0, 0xc00020c640)
        tailscale.com@v1.20.2/net/netcheck/netcheck.go:441 +0x2ab
tailscale.com/net/netcheck.makeProbePlan(0xc0000b4050, 0xc000516000, 0xc0000b6280)
        tailscale.com@v1.20.2/net/netcheck/netcheck.go:355 +0x13c
tailscale.com/net/netcheck.(*Client).GetReport(0xc00012a7e0, {0xd72da8, 0xc0006d4060}, 0xc0002030f0)
        tailscale.com@v1.20.2/net/netcheck/netcheck.go:862 +0xda5
tailscale.com/wgengine/magicsock.(*Conn).updateNetInfo(0xc0000d1340, {0xd72d38, 0xc0001808c0})
        tailscale.com@v1.20.2/wgengine/magicsock/magicsock.go:739 +0x1da
tailscale.com/wgengine/magicsock.(*Conn).determineEndpoints(0xc0000d1340, {0xd72d38, 0xc0001808c0})
        tailscale.com@v1.20.2/wgengine/magicsock/magicsock.go:1032 +0xcb
tailscale.com/wgengine/magicsock.(*Conn).updateEndpoints(0xc0000d1340, {0xc3a960, 0xf})
        tailscale.com@v1.20.2/wgengine/magicsock/magicsock.go:653 +0x1d8
created by tailscale.com/wgengine/magicsock.(*Conn).ReSTUN
        tailscale.com@v1.20.2/wgengine/magicsock/magicsock.go:2787 +0x3b2
```
Another problem:
On tailscale web site I notice a my win10 show a wired delay to tailscale derpers.
```
win 10
Relays
Sydney: 0.53 ms
Tokyo: 0.53 ms
Bangalore: 1.05 ms
```

```
openwrt 
Relay #900: 0.70 ms
Tokyo: 165.65 ms
Singapore: 283.42 ms
```

win10 and openwrt is in one network,I think the delay win10 to Tokyo server is not passible so low. But Im not sure what happend.

### OS

Linux

### Tailscale version

1.20.2   tailscale commit: 312750ddd288cf4073cfaef56a45102b9c1e8421   other commit: 2c164d9c7443e2f3014fa54ea45e946b35152680   go version: go1.17.6-tse44d304e54

### Bug report

BUG-06cac09073c447b734db0f3f44a978c630e27fd4151f3581dc0a28cc78835f6d-20220209163824Z-b72edada0b5c0095

**Comment by mwcodefun** [comment]
> Ah, it looks like you originally had a specific region null'ed out () in your value, and then you added , in which case we passed through your derpMap unmodified to the client, but the client crashes on a null region definition, as that's only a server-side concept that should get cleaned up.`"1": null``"derpMap"``OmitDefaultRegions`
> 
> We can fix the server so that's okay to do.

Work perfect after remove null value.
And why is win10 delay  so low?

**Comment by bradfitz** [comment]
I've sent out a fix to the server. It will be deployed later today, so the null+ OmitDefaultRegions won't crash the client. No client update will be needed after that's deployed.

> And why is win10 delay so low?

Looks like you're behind a "hard NAT" (endpoint-depending mapping) on all devices, don't have IPv6, and your router doesn't support PMP/PCP/UPnP. That's basically the worst of all situations. What's your ISP & router that they're behind? Can you manually add port mappings?

If you're in China, the Great Firewall is almost certainly interfering with your traffic and we can't really help.

**Comment by mwcodefun** [comment]
> I've sent out a fix to the server. It will be deployed later today, so the null+ OmitDefaultRegions won't crash the client. No client update will be needed after that's deployed.
> 
> > And why is win10 delay so low?
> 
> Looks like you're behind a "hard NAT" (endpoint-depending mapping) on all devices, don't have IPv6, and your router doesn't support PMP/PCP/UPnP. That's basically the worst of all situations. What's your ISP & router that they're behind? Can you manually add port mappings?
> 
> If you're in China, the Great Firewall is almost certainly interfering with your traffic and we can't really help.

I had set a proxy  on openwrt to jump GTW, I mean my win10 machine is in subnet of openwrt,openwrt delay to Tokyo is 100+ms,but win10's delay to Tokyo is 0.05ms,and why? the win10 is not traffic after openwrt router? Sorry Im known less about network.Maybe I need to read some wiki?
