### ISSUE TITLE
Wear OS support

### ISSUE THREAD

**Issue by sergmaxin** [tailscale/tailscale#3972]
### What are you trying to do?

i want to access via vpn to Home Assistant (Wear OS client)

### How should we solve this?

Wear OS support

**Comment by bootstrap-prime** [comment]
Seconding this - wearos support would be incredibly convenient. 
I attempted to sideload the normal tailscale app, assuming it'd be a little wonky but work since wearos is just android, and I was able to log in to tailscale. Unfortunately, after sign in it would just consistently crash. (not sure how to get debug logs from the watch, unfortunately.)

**Comment by bradfitz** [comment]
What does `adb logcat` say when it crashes?

**Comment by bootstrap-prime** [comment]
I'm not sure how to interpret this, and the log of the few seconds is rather large (4.8MB). should I load it into a gist and toss a link? (I'm not sure if adb logcat can contain sensitive information)

**Comment by DentonGentry** [comment]
You're welcome to email a link to support@tailscale.com and reference issue 3972, to keep it out of the public bug.

**Comment by DentonGentry** [comment]
I think this is it, `dlopen failed: library "libgio.so" not found`:
```
05-30 16:21:14.604  5714  5714 D AndroidRuntime: Shutting down VM
05-30 16:21:14.614  5714  5714 E AndroidRuntime: FATAL EXCEPTION: main
05-30 16:21:14.614  5714  5714 E AndroidRuntime: Process: com.tailscale.ipn, PID: 5714
05-30 16:21:14.614  5714  5714 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libgio.so" not found
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at org.gioui.Gio.init(Gio.java:37)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at com.tailscale.ipn.App.onCreate(App.java:93)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1192)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6746)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:241)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1920)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7690)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
05-30 16:21:14.614  5714  5714 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)
05-30 16:21:14.627   555  3018 D Debug   : low && ship && 3rd party app crash, so skip dump
05-30 16:21:14.631   555  7116 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-30 16:21:14.631   555  3018 W ActivityTaskManager:   Force finishing activity com.tailscale.ipn/.IPNActivity
```

**Comment by bootstrap-prime** [comment]
Is there any other information I can provide to assist diagnosis and fix?

**Comment by DentonGentry** [comment]
What model is the wearOS device?

I don't immediately know why libgio is missing, it is bundled into the Tailscale app.

**Comment by bradfitz** [comment]
Probably a missing 32-bit architecture.

**Comment by bootstrap-prime** [comment]
Galaxy Watch 4 SM-R860

**Comment by DentonGentry** [comment]
> Galaxy Watch 4 SM-R860

Exynos W920 dual core 1.18 GHz CPU
It is an ARM Cortex A55, which is an ARM64 v8.2

**Comment by OshedheMunasinghe** [comment]
I have a Samsung watch pro 5. It would be nice if you guys can do it with a smartwatch.

**Comment by DentonGentry** [comment]
Samsung Watch Pro 5 uses an Exynos W920, which is a dual Cortex-A55.
Cortex-A55 is an arm64.

Even if we sort out why libgio is missing, we'd need a different UI to be functional on a watch form factor.

**Comment by clari7744** [comment]
Throwing in that I also have a Galaxy Watch6 and would enjoy seeing this feature. My main use case would be for accessing my watch over ADB on networks where my devices can't see each other; for example my home network is isolated so I have to use https://github.com/lakinduakash/linux-wifi-hotspot and connect my watch to that for ADB. Using Tailscale would cut that need out.

**Comment by shschampion** [comment]
If I may, I would like to add my voice to the (rather feeble) chorus asking for the ability to run Tailscale on WearOS. My use case: Samsung Galaxy Watch 6, Home Assistant Companion App while away from the home network

**Comment by Digicrat** [comment]
+1 here, also for Home Assistant usage.  

Alternatively, some other method to explicitly expose a specific IP/port to other devices connected to the phone via BT and/or Wifi hotspot...

**Comment by jonathans859** [comment]
Another +1 for Home Assistant, and generally that seems like a nice thing to have.

**Comment by ljcucc** [comment]
I got another error on Xiaomi watch 2.

The app opens then crashes after trying to add VPN profile.
wearOS: 3.5
Tailscale version: 1.88.3

```
10-23 22:13:47.422 12578 12649 D ProfileInstaller: Installing profile for com.tailscale.ipn
10-23 22:13:48.114 12578 12578 D VpnPermissions: vpnIntent=Intent { cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub }
10-23 22:13:48.115 12578 12636 D gojni   : VpnPermissions: vpnIntent=Intent { cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub }
10-23 22:13:48.116  1058  2365 I ActivityTaskManager: START u0 {cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub} from uid 10075
10-23 22:13:48.119  1058  2365 W ActivityTaskManager: Permission Denial: starting Intent { cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub } from ProcessRecord{c36fce1 12578:com.tailscale.ipn/u0a75} (pid=12578, uid=10075) not exported from uid 10028
10-23 22:13:48.153 12578 12578 E AndroidRuntime: FATAL EXCEPTION: main
10-23 22:13:48.153 12578 12578 E AndroidRuntime: Process: com.tailscale.ipn, PID: 12578
10-23 22:13:48.153 12578 12578 E AndroidRuntime: java.lang.SecurityException: Permission Denial: starting Intent { cmp=com.google.android.wearable.frameworkpackagestubs/.Stubs$VpnStub } from ProcessRecord{c36fce1 12578:com.tailscale.ipn/u0a75} (pid=12578, uid=10075) not exported from uid 10028
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2387)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2371)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2354)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2296)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3719)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1723)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5314)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at c.n.startActivityForResult(SourceFile:2)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at c.l.b(Unknown Source:273)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at f.h.a(Unknown Source:101)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.tailscale.ipn.ui.viewModel.MainViewModel.showVPNPermissionLauncherIfUnauthorized(Unknown Source:37)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.tailscale.ipn.ui.view.MainViewKt$MainView$1$1$1$9.invoke(SourceFile:2)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.tailscale.ipn.ui.view.MainViewKt$MainView$1$1$1$9.invoke(SourceFile:1)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.tailscale.ipn.ui.view.MainViewKt$ConnectView$1$1.invokeSuspend(Unknown Source:19)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at m4.a.resumeWith(Unknown Source:8)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at M5.L.run(Unknown Source:112)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at D0.l0.K(Unknown Source:23)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at D0.k0.run(Unknown Source:2)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7651)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:953)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	Suppressed: R5.g: [D0.O0@9e7c624, R.g@9e6858d, z0{Cancelling}@be60342, l0@cf9af53]
10-23 22:13:48.153 12578 12578 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1060)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1006)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:676)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1194)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 	at com.android.server.wm.ActivityTaskManagerService.startActivityAsUser(ActivityTaskManagerService.java:1157)
10-23 22:13:48.153 12578 12578 E AndroidRuntime: 
```

**Comment by obj-obj** [comment]
+1 for home assistant, tried sideloading the regular android app but it immediately crashes. Seems my pixel watch 3 is some weird variant of armv8 that's 32-bit only.

**Comment by owense** [comment]
+1 here, definitely would love to have tailscale connectivity on my pixel watch 3.

**Comment by pascu-cd** [comment]
1+ here too, would love to get tailscale on my pixel watch 3 too

**Comment by dedsecorg** [comment]
+1 I would also want this to work on my Samsung watch 5 too!
