### ISSUE TITLE
Random panicking

### ISSUE THREAD

**Issue by danlsgiga** [tailscale/tailscale#4207]
### What is the issue?

Tailscale crashes randomly with the following error:

```
panic: Incrementing non-positive count 0x400037dc00 on stack.PacketBuffer

goroutine 281 [running]:
gvisor.dev/gvisor/pkg/tcpip/stack.(*packetBufferRefs).IncRef(0x400037dc00)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/packet_buffer_refs.go:80 +0x164
gvisor.dev/gvisor/pkg/tcpip/transport/udp.(*endpoint).HandlePacket(0x4000542000, {0xd9d, {0x400058abc0, 0x4}, 0x4014, {0x400058abbc, 0x4}}, 0x400037dc00)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/transport/udp/endpoint.go:924 +0x444
gvisor.dev/gvisor/pkg/tcpip/stack.(*endpointsByNIC).handlePacket(0x40002da0f0, {0xd9d, {0x400058abc0, 0x4}, 0x4014, {0x400058abbc, 0x4}}, 0x400037dc00)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/transport_demuxer.go:185 +0x2a8
gvisor.dev/gvisor/pkg/tcpip/stack.(*transportDemuxer).deliverPacket(0x400000cc90, 0x11, 0x400037dc00, {0xd9d, {0x400058abc0, 0x4}, 0x4014, {0x400058abbc, 0x4}})
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/transport_demuxer.go:595 +0x414
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).DeliverTransportPacket(0x400024a000, 0x11, 0x400037dc00)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/nic.go:861 +0x310
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).handleValidatedPacket(0x40000bb100, {0x400003c550, 0x14, 0x50}, 0x4000294000, {0x0, 0x0})
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/network/ipv4/ipv4.go:998 +0x15f0
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).HandlePacket(0x40000bb100, 0x4000294000)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/network/ipv4/ipv4.go:784 +0x564
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).DeliverNetworkPacket(0x400024a000, {0x0, 0x0}, {0x0, 0x0}, 0x800, 0x4000294000)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/nic.go:777 +0x340
gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).InjectLinkAddr(...)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/link/channel/channel.go:196
gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).InjectInbound(...)
	gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/link/channel/channel.go:191
tailscale.com/wgengine/netstack.(*Impl).injectInbound(0x4000154460, 0x4000278680, 0x4000204000)
	tailscale.com/wgengine/netstack/netstack.go:577 +0x66c
tailscale.com/net/tstun.(*Wrapper).filterIn(0x4000204000, {0x40006fc010, 0x47, 0xffef})
	tailscale.com/net/tstun/wrap.go:614 +0x718
tailscale.com/net/tstun.(*Wrapper).Write(0x4000204000, {0x40006fc000, 0x57, 0xffff}, 0x10)
	tailscale.com/net/tstun/wrap.go:627 +0xb4
golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialReceiver(0x4000350380)
	golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/receive.go:477 +0x560
created by golang.zx2c4.com/wireguard/device.(*Peer).Start
	golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/peer.go:199 +0x2bc
```

### Steps to reproduce

I can't reproduce it myself, it is just randomly happening.

I'm running `tailscale/tailscale:latest` inside Nomad as follows:

```hcl
job "tailscale" {
  datacenters = ["homelab"]
  type        = "service"
  namespace   = "vpn"

  group "tailscale" {
    count = 1

    network {
      mode = "bridge"
    }

    service {
      name = "tailscale"

      tags = [
        "subnet-router",
        "exit-node"
      ]
    }

    task "agent" {
      driver = "docker"

      config {
        image = "tailscale/tailscale:latest"
        command = "/bin/sh"
        args = [
          "/secrets/start.bash"
        ]
      }

      template {
        data = <<-SCRIPT
          cleanup() {
            echo -n "cleaning up and stopping ... "
            # Our cleanup code goes here
            echo "done"
          }
          trap 'trap " " SIGTERM; kill 0; wait; cleanup' SIGINT SIGTERM
          # Start the tailscaled daemon
          tailscaled --tun userspace-networking &
          # Wait for the daemon to start
          sleep 5
          # Auth and connect to Tailscale
          tailscale up \
                    --auth-key "[[ with secret "tailscale/data/creds" ]][[ .Data.data.auth_key ]][[ end ]]" \
                    --advertise-exit-node \
                    --hostname vpn \
                    --advertise-routes 192.168.1.0/24
          wait
        SCRIPT

        left_delimiter = "[["
        right_delimiter = "]]"
        destination = "secrets/start.bash"
      }

      vault {
        policies = ["tailscale-ro"]
        change_mode = "noop"
      }

      resources {
        cpu    = 256
        memory = 128
      }
    }
  }
}

```

Keep in mind I'm running `tailscaled --tun userspace-networking` so I don't need the container to run in `privileged` mode.

The connection sometimes crash in about 30 min, other times in days.

### Are there any recent changes that introduced the issue?

No

### OS

Linux

### OS version

Ubuntu 20.04.3 LTS arm64

### Tailscale version

latest docker tag

### Bug report

BUG-4fc2c7a24a1a7f0af4441ee8f82bbdfc8539ac16d22d493e91c448913c6a98f1-20220317225838Z-0e99fefc701183cb

**Comment by bradfitz** [comment]
Cc @raggi

**Comment by bradfitz** [comment]
> Tailscale version
> latest docker tag

To save others the lookup cost and for posterity: it's 1.22.1, per logs.

No crash in logs, probably because it's generating a new logid per start, as the nomad config doesn't have persistent state storage per runs.

I'm going to close this one as a dup of the earlier #4144 and summarize this one there.

**Comment by danlsgiga** [comment]
Thanks for pointing that out! I'm in the early stages of learning tailscale and I didn't know it had state. Now that I know, I added persistent storage via CSI now for the tailscale job and so far I'm not seeing any crashes and the job migrating between nodes has its hostname consistent now in the Admin UI (it was creating new machines with incrementing numbers before).
Thanks for looking into this!

**Comment by bradfitz** [comment]
Well, adding state shouldn't fix any crashes. I still expect you'll hit the crash, but then at least we'll be able to find it in logs, as your future "bugreport" post-crash won't be in a different world.
