### ISSUE TITLE
Windows frontend crashing from watchdog after time jump, should suppress watchdog after being suspended

### ISSUE THREAD

**Issue by sphr2k** [tailscale/tailscale#4212]
### What is the issue?

The Windows client exits (crashes) silently approx. once per day. The tunnel is always up and runs in the foreground. This started approx. 4 weeks ago (with the version that was current at the time).

### OS

Windows

### OS version

10 21H2

### Tailscale version

1.22.2

### Bug report

BUG-a2980ce65a8251682a5064ca93b34a8eaa8e866e24920ea3b382bba490b9cd1c-20220318125425Z-e48b4a29d8925ef3

**Comment by bradfitz** [comment]
> The Windows client exits (crashes) silently approx. once per day. The tunnel is always up and runs in the foreground

So you're saying the system tray GUI stops but the service is still running? Is it still running and otherwise working? Do you run in Unattended mode?

/cc @dblohm7

**Comment by bradfitz** [comment]
Probably unrelated, but there's a lot of this in the frontend logs, @dblohm7:

```
2022-03-18 13:50:21.2882401 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-03-18 13:50:21.2885301 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-03-18 13:50:21.2885301 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-03-18 13:50:21.2885301 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-03-18 13:50:21.289026 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-03-18 13:50:21.289026 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-03-18 13:50:21.289026 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-03-18 13:50:21.2895227 +0100 +0100: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
```

**Comment by bradfitz** [comment]
Ah, here we go. Frontend is locking up, which the ticker watchdog detects and crashes with:

```
2022-03-17 01:29:45.7171515 +0100 +0100: ui: stateChanged: NoState -> Starting
2022-03-17 01:29:47.8265194 +0100 +0100: ui: stateChanged: Starting -> Running
2022-03-17 01:29:47.8265194 +0100 +0100: ui: Bytes were transferred: connection established! (prev=Running)
2022-03-17 09:00:51.3107943 +0100 +0100: ui: ticker stalled; goroutines: goroutine 51 [running]:
tailscale.io/win/ui.logTickerTimeout()
        tailscale.io/win/ui/ui.go:1401 +0x45
created by time.goFunc
        time/sleep.go:180 +0x31

goroutine 1 [runnable, locked to thread]:
syscall.Syscall6(0x7ffdf2ad1b10, 0x4, 0x230e1723820, 0x0, 0x0, 0x0, 0x0, 0x0)
        runtime/syscall_windows.go:497 +0xfa
github.com/lxn/win.GetMessage(0x230e1723820, 0x230e1723820, 0x0, 0x0)
        github.com/lxn/win@v0.0.0-20210218163916-a377121e959e/user32.go:2642 +0x7e
github.com/lxn/walk.(*FormBase).mainLoop(0xc00004f400)
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/mainloop_default.go:20 +0x95
github.com/lxn/walk.(*FormBase).Run(0xc00004f400)
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/form.go:375 +0x1af
tailscale.io/win/ui.(*app).Run(0xc00038c240)
        tailscale.io/win/ui/ui.go:1068 +0x105
tailscale.io/win/ui.RunUI({0xc00001cb00, 0x40})
        tailscale.io/win/ui/ui.go:1058 +0x325
tailscale.io/win/ui.Main()
        tailscale.io/win/ui/main.go:84 +0x471
main.main()
        tailscale.io/win/wg64/main.go:13 +0x17

goroutine 17 [runnable, locked to thread]:
runtime.goexit()
        runtime/asm_amd64.s:1581 +0x1

goroutine 6 [select, 451 minutes]:
tailscale.com/logtail.(*Logger).drainBlock(0xc0000db000)
        tailscale.com@v1.22.1/logtail/logtail.go:201 +0xd9
tailscale.com/logtail.(*Logger).drainPending(0xc0000c62c0, {0xc00018a000, 0xc00002e5c0, 0x0})
        tailscale.com@v1.22.1/logtail/logtail.go:238 +0x158
tailscale.com/logtail.(*Logger).uploading(0xc0000c62c0, {0x10795d8, 0xc00002e5c0})
        tailscale.com@v1.22.1/logtail/logtail.go:281 +0xcf
created by tailscale.com/logtail.NewLogger
        tailscale.com@v1.22.1/logtail/logtail.go:111 +0x596

goroutine 8 [select, 451 minutes]:
github.com/lxn/walk.startLayoutPerformer.func1()
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/layout.go:118 +0x1be
created by github.com/lxn/walk.startLayoutPerformer
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/layout.go:111 +0x24f

goroutine 24 [IO wait]:
internal/poll.runtime_pollWait(0x230e93f78d0, 0x72)
        runtime/netpoll.go:234 +0x89
internal/poll.(*pollDesc).wait(0x0, 0x0, 0x0)
        internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.execIO(0xc000148398, 0xfecf78)
        internal/poll/fd_windows.go:177 +0xe5
internal/poll.(*FD).Read(0xc000148380, {0xc00048fdc4, 0x4, 0x4})
        internal/poll/fd_windows.go:443 +0x25f
net.(*netFD).Read(0xc000148380, {0xc00048fdc4, 0x0, 0x0})
        net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc00012a028, {0xc00048fdc4, 0x230e1b10a28, 0x0})
        net/net.go:183 +0x45
io.ReadAtLeast({0x230e71858b8, 0xc00012a028}, {0xc00048fdc4, 0x4, 0x4}, 0x4)
        io/io.go:328 +0x9a
io.ReadFull(...)
        io/io.go:347
tailscale.com/ipn.ReadMsg({0x230e71858b8, 0xc00012a028})
        tailscale.com@v1.22.1/ipn/message.go:327 +0x65
tailscale.io/win/ui.pump({0x1079610, 0xc000018098}, 0xc000065e38, {0x1080918, 0xc00012a028}, 0xfed8c0)
        tailscale.io/win/ui/ui.go:57 +0x15d
tailscale.io/win/ui.(*app).connectAndPump(0xc00038c240)
        tailscale.io/win/ui/ui.go:948 +0x951
created by tailscale.io/win/ui.(*app).Run
        tailscale.io/win/ui/ui.go:1064 +0xa5

goroutine 25 [runnable]:
tailscale.io/win/ui.(*app).runTicker(0xc00038c240)
        tailscale.io/win/ui/ui.go:1298 +0xdc
created by tailscale.io/win/ui.(*app).Run
```

**Comment by bradfitz** [comment]
Oh, this might be a time jump from resuming a machine from sleep or something.

I forget whether we were using the right time of timer (one that counts suspended time or not). But really we should just check for that on the watchdog timeout and not crash if we just came out of sleep and instead give the ticker another chance.

**Comment by sphr2k** [comment]
> > The Windows client exits (crashes) silently approx. once per day. The tunnel is always up and runs in the foreground
> 
> So you're saying the system tray GUI stops but the service is still running? Is it still running and otherwise working? Do you run in Unattended mode?
> 
> /cc @dblohm7 

Sorry for the unclear wording. Not using unattended mode. The client crashes, after which the tunnel is down.
