### ISSUE TITLE
Random crashes on gvisor.dev/gvisor/pkg/tcpip running version 1.22.2 (OPNSense)

### ISSUE THREAD

**Issue by jorgejams88** [tailscale/tailscale#4308]
### What is the issue?

Works normally and it suddenly crashes on FreeBSD

### Steps to reproduce

Run tailscaled daemon for some time, and it eventually crashes, the only way to recover is to run tailscaled --cleanup, but it eventually crashes again with this stack trace:

panic: Incrementing non-positive count 0xc0006ffc00 on stack.PacketBuffer

```
goroutine 164 [running]:
gvisor.dev/gvisor/pkg/tcpip/stack.(*packetBufferRefs).IncRef(0xc0006ffc00)
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/packet_buffer_refs.go:80 +0x16a
gvisor.dev/gvisor/pkg/tcpip/transport/udp.(*endpoint).HandlePacket(0xc0002c6600, {0x76db, {0xc00017d270, 0x4}, 0x575e, {0xc00017d26c, 0x4}}, 0xc0006ffc00)
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/transport/udp/endpoint.go:924 +0x305
gvisor.dev/gvisor/pkg/tcpip/stack.(*endpointsByNIC).handlePacket(0xc000708a80, {0x76db, {0xc00017d270, 0x4}, 0x575e, {0xc00017d26c, 0x4}}, 0xc0006ffc00)
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/transport_demuxer.go:185 +0x2c9
gvisor.dev/gvisor/pkg/tcpip/stack.(*transportDemuxer).deliverPacket(0xc00000e258, 0x11, 0xc0006ffc00, {0x76db, {0xc00017d270, 0x4}, 0x575e, {0xc00017d26c, 0x4}})
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/transport_demuxer.go:595 +0x3ac
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).DeliverTransportPacket(0xc00000c1e0, 0x11, 0xc0006ffc00)
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/nic.go:861 +0x29d
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).handleValidatedPacket(0xc000127800, {0xc0000cc210, 0x14, 0xb0}, 0xc0004f2000, {0x0, 0x0})
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/network/ipv4/ipv4.go:998 +0x1233
gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).HandlePacket(0xc000127800, 0xc0004f2000)
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/network/ipv4/ipv4.go:784 +0x39b
gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).DeliverNetworkPacket(0xc00000c1e0, {0x0, 0x0}, {0x0, 0x0}, 0x800, 0xc0004f2000)        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/nic.go:777 +0x349
gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).InjectLinkAddr(...)
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/link/channel/channel.go:196
gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).InjectInbound(...)
        gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/link/channel/channel.go:191
tailscale.com/wgengine/netstack.(*Impl).injectInbound(0xc0001b45a0, 0xc000148280, 0xc00045c000)
        tailscale.com/wgengine/netstack/netstack.go:577 +0x765
tailscale.com/net/tstun.(*Wrapper).filterIn(0xc00045c000, {0xc00077c010, 0xae, 0xffef})
        tailscale.com/net/tstun/wrap.go:614 +0x893
tailscale.com/net/tstun.(*Wrapper).Write(0xc00045c000, {0xc00077c000, 0xbe, 0xffff}, 0x10)
        tailscale.com/net/tstun/wrap.go:627 +0x90
golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialReceiver(0xc0000a9c00)
        golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/receive.go:477 +0x5b7
created by golang.zx2c4.com/wireguard/device.(*Peer).Start
        golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/peer.go:199 +0x2d1
```

### Are there any recent changes that introduced the issue?

Installed version 1.22.2

### OS

Other

### OS version

OPNsense 22.1.3-amd64

### Tailscale version

 1.22.2

### Bug report

BUG-a434803a4963f3ca28bcfb0ad7076259d0fb29b37a5bde27f90a606c83af23c2-20220328194446Z-0b3702b69cf514ff

**Comment by bradfitz** [comment]
Dup of #4144.

cc @raggi
