### ISSUE TITLE
panic when starting the relay node

### ISSUE THREAD

**Issue by HeavyHorst** [tailscale/tailscale#45]
I compiled the relaynode from source and when i try to start it i get a panic:

```
sudo /usr/sbin/relaynode --config=/var/lib/tailscale/relay.conf --tun=wg0 --port=41641 --acl-file=/etc/tailscale/acl.json                                                                                                                                                          :(
logtail started
Program starting: vLONGVER-TODO: []string{"/usr/sbin/relaynode", "--config=/var/lib/tailscale/relay.conf", "--tun=wg0", "--port=41641", "--acl-file=/etc/tailscale/acl.json"}
LogID: 560f0c00b49bd7c56b4018db6d3cb0d1760aaf3f0de6e3a3adede46b3701f4a3
7.0M/9.9M Starting userspace wireguard engine.
15.1M/10.2M external packet routing via --tun=wg0 enabled
15.5M/11.7M CreateTUN ok.
15.6M/11.9M Routine: event worker - started
15.6M/11.9M Interface set up
15.7M/11.9M UDP bind has been updated
15.8M/11.9M external route MTU: 1420 (<nil>)
15.8M/11.9M external route MTU: 1420 (<nil>)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x68 pc=0x89581f]

goroutine 1 [running]:
tailscale.com/wgengine.(*linuxRouter).SetRoutes(0xc0007c03c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/rkaufmann/go/src/tailscale.com/wgengine/router_linux.go:114 +0x9f
tailscale.com/wgengine.NewUserspaceEngineAdvanced(0xc00018e040, 0xa6f640, 0xc0007a2120, 0x9cc650, 0xa2a9, 0x0, 0x0, 0x10, 0x92d460)
        /home/rkaufmann/go/src/tailscale.com/wgengine/userspace.go:186 +0x68e
tailscale.com/wgengine.NewUserspaceEngine(0xc00018e040, 0x7ffdd13f075e, 0x3, 0xa2a9, 0xc000182180, 0x0, 0xc00021fcb0, 0x1)
        /home/rkaufmann/go/src/tailscale.com/wgengine/userspace.go:75 +0x288
main.main()
        /home/rkaufmann/go/src/tailscale.com/cmd/relaynode/relaynode.go:80 +0x1897
```

**Comment by bradfitz** [comment]
My fault probably. Will look. Thanks.
