### ISSUE TITLE
Tray and service can't connect, TUN "Error creating interface"

### ISSUE THREAD

**Issue by sgraham** [tailscale/tailscale#4678]
### What is the issue?

![image](https://user-images.githubusercontent.com/1822/168458096-fb6d637c-67a4-423a-aaf3-f3bdfc6eab01.png)

The tray app says the service isn't running, but it is.

I got this message after about a minute:

---------------------------
Tailscale Error
---------------------------
Tailscale backend error:

TUN: Error creating interface: The system cannot find the file specified.

logid: b586cb15dd958aa6d44d2f6ec6f797282946650d3700bbe74fcb70d1eac74b29
---------------------------
OK   
---------------------------

### Steps to reproduce

Unfortunately, I don't know yet. I don't see anything in Event Viewer.

### Are there any recent changes that introduced the issue?

I recently upgraded from 1.16.x to 1.24.2. I also hadn't rebooted in a while and just had to so could be either of those.

### OS

Windows

### OS version

10

### Tailscale version

1.24.2 (t9d6867fb0-g2d0f7ddc3)

### Bug report

BUG-b586cb15dd958aa6d44d2f6ec6f797282946650d3700bbe74fcb70d1eac74b29-20220515050744Z-fc59c7654c1afed3

**Comment by sgraham** [comment]
Hrm, I didn't file this until after about 4-5 app and service restarts.

But now after nuking most of %LOCALAPPDATA%\Tailscale (to try to get some better logs) and restarting it came back up fine.

So I don't know if that was relevant or incidental now.

**Comment by DentonGentry** [comment]
Around the time of the bugreport, the frontend was reporting:
```
2022-05-14 22:11:06.6752202 -0700 PDT: ui: stateChanged: NoState -> Starting
2022-05-14 22:11:07.0125686 -0700 PDT: ui: stateChanged: Starting -> Running
2022-05-14 22:11:07.0130934 -0700 PDT: ui: Bytes were transferred: connection established! (prev=Running)
2022-05-14 22:48:05.2242292 -0700 PDT: ui: ticker stalled; goroutines: goroutine 49 [running]:
tailscale.io/win/ui.logTickerTimeout()
        tailscale.io/win/ui/ui.go:1415 +0x45
created by time.goFunc
        time/sleep.go:176 +0x32

goroutine 1 [syscall, locked to thread]:
syscall.SyscallN(0x0?, {0xc00058fc20?, 0x0?, 0xc000088000?})
        runtime/syscall_windows.go:538 +0x109
syscall.Syscall6(0x0?, 0xe73620?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
        runtime/syscall_windows.go:482 +0x50
github.com/lxn/win.GetMessage(0xc00037e000?, 0xb40?, 0x0, 0x0)
        github.com/lxn/win@v0.0.0-20210218163916-a377121e959e/user32.go:2642 +0x7c
github.com/lxn/walk.(*FormBase).mainLoop(0xc000358000)
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/mainloop_default.go:20 +0x95
github.com/lxn/walk.(*FormBase).Run(0xc000358000)
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/form.go:375 +0x1af
tailscale.io/win/ui.(*app).Run(0xc0003c25a0)
        tailscale.io/win/ui/ui.go:1082 +0xf5
tailscale.io/win/ui.RunUI({0xc000350040, 0x40})
        tailscale.io/win/ui/ui.go:1072 +0x325
tailscale.io/win/ui.Main()
        tailscale.io/win/ui/main.go:84 +0x471
main.main()
        tailscale.io/win/wg64/main.go:13 +0x17

goroutine 19 [select, 37 minutes]:
tailscale.com/logtail.(*Logger).drainBlock(0xc000170000?)
        tailscale.com@v1.24.2/logtail/logtail.go:209 +0xcd
tailscale.com/logtail.(*Logger).drainPending(0xc000095d40, {0xc000180000?, 0xc0000f8580?, 0x0?})
        tailscale.com@v1.24.2/logtail/logtail.go:246 +0x156
tailscale.com/logtail.(*Logger).uploading(0xc000095d40, {0xfd35f0, 0xc0000f8580})
        tailscale.com@v1.24.2/logtail/logtail.go:289 +0xcf
created by tailscale.com/logtail.NewLogger
        tailscale.com@v1.24.2/logtail/logtail.go:113 +0x5be

goroutine 10 [IO wait]:
internal/poll.runtime_pollWait(0x18e2a9c26d0, 0x72)
        runtime/netpoll.go:302 +0x89
internal/poll.(*pollDesc).wait(0x0?, 0xc0001eba80?, 0x0)
        internal/poll/fd_poll_runtime.go:83 +0x32
internal/poll.execIO(0xc000412298, 0xf44838)
        internal/poll/fd_windows.go:175 +0xe5
internal/poll.(*FD).Read(0xc000412280, {0xc0003460cc, 0x4, 0x4})
        internal/poll/fd_windows.go:441 +0x25f
net.(*netFD).Read(0xc000412280, {0xc0003460cc?, 0x1000000000000?, 0x0?})
        net/fd_posix.go:55 +0x29
net.(*conn).Read(0xc000410010, {0xc0003460cc?, 0xc0001ebbb0?, 0xa3a192?})
        net/net.go:183 +0x45
io.ReadAtLeast({0x18e2c7a0008, 0xc000410010}, {0xc0003460cc, 0x4, 0x4}, 0x4)
        io/io.go:331 +0x9a
io.ReadFull(...)
        io/io.go:350
tailscale.com/ipn.ReadMsg({0x18e2c7a0008, 0xc000410010})
        tailscale.com@v1.24.2/ipn/message.go:327 +0x65
tailscale.io/win/ui.pump({0xfd3628, 0xc0000b2058}, 0xc0001ebe38, {0xfd4aa0?, 0xc000410010}, 0xf45150)
        tailscale.io/win/ui/ui.go:57 +0x127
tailscale.io/win/ui.(*app).connectAndPump(0xc0003c25a0)
        tailscale.io/win/ui/ui.go:962 +0x965
created by tailscale.io/win/ui.(*app).Run
        tailscale.io/win/ui/ui.go:1078 +0x97

goroutine 34 [select, 37 minutes]:
github.com/lxn/walk.startLayoutPerformer.func1()
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/layout.go:118 +0x1be
created by github.com/lxn/walk.startLayoutPerformer
        github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/layout.go:111 +0x24a

goroutine 11 [chan receive (nil chan)]:
tailscale.io/win/ui.(*app).runTicker.func1()
        tailscale.io/win/ui/ui.go:1306 +0x45
tailscale.io/win/ui.(*app).runTicker(0xc0003c25a0)
        tailscale.io/win/ui/ui.go:1314 +0xf6
created by tailscale.io/win/ui.(*app).Run
        tailscale.io/win/ui/ui.go:1079 +0xd6
2022-05-14 22:48:05.4170106 -0700 PDT: logtail: CONNECT response error from tailscaled: 502 Fail
```

The backend Service was reporting:
```
2022-05-14 22:01:12.0877485 -0700 PDT: tailscaled: getting engine... (try 3)
2022-05-14 22:01:12.1365758 -0700 PDT: Using existing driver 0.14
2022-05-14 22:01:12.1412827 -0700 PDT: Creating adapter
2022-05-14 22:01:27.1557825 -0700 PDT: Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
2022-05-14 22:01:27.1557825 -0700 PDT: Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC00002F0): The system cannot find the file specified. (Code 0x00000002)
2022-05-14 22:01:27.1648489 -0700 PDT: tailscaled: engine fetch error (try 3) in 15.077s (total 15.077s, sysUptime 10h58m47s): TUN: Error creating interface: The system cannot find the file specified.
2022-05-14 22:01:32.1722139 -0700 PDT: tailscaled: getting engine... (try 4)
2022-05-14 22:01:32.2201216 -0700 PDT: Using existing driver 0.14
2022-05-14 22:01:32.2238181 -0700 PDT: Creating adapter
2022-05-14 22:01:47.237626 -0700 PDT: Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
2022-05-14 22:01:47.237626 -0700 PDT: Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC00002F0): The system cannot find the file specified. (Code 0x00000002)
2022-05-14 22:01:47.2467259 -0700 PDT: tailscaled: engine fetch error (try 4) in 15.075s (total 15.075s, sysUptime 10h59m7s): TUN: Error creating interface: The system cannot find the file specified.
2022-05-14 22:01:47.2467259 -0700 PDT: ipnserver: initial getEngine call: TUN: Error creating interface: The system cannot find the file specified.
2022-05-14 22:01:47.2467259 -0700 PDT: logid: b586cb15dd958aa6d44d2f6ec6f797282946650d3700bbe74fcb70d1eac74b29
2022-05-14 22:01:47.2467259 -0700 PDT: ipnserver: try1: trying getEngine again...
2022-05-14 22:01:52.2600952 -0700 PDT: tailscaled: getting engine... (try 5)
2022-05-14 22:01:52.3099669 -0700 PDT: Using existing driver 0.14
2022-05-14 22:01:52.3146934 -0700 PDT: Creating adapter
2022-05-14 22:02:07.3239546 -0700 PDT: Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
2022-05-14 22:02:07.3239546 -0700 PDT: Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC00002F0): The system cannot find the file specified. (Code 0x00000002)
2022-05-14 22:02:07.3330455 -0700 PDT: tailscaled: engine fetch error (try 5) in 15.073s (total 15.073s, sysUptime 10h59m27s): TUN: Error creating interface: The system cannot find the file specified.
2022-05-14 22:02:07.3330455 -0700 PDT: ipnserver1: getEngine failed again: TUN: Error creating interface: The system cannot find the file specified.
2022-05-14 22:02:07.3330455 -0700 PDT: logid:b586cb15dd958aa6d44d2f6ec6f797282946650d3700bbe74fcb70d1eac74b29
2022-05-14 22:02:12.3398388 -0700 PDT: tailscaled: getting engine... (try 6)
2022-05-14 22:02:12.387095 -0700 PDT: Using existing driver 0.14
2022-05-14 22:02:12.3907626 -0700 PDT: Creating adapter
2022-05-14 22:02:27.4050414 -0700 PDT: Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
2022-05-14 22:02:27.4050414 -0700 PDT: Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC00002F0): The system cannot find the file specified. (Code 0x00000002)
2022-05-14 22:02:27.4147204 -0700 PDT: tailscaled: engine fetch error (try 6) in 15.075s (total 15.075s, sysUptime 10h59m47s): TUN: Error creating interface: The system cannot find the file specified.
```

**Comment by DentonGentry** [comment]
On a system without this issue, the very first attempt to bring up wintun does not log `Using existing driver 0.14`. It installs the driver afresh.

```
2022-08-27 18:05:31.292461 -0700 PDT: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-08-27 18:05:31.3237172 -0700 PDT: registry.OpenKey(SOFTWARE\Policies\Tailscale): The system cannot find the file specified.
2022-08-27 18:05:31.3237172 -0700 PDT: exec: "C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe" [/subproc 34b754ceeb57c111ba374abb977efd4cd84ef18d4fbf016d0d07f23fa553931c]
2022-08-27 18:05:32.1204786 -0700 PDT: Program starting: v1.29.193-tf1c981218-g8e67294b6: []string{"C:\\Program Files (x86)\\Tailscale IPN\\tailscaled.exe", "/subproc", "34b754ceeb57c111ba374abb977efd4cd84ef18d4fbf016d0d07f23fa553931c"}
2022-08-27 18:05:32.121054 -0700 PDT: subproc mode: logid=34b754ceeb57c111ba374abb977efd4cd84ef18d4fbf016d0d07f23fa553931c
2022-08-27 18:05:32.2242324 -0700 PDT: tailscaled: getting engine... (try 1)
2022-08-27 18:05:32.296445 -0700 PDT: Listening on 127.0.0.1:41112
2022-08-27 18:05:32.5206695 -0700 PDT: Installing driver 0.14
2022-08-27 18:05:32.5224755 -0700 PDT: Extracting driver
2022-08-27 18:05:32.5271215 -0700 PDT: Installing driver
2022-08-27 18:05:33.7824795 -0700 PDT: Creating adapter
2022-08-27 18:05:34.6045131 -0700 PDT: waitInterfaceUp: TUN interface already up; no need to wait
```

There may be a nonfunctional wintun driver installation wedged and not letting itself be removed. You may be able to forcible remove it: https://github.com/tailscale/tailscale/issues/1290#issuecomment-921306345

**Comment by bradfitz** [comment]
I get this 15 second hang + failure too when working on Tailscale for Windows. e.g.

```
Y:\>tswin.exe -gui=false
2022/11/06 19:57:02 Tailscale service running: false
2022/11/06 19:57:02 tswin: no old processes running
2022/11/06 19:57:06 You have disabled logging. Tailscale will not be able to provide support.
logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.33.41-t37da61738-g6246d9ff2, Go 1.19.2-ts3fd24de: []string{"c:\\tsdev\\tailscaled.exe"}
cleaning log files; number of files 51 > 50
cleaned log file C:\ProgramData\Tailscale\Logs\tailscale-service-20220925T071625-1664115385.txt (size 7316); new bytes=469556, files=50
LogID: 8a7972f40870ce1f761e7d572c7afeaf4fe94b91e13411c5ddad754eb8e7dfc2
logpolicy: using dir C:\ProgramData\Tailscale
wgengine.NewUserspaceEngine(tun "Tailscale") ...
Using existing driver 0.14
Creating adapter
Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): Cannot create a file when that file already exists. (Code 0x000000B7)
no TUN failure diagnostics for OS "windows"
wgengine.NewUserspaceEngine(tun "Tailscale") error: tstun.New("Tailscale"): Error creating interface: Cannot create a file when that file already exists.
flushing log.
logger closing down
createEngine: tstun.New("Tailscale"): Error creating interface: Cannot create a file when that file already exists.
2022/11/06 19:57:21 backend stopped with error: exit status 1
2022/11/06 19:57:21 tswin ending.
2022/11/06 19:57:21 Tailscale service running: false
2022/11/06 19:57:21 tswin: no old processes running
2022/11/06 19:57:21 tswin done.
```

**Comment by bradfitz** [comment]
This seems super reproducible. It looks like it happens every other time I run it...

```
X:\>tswin -gui=false
2022/11/06 20:12:46 Tailscale service running: false
2022/11/06 20:12:46 tswin: no old processes running
2022/11/06 20:12:50 You have disabled logging. Tailscale will not be able to provide support.
logtail started
local disk logdir: C:\ProgramData\Tailscale\Logs
Program starting: v1.33.145-t036334e91-g8bfe3019f, Go 1.19.2-ts3fd24de: []string{"c:\\tsdev\\tailscaled.exe"}
cleaning log files; number of files 51 > 50
cleaned log file C:\ProgramData\Tailscale\Logs\tailscale-service-20220930T062831-1664544511.txt (size 7311); new bytes=445640, files=50
LogID: 8a7972f40870ce1f761e7d572c7afeaf4fe94b91e13411c5ddad754eb8e7dfc2
logpolicy: using dir C:\ProgramData\Tailscale
wgengine.NewUserspaceEngine(tun "Tailscale") ...
Using existing driver 0.14
Creating adapter
Timed out waiting for device query: The wait operation timed out. (Code 0x00000102)
Failed to setup adapter (problem code: 0x1F, ntstatus: 0xC0000035): Cannot create a file when that file already exists. (Code 0x000000B7)
no TUN failure diagnostics for OS "windows"
wgengine.NewUserspaceEngine(tun "Tailscale") error: tstun.New("Tailscale"): Error creating interface: Cannot create a file when that file already exists.
flushing log.
logger closing down
createEngine: tstun.New("Tailscale"): Error creating interface: Cannot create a file when that file already exists.
2022/11/06 20:13:06 backend stopped with error: exit status 1
2022/11/06 20:13:06 tswin ending.
2022/11/06 20:13:07 Tailscale service running: false
2022/11/06 20:13:07 tswin: no old processes running
2022/11/06 20:13:07 tswin done.
```

**Comment by bradfitz** [comment]
Also seen:

```
Creating WireGuard device...
Bringing WireGuard device up...
Bringing router up...
router: firewall: marking for removal
router: firewall: starting netsh goroutine
router: firewall: clearing Tailscale-In firewall rules...
wgengine.NewUserspaceEngine(tun "Tailscale") error: router.Up: monitorDefaultRoutes, after 115ms: getting v4 interface: The parameter is incorrect.
flushing log.
logger closing down
createEngine: router.Up: monitorDefaultRoutes, after 115ms: getting v4 interface: The parameter is incorrect.
```

**Comment by dblohm7** [comment]
This one differs from the other diagnostics I was adding, where the adapter could not be created in the first place. This "device already exists" stuff is not really supposed to happen, which makes me think we might be hitting a bug in `wintun.dll`. I'll take a closer look.

**Comment by bradfitz** [comment]
@dblohm7, I can still reproduce this on demand. It still happens every other start for me so let me know if you want to pair on debugging it.

**Comment by dblohm7** [comment]
@bradfitz I've thrown together a win-franken-tun at https://github.com/dblohm7/wintun/releases/tag/v0.14-dblohm7_1 which contains a potential bug fix in the DLL, but embeds the signed drivers from 0.14.1. It's amd64-only. If you're still able to repro this on demand, I'd love to hear how things work when you drop this DLL into your installation.

**Comment by bradfitz** [comment]
(replied on Slack. Summary: I didn't observe any change. But maybe I had the wrong DLL? @dblohm7 was going to change the error strings to make it clear whether I was running the right DLL)

**Comment by lezzi** [comment]
@bradfitz I was wondering if you were able to fix this in the end?
