### ISSUE TITLE
ipn/ipnlocal: panic: Log in goroutine after TestStateMachine has completed

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#4774]
```
panic: Log in goroutine after TestStateMachine has completed: 
(ignored) Notify{wg={0 0 0 0 map[]}}



goroutine 188 [running]:
testing.(*common).logDepth(0xc000412000, {0xc00003f5f0, 0x27}, 0x3)
	/opt/hostedtoolcache/go/1.18.2/x64/src/testing/testing.go:887 +0x4c7
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.18.2/x64/src/testing/testing.go:869
testing.(*common).Logf(0xc000412000, {0xc[96](https://github.com/tailscale/tailscale/runs/6711128177?check_suite_focus=true#step:6:97)809?, 0xc0000fe180?}, {0xc00029eaf0?, 0xc0000fe180?, 0xc00006bcf0?})
	/opt/hostedtoolcache/go/1.18.2/x64/src/testing/testing.go:920 +0x5a
tailscale.com/ipn/ipnlocal.TestStateMachine.func3({{}, {0xc0001302b0, 0xc}, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001cb770, 0x0, ...})
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/state_test.go:340 +0x239
tailscale.com/ipn/ipnlocal.(*LocalBackend).send(0x0?, {{}, {0xc0001302b0, 0xc}, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0001cb770, ...})
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/local.go:1405 +0x135
tailscale.com/ipn/ipnlocal.(*LocalBackend).setWgengineStatus(0xc0000fc840, 0xc0002ded20, {0x0?, 0x0?})
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/local.go:787 +0x5cd
tailscale.com/wgengine.(*userspaceEngine).RequestStatus(0xc0001eec80)
	/home/runner/work/tailscale/tailscale/wgengine/userspace.go:[113](https://github.com/tailscale/tailscale/runs/6711128177?check_suite_focus=true#step:6:114)9 +0x92
created by tailscale.com/ipn/ipnlocal.(*LocalBackend).requestEngineStatusAndWait
	/home/runner/work/tailscale/tailscale/ipn/ipnlocal/local.go:2832 +0xca
exit status 2
FAIL	tailscale.com/ipn/ipnlocal	0.965s
PASS
```

**Comment by DentonGentry** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/6173
