### ISSUE TITLE
magicsock/test test flake panic: send on closed channel

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#487]
On Mac builder:

```
panic: send on closed channel

goroutine 78 [running]:
github.com/tailscale/wireguard-go/device.(*Peer).SendKeepalive(0xc0004fc000, 0x0)
	/Users/runner/runners/2.263.0/work/corp/corp/wireguard-go/device/send.go:117 +0xb6
github.com/tailscale/wireguard-go/device.(*Device).RoutineHandshake(0xc0000f0840)
	/Users/runner/runners/2.263.0/work/corp/corp/wireguard-go/device/receive.go:500 +0x91b
created by github.com/tailscale/wireguard-go/device.NewDevice
	/Users/runner/runners/2.263.0/work/corp/corp/wireguard-go/device/device.go:385 +0x45b
FAIL	tailscale.com/wgengine/magicsock	0.168s
FAIL
redo      oss/wgengine/packet/test
```

/cc @dshynkev @danderson

**Comment by dshynkev** [comment]
The fix was merged in our fork and updated in corp, so let's say this is resolved.
