### ISSUE TITLE
Tailscale SSH won't work

### ISSUE THREAD

**Issue by nhocki** [tailscale/tailscale#4906]
### What is the issue?

Trying to ssh into my rasperry pi (after starting tailscale with `--ssh`) and now I cannot get in:

```
$ ssh <user>@pi
panic: unaligned 64-bit atomic operation
preempt off reason: doAllThreadsSyscall
fatal error: panic during preemptoff

goroutine 1 [running]:
runtime.throw({0x8c84aa, 0x17})
	runtime/panic.go:992 +0x5c fp=0x1507d5c sp=0x1507d48 pc=0x4bb44
panic({0x7db110, 0x9ee180})
	runtime/panic.go:780 +0x710 fp=0x1507dbc sp=0x1507d5c pc=0x4b98c
runtime/internal/atomic.panicUnaligned()
	runtime/internal/atomic/unaligned.go:8 +0x24 fp=0x1507dc8 sp=0x1507dbc pc=0x11f74
runtime/internal/atomic.Load64(0x1480024)
	runtime/internal/atomic/atomic_arm.s:280 +0x14 fp=0x1507dcc sp=0x1507dc8 pc=0x12340
syscall.runtime_doAllThreadsSyscall(0xce, 0x11, 0x162e050, 0x0, 0x0, 0x0, 0x0)
	runtime/os_linux.go:816 +0x360 fp=0x1507e3c sp=0x1507dcc pc=0x80ea8
syscall.AllThreadsSyscall(0xce, 0x11, 0x162e050, 0x0)
	syscall/syscall_linux.go:987 +0x6c fp=0x1507e68 sp=0x1507e3c pc=0x95448
syscall.Setgroups({0x163a000, 0x11, 0x20})
	syscall/syscall_linux.go:307 +0x2cc fp=0x1507e90 sp=0x1507e68 pc=0x94588
tailscale.com/ssh/tailssh.beIncubator({0x1424478, 0xb, 0xb})
	tailscale.com@v1.24.2/ssh/tailssh/incubator.go:189 +0x5fc fp=0x1507f34 sp=0x1507e90 pc=0x602d74
main.beChild({0x1424470, 0xc, 0xc})
	tailscale.com@v1.24.2/cmd/tailscaled/tailscaled.go:631 +0x9c fp=0x1507f64 sp=0x1507f34 pc=0x761908
main.main()
	tailscale.com@v1.24.2/cmd/tailscaled/tailscaled.go:153 +0x69c fp=0x1507fc0 sp=0x1507f64 pc=0x75dc50
runtime.main()
	runtime/proc.go:250 +0x26c fp=0x1507fec sp=0x1507fc0 pc=0x4ed6c
runtime.goexit()
	runtime/asm_arm.s:824 +0x4 fp=0x1507fec sp=0x1507fec pc=0x84f08

goroutine 6 [chan receive]:
github.com/godbus/dbus/v5.newConn.func1()
	github.com/godbus/dbus/v5@v5.0.6/conn.go:288 +0x40
created by github.com/godbus/dbus/v5.newConn
	github.com/godbus/dbus/v5@v5.0.6/conn.go:287 +0x198

goroutine 17 [IO wait]:
internal/poll.runtime_pollWait(0xa6c26fbc, 0x72)
	runtime/netpoll.go:302 +0x54
internal/poll.(*pollDesc).wait(0x14764c4, 0x72, 0x0)
	internal/poll/fd_poll_runtime.go:83 +0x30
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:88
internal/poll.(*FD).ReadMsg(0x14764b0, {0x160a6f0, 0x10, 0x10}, {0x1569310, 0x1000, 0x1000}, 0x40000000)
	internal/poll/fd_unix.go:304 +0x278
net.(*netFD).readMsg(0x14764b0, {0x160a6f0, 0x10, 0x10}, {0x1569310, 0x1000, 0x1000}, 0x40000000)
	net/fd_posix.go:78 +0x58
net.(*UnixConn).readMsg(0x140f530, {0x160a6f0, 0x10, 0x10}, {0x1569310, 0x1000, 0x1000})
	net/unixsock_posix.go:115 +0x58
net.(*UnixConn).ReadMsgUnix(0x140f530, {0x160a6f0, 0x10, 0x10}, {0x1569310, 0x1000, 0x1000})
	net/unixsock.go:143 +0x58
github.com/godbus/dbus/v5.(*oobReader).Read(0x1569300, {0x160a6f0, 0x10, 0x10})
	github.com/godbus/dbus/v5@v5.0.6/transport_unix.go:21 +0x50
io.ReadAtLeast({0x9ef084, 0x1569300}, {0x160a6f0, 0x10, 0x10}, 0x10)
	io/io.go:331 +0x90
io.ReadFull(...)
	io/io.go:350
github.com/godbus/dbus/v5.(*unixTransport).ReadMessage(0x140cd10)
	github.com/godbus/dbus/v5@v5.0.6/transport_unix.go:91 +0x128
github.com/godbus/dbus/v5.(*Conn).inWorker(0x1516600)
	github.com/godbus/dbus/v5@v5.0.6/conn.go:389 +0x48
created by github.com/godbus/dbus/v5.(*Conn).Auth
	github.com/godbus/dbus/v5@v5.0.6/auth.go:118 +0x94c
Connection to pi closed.
```

### Steps to reproduce

Enabled ssh in my Rasperry Pi and tried to SSH into it. Logged in with Tailscale and now it panics every time.

### Are there any recent changes that introduced the issue?

Launched Tailscale SSH: https://tailscale.com/blog/tailscale-ssh/

### OS

Linux, macOS

**Comment by maisem** [comment]
This was a problem in 1.24 I think and has been fixed. Which version are you on?

**Comment by nhocki** [comment]
@DentonGentry I _think_ it is because it's on Raspberry Pi OS and that is only 32bit. But I cannot run any command because I can no longer SSH into it. I'm not at home but will be able to debug further next week 🤷‍♂️ .

**Comment by bradfitz** [comment]
Yes, that was fixed upstream in Go, in Go 1.18.2: https://github.com/golang/go/issues/52305

**Comment by bradfitz** [comment]
@nhocki, update to the latest Tailscale 1.26.1 and it should work for you.

**Comment by bradfitz** [comment]
@nhocki, update to the latest Tailscale 1.26.1 and it should work for you.
