### ISSUE TITLE
Tailscaled crash at HEAD

### ISSUE THREAD

**Issue by danderson** [tailscale/tailscale#515]
```
Jun 30 22:35:54 vega tailscaled[14137]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x86ea1c]
Jun 30 22:35:54 vega tailscaled[14137]: goroutine 223 [running]:
Jun 30 22:35:54 vega tailscaled[14137]: github.com/tailscale/wireguard-go/device.(*Peer).SetEndpointAddress(0xc0006a3c00, 0x0)
Jun 30 22:35:54 vega tailscaled[14137]:         github.com/tailscale/wireguard-go@v0.0.0/device/peer.go:328 +0x5c
Jun 30 22:35:54 vega tailscaled[14137]: github.com/tailscale/wireguard-go/device.(*Peer).RoutineSequentialReceiver(0xc0006a3c00)
Jun 30 22:35:54 vega tailscaled[14137]:         github.com/tailscale/wireguard-go@v0.0.0/device/receive.go:561 +0x270
Jun 30 22:35:54 vega tailscaled[14137]: created by github.com/tailscale/wireguard-go/device.(*Peer).Start
Jun 30 22:35:54 vega tailscaled[14137]:         github.com/tailscale/wireguard-go@v0.0.0/device/peer.go:240 +0x329
```

cc @bradfitz guessing related to new discovery endpoints?

**Comment by bradfitz** [comment]
discovery stuff should all be off by default. Probably some related netaddr changes? Will look tomorrow. Not sure how I didn't hit it myself though.

**Comment by bradfitz** [comment]
I can reproduce. Seems to start at e96f22e56007025dbce35015d481853f71bbc062
