### ISSUE TITLE
tailscaled 0.100.0 crashes on "tailscale up"

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#525]
I'd added an invariant check in magicsock that you can't change the disco key once it's already set:

```go
// SetDiscoPrivateKey sets the discovery key.                                                                                                                                                                  
func (c *Conn) SetDiscoPrivateKey(k key.Private) {
        c.mu.Lock()
        defer c.mu.Unlock()
        if !c.discoPrivate.IsZero() && c.discoPrivate != k {
                // TODO: support changing a key at runtime; need to                                                                                                                                            
                // clear a bunch of maps at least                                                                                                                                                              
                panic("unsupported")
        }
        c.discoPrivate = k
        c.discoPublic = tailcfg.DiscoKey(k.Public())
        c.discoShort = c.discoPublic.ShortString()
        c.logf("magicsock: set disco key = %v", c.discoShort)
}
```

Turns out `tailscale up` trips that, where the new `k` is non-zero and not equal to the old non-zero key:

```
Jul 06 10:01:14 tspaste tailscaled[15659]: panic: unsupported
Jul 06 10:01:14 tspaste tailscaled[15659]: goroutine 1124 [running]:
Jul 06 10:01:14 tspaste tailscaled[15659]: tailscale.com/wgengine/magicsock.(*Conn).SetDiscoPrivateKey(0xc00047c600, 0x5c16a17a8e387f2c, 0x5d2e2966f85a5e94, 0xf98e6f0fbc7bc0ab, 0x67e08f233bbaad69)
Jul 06 10:01:14 tspaste tailscaled[15659]:         tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/magicsock/magicsock.go:514 +0x3c8
Jul 06 10:01:14 tspaste tailscaled[15659]: tailscale.com/wgengine.(*userspaceEngine).SetDiscoPrivateKey(0xc000001c80, 0x5c16a17a8e387f2c, 0x5d2e2966f85a5e94, 0xf98e6f0fbc7bc0ab, 0x67e08f233bbaad69)
Jul 06 10:01:14 tspaste tailscaled[15659]:         tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/userspace.go:831 +0x43
Jul 06 10:01:14 tspaste tailscaled[15659]: tailscale.com/wgengine.(*watchdogEngine).SetDiscoPrivateKey.func1()
Jul 06 10:01:14 tspaste tailscaled[15659]:         tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:105 +0x58
Jul 06 10:01:14 tspaste tailscaled[15659]: tailscale.com/wgengine.(*watchdogEngine).watchdog.func1(0xc000915d40, 0xc0003127b0)
Jul 06 10:01:14 tspaste tailscaled[15659]:         tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:64 +0x24
Jul 06 10:01:14 tspaste tailscaled[15659]: tailscale.com/wgengine.(*watchdogEngine).watchdogErr.func1(0xc000915da0, 0xc0005e2bf0)
Jul 06 10:01:14 tspaste tailscaled[15659]:         tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:46 +0x27
Jul 06 10:01:14 tspaste tailscaled[15659]: created by tailscale.com/wgengine.(*watchdogEngine).watchdogErr
Jul 06 10:01:14 tspaste tailscaled[15659]:         tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/watchdog.go:45 +0x77
```

Need to figure out the state machine and fix.

Or maybe just ignore subsequent key sets?

/cc @danderson @crawshaw @dshynkev

**Comment by dshynkev** [comment]
The way `tailscale up` works right now is generally unfortunate, I think. It runs `LocalBackend.Start`, doing a lot of seemingly unnecessary work in the process. This bug is one consequence of that, since `b.e.SetDiscoPrivateKey(discoPrivate)` is part of `LocalBackend.Start`.

I have only a very nebulous idea of how much work it would be to make `tailscale up` properly, but it seems like a good idea to at least divide `LocalBackend.Start` into the part that is influenced by things `tailscale up` can change and the part that isn't, the latter running in a `Once` or similar.
