### ISSUE TITLE
Tailscale crashing on Synology DSM

### ISSUE THREAD

**Issue by sandr01d** [tailscale/tailscale#5387]
### What is the issue?

I just installed Tailscale on a Synology NAS via Synology's Package Center. Tailscale is running as an exit node on this device (not sure if that makes a difference here). After running for a while Tailscale crashes on this device. When I restart Tailscale, everything is back to normal, but after a while it will crash again.

### Steps to reproduce

Unfortunately I could not yet find a reliable way to reproduce the crash, but I've looked into the log file at /var/packages/Tailscale/var/tailscaled.stdout.log and found the following error:

```log
RAW-STDERR: panic: Incrementing non-positive count 0xc0000e4000 on stack.PacketBuffer
RAW-STDERR:
RAW-STDERR: goroutine 967 [running]:
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/stack.(*packetBufferRefs).IncRef(0xc0000e4000)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/packet_buffer_refs.go:80 +0x105
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/transport/udp.(*endpoint).HandlePacket(0xc00066c300, {0xd96, {0xc0003025d8, 0x4}, 0xc1d4, {0xc0003025d4, 0x4}}, 0xc0000e4000)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/transport/udp/endpoint.go:924 +0x2ed
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/stack.(*endpointsByNIC).handlePacket(0xc0005fa4b0, {0xd96, {0xc0003025d8, 0x4}, 0xc1d4, {0xc0003025d4, 0x4}}, 0xc0000e4000)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/transport_demuxer.go:185 +0x27f
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/stack.(*transportDemuxer).deliverPacket(0xc00000c450, 0x11, 0xc0000e4000, {0xd96, {0xc0003025d8, 0x4}, 0xc1d4, {0xc0003025d4, 0x4}})
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/transport_demuxer.go:595 +0x3c5
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).DeliverTransportPacket(0xc00000a1e0, 0x11, 0xc0000e4000)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/nic.go:861 +0x1fe
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).handleValidatedPacket(0xc00037d800, {0xc000318140, 0x14, 0x50}, 0xc0000e4380, {0x0, 0x0})
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/network/ipv4/ipv4.go:998 +0xfd6
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/network/ipv4.(*endpoint).HandlePacket(0xc00037d800, 0x88fa75)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/network/ipv4/ipv4.go:784 +0x2b8
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/stack.(*nic).DeliverNetworkPacket(0xc00000a1e0, {0xc000535bf0, 0x1}, {0x0, 0x0}, 0x800, 0xc0000e4380)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/stack/nic.go:777 +0x2dd
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).InjectLinkAddr(...)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/link/channel/channel.go:196
RAW-STDERR: gvisor.dev/gvisor/pkg/tcpip/link/channel.(*Endpoint).InjectInbound(...)
RAW-STDERR:     gvisor.dev/gvisor@v0.0.0-20220126021142-d8aa030b2591/pkg/tcpip/link/channel/channel.go:191
RAW-STDERR: tailscale.com/wgengine/netstack.(*Impl).injectInbound(0xc0001fc000, 0xc000670500, 0xc000125a40)
RAW-STDERR:     tailscale.com/wgengine/netstack/netstack.go:577 +0x744
RAW-STDERR: tailscale.com/net/tstun.(*Wrapper).filterIn(0xc000580000, {0xc0008f0010, 0x48, 0xffef})
RAW-STDERR:     tailscale.com/net/tstun/wrap.go:614 +0x78d
RAW-STDERR: tailscale.com/net/tstun.(*Wrapper).Write(0xc000580000, {0xc0008f0000, 0xc0006c7680, 0x1}, 0x10)
RAW-STDERR:     tailscale.com/net/tstun/wrap.go:627 +0x7c
RAW-STDERR: golang.zx2c4.com/wireguard/device.(*Peer).RoutineSequentialReceiver(0xc0002dce00)
RAW-STDERR:     golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/receive.go:477 +0x4d1
RAW-STDERR: created by golang.zx2c4.com/wireguard/device.(*Peer).Start
RAW-STDERR:     golang.zx2c4.com/wireguard@v0.0.0-20211116201604-de7c702ace45/device/peer.go:199 +0x295
````

### Are there any recent changes that introduced the issue?

No, just installed Tailscale on this device.

### OS

Synology

### OS version

Synology DSM 7.1-42661

### Tailscale version

1.22.2-220027

### Bug report

BUG-e5ca7dd22d51a5c0d9e6adb82f34c1da6ceb2d05f951ac5b8fcadda638eb19b4-20220816125227Z-275eabce007a5307

**Comment by bradfitz** [comment]
Dup of #4144, fixed in 1.24.0+.

I guess Synology's version is behind a bit. In the meantime you can upgrade from https://pkgs.tailscale.com/stable/#spks by installing the SPK manually.
