### ISSUE TITLE
tsconnect: resizing terminal window causes panic

### ISSUE THREAD

**Issue by catzkorn** [tailscale/tailscale#5567]
### What is the issue?

resizing terminal window causes a panic:

```
5:48:38.949 panic: runtime error: invalid memory address or nil pointer dereference [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.949 [signal 0xb code=0x0 addr=0x0 pc=0x0] [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.950 <empty string> [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.950 goroutine 6 [running]: [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.950 golang.org/x/crypto/ssh.(*Session).WindowChange(0x0, 0x18, 0x49) [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.950 	golang.org/x/crypto@v0.0.0-20220427172511-eb4f295cb31f/ssh/session.go:251 +0xa [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.951 main.(*jsSSHSession).Resize(...) [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.951 	tailscale.com/cmd/tsconnect/wasm/wasm_js.go:441 [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.951 main.(*jsIPN).ssh.func2({{}, 0x7ff80001000007a9, 0x1401348}, {0xfb0720, 0x2, 0x2}) [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.951 	tailscale.com/cmd/tsconnect/wasm/wasm_js.go:335 +0x16 [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.951 syscall/js.handleEvent() [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
15:48:38.951 	syscall/js/func.go:94 +0x26 [wasm_exec.js:22:13](http://localhost:31544/.cache/tailscale-go/misc/wasm/wasm_exec.js)
```

Browser: Firefox (also seen in Chrome)

**Comment by catzkorn** [comment]
Also happens on typing, in firefox.
