### ISSUE TITLE
nil pointer dereference when running `tailscale netcheck`

### ISSUE THREAD

**Issue by nebulatgs** [tailscale/tailscale#5919]
### What is the issue?

Running `tailscale netcheck` while connected to an exit node causes a nil pointer deref.

Client: Tailscale 1.32.0 on Windows 11 (22H2)
Exit Node: Tailscale 1.32.0 on Windows 10 (21H2)

### Steps to reproduce

```
C:\Users\Nebula>tailscale netcheck
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x1378238]

goroutine 175 [running]:
tailscale.com/derp/derphttp.(*Client).Close(0xc00069c2d0)
        tailscale.com@v1.32.0/derp/derphttp/derphttp_client.go:988 +0x38
tailscale.com/net/netcheck.(*Client).measureHTTPSLatency(0xc000240000, {0x15f3668, 0xc0002802a0}, 0x0?)
        tailscale.com@v1.32.0/net/netcheck/netcheck.go:1195 +0xa7c
tailscale.com/net/netcheck.(*Client).GetReport.func8(0xc0002b6640)
        tailscale.com@v1.32.0/net/netcheck/netcheck.go:1033 +0x97
created by tailscale.com/net/netcheck.(*Client).GetReport
        tailscale.com@v1.32.0/net/netcheck/netcheck.go:1031 +0x1c72
```

### OS

Windows

### OS version

22H2

### Tailscale version

1.32.0

### Bug report

BUG-a01c06d9d3e148a6c8c549f5ac2362b66b80190e0c272eed365057a70efa314f-20221013140405Z-6b8508d4502d0499

**Comment by nmcc1212** [comment]
having the same issue on macOS, App version: 1.32.0 (App Store)
``` panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10307a1cc]

goroutine 188 [running]:
tailscale.com/derp/derphttp.(*Client).Close(0x140005b41e0)
	tailscale.com@v1.32.0/derp/derphttp/derphttp_client.go:988 +0x2c
tailscale.com/net/netcheck.(*Client).measureHTTPSLatency(0x140000e2000, {0x1035dcbc8, 0x140000ae4e0}, 0x0?)
	tailscale.com@v1.32.0/net/netcheck/netcheck.go:1195 +0x7cc
tailscale.com/net/netcheck.(*Client).GetReport.func8(0x140000fc640)
	tailscale.com@v1.32.0/net/netcheck/netcheck.go:1033 +0x74
created by tailscale.com/net/netcheck.(*Client).GetReport
	tailscale.com@v1.32.0/net/netcheck/netcheck.go:1031 +0x18ac
[1]    89571 abort      /Applications/Tailscale.app/Contents/MacOS/Tailscale netcheck
```

**Comment by nmcc1212** [comment]
when will the fix be availible, next release?

**Comment by DentonGentry** [comment]
It will be in a 1.32.1 release as soon as we can get it delivered.
