### ISSUE TITLE
Panic in derphttp.(*Client).Close()

### ISSUE THREAD

**Issue by eric** [tailscale/tailscale#6027]
### What is the issue?

We have embedded tailscale in a go app and I noticed this in our logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10374cc0c]

goroutine 3695 [running]:
tailscale.com/derp/derphttp.(*Client).Close(0x140002ba5a0)
	tailscale.com@v1.32.0/derp/derphttp/derphttp_client.go:988 +0x2c
tailscale.com/net/netcheck.(*Client).measureHTTPSLatency(0x140002ebd60, {0x104151538, 0x14000b80140}, 0x14000b34000?)
	tailscale.com@v1.32.0/net/netcheck/netcheck.go:1195 +0x7cc
tailscale.com/net/netcheck.(*Client).GetReport.func8(0x14000ba29b0)
	tailscale.com@v1.32.0/net/netcheck/netcheck.go:1033 +0x74
created by tailscale.com/net/netcheck.(*Client).GetReport
	tailscale.com@v1.32.0/net/netcheck/netcheck.go:1031 +0x1a44
```

### Steps to reproduce

I'm not really sure. I was running this on my laptop and close and open it from time to time and saw log messages in my logs related to not having connectivity.

### OS

macOS

### OS version

macOS 12.6

### Tailscale version

1.32.0

**Comment by eric** [comment]
Just noticed this appears to be a dup of #5919 and fixed in #5924.
