### ISSUE TITLE
`send on closed channel` panic in dns/manager.go

### ISSUE THREAD

**Issue by mihaip** [tailscale/tailscale#6687]
https://github.com/tailscale/tailscale/blob/c084c7d7edf425fa661e7543298c14a93f867c81/net/dns/manager.go#L479-L482 is closed in some cases, leading to:

```
16:49:00 | netcheck: report: udp=true v6=false v6os=true mapvarydest=false hair=false portmap=U v4a=50.82.216.157:62913 derp=12 derpdist=9v4:33ms,12v4:22ms,21v4:26ms
16:49:01 | dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
16:49:01 | dns: resolver: forward: no upstream resolvers set, returning SERVFAIL
16:49:01 | dns: tcp request too large (10501 > 2048)
16:49:01 | dns: resolver: parseQuery(00): unpacking header: id: insufficient data for base length type
16:49:01 | panic: send on closed channel
16:49:01 |  
16:49:01 | goroutine 492437 [running]:
16:49:01 | tailscale.com/net/dns.(*dnsTCPSession).handleQuery(0xc000ad4720, {0x1522e18?, 0xc000e56264?, 0x4?})
16:49:01 | tailscale.com@v1.34.0/net/dns/manager.go:479 +0x1ed
16:49:01 | created by tailscale.com/net/dns.(*dnsTCPSession).handleReads
16:49:01 | tailscale.com@v1.34.0/net/dns/manager.go:518 +0x85
```
(from http://logz.ts.tailscale.com:9431/logs?start=2022-12-07T16%3A48%3A01Z&end=now&instances=8a7fa2f5e7c284473a65b3a5a134b2ecbc6c9097ca189e4082bcba74a9a090ef&match=)

25 occurrences/day based on http://go/panics

**Comment by bradfitz** [comment]
cc @twitchyliquid64

**Comment by dblohm7** [comment]
Fixed by https://github.com/tailscale/tailscale/pull/6728 @andrew-d ?

**Comment by bradfitz** [comment]
Yup. #6725 was a dup of this.
