### ISSUE TITLE
crash in unstable build v1.1.109

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#691]
```
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: No AuthURL
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: sendStatus: authRoutine4: state:authenticated
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M blockEngineUpdates(false)
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M authReconfig: netmap not yet valid. Skipping.
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M authReconfig: netmap not yet valid. Skipping.
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: cancelMapSafely: synced=false
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: cancelMapSafely: wrote to channel
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: mapRoutine: new map needed while idle.
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: authRoutine: state:authenticated
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: mapRoutine: state:authenticated
Aug 17 14:20:39 raspberrypi tailscaled[9639]: 5.3M/19.7M control: PollNetMap: stream=-1 :0 []
Aug 17 14:20:39 raspberrypi tailscaled[9639]: panic: runtime error: negative shift amount
Aug 17 14:20:39 raspberrypi tailscaled[9639]: goroutine 93 [running]:
Aug 17 14:20:39 raspberrypi tailscaled[9639]: tailscale.com/wgengine/filter.Netmask(...)
Aug 17 14:20:39 raspberrypi tailscaled[9639]: #011tailscale.com@v0.0.0-00010101000000-000000000000/wgengine/filter/match.go:48
Aug 17 14:20:39 raspberrypi tailscaled[9639]: tailscale.com/control/controlclient.parseIP(0x2173605, 0xb, 0x21, 0x2, 0x3, 0x2006ba0, 0x2)
Aug 17 14:20:39 raspberrypi tailscaled[9639]: #011tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/filter.go:31 +0x278
Aug 17 14:20:39 raspberrypi tailscaled[9639]: tailscale.com/control/controlclient.(*Direct).parsePacketFilter(0x1cca3c0, 0x1e7cb00, 0x12, 0x13, 0x2712e69b, 0xb2835bad, 0xf2cb713c)
Aug 17 14:20:39 raspberrypi tailscaled[9639]: #011tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/filter.go:63 +0x428
Aug 17 14:20:39 raspberrypi tailscaled[9639]: tailscale.com/control/controlclient.(*Direct).PollNetMap(0x1cca3c0, 0x67af58, 0x1d06cc0, 0xffffffff, 0x2037f40, 0x0, 0x0)
Aug 17 14:20:39 raspberrypi tailscaled[9639]: #011tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/direct.go:654 +0x1238
Aug 17 14:20:39 raspberrypi tailscaled[9639]: tailscale.com/control/controlclient.(*Client).mapRoutine(0x2056000)
Aug 17 14:20:39 raspberrypi tailscaled[9639]: #011tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:502 +0x430
Aug 17 14:20:39 raspberrypi tailscaled[9639]: created by tailscale.com/control/controlclient.(*Client).Start
Aug 17 14:20:39 raspberrypi tailscaled[9639]: #011tailscale.com@v0.0.0-00010101000000-000000000000/control/controlclient/auto.go:200 +0x48
Aug 17 14:20:39 raspberrypi systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 17 14:20:39 raspberrypi tailscaled[9690]: logtail started
Aug 17 14:20:39 raspberrypi tailscaled[9690]: Program starting: v1.1.109-g42090beaf, Go 1.15-ts2ce6917: []string{"/usr/sbin/tailscaled", "--cleanup"}
Aug 17 14:20:39 raspberrypi tailscaled[9690]: LogID: 39e8599fd9cadce4e345206d51833b3fcd113a06ca4d5520919f15dc61b8fa46
Aug 17 14:20:39 raspberrypi tailscaled[9690]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Aug 17 14:20:39 raspberrypi tailscaled[9690]: 3.2M/18.1M dns: resolvconf implementation is openresolv
Aug 17 14:20:39 raspberrypi tailscaled[9690]: 3.2M/18.1M dns: using dns.resolvconfManager
Aug 17 14:20:39 raspberrypi tailscaled[9690]: flushing log.
Aug 17 14:20:39 raspberrypi tailscaled[9690]: logger closing down
```

**Comment by bradfitz** [comment]
In addition to fixing client, it's likely the control server side also needs an update to not send these and possibly reject ACL saves with the content that generated this.

**Comment by bradfitz** [comment]
Actually unrelated to v1.1.109. Applies to all versions if you use an invalid IPv4 CIDR like /33 in your ACL rules.
 
Fixing both sides.
