### ISSUE TITLE
tstest/integration.newTestEnv is flaky

### ISSUE THREAD

**Issue by andrew-d** [tailscale/tailscale#7036]
https://github.com/tailscale/corp/actions/runs/3989076415/jobs/6841058944

<details>
  <summary>Click to expand test logs</summary>

```
panic: test timed out after 10m0s

goroutine 511 [running]:
testing.(*M).startAlarm.func1()
	/home/ubuntu/.cache/tailscale-go/src/testing/testing.go:2036 +0xb4
created by time.goFunc
	/home/ubuntu/.cache/tailscale-go/src/time/sleep.go:176 +0x48

goroutine 1 [chan receive, 9 minutes]:
testing.tRunner.func1()
	/home/ubuntu/.cache/tailscale-go/src/testing/testing.go:1412 +0x5dc
testing.tRunner(0xc000228820, 0xc000161aa8)
	/home/ubuntu/.cache/tailscale-go/src/testing/testing.go:1452 +0x1bc
testing.runTests(0xc000224b40?, {0x11b06a0, 0xd, 0xd}, {0x4?, 0xa?, 0x11bbf40?})
	/home/ubuntu/.cache/tailscale-go/src/testing/testing.go:1844 +0x6d0
testing.(*M).Run(0xc000224b40)
	/home/ubuntu/.cache/tailscale-go/src/testing/testing.go:1726 +0x880
tailscale.com/tstest/integration.TestMain(0x0?)
	/home/ubuntu/go/pkg/mod/tailscale.com@v1.1.1-0.20230122221356-64547b2b86f3/tstest/integration/integration_test.go:57 +0xd4
main.main()
	_testmain.go:73 +0x308

goroutine 28 [syscall, 9 minutes]:
syscall.Syscall6(0xc00070f8d8?, 0xab958?, 0xc00070f8e8?, 0xacc18?, 0xc00070f918?, 0xb77c0?, 0xc00070f938?)
	/home/ubuntu/.cache/tailscale-go/src/syscall/syscall_linux.go:90 +0x34
os.(*Process).blockUntilWaitable(0xc000040540)
	/home/ubuntu/.cache/tailscale-go/src/os/wait_waitid.go:32 +0x7c
os.(*Process).wait(0xc000040540)
	/home/ubuntu/.cache/tailscale-go/src/os/exec_unix.go:22 +0x48
os.(*Process).Wait(...)
	/home/ubuntu/.cache/tailscale-go/src/os/exec.go:132
os/exec.(*Cmd).Wait(0xc000444420)
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:599 +0x78
os/exec.(*Cmd).Run(0x1?)
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:437 +0x58
os/exec.(*Cmd).CombinedOutput(0xc000444420)
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:707 +0x218
tailscale.com/tstest/integration.(*testNode).MustUp(0xc00035c230, {0x0, 0x0, 0x0?})
	/home/ubuntu/go/pkg/mod/tailscale.com@v1.1.1-0.20230122221356-64547b2b86f3/tstest/integration/integration_test.go:844 +0x25c
tailscale.com/tstest/integration.TestC2NPingRequest(0xc000288820)
	/home/ubuntu/go/pkg/mod/tailscale.com@v1.1.1-0.20230122221356-64547b2b86f3/tstest/integration/integration_test.go:387 +0x94
testing.tRunner(0xc000288820, 0xb81090)
	/home/ubuntu/.cache/tailscale-go/src/testing/testing.go:1446 +0x18c
created by testing.(*T).Run
	/home/ubuntu/.cache/tailscale-go/src/testing/testing.go:1493 +0x568

goroutine 34 [IO wait, 10 minutes]:
net.(*TCPListener).accept(0xc00033afa8)
	/home/ubuntu/.cache/tailscale-go/src/net/tcpsock_posix.go:142 +0x3c
net.(*TCPListener).Accept(0xc00033afa8)
	/home/ubuntu/.cache/tailscale-go/src/net/tcpsock.go:288 +0x68
net/http.(*Server).Serve(0xc00035e0f0, {0xccaee0, 0xc00033afa8})
	/home/ubuntu/.cache/tailscale-go/src/net/http/server.go:3070 +0x440
net/http/httptest.(*Server).goServe.func1()
	/home/ubuntu/.cache/tailscale-go/src/net/http/httptest/server.go:310 +0xa4
created by net/http/httptest.(*Server).goServe
	/home/ubuntu/.cache/tailscale-go/src/net/http/httptest/server.go:308 +0x9c

goroutine 36 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0xffff9066c840, 0x72)
	/home/ubuntu/.cache/tailscale-go/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0xc000092378, 0xc00031a000?, 0x1)
	/home/ubuntu/.cache/tailscale-go/src/internal/poll/fd_poll_runtime.go:84 +0xc0
internal/poll.(*pollDesc).waitRead(...)
	/home/ubuntu/.cache/tailscale-go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc000092360, {0xc00031a000, 0x8000, 0x8000})
	/home/ubuntu/.cache/tailscale-go/src/internal/poll/fd_unix.go:167 +0x2f8
os.(*File).read(...)
	/home/ubuntu/.cache/tailscale-go/src/os/file_posix.go:31
os.(*File).Read(0xc000308068, {0xc00031a000, 0x8000, 0x8000})
	/home/ubuntu/.cache/tailscale-go/src/os/file.go:119 +0x9c
io.copyBuffer({0xcc30c0, 0xc0003806f0}, {0xcc2d40, 0xc000308068}, {0x0, 0x0, 0x0})
	/home/ubuntu/.cache/tailscale-go/src/io/io.go:427 +0x1f0
io.Copy(...)
	/home/ubuntu/.cache/tailscale-go/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1()
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:407 +0x60
os/exec.(*Cmd).Start.func1(0xc00028e040)
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:544 +0x38
created by os/exec.(*Cmd).Start
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:543 +0x988

goroutine 73 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0xffff8879f3d8, 0x72)
	/home/ubuntu/.cache/tailscale-go/src/runtime/netpoll.go:305 +0xa0
internal/poll.(*pollDesc).wait(0xc00066e5b8, 0xc000394600?, 0x1)
	/home/ubuntu/.cache/tailscale-go/src/internal/poll/fd_poll_runtime.go:84 +0xc0
internal/poll.(*pollDesc).waitRead(...)
	/home/ubuntu/.cache/tailscale-go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00066e5a0, {0xc000394600, 0x200, 0x200})
	/home/ubuntu/.cache/tailscale-go/src/internal/poll/fd_unix.go:167 +0x2f8
os.(*File).read(...)
	/home/ubuntu/.cache/tailscale-go/src/os/file_posix.go:31
os.(*File).Read(0xc0003082f8, {0xc000394600, 0x200, 0x200})
	/home/ubuntu/.cache/tailscale-go/src/os/file.go:119 +0x9c
bytes.(*Buffer).ReadFrom(0xc00037a3f0, {0xcc2d40, 0xc0003082f8})
	/home/ubuntu/.cache/tailscale-go/src/bytes/buffer.go:202 +0xec
io.copyBuffer({0xcc1060, 0xc00037a3f0}, {0xcc2d40, 0xc0003082f8}, {0x0, 0x0, 0x0})
	/home/ubuntu/.cache/tailscale-go/src/io/io.go:413 +0x[158](https://github.com/tailscale/corp/actions/runs/3989076415/jobs/6841058944#step:5:159)
io.Copy(...)
	/home/ubuntu/.cache/tailscale-go/src/io/io.go:386
os/exec.(*Cmd).writerDescriptor.func1()
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:407 +0x60
os/exec.(*Cmd).Start.func1(0xc00028e5e0)
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:544 +0x38
created by os/exec.(*Cmd).Start
	/home/ubuntu/.cache/tailscale-go/src/os/exec/exec.go:543 +0x988
FAIL	tailscale.com/tstest/integration	600.202s
```

</details>

**Comment by bradfitz** [comment]
Seems like this is nothing to do with C2N necessarily but anything using the tstest/integration helpers. That `MustUp` is hanging.

**Comment by bradfitz** [comment]
```
cloud@cloud:~/tailscale$ time ./tool/go test -v -run=C2NPing -count=50 ./tstest/integration/ --verbose-tailscaled
...
2024/04/13 21:56:53 ipnserver: http: panic serving @: LocalBackend.assertClient: b.cc == nil
goroutine 87 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1898 +0xbe
panic({0xef9bc0?, 0x12bcd60?})
        runtime/panic.go:770 +0x132
tailscale.com/ipn/ipnlocal.(*LocalBackend).assertClientLocked(...)
        tailscale.com/ipn/ipnlocal/local.go:4746
tailscale.com/ipn/ipnlocal.(*LocalBackend).StartLoginInteractive(0xc000223208)
        tailscale.com/ipn/ipnlocal/local.go:2853 +0x1bb
tailscale.com/ipn/localapi.(*Handler).serveLoginInteractive(0xc0002b60f5?, {0x12cde90, 0xc0023bc000}, 0x16?)
        tailscale.com/ipn/localapi/localapi.go:1322 +0x69
tailscale.com/ipn/localapi.(*Handler).ServeHTTP(0xc0000ae1c0, {0x12cde90, 0xc0023bc000}, 0xc00025dd40)
        tailscale.com/ipn/localapi/localapi.go:224 +0x5cc
tailscale.com/ipn/ipnserver.(*Server).serveHTTP(0xc000302480, {0x12cde90, 0xc0023bc000}, 0xc00025dd40)
        tailscale.com/ipn/ipnserver/server.go:206 +0x68a
net/http.HandlerFunc.ServeHTTP(0x46e379?, {0x12cde90?, 0xc0023bc000?}, 0xc00011ab68?)
        net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0xc0023b4120?}, {0x12cde90?, 0xc0023bc000?}, 0x6?)
        net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc0000bba70, {0x12cf9d8, 0xc0023b40c0})
        net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        net/http/server.go:3285 +0x4b4
```

**Comment by bradfitz** [comment]
More context of what led to that:
```
    integration_test.go:588: Running /tmp/3850011189/tailscale --socket=/tmp/TestC2NPingRequest140537772/001/tailscale.sock up --login-server=http://127.0.0.1:36523 --reset ...
2024/04/13 21:56:53 pm: migrating "_daemon" profile to new format
2024/04/13 21:56:53 envknob: TS_DEBUG_FAKE_GOOS="linux"
2024/04/13 21:56:53 envknob: TS_DISABLE_UPNP="true"
2024/04/13 21:56:53 envknob: TS_PARENT_DEATH_FD="3"
2024/04/13 21:56:53 netmap packet filter: (not ready yet)
2024/04/13 21:56:53 got LocalBackend in 16ms
2024/04/13 21:56:53 Start
2024/04/13 21:56:53 {"Hostinfo":{"IPNVersion":"1.65.6-t1cd51f95c","BackendLogID":"3894c172d7b20e5c6b04165fd1f2e051a3e07463323ecd5438485686834a3960","OS":"linux","OSVersion":"5.15.0-101-generic","Container":false,"Distro":"ubuntu","DistroVersion":"22.04","DistroCodeName":"jammy","Desktop":false,"Hostname":"cloud","Machine":"x86_64","GoArch":"amd64","GoArchVar":"v1","GoVersion":"go1.22.2","Userspace":true,"UserspaceRouter":true,"AppConnector":false}}
2024/04/13 21:56:53 netmap packet filter: (not ready yet)
2024/04/13 21:56:53 got initial portlist info in 3ms
2024/04/13 21:56:53 control: HostInfo: {"IPNVersion":"1.65.6-t1cd51f95c","BackendLogID":"3894c172d7b20e5c6b04165fd1f2e051a3e07463323ecd5438485686834a3960","OS":"linux","OSVersion":"5.15.0-101-generic","Container":false,"Distro":"ubuntu","DistroVersion":"22.04","DistroCodeName":"jammy","Desktop":false,"Hostname":"cloud","Machine":"x86_64","GoArch":"amd64","GoArchVar":"v1","GoVersion":"go1.22.2","Services":[{"Proto":"tcp","Port":22},{"Proto":"tcp","Port":53}],"Userspace":true,"UserspaceRouter":true,"AppConnector":false}
2024/04/13 21:56:53 Backend: logs: be:3894c172d7b20e5c6b04165fd1f2e051a3e07463323ecd5438485686834a3960 fe:
2024/04/13 21:56:53 control: authRoutine: state:new; goal=nil paused=false
2024/04/13 21:56:53 Switching ipn state NoState -> NeedsLogin (WantRunning=false, nm=false)
2024/04/13 21:56:53 blockEngineUpdates(true)
2024/04/13 21:56:53 magicsock: peermtu: peer MTU status is false
2024/04/13 21:56:53 wgengine: Reconfig: configuring userspace WireGuard config (with 0/0 peers)
2024/04/13 21:56:53 wgengine: Reconfig: configuring router
2024/04/13 21:56:53 warning: fakeRouter.Set: not implemented.
2024/04/13 21:56:53 wgengine: Reconfig: configuring DNS
2024/04/13 21:56:53 control: mapRoutine: state:new
2024/04/13 21:56:53 health("overall"): error: state=NeedsLogin, wantRunning=false
2024/04/13 21:56:53 dns: Set: {DefaultResolvers:[] Routes:{} SearchDomains:[] Hosts:0}
2024/04/13 21:56:53 dns: Resolvercfg: {Routes:{} Hosts:0 LocalDomains:[]}
2024/04/13 21:56:53 dns: OScfg: {}
2024/04/13 21:56:53 wgengine: Reconfig done
2024/04/13 21:56:53 Start
2024/04/13 21:56:53 {"Hostinfo":{"IPNVersion":"1.65.6-t1cd51f95c","BackendLogID":"3894c172d7b20e5c6b04165fd1f2e051a3e07463323ecd5438485686834a3960","OS":"linux","OSVersion":"5.15.0-101-generic","Container":false,"Distro":"ubuntu","DistroVersion":"22.04","DistroCodeName":"jammy","Desktop":false,"Hostname":"cloud","Machine":"x86_64","GoArch":"amd64","GoArchVar":"v1","GoVersion":"go1.22.2","Userspace":true,"UserspaceRouter":true,"AppConnector":false}}
2024/04/13 21:56:53 generating new machine key
2024/04/13 21:56:53 machine key written to store
2024/04/13 21:56:53 control: client.Shutdown()
2024/04/13 21:56:53 control: client.Shutdown
2024/04/13 21:56:53 control: mapRoutine: context done.
2024/04/13 21:56:53 control: mapRoutine: exiting
2024/04/13 21:56:53 control: authRoutine: context done.
2024/04/13 21:56:53 control: authRoutine: exiting
2024/04/13 21:56:53 control: updateRoutine: exiting
2024/04/13 21:56:53 control: Client.Shutdown done.
2024/04/13 21:56:53 ipnserver: http: panic serving @: LocalBackend.assertClient: b.cc == nil
```
