### ISSUE TITLE
magicsock: sync.Cond deadlock on Close

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#712]
From one of our e2e tests at HEAD 169ff22a8:

```
goroutine 35 [sync.Cond.Wait, 9 minutes]:                                                                      
runtime.goparkunlock(...)                                                                                      
        /home/crawshaw/.cache/tailscale-go/src/runtime/proc.go:312                                             
sync.runtime_notifyListWait(0xc00028e810, 0x0)                                                                 
        /home/crawshaw/.cache/tailscale-go/src/runtime/sema.go:513 +0xf8                                       
sync.(*Cond).Wait(0xc00028e800)                                                                                
        /home/crawshaw/.cache/tailscale-go/src/sync/cond.go:56 +0x9d                                           
tailscale.com/wgengine/magicsock.(*Conn).Close(0xc0000ee6c0, 0x0, 0x0)                                         
        /home/crawshaw/repo/corp/oss/wgengine/magicsock/magicsock.go:2234 +0x1ac                               
tailscale.com/wgengine.(*userspaceEngine).Close(0xc00029a1a0)
        /home/crawshaw/repo/corp/oss/wgengine/userspace.go:1084 +0x33a
```

The test locks up waiting for `c.muCond.Wait()` to return. There is little else of interest in the large stack trace this came from. Nothing is waiting to acquire the mutex.

I suspect, because the calls to `c.muCond.Broadcast()` are not done while holding `c.mu`, that the condition test `c.goroutinesRunningLocked()` races with waiting on the condition. That is:

````
goroutine 1: c.goroutinesRunningLocked() // reports true
goroutine 2: c.muCond.Broadcast()
goroutine 1: c.muCond.Wait() // too late, missed the broadcast
```

**Comment by crawshaw** [comment]
The key to triggering this consistently seems to be providing a DERPMap with a single entry that is unreachable.

**Comment by DentonGentry** [comment]
It has been almost a year since this test failure occurred with no additional instances noted. Barring further updates, we'll expect to close this during the next bug scrub.
