### ISSUE TITLE
nil pointer dereference panic in ipn/ipnlocal/local.go

### ISSUE THREAD

**Issue by jwhited** [tailscale/tailscale#7392]
```
07:27:21 | setClientStatus: netmap expiry timer triggered after 45h45m26.64464318s
[...]
07:27:23 | panic: runtime error: invalid memory address or nil pointer dereference
07:27:23 | [signal 0xc0000005 code=0x0 addr=0x48 pc=0xb5d833]
07:27:23 |  
07:27:23 | goroutine 641623 [running]:
07:27:23 | tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus(0xc00011c380,  {{}, 0x0, 0x0, {0x0, 0x0}, {0x0, 0x0}, 0xc0007d3b00, 0x5, ...})
07:27:23 | tailscale.com@v1.1.1-0.20230217011852-d811c5a7f099/ipn/ipnlocal/local.go:985 +0x17f3
07:27:23 | tailscale.com/ipn/ipnlocal.(*LocalBackend).setClientStatus.func1()
07:27:23 | tailscale.com@v1.1.1-0.20230217011852-d811c5a7f099/ipn/ipnlocal/local.go:866 +0xf0
07:27:23 | created by time.goFunc
07:27:23 | time/sleep.go:176 +0x32
```

https://github.com/tailscale/tailscale/blob/d811c5a7f099cadb050f800ca1362766cf6ab02f/ipn/ipnlocal/local.go#L985
The control client is nil when `setClientStatus()` is being called recursively to expire nodes in the future via `time.AfterFunc()`

https://github.com/tailscale/tailscale/blob/d811c5a7f099cadb050f800ca1362766cf6ab02f/ipn/ipnlocal/local.go#L866

**Comment by bradfitz** [comment]
cc @andrew-d
