### ISSUE TITLE
tsnet: panic accessing Addr of loopback net.Listener

### ISSUE THREAD

**Issue by crawshaw** [tailscale/tailscale#7488]
### What is the issue?

Just saw this on the libtailscale CI:

https://github.com/tailscale/libtailscale/actions/runs/4356929373/jobs/7615585178

```
--- FAIL: TestConn (0.83s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc4da07]

goroutine 19 [running]:
testing.tRunner.func1.2({0xd28c00, 0x14df410})
	/opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.1/x64/src/testing/testing.go:1529 +0x39f
panic({0xd28c00, 0x14df410})
	/opt/hostedtoolcache/go/1.20.1/x64/src/runtime/panic.go:884 +0x213
tailscale.com/tsnet.(*Server).Loopback(0xc00023e160)
	/home/runner/go/pkg/mod/tailscale.com@v1.1.1-0.202303061[70](https://github.com/tailscale/libtailscale/actions/runs/4356929373/jobs/7615585178#step:4:71)009-387b68fe113f/tsnet/tsnet.go:217 +0x547
```

If I've got this right, the error is in 

```
return s.loopbackListener.Addr().String(), s.proxyCred, s.localAPICred, nil
```

which means that `s.loopbackListener.Addr()` is returning nil, which I believe should be impossible. I took a read through the stdlib sources and couldn't find a path that would make that true.

**Comment by crawshaw** [comment]
Running locally on linux I also saw `net.Listen("tcp", "127.0.0.1:0")` fail with `EBADF`, which doesn't really make any sense.

I am wondering if I'm running into a cgo callback bug in stdlib.

**Comment by crawshaw** [comment]
To follow up on the last comment, here's another example from my linux/amd64 machine running the libtailscale test in a loop:

```
=== RUN   TestConn
    tsnetctest.go:164: DERP httpsrv listener: 127.0.0.1:36307
    tsnetctest.go:172: testcontrol listening on http://127.0.0.1:35207
    tsnetctest.go:185: b: listen tcp 127.0.0.1:0: setsockopt: bad file descriptor
    stuntest.go:63: STUN server shutdown
--- FAIL: TestConn (1.39s)
```

Using stock `go version go1.20 linux/amd64`.

That's super suspicious. It's an error from inside the `net` package, after the socket is created during a use of setsockopt. It really is making me think the fact I'm calling Go from C (via cgo, correctly). I took a guess that it might be a signal handler, but `GODEBUG=asyncpreemptoff=1` didn't help.
