### ISSUE TITLE
wireguard-go/tun/wintun/registry: checkptr: converted pointer straddles multiple allocations

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#833]
Building tailscaled in race mode on Windows, I get:

```
Z:\>tswin
2020/10/19 09:14:46 Tailscale service running: false
2020/10/19 09:14:46 tswin: no old processes running
logtail started
Program starting: v1.1.558-gfc8d93122, Go 1.15-tsc099eea: []string{"c:\\tsdev\\tailscale-ipn.exe", "/server"}
LogID: 2612b12569f9d991a7537c3ff0987ec459024ad0a8a0fbdef51af9b9daf3cb4b
logpolicy: using UserCacheDir, "C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\Tailscale"
stdout ok.
stderr ok.
log ok.
Running server directly...
exec: "c:\\tsdev\\tailscale-ipn.exe" [/subproc 2612b12569f9d991a7537c3ff0987ec459024ad0a8a0fbdef51af9b9daf3cb4b]
Program starting: v1.1.558-gfc8d93122: []string{"c:\\tsdev\\tailscale-ipn.exe", "/subproc", "2612b12569f9d991a7537c3ff0987ec459024ad0a8a0fbdef51af9b9daf3cb4b"}
subproc mode: logid=2612b12569f9d991a7537c3ff0987ec459024ad0a8a0fbdef51af9b9daf3cb4b
srv: local disk logdir: C:\Windows\System32\config\systemprofile\AppData\Local\Tailscale\Logs
srv: Starting userspace wireguard engine with tun device "Tailscale"
fatal error: checkptr: converted pointer straddles multiple allocations

goroutine 1 [running]:
runtime.throw(0xde314a, 0x3a)
        runtime/panic.go:1116 +0x79 fp=0xc00010f338 sp=0xc00010f308 pc=0x1bbbf9
runtime.checkptrAlignment(0xc00010f448, 0xcaf040, 0x1)
        runtime/checkptr.go:20 +0xc9 fp=0xc00010f368 sp=0xc00010f338 pc=0x188189
github.com/tailscale/wireguard-go/tun/wintun/registry.toString(0xc00010f448, 0x4e, 0x100, 0xc000000001, 0x0, 0x0, 0xc00010f448, 0x4e, 0x100, 0x1)
        github.com/tailscale/wireguard-go@v0.0.0/tun/wintun/registry/registry_windows.go:186 +0x8d fp=0xc00010f3d8 sp=0xc00010f368 pc=0x832b6d
github.com/tailscale/wireguard-go/tun/wintun/registry.GetStringValue(0x254, 0xdc55c8, 0x10, 0x100000002, 0x254, 0x0, 0x0)
fatal error: checkptr: converted pointer straddles multiple allocations
        github.com/tailscale/wireguard-go@v0.0.0/tun/wintun/registry/registry_windows.go:260 +0xf8 fp=0xc00010f568 sp=0xc00010f3d8 pc=0x833018
```

/cc @alexbrainman

**Comment by bradfitz** [comment]
Sent https://github.com/WireGuard/wireguard-windows/pull/11

**Comment by alexbrainman** [comment]
@bradfitz try running `go test` command with `-gcflags=all=-d=checkptr` or with race flag. You should be able to find all related problems, if you test code coverage is good enough. Is that what you did?

Alex

**Comment by alexbrainman** [comment]
> Sent [WireGuard/wireguard-windows#11](https://github.com/WireGuard/wireguard-windows/pull/11)

LGTM so far.

Alex

**Comment by bradfitz** [comment]
This has been fixed.

**Comment by alexbrainman** [comment]
Should we run

`go test -race ./...`

workflow Github Action so this does not regress?

Alex

**Comment by bradfitz** [comment]
@alexbrainman, isn't that #913?

**Comment by bradfitz** [comment]
Oh, `-race` for tailscaled. I thought we did, but maybe only for Linux? Feel free to add another to windows.

**Comment by alexbrainman** [comment]
> Oh, `-race` for tailscaled.

Correct.

> I thought we did, but maybe only for Linux?

You did not. Even on Linux.

> Feel free to add another to windows.

See #991.

Alex
