### ISSUE TITLE
tailscale-1.46.0 does not work on ARM64 systems with page size != 4k

### ISSUE THREAD

**Issue by krsuhjunho** [tailscale/tailscale#8658]
### What is the issue?

1.46.0-1
panic: Only 4K page size is supported on arm64!

goroutine 1 [running]:
gvisor.dev/gvisor/pkg/hostarch.init.0()
        gvisor.dev/gvisor@v0.0.0-20230504175454-7b0a1988a28f/pkg/hostarch/hostarch_arm64.go:59 +0x44

1.44.0 

No Error

Thank you

### Steps to reproduce

tailscale in ssh 

### OS

Linux

### OS version

AlmaLinux release 8.8 (Sapphire Caracal)

### Tailscale version

1.46.0-1

**Comment by MDrollette** [comment]
I ran into this this morning as well. It had been working fine and suddenly started getting this error during the middle of the night. I'm not sure if it was a tailscale auto-update or an Oracle update that triggered it.

**Comment by DentonGentry** [comment]
We are looking into this.

**Comment by bradfitz** [comment]
@DentonGentry, debugging notes. We didn't bump our gvisor dep from 1.44.2 to 1.46.0:

```patch
$ git diff -r v1.44.2..v1.46.0 go.mod
diff --git a/go.mod b/go.mod
index 92613bc6..97314f32 100644
--- a/go.mod
+++ b/go.mod
@@ -59,28 +59,29 @@ require (
 	github.com/tailscale/certstore v0.1.1-0.20220316223106-78d6e1c49d8d
 	github.com/tailscale/depaware v0.0.0-20210622194025-720c4b409502
 	github.com/tailscale/goexpect v0.0.0-20210902213824-6e8c725cea41
-	github.com/tailscale/golang-x-crypto v0.0.0-20221115211329-17a3db2c30d2
+	github.com/tailscale/golang-x-crypto v0.0.0-20230713185742-f0b76a10a08e
 	github.com/tailscale/goupnp v1.0.1-0.20210804011211-c64d0f06ea05
 	github.com/tailscale/hujson v0.0.0-20221223112325-20486734a56a
 	github.com/tailscale/mkctr v0.0.0-20220601142259-c0b937af2e89
 	github.com/tailscale/netlink v1.1.1-0.20211101221916-cabfb018fe85
-	github.com/tailscale/wireguard-go v0.0.0-20230410165232-af172621b4dd
+	github.com/tailscale/wireguard-go v0.0.0-20230710185534-bb2c8f22eccf
 	github.com/tc-hib/winres v0.2.0
 	github.com/tcnksm/go-httpstat v0.2.0
 	github.com/toqueteos/webbrowser v1.2.0
 	github.com/u-root/u-root v0.11.0
 	github.com/vishvananda/netlink v1.2.1-beta.2
+	github.com/vishvananda/netns v0.0.4
 	go.uber.org/zap v1.24.0
 	go4.org/mem v0.0.0-20220726221520-4f986261bf13
 	go4.org/netipx v0.0.0-20230303233057-f1b76eb4bb35
-	golang.org/x/crypto v0.8.0
+	golang.org/x/crypto v0.11.0
 	golang.org/x/exp v0.0.0-20230425010034-47ecfdc1ba53
 	golang.org/x/mod v0.10.0
 	golang.org/x/net v0.10.0
 	golang.org/x/oauth2 v0.7.0
 	golang.org/x/sync v0.2.0
-	golang.org/x/sys v0.8.1-0.20230609144347-5059a07aa46a
-	golang.org/x/term v0.8.0
+	golang.org/x/sys v0.10.0
+	golang.org/x/term v0.10.0
 	golang.org/x/time v0.3.0
 	golang.org/x/tools v0.9.1
 	golang.zx2c4.com/wintun v0.0.0-20230126152724-0fa3db229ce2
@@ -154,7 +155,7 @@ require (
 	github.com/davecgh/go-spew v1.1.1 // indirect
 	github.com/denis-tingaikin/go-header v0.4.3 // indirect
 	github.com/docker/cli v23.0.5+incompatible // indirect
-	github.com/docker/distribution v2.8.1+incompatible // indirect
+	github.com/docker/distribution v2.8.2+incompatible // indirect
 	github.com/docker/docker v23.0.5+incompatible // indirect
 	github.com/docker/docker-credential-helpers v0.7.0 // indirect
 	github.com/emicklei/go-restful/v3 v3.10.2 // indirect
@@ -322,7 +323,6 @@ require (
 	github.com/ultraware/whitespace v0.0.5 // indirect
 	github.com/uudashr/gocognit v1.0.6 // indirect
 	github.com/vbatts/tar-split v0.11.2 // indirect
-	github.com/vishvananda/netns v0.0.4 // indirect
 	github.com/x448/float16 v0.8.4 // indirect
 	github.com/xanzy/ssh-agent v0.3.3 // indirect
 	github.com/yagipy/maintidx v1.0.0 // indirect
@@ -333,7 +333,7 @@ require (
 	go.uber.org/multierr v1.11.0 // indirect
 	golang.org/x/exp/typeparams v0.0.0-20230425010034-47ecfdc1ba53 // indirect
 	golang.org/x/image v0.7.0 // indirect
-	golang.org/x/text v0.9.0 // indirect
+	golang.org/x/text v0.11.0 // indirect
 	gomodules.xyz/jsonpatch/v2 v2.3.0 // indirect
 	google.golang.org/appengine v1.6.7 // indirect
 	google.golang.org/protobuf v1.30.0 // indirect
```

Maybe something in Go or `golang.org/x/sys` changed?

**Comment by bradfitz** [comment]
x/sys/unix.Getpagesize just forwards to Go's std syscall package:

```go
func Getpagesize() int {
        return syscall.Getpagesize()
}
```

**Comment by bradfitz** [comment]
I haven't found a Go change in that range that changes what Getpagesize reports.

And at least on darwin/arm64 it reported non-4K previously and still does:

```
bradfitz@book1pro tailscale.com % go test -v -run=Page
=== RUN   TestPageSize
    version_test.go:17: Go version "go1.20.4" says size = 16384
--- PASS: TestPageSize (0.00s)
PASS
ok  	tailscale.com	0.082s
bradfitz@book1pro tailscale.com % ./tool/go test -v -run=Page
=== RUN   TestPageSize
    version_test.go:17: Go version "go1.21rc3" says size = 16384
--- PASS: TestPageSize (0.00s)
PASS
ok  	tailscale.com	0.197s
bradfitz@book1pro tailscale.com % uname -a
Darwin book1pro.localdomain 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 arm64
```

**Comment by A-z-z-y** [comment]
Getting this issue on Asahi Linux on version 1.46.0-1 also.

**Comment by bradfitz** [comment]
Ah, figured it out.

This was due to https://github.com/tailscale/tailscale/commit/a3c7b21cd18866cd8ceeee9b102c9e4171fcd719 (cc @KevinLiang10 @catzkorn) which I'd said was probably safe as a last minute commit before the release because it was all behind a flag and off by default. But its init dependencies result this this new path, only on Linux (not darwin):

> "./cmd/tailscaled" "tailscale.com/wgengine/router" "tailscale.com/util/linuxfw" "gvisor.dev/gvisor/pkg/abi/linux" "gvisor.dev/gvisor/pkg/marshal/primitive" "gvisor.dev/gvisor/pkg/marshal" "gvisor.dev/gvisor/pkg/hostarch"]

And that final package (hostarch) explodes in init on non-4K page machines.

**Comment by DentonGentry** [comment]
We removed the ARM64 Tailscale 1.46 RPM, deb, and static binaries.
This means that all ARM64 devices will be offered Tailscale 1.44.2, even machines with 4k pages which would otherwise work with 1.46.0.

We'll expect to build a 1.46.1 to fix this issue.

**Comment by krsuhjunho** [comment]
> 

Thank you!
