### ISSUE TITLE
net/nettest: TestPipeTimeout occasional failure on Windows

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#873]
@crawshaw, any idea?

```
panic: test timed out after 10m0s

goroutine 5 [running]:
testing.(*M).startAlarm.func1()
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1618 +0xe6
created by time.goFunc
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/time/sleep.go:167 +0x4b

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0000c0600, 0x10f0b7a, 0xf, 0x10fa3b0, 0x101d401)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1169 +0x2da
testing.runTests.func1(0xc0000c0180)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1439 +0x7f
testing.tRunner(0xc0000c0180, 0xc0000b9de0)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1123 +0xef
testing.runTests(0xc00008a4a0, 0x11d8980, 0x3, 0x3, 0xbfdee7ca89b87870, 0x8bb352e705, 0x11dc700, 0xf9e010)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1437 +0x310
testing.(*M).Run(0xc0000e8000, 0x0)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1345 +0x1f5
main.main()
	_testmain.go:47 +0x145

goroutine 20 [chan receive]:
testing.(*T).Run(0xc0000c0c00, 0x10efc16, 0xb, 0x10fa3a0, 0x49f0d4fc01)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1169 +0x2da
tailscale.com/net/nettest.TestPipeTimeout(0xc0000c0600)
	D:/a/tailscale/tailscale/net/nettest/pipe_test.go:59 +0xb5
testing.tRunner(0xc0000c0600, 0x10fa3b0)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1168 +0x2b3

goroutine 23 [chan receive]:
tailscale.com/net/nettest.(*Pipe).Write(0xc0000f21b0, 0xc00003bf37, 0x0, 0x0, 0x1, 0x0, 0x0)
	D:/a/tailscale/tailscale/net/nettest/pipe.go:122 +0x231
tailscale.com/net/nettest.TestPipeTimeout.func3(0xc0000c0c00)
	D:/a/tailscale/tailscale/net/nettest/pipe_test.go:68 +0x229
testing.tRunner(0xc0000c0c00, 0x10fa3a0)
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.15.3/x64/src/testing/testing.go:1168 +0x2b3
FAIL	tailscale.com/net/nettest	600.032s
```

**Comment by josharian** [comment]
I can't reproduce here after 50k runs, so it does seem to be Windows-only.

But there's no Windows-specific code (or OS-specific code) I see anywhere in that package. That's quite disconcerting.

Can anyone running Windows reproduce locally, or is this GitHub-only?

**Comment by josharian** [comment]
Thanks, @alexbrainman. Would you test `tailscale.com/net/nettest` (instead of `tailscale.com/net/netstat`)? (I'm also debugging indirectly over at https://github.com/tailscale/tailscale/pull/1141.)

**Comment by alexbrainman** [comment]
> Would you test `tailscale.com/net/nettest` (instead of `tailscale.com/net/netstat`)?

Oops.

Still passes here against your #1141

```
c:\Users\Alex\dev\src\github.com\tailscale\tailscale>go test -count=1000 -timeout=45s tailscale.com/net/nettest
ok      tailscale.com/net/nettest       21.520s

c:\Users\Alex\dev\src\github.com\tailscale\tailscale>go test -count=1000 -timeout=45s tailscale.com/net/nettest
ok      tailscale.com/net/nettest       21.797s

c:\Users\Alex\dev\src\github.com\tailscale\tailscale>go test -count=1000 -timeout=45s tailscale.com/net/nettest
ok      tailscale.com/net/nettest       21.800s

c:\Users\Alex\dev\src\github.com\tailscale\tailscale>go test -count=10000 -timeout=450s tailscale.com/net/nettest
ok      tailscale.com/net/nettest       244.228s

c:\Users\Alex\dev\src\github.com\tailscale\tailscale>
```

**Comment by josharian** [comment]
Thanks, Alex. Sadly, my #1141 also keeps passing. :(

**Comment by josharian** [comment]
I have a theory: Windows has low resolution timers. We expect a timeout here:

```
		timedout := !p.writeTimeout.IsZero() && time.Now().After(p.writeTimeout)
```

but we don't get it, because time.Now == p.writeTimeout. Fix is !time.Now().Before(p.writeTimeout).

Testing out that theory...

**Comment by josharian** [comment]
That was it. Fix and details (and other improvements) in #1141.
