### ISSUE TITLE
derp: maybeCloseDERPsOnRebind panic, crash

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#9128]
This is a top crasher in 1.48.x:

```
panic: runtime error: slice bounds out of range [54:35]
--
13:35:08 |  
13:35:08 | goroutine 54800 [running]:
13:35:08 | internal/poll.(*FD).Write(0x14000a38820, {0x14000be6270, 0x23, 0x23})
13:35:08 | internal/poll/fd_unix.go:380 +0x3ac
13:35:08 | net.(*netFD).Write(0x14000a38820, {0x14000be6270?, 0x0?, 0x102342bf8?})
13:35:08 | net/fd_posix.go:132 +0x28
13:35:08 | net.(*conn).Write(0x14000242050, {0x14000be6270?, 0x14000d19b28?, 0x140000c0218?})
13:35:08 | net/net.go:191 +0x34
13:35:08 | crypto/tls.(*Conn).write(0x14000ae0000, {0x14000be6270?, 0x5?, 0x5?})
13:35:08 | crypto/tls/conn.go:944 +0x100
13:35:08 | crypto/tls.(*Conn).writeRecordLocked(0x14000ae0000, 0x17, {0x14000b00000, 0xd, 0x1000})
13:35:08 | crypto/tls/conn.go:1025 +0x508
13:35:08 | crypto/tls.(*Conn).Write(0x14000ae0000, {0x14000b00000, 0xd, 0x1000})
13:35:08 | crypto/tls/conn.go:1232 +0x364
13:35:08 | bufio.(*Writer).Flush(0x14000bfa5c0)
13:35:08 | bufio/bufio.go:642 +0x5c
13:35:08 | tailscale.com/derp.(*Client).sendPingOrPong(0x140006be8c0, 0x61?, {0x5d, 0x7f, 0x9, 0x9c, 0x45, 0x4a, 0x36, 0x3a})
13:35:08 | tailscale.com@v1.48.0/derp/derp_client.go:288 +0x140
13:35:08 | tailscale.com/derp.(*Client).SendPing(...)
13:35:08 | tailscale.com@v1.48.0/derp/derp_client.go:272
13:35:08 | tailscale.com/derp/derphttp.(*Client).SendPing(0x140004fe240?, {0x5d, 0x7f, 0x9, 0x9c, 0x45, 0x4a, 0x36, 0x3a})
13:35:08 | tailscale.com@v1.48.0/derp/derphttp/derphttp_client.go:878 +0x104
13:35:08 | tailscale.com/derp/derphttp.(*Client).Ping(0x140004fe240, {0x102f425a8, 0x1400020c230})
13:35:08 | tailscale.com@v1.48.0/derp/derphttp/derphttp_client.go:853 +0x16c
13:35:08 | tailscale.com/wgengine/magicsock.(*Conn).maybeCloseDERPsOnRebind.func1()
13:35:08 | tailscale.com@v1.48.0/wgengine/magicsock/derp.go:783 +0x78
13:35:08 | created by tailscale.com/wgengine/magicsock.(*Conn).maybeCloseDERPsOnRebind in goroutine 55699
13:35:08 | tailscale.com@v1.48.0/wgengine/magicsock/derp.go:780 +0x27c
```

**Comment by andrew-d** [comment]
Possibly related (but possibly not) https://github.com/golang/go/issues/61060

**Comment by raggi** [comment]
We're seeing quite a bit of this again. I found a single client log with a large number of different code paths for this, on 1.70. It feels like enough different code paths that it seems less likely that it's a caller bug. We've got stuff in control client, derp client, log upload, some mid tls handshake, some in close tls alert send, many mid stream.

Unless I'm missing something truly obvious, the only low criticality way we fault at fd_unix.go:380 (the wrapped syscall.Write below) with values of nn>0 is if the loop has iterated more than once:

```
// Write implements io.Writer.
func (fd *FD) Write(p []byte) (int, error) {
	if err := fd.writeLock(); err != nil {
		return 0, err
	}
	defer fd.writeUnlock()
	if err := fd.pd.prepareWrite(fd.isFile); err != nil {
		return 0, err
	}
	var nn int
	for {
		max := len(p)
		if fd.IsStream && max-nn > maxRW {
			max = nn + maxRW
		}
		n, err := ignoringEINTRIO(syscall.Write, fd.Sysfd, p[nn:max])
		if n > 0 {
			nn += n
		}
		if nn == len(p) {
			return nn, err
		}
		if err == syscall.EAGAIN && fd.pd.pollable() {
			if err = fd.pd.waitWrite(fd.isFile); err == nil {
				continue
			}
		}
		if err != nil {
			return nn, err
		}
		if n == 0 {
			return nn, io.ErrUnexpectedEOF
		}
	}
}```

`ignoringEINTRIO` assumes that EINTR implies n==0, which does not seem safe in our new EDR-ful universe, but again can't actually lead to the concrete cases that we're seeing, as nn is too large, not too small.

The slice header is being passed by value, so we have to assume, inline or wild bugs aside, that max := len(p) and max < maxRW, as such, max == len(p) at the slice event. Many of the call sites involved would generate values in the ranges we're seeing as subslice parameters, and so >maxRW is extremely unlikely.

So then nn has incremented beyond max, which the code can produce, and does not check. This suggests that libc / syscall, depending on build, are returning bad values for `n`. In our EDR-ful universe, this is more likely than it used to be, but is probably equally likely to a compiler/linker bug or a bug in stack handling somewhere.

If we're in either territory of compiler or stack corruption, then the issue of max correctness is back on the table, so perhaps we can at least estimate max correctness based on concrete values from our crash samples. Unfortunately every case we have does appear to be somewhere in a tls session, and without knowledge of the parameters it can be very difficult to estimate. We see a derp ping message with 54:35, 35 seems almost too small inside a tls record, and 54 just seems like an unusual value, though plausible for some suites. We have a tls alert message mid close to log collector at 26:24, and still not sufficiently tight to make an assertion with the info we have. we have a post handshake response out of handshake_client_tls13.go at 69:64. Some of these conns are going via control client, some via http2, some via http1, some through our controlbase conn setup, and some direct (like logprint).

The range of differences between nn:max seen in a larger sample of cases is:

```
[8, 8, 14, 17, 6, 6, 5, 19, 6, 14, 6, 6, 6, 2, 22, 14, 21, 8, 8, 27, 14, 16, 21, 3, 10, 6, 8, 22, 14, 10, 3, 2, 6, 15, 23, 21, 7, 5, 6, 6, 10, 9, 14, 16, 10, 14, 14]
```

It smells like the most plausible explanation here is incorrect values from write(2), intuition says compiler bugs should be showing up in more cases than we're seeing, especially given the broad spread across callers. If there's some software doing syscall level interception of TLS conns, it's sadly plausible it's doing something silly like passing the upstream write size of a mitm'd connection back down in response to write(2), which would approximate the kinds of size range variance that we're seeing. So far I don't think I've seen this error in a stack coming from the initial clienthello, yet i've seen stacks for all other major connection states.

I'm tempted to add some code to our Go to catch this case with some reasonable locality to the write and dump some more information so we can get stronger signal as to which side of write(2) the problem comes from, but also on macOS in particular to also log system extensions at that time.

thoughts?

cc @jwhited who was also looking at this some with me

**Comment by raggi** [comment]
for reference, internal link to the set of stacks i studied most closely this evening: https://paste.corp.ts.net/paste/54627a0d-93f6-42b4-a8c6-7c83d9e610b5. I also had a scan over the arm64 versions of poll write just in case, nothing stood out: https://paste.corp.ts.net/paste/95710e62-866b-46f4-adb0-0d9007fb7daa/raw
