### ISSUE TITLE
ipnlocal: Android crash

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#9132]
One of the top Android crashes in 1.48.1 from crash logs:

```
13:38:39 | panic: LocalBackend.assertClient: b.cc == nil
13:38:39 |  
13:38:39 | goroutine 158 [running]:
13:38:39 | tailscale.com/ipn/ipnlocal.(*LocalBackend).assertClientLocked(...)
13:38:39 | /build/go/pkg/mod/tailscale.com@v1.48.1/ipn/ipnlocal/local.go:3927
13:38:39 | tailscale.com/ipn/ipnlocal.(*LocalBackend).StartLoginInteractive(0x40008b5180)
13:38:39 | /build/go/pkg/mod/tailscale.com@v1.48.1/ipn/ipnlocal/local.go:2389 +0x1b8
13:38:39 | created by main.(*App).runBackend in goroutine 23
13:38:39 | /build/tailscale-android/cmd/tailscale/main.go:441 +0x644
```

/cc @maisem @DentonGentry @catzkorn

**Comment by DentonGentry** [comment]
> I’m seeing this error (I think it’s the error described here), sporadically but on an ongoing basis, on some alpine linux hosts.

It is really not possible to have Alpine Linux crash in `/build/tailscale-android/cmd/tailscale/main.go`.
If you can capture any information about an issue on Linux, please file a new bug.

**Comment by icebergtsn** [comment]
I also encountered this issue on my Android phone. Has this problem been fixed? If so, how was it fixed?
Is the pull request #10160 the commit that fixes this issue?
