### ISSUE TITLE
cmd/tailscaled: 600% CPU spin on macOS in race mode

### ISSUE THREAD

**Issue by bradfitz** [tailscale/tailscale#9209]
gVisor has some sadness on macOS in race mode, consuming all available CPU:

![Screenshot 2023-09-01 at 12 42 03 PM](https://github.com/tailscale/tailscale/assets/2621/32a1bb61-c75a-4bca-ae59-60e57e7096c6)

This is at 055fdb235f, which uses `gvisor.dev/gvisor v0.0.0-20230504175454-7b0a1988a28f`

/cc @maisem @raggi

**Comment by raggi** [comment]
Looks like gvisor.dev/pkg/sleep is bugged on macos on go1.21 with trace events enabled, for some reason we're constantly waking up in g selection, but runtime traces are also not working properly here, so it'll take some time to diagnose the diagnostic tools first. A debugger would probably do.

It might be worth reading through recent changes in the runtime scheduler and tracer to see what has changed.

We'd also do well to file an upstream bug, as if there's still someone around who remembers the guts, they'll be able to spot this faster. Perhaps @amscanne still remembers?

**Comment by bradfitz** [comment]
cc @prattmic too, who I saw committed something titled "Remove last remaining !go1.22 build tag" on July 21st, after our last update. But at first glance, https://github.com/google/gvisor/commit/f3e4a1fc3b4930c72a6316611931ae277e96ecca seems unrelated.

I'll try to bisect. Making a smaller repro than all of tailscaled might be tedious, but so might bisecting gvisor while updating to its API changes from tailscaled. I'll have to see which is less painful.

But if anybody has clues where to start from, let us know? Thanks!

**Comment by raggi** [comment]
>I'll try to bisect. Making a smaller repro than all of tailscaled might be tedious, but so might bisecting gvisor while updating to its API changes from tailscaled. I'll have to see which is less painful.

go test -race ./pkg/sleep in gvisor is sufficient, it hangs similarly.

**Comment by bradfitz** [comment]
Great! Only with Go 1.21 or earlier Go too? (Clearly I'm not at a computer :))

**Comment by raggi** [comment]
> Great! Only with Go 1.21 or earlier Go too? (Clearly I'm not at a computer :))

I only briefly tested 1.21

**Comment by prattmic** [comment]
You could try https://go.dev/cl/494185, which affects scheduling. I doubt it is the cause though since wakep doesn’t appear in the profile.

Also https://go.dev/cl/494185, which changed the signature of gopark. But it was just byte -> uint8 and the values were the same, so I think that is fine too.

**Comment by bradfitz** [comment]
It repros on Go 1.19, Go 1.20, and Go 1.21 on darwin/arm64 in race mode.

```
bradfitz@book1pro gvisor % git rev-parse HEAD
c2a7efe6a23072acfde99147bd8e81130500bff3
bradfitz@book1pro gvisor % ~/go/bin/go1.20.4 test -count=1 -race -v ./pkg/sleep
=== RUN   TestBlock
--- PASS: TestBlock (2.00s)
=== RUN   TestNonBlock
--- PASS: TestNonBlock (0.00s)
=== RUN   TestMultiple
--- PASS: TestMultiple (0.00s)
=== RUN   TestDoneFunction
--- PASS: TestDoneFunction (0.15s)
=== RUN   TestAssertFetch
...
```

Then 600-700% CPU.

SIGQUIT all like:

```
goroutine 140 [runnable]:
runtime.gopark(0x102a7ff58?, 0xc0001ab758?, 0x9?, 0x18?, 0x0?)
	/Users/bradfitz/sdk/go1.20.4/src/runtime/proc.go:364 +0x120 fp=0xc00058cdb0 sp=0xc00058cdb0 pc=0x102907c10
gvisor.dev/gvisor/pkg/sync.Gopark(0xc0001ab778?, 0x0?, 0x1?, 0x0?, 0x1?)
	/Users/bradfitz/hack/gvisor/pkg/sync/runtime_unsafe.go:33 +0x40 fp=0xc00058ce00 sp=0xc00058cdb0 pc=0x1029fe0d0
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).nextWaker(0xc0001ab740, 0x1, 0x1)
	/Users/bradfitz/hack/gvisor/pkg/sleep/sleep_unsafe.go:209 +0xec fp=0xc00058ce70 sp=0xc00058ce00 pc=0x102a019bc
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).fetch(0xc0003d0828?, 0xd0?, 0x32?)
	/Users/bradfitz/hack/gvisor/pkg/sleep/sleep_unsafe.go:256 +0x30 fp=0xc00058ceb0 sp=0xc00058ce70 pc=0x102a01b40
gvisor.dev/gvisor/pkg/sleep.(*Sleeper).AssertAndFetch(0xc00012406c?, 0x0?)
	/Users/bradfitz/hack/gvisor/pkg/sleep/sleep_unsafe.go:294 +0x38 fp=0xc00058cee0 sp=0xc00058ceb0 pc=0x102a01bc8
gvisor.dev/gvisor/pkg/sleep.TestAssertFetch.func2(0x56)
	/Users/bradfitz/hack/gvisor/pkg/sleep/sleep_test.go:366 +0x148 fp=0xc00058cfa0 sp=0xc00058cee0 pc=0x102a03398
gvisor.dev/gvisor/pkg/sleep.TestAssertFetch.func3()
	/Users/bradfitz/hack/gvisor/pkg/sleep/sleep_test.go:369 +0x48 fp=0xc00058cfd0 sp=0xc00058cfa0 pc=0x102a03218
runtime.goexit()
	/Users/bradfitz/sdk/go1.20.4/src/runtime/asm_arm64.s:1172 +0x4 fp=0xc00058cfd0 sp=0xc00058cfd0 pc=0x10293a404
created by gvisor.dev/gvisor/pkg/sleep.TestAssertFetch
	/Users/bradfitz/hack/gvisor/pkg/sleep/sleep_test.go:360 +0x148
```

**Comment by bradfitz** [comment]
Also at Go head:

```
bradfitz@book1pro gvisor % go version
go version devel go1.22-0cd473d97a Sat Sep 2 22:09:21 2023 +0000 darwin/arm64
bradfitz@book1pro gvisor % go test -count=1 -race -v ./pkg/sleep/
=== RUN   TestBlock
--- PASS: TestBlock (2.00s)
=== RUN   TestNonBlock
--- PASS: TestNonBlock (0.00s)
=== RUN   TestMultiple
--- PASS: TestMultiple (0.00s)
=== RUN   TestDoneFunction
--- PASS: TestDoneFunction (0.12s)
=== RUN   TestAssertFetch
(spin)
```

**Comment by bradfitz** [comment]
Backing git up to @amscanne's original https://github.com/google/gvisor/commit/9afac716b11767fcb8142606bbe6ddfefe89f65f and using to stable Go that was on that date (Dec 10, 2021), same:

```
bradfitz@book1pro gvisor % git rev-parse HEAD
9afac716b11767fcb8142606bbe6ddfefe89f65f
bradfitz@book1pro gvisor % ~/go/bin/go1.17.1  test -count=1 -race -v ./pkg/sleep
=== RUN   TestBlock
--- PASS: TestBlock (2.00s)
=== RUN   TestNonBlock
--- PASS: TestNonBlock (0.00s)
=== RUN   TestMultiple
--- PASS: TestMultiple (0.00s)
=== RUN   TestDoneFunction
--- PASS: TestDoneFunction (0.12s)
=== RUN   TestAssertFetch
(spin)
```

So it's not a regression. It just never worked and we hadn't noticed until now.

**Comment by bradfitz** [comment]
Confirmed that the spin started at https://github.com/google/gvisor/commit/9afac716b11767fcb8142606bbe6ddfefe89f65f

It works at the prior commit:

```
bradfitz@book1pro gvisor % git reset --hard HEAD^
HEAD is now at 4d29819e1 pipe: have separate notifiers for readers and writers
bradfitz@book1pro gvisor % ~/go/bin/go1.17.1  test -count=1 -race -v ./pkg/sleep
=== RUN   TestBlock
--- PASS: TestBlock (2.00s)
=== RUN   TestNonBlock
--- PASS: TestNonBlock (0.00s)
=== RUN   TestMultiple
--- PASS: TestMultiple (0.00s)
=== RUN   TestDoneFunction
--- PASS: TestDoneFunction (0.12s)
=== RUN   TestRace
--- PASS: TestRace (5.59s)
=== RUN   TestRaceInOrder
--- PASS: TestRaceInOrder (0.03s)
PASS
ok  	gvisor.dev/gvisor/pkg/sleep	7.932s
```

**Comment by bradfitz** [comment]
Ah. It's likely arm64 (Apple Silicon) specific. There's only amd64 (not arm64) support:

```
bradfitz@book1pro gvisor % git grep supportsWakeSuppression
pkg/sync/runtime_amd64.go:const supportsWakeSuppression = true
pkg/sync/runtime_other.go:const supportsWakeSuppression = false
pkg/sync/runtime_unsafe.go:     if supportsWakeSuppression {
pkg/sync/runtime_unsafe.go:     if supportsWakeSuppression && !wakep {
pkg/sync/runtime_unsafe.go:     if supportsWakeSuppression && !wakep {
```

I wonder if it also spins on linux/arm64 in race mode.
