### ISSUE TITLE
Slow throughput over tsnet compared to Windows tailscaled

### ISSUE THREAD

**Issue by tmm1** [tailscale/tailscale#9707]
### What is the issue?

I have a go http server that serves up https://github.com/librespeed/speedtest.

I made this server accessible on my tailnet, using both system tailscale (windows 1.50) and embedded tsnet.

On a remote node across the country where I am accessing the speedtest, I confirmed via `tailscale status` there's a direct connection to both IPs.

When I invoke the browser based speed test, the speeds shown on the system tailscale IP will stabilize after a few seconds and in my case measure 35mbps. Hitting the same server on the same node using its tsnet IP, the speeds never stabilize, keep dropping, and are near 4mbps at the end of the test.

cc @eric

### Steps to reproduce

full standalone repro to come

here are the gin-gonic routes being used to drive the speed test:

```go
	r.GET("/garbage", func(c *gin.Context) {
		c.Header("Content-Description", "File Transfer")
		c.Header("Content-Type", "application/octet-stream")
		c.Header("Content-Disposition", "attachment; filename=random.dat")
		c.Header("Content-Transfer-Encoding", "binary")
		ckSize, _ := strconv.ParseInt(c.Query("ckSize"), 10, 64)
		if ckSize == 0 || ckSize > 2048 {
			ckSize = 4
		}
		data := make([]byte, 1024*1024)
		io.ReadAtLeast(rand.Reader, data, len(data))
		for ckSize > 0 {
			_, err := c.Writer.Write(data)
			if err != nil {
				break
			}
			ckSize--
		}
	})

	r.GET("/empty", func(c *gin.Context) {
		c.Status(200)
	})
```

### Are there any recent changes that introduced the issue?

Not sure, but I upgraded tsnet from 1.48 to `main` (which includes a gvisor bump) and did not observe any improvement.

I also ran the same test against a linux and macos server and observed the same behavior where the speed declines continuously over tsnet

### OS

Windows

### OS version

Windows 11

### Tailscale version

1.51.0-dev20231007

**Comment by DentonGentry** [comment]
It isn't that surprising that the userspace TCP/IP stack doesn't achieve the same throughput as the Microsoft stack does. Though improvement in tsnet throughput is possible, I'd suggest that the system tailscale is likely to be faster for the foreseeable future.

If maximum throughput is important, more of the offloading code paths work when running on Linux.
- [Userspace isn't slow, some kernel interfaces are!](https://tailscale.com/blog/throughput-improvements/)
- [Surpassing 10Gb/s over Tailscale](https://tailscale.com/blog/more-throughput/)

**Comment by raggi** [comment]
I wonder if there's a new problem with selective ack, it'll be worth looking at a pcap.

**Comment by raggi** [comment]
I attempted to fetch what appears to be the expected worker js for your html page, but it didn't produce any useful output, and stopped testing after some number of requests, less than 100.

I made a quick server that responds with 0-65536 stable random bytes on request, that listens on both host:8080 and tsnet:80. I picked a not particularly fast server 75ms away from me:

These are 32kb response payloads:

```
~github/wg/wrk master % curl -s http://tsnetrandom/32768 | wc -c
32768
```

```
~github/wg/wrk master % ./wrk -c 6 http://tsnetrandom/32768
Running 10s test @ http://tsnetrandom/32768
  2 threads and 6 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    84.83ms    7.81ms 166.84ms   98.71%
    Req/Sec    35.46      8.31    60.00     82.14%
  699 requests in 10.01s, 21.93MB read
Requests/sec:     69.82
Transfer/sec:      2.19MB
```

```
~github/wg/wrk master * ./wrk -c 6 http://host:8080/32768
Running 10s test @ http://host:8080/32768
  2 threads and 6 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    81.04ms    7.40ms 161.17ms   99.04%
    Req/Sec    37.09     10.78    60.00     76.02%
  731 requests in 10.01s, 22.93MB read
Requests/sec:     73.01
Transfer/sec:      2.29MB
```

There's space for some BDP optimization here, but this VPS which is the one I had handy on the other side of the country is limited on throughput not too far off this:

```
Host link:
[ ID] Interval           Transfer     Bitrate         Retr
[  6]   0.00-10.00  sec  43.9 MBytes  36.8 Mbits/sec    2             sender
[  6]   0.00-10.07  sec  42.0 MBytes  35.0 Mbits/sec                  receiver

Over tailscale:
[ ID] Interval           Transfer     Bitrate         Retr
[  6]   0.00-10.00  sec  47.0 MBytes  39.4 Mbits/sec   18             sender
[  6]   0.00-10.09  sec  44.0 MBytes  36.6 Mbits/sec                  receiver
```

Importantly, dropping to 2kb which appears to be the size of requests being made by the worker code (if I found the right code), that won't leave enough in the pipeline over six conns at this latency:

host:
```
~github/wg/wrk master % ./wrk -c 6 http://host:8080/2048
Running 10s test @ http://host:8080/2048
  2 threads and 6 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    77.71ms    2.51ms  85.19ms   66.71%
    Req/Sec    38.38      9.62    60.00     74.75%
  763 requests in 10.01s, 1.57MB read
Requests/sec:     76.20
Transfer/sec:    160.15KB
```

tsnet:
```
~github/wg/wrk master % ./wrk -c 6 http://tsnetrandom/2048
Running 10s test @ http://tsnetrandom/2048
  2 threads and 6 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    79.41ms    2.85ms  87.95ms   53.22%
    Req/Sec    37.52      9.83    60.00     78.28%
  746 requests in 10.01s, 1.53MB read
Requests/sec:     74.51
Transfer/sec:    156.60KB
```

As you can see the request rate barely changed here, we're strictly latency bound.

I can't wholly explain the results you report, and there may yet be something more to dig into, but some amount of this, given the apparent test, may be expected - and the more important factor may be a spurious burst in the host environment.

One potentially relevant factor would be if you happen to have http2 over tls on the host side, which may be enabling pipelining that is not being done over tsnet if you're hosting a non-http2 service on tsnet.

**Comment by tmm1** [comment]
@eric pulled together the code we were using here: https://github.com/fancybits/tsnetspeedtest

the js file we're using apparently is quite old (from https://github.com/librespeed/speedtest/tree/752cf462b3176a4ed58252f14e73a73aac99e320)

further testing today suggests the issue is specific to Windows. when testing against a macOS server, the tsnet implementation was on-par or faster than system tailscale.

here's what i observed with a windows machine running the server. the screenshots are comparing system tailscale (top) vs tsnet.

**windows server in VA:**
```
PS C:\> & 'C:\Program Files\Go\bin\go.exe' install github.com/fancybits/tsnetspeedtest@latest
go: downloading github.com/fancybits/tsnetspeedtest v0.0.0-20231008210154-130aed47a0c2
go: downloading tailscale.com v1.50.1

PS C:\> ~\go\bin\tsnetspeedtest.exe
```

**mac client in VA:**

<img width="798" alt="Screenshot 2023-10-08 at 2 55 03 PM" src="https://github.com/tailscale/tailscale/assets/2567/62b0a7d3-4f5a-4e2f-ad27-b400aae265e4">

**mac client in CA:**

<img width="657" alt="Screenshot 2023-10-08 at 3 07 38 PM" src="https://github.com/tailscale/tailscale/assets/2567/c7c130ef-a889-4e36-a20f-e12b5f309012">

it appears tsnet performance on windows is quite poor, achieving only ~15% of throughput compared to the OS stack

**Comment by DentonGentry** [comment]
If you're willing to run Wireshark on the Windows system I imagine it would be illuminating. With the TCP/IP stack in userspace I don't think we have a straightforward way for Wireshark to see the unencrypted packets within the Wireguard tunnel, but even looking at the LAN interface would show if there is fragmentation or something similarly unexpected.

**Comment by DentonGentry** [comment]
Using a Windows 11 VM running https://github.com/fancybits/tsnetspeedtest, I get about 25 Mbps to tsnet. A time-sequence graph from wireshark is attached. Zooming way in we see a lot of selective ACK and retransmissions.

<img width="818" alt="Screenshot 2023-10-09 at 10 25 47 AM" src="https://github.com/tailscale/tailscale/assets/1140756/115b41a9-4e99-4261-a6ef-2d3f68ac631d">
<img width="828" alt="Screenshot 2023-10-09 at 10 26 45 AM" src="https://github.com/tailscale/tailscale/assets/1140756/f90c4d7a-60ac-433e-9614-c989c6a075b4">

--------

Using the LAN to the same VM achieves 500 Mbps. A time-sequence graph shows no significant retransmissions.

<img width="824" alt="Screenshot 2023-10-09 at 10 33 26 AM" src="https://github.com/tailscale/tailscale/assets/1140756/56b2d14b-eda0-45f9-8dd1-916b8c1f0aae">

<img width="825" alt="Screenshot 2023-10-09 at 10 34 20 AM" src="https://github.com/tailscale/tailscale/assets/1140756/2db4c751-d4a1-4b9c-a98c-4b3ab23e684c">

**Comment by DentonGentry** [comment]
With Linux as the tsnetspeedtest host, running over tsnet shows relatively few retransmissions and duplicates. Throughput isn't quite equal to the LAN throughput but is within 25%:

<img width="820" alt="Screenshot 2023-10-09 at 1 45 55 PM" src="https://github.com/tailscale/tailscale/assets/1140756/49acbeb9-a7b3-47ce-af14-1e7fbc193428">

<img width="823" alt="Screenshot 2023-10-09 at 1 46 25 PM" src="https://github.com/tailscale/tailscale/assets/1140756/5252a227-0e97-4fd7-886a-c3c0a8a14349">

--------

The LAN shows a few dropped packets, and overall throughput is good:

<img width="826" alt="Screenshot 2023-10-09 at 1 48 54 PM" src="https://github.com/tailscale/tailscale/assets/1140756/fc144260-a065-44b4-aeb4-55e8846c6ffd">

<img width="832" alt="Screenshot 2023-10-09 at 1 49 13 PM" src="https://github.com/tailscale/tailscale/assets/1140756/1786282e-7f4d-4391-8e48-dfa7bb805f90">

**Comment by tmm1** [comment]
Thanks @DentonGentry, glad to see you were able to reproduce! 25mbps vs 500mbps is quite the difference over LAN.

We poked around wireshark yesterday, but weren't aware of these views; so thanks for sharing.

What do the SACKs and retransmits indicate? That the Windows server is dropping outgoing UDP packets?

We updated tsnetspeedtest to use `tailscale.com@main`, which brings in an newer gVisor with https://github.com/google/gvisor/issues/6113#issuecomment-1751179726. The results are the same however.

**Comment by DentonGentry** [comment]
The Windows machine appears to be retransmitting packets which shouldn't need to be retransmitted.

The test setup is a brrowser on a Mac connecting over Tailscale to the tsspeedtest app running on Windows. The pcaps are gathered on the Mac, where we have a full Tailscale installed using a tun device where we can capture the cleartext content inside the Wireguard tunnel. We don't have a way to get a pcap of the cleartext from inside the tsnet app on Windows.

This is called a time-sequence graph, which shows packets transmitted as vertical lines, and the ACK going back as horizontal. It can be found in the Wireshark Statistics -> TCP Stream Graph selection.
  
<img width="1315" alt="Screenshot 2023-10-09 at 5 31 51 PM" src="https://github.com/tailscale/tailscale/assets/1140756/a0b15694-ab9f-4511-a38c-49034cce01c9">


The red lines are four packets which the Windows machine decided to retransmit for unclear reasons. The Mac had sent back an ACK, but the Windows system retransmitted anyway. The Windows system appears to either be losing ACKs, or at least is very tardy in processing them.

Packet dissections from the PCAP of the retransmission marked "A" are show below.
- Packet 5284 is the first vertical line where the Windows system sent a chunk of data for the first time.
- Packet 5289 is the ACK from the Mac back to Windows.
- Packet 5332 is the Windows system retransmitting the packet, which should have already been successfully acknowledged.
- Packet 5334 is the Mac sending another ACK for the retransmission.
- Packet 5335 is the Mac re-sending the ACK yet again, presumably for for good measure. 

```
No.     Time           Source                Destination           Protocol Length Info
   5284 28.940318      100.71.236.150        100.100.165.16        TCP      1252   80 → 55535 [ACK] Seq=800897 Ack=393 Win=524288 Len=1200 TSval=3710253163 TSecr=2922268938 [TCP segment of a reassembled PDU]

Frame 5284: 1252 bytes on wire (10016 bits), 1252 bytes captured (10016 bits) on interface utun5, id 0
Raw packet data
Internet Protocol Version 4, Src: 100.71.236.150, Dst: 100.100.165.16
Transmission Control Protocol, Src Port: 80, Dst Port: 55535, Seq: 800897, Ack: 393, Len: 1200

No.     Time           Source                Destination           Protocol Length Info
   5289 28.940389      100.100.165.16        100.71.236.150        TCP      52     55535 → 80 [ACK] Seq=393 Ack=802097 Win=512960 Len=0 TSval=2922268946 TSecr=3710253163

Frame 5289: 52 bytes on wire (416 bits), 52 bytes captured (416 bits) on interface utun5, id 0
Raw packet data
Internet Protocol Version 4, Src: 100.100.165.16, Dst: 100.71.236.150
Transmission Control Protocol, Src Port: 55535, Dst Port: 80, Seq: 393, Ack: 802097, Len: 0

No.     Time           Source                Destination           Protocol Length Info
   5332 28.948753      100.71.236.150        100.100.165.16        TCP      1252   [TCP Spurious Retransmission] 80 → 55535 [ACK] Seq=800897 Ack=393 Win=524288 Len=1200 TSval=3710253171 TSecr=2922268944

Frame 5332: 1252 bytes on wire (10016 bits), 1252 bytes captured (10016 bits) on interface utun5, id 0
Raw packet data
Internet Protocol Version 4, Src: 100.71.236.150, Dst: 100.100.165.16
Transmission Control Protocol, Src Port: 80, Dst Port: 55535, Seq: 800897, Ack: 393, Len: 1200

No.     Time           Source                Destination           Protocol Length Info
   5334 28.948772      100.100.165.16        100.71.236.150        TCP      64     [TCP Dup ACK 5289#2] 55535 → 80 [ACK] Seq=393 Ack=802097 Win=512960 Len=0 TSval=2922268955 TSecr=3710253163 SLE=798497 SRE=800897

Frame 5334: 64 bytes on wire (512 bits), 64 bytes captured (512 bits) on interface utun5, id 0
Raw packet data
Internet Protocol Version 4, Src: 100.100.165.16, Dst: 100.71.236.150
Transmission Control Protocol, Src Port: 55535, Dst Port: 80, Seq: 393, Ack: 802097, Len: 0

No.     Time           Source                Destination           Protocol Length Info
   5335 28.948791      100.100.165.16        100.71.236.150        TCP      64     [TCP Dup ACK 5289#3] 55535 → 80 [ACK] Seq=393 Ack=802097 Win=512960 Len=0 TSval=2922268955 TSecr=3710253171 SLE=800897 SRE=802097

Frame 5335: 64 bytes on wire (512 bits), 64 bytes captured (512 bits) on interface utun5, id 0
Raw packet data
Internet Protocol Version 4, Src: 100.100.165.16, Dst: 100.71.236.150
Transmission Control Protocol, Src Port: 55535, Dst Port: 80, Seq: 393, Ack: 802097, Len: 0
```

**Comment by eric** [comment]
> The Windows machine appears to be retransmitting packets which shouldn't need to be retransmitted.

When you say "Windows", are you meaning that the Windows OS is re-sending a UDP packet again? Excuse my ignorance about Wireshark, but if the same UDP packet was sent again, would that manifest itself in seeing that TCP packet inside the tunnel, or would that be suppressed by the receiver because it had already seen it?

I'm trying to understand if it is more likely this issue is coming from Windows itself or gvizor.

**Comment by DentonGentry** [comment]
There is no mechanism by which Windows would retransmit a UDP packet, UDP is send-and-forget. The retransmission is gvisor within the tsnet app deciding to re-send a TCP packet.

Because there is clearly some sort of Windows involvement in the result, my guess would be that either:
- Windows is losing small UDP frames containing the ACKs back from the Mac. The pcap is gathered on the Mac, which only knows that it saw them going out and doesn't know whether Windows received them.
- Windows is delaying small UDP frames containing the ACKs back from the Mac.
- Something in goroutine scheduling specific to Windows is resulting in not processing the ACKs in a timely way.

**Comment by raggi** [comment]
There's definitely some kind of bug in the flow with gvisor, and it is significantly worsened with SACK enabled. The results are also skewed when RACK is enabled, but disabling both does not result in satisfactory statistics on a local link.

I still for example see ~15k fast retransmits over a run with both RACK and SACK disabled. Disabling SACK will however improve throughput by 60-100%, depending on some other luck - this effectively mitigates part of the problem, but it's not a solution.

I suspect this probably is also happening on Linux as well, but the impact may be lower.

I've not yet validated the part that this may not be occurring when running in privileged mode, certainly I would expect to have noticed if it was occurring in tun mode. There is no platform specific code on the gvisor side related to timers and retries, intuitions suggests this may be an issue with unprivileged userspace failing to set socket buffers and then bursting far too much traffic. What isn't immediately obvious from that theory is why the window size doesn't eventually get this under control, as retransmits continue throughout a test run. Plenty to look into still.

cc @jwhited who will also be interested in this.

**Comment by tmm1** [comment]
>intuitions suggests this may be an issue with unprivileged userspace failing to set socket buffers and then bursting far too much traffic

I guess this should be easy to validate.

Is this the place where the buffers are adjusted? Or would it be in gvisor somewhere?

https://github.com/tailscale/tailscale/blob/b1867eb23f140b66bc5aba311763192e741b3bf6/wgengine/magicsock/magicsock.go#L2750-L2756

https://github.com/tailscale/tailscale/blob/b1867eb23f140b66bc5aba311763192e741b3bf6/wgengine/magicsock/magicsock.go#L74-L77

**Comment by raggi** [comment]
Yup, that's the spot!

**Comment by eric** [comment]
We are not seeing those `magicsock: ` error messages that would make it seem like the issue is that we are failing to set the buffer size. Does anyone have any other ideas on how to resolve this? It's greatly impacting our Windows users.

**Comment by eric** [comment]
Is there any chance we could get progress here? If not, we'll need to document in the Channels DVR that our in-app integration has poor performance on Windows.

**Comment by DentonGentry** [comment]
You'll need to decide how to proceed, I do not have an ETA to commit when this will be resolved nor whether it will be in time for your launch.

--------

https://github.com/tailscale/tailscale/pull/10377 proposes to add a Pcap capture facility to tsnet. Using that, we can capture packets on both the Mac system serving as a client and on the Win11 system hosting `tsnetspeedtest`. By doing so we can zoom in to the same point in the TCP connection as seen by each side of the connection.

<img width="1285" alt="b9707 mac TSG" src="https://github.com/tailscale/tailscale/assets/1140756/dd2b2e4b-dbc1-4c58-836c-ed54541247b2">
<img width="1281" alt="b9707 tsnet TSG" src="https://github.com/tailscale/tailscale/assets/1140756/e4e08b7b-c4a2-4acc-95e9-53a40ddaf315">

One of the big differences we see is in the timing of ACKs.
- the Mac sees itself as sending ACKs promptly upon processing the incoming frames
- the tsnet server sees the ACKs long enough delayed that it frequently decides to retransmit before the ACK can be processed

**Comment by DentonGentry** [comment]
https://github.com/tailscale/tailscale/issues/9707#issuecomment-1760804551

I don't see errors in the log output about setting UDP socket buffer sizes.
https://github.com/tailscale/tailscale/blob/b1867eb23f140b66bc5aba311763192e741b3bf6/wgengine/magicsock/magicsock.go#L2750-L2756

**Comment by eric** [comment]
Here's a pcap capture from a Windows VM:

[windows-2.pcap.gz](https://github.com/tailscale/tailscale/files/13463116/windows-2.pcap.gz)

**Comment by eric** [comment]
Here's a capture of both sides.

The mac side was captured with:

     $ sudo tcpdump -l -w macos-3.pcap -i any host tsnetspeedtest-windows-arm64

[macos-3.pcap.gz](https://github.com/tailscale/tailscale/files/13463123/macos-3.pcap.gz)
[windows-3.pcap.gz](https://github.com/tailscale/tailscale/files/13463124/windows-3.pcap.gz)

**Comment by DentonGentry** [comment]
Traffic is being generated by the tsnet app to send to the Mac.
The Mac receives the frames and generates ACKs back to tsnet.

1/
Looking at the tsnet app sending packets, to the left of the 1.08 second timestamp, we see tsnet send a burst of four packets followed a short time later by a  burst of three packets.
<img width="1281" alt="b9707 tsnet TSG" src="https://github.com/tailscale/tailscale/assets/1140756/434560c6-1bfe-491b-a1cb-268b5faefc61">

--------

2/
Looking at the Mac between 1.2 and 1.205 seconds:
<img width="1285" alt="b9707 mac TSG" src="https://github.com/tailscale/tailscale/assets/1140756/d919162b-a63e-474a-90f4-31c1f6d1280d">
The timestamps are relative to the start of the capture and not synchronized between the Mac and tsnet systems, don't pay attention to 1.08 versus 1.2 seconds.

- The Mac receives four packets, and generates an ACK which goes out almost immediately.
- The Mac receives three more packets a short time later, and generates another ACK almost immediately.

--------

3/
Looking at tsnet again, the ACKs sent by the MAC are not received until almost 1.086. Zooming in on that timestamp:

<img width="529" alt="b9707 tsnet TSG zoomed in" src="https://github.com/tailscale/tailscale/assets/1140756/9be0322c-ad9a-430b-a83e-9f6709fb3912">

- We see tsnet decide to retransmit all seven packets, the set of four and the set of three. It also sends a couple more, fresh packets.
- At that **very instant** it receives an ACK for seven frames.

Clearly this was the ACKs for four packets and for three packets which the Mac sent some time ago in response to receiving the first transmission of these packets. They can't possibly arrive instantaneously after retransmitting, the ACKs must have been sitting in a queue waiting to be processed.

To me it looks like tsnet is only processing ACKs when it decides to transmit something, so it finally receives the ACK after already having decided to retransmit. The retransmission is unnecessary.

**Comment by DentonGentry** [comment]
I added a runtime/debug PrintBackTrace() in injectInbound(), to be sure of how it was being called.

The backtrace is:
```
2023/11/25 11:11:50 [v2] packet in (from 100.100.165.16:49170): 45 00 00 28 9e f2 00 00 40 06 31 5b 64 64 a5 10 64 63 3c ab c0 12 00 50 39 ad 35 5f 00 00 00 00 50 04 00 00 d5 ee 00 00
goroutine 411 [running]:
runtime/debug.Stack()
        C:/Program Files/Go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        C:/Program Files/Go/src/runtime/debug/stack.go:16 +0x13
tailscale.com/wgengine/netstack.(*Impl).injectInbound(0xc000136840, 0xc0001d2a90, 0xc0001d0630?)
        C:/Users/DGentry/go/pkg/mod/tailscale.com@v1.1.1-0.20231125190428-20fa0b3d59f9/wgengine/netstack/netstack.go:752 +0x848
tailscale.com/net/tstun.(*Wrapper).filterPacketInboundFromWireGuard(0xc000226420, 0xc0001d2a90, 0xc0006842f0?)
        C:/Users/DGentry/go/pkg/mod/tailscale.com@v1.1.1-0.20231125190428-20fa0b3d59f9/net/tstun/wrap.go:1050 +0x785
tailscale.com/net/tstun.(*Wrapper).Write(0xc000226420, {0xc0001198c0, 0x1, 0x1}, 0x10)
        C:/Users/DGentry/go/pkg/mod/tailscale.com@v1.1.1-0.20231125190428-20fa0b3d59f9/net/tstun/wrap.go:1070 +0x234
github.com/tailscale/wireguard-go/device.(*Peer).RoutineSequentialReceiver(0xc00061c300, 0x1)
        C:/Users/DGentry/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20231121184858-cc193a0b3272/device/receive.go:525 +0x2ff
created by github.com/tailscale/wireguard-go/device.(*Peer).Start in goroutine 409
        C:/Users/DGentry/go/pkg/mod/github.com/tailscale/wireguard-go@v0.0.0-20231121184858-cc193a0b3272/device/peer.go:209 +0x2e5
```

This calls netstack.go:injectInboud():
https://github.com/tailscale/tailscale/blob/d5d84f1a68dc9495ed7b91b4655a869268ac3cfd/wgengine/netstack/netstack.go#L710

which calls ns.linkEP.InjectInbound() to send the packet in to netstack:
https://github.com/tailscale/tailscale/blob/d5d84f1a68dc9495ed7b91b4655a869268ac3cfd/wgengine/netstack/netstack.go#L753

**Comment by jwhited** [comment]
@tmm1 & @eric - can you re-test with https://github.com/tailscale/tailscale/commit/5e861c38718ffcde3ded6d2922ca464886e41321 or later? This commit improves performance significantly in my local testing of tsnet on Windows. 

The results I gathered from before the change aligns with @DentonGentry's findings in that gVisor appears to be slow to handle ACKs, or possibly mishandles them until one w/SACK option is seen. Without TCP RACK this behavior is less apparent as seen via less spurious retransmissions, and higher throughput.

**Comment by eric** [comment]
@jwhited This looks a lot better! I just tested it (obviously couldn't capture a pcap) and it was a lot better speeds.

**Comment by DentonGentry** [comment]
I think this is as far as we're going to be able to take it for now. We'd need to have a full team of engineers go dig into netstack at this point and then push any fixes upstream, and right now we don't have staff available to do that. It will be a while before we can do significantly more work on tsnet throughput for Windows.

**Comment by jwhited** [comment]
In 1.72 we increased gVisor's TCP send & receive buffers, which can increase throughput for high latency paths. 

@tmm1 & @eric: if this is still relevant for your use cases we would appreciate any 1.72 performance testing feedback. Assuming things still look nominal or are improved we will probably close this issue.

We will still be working on performance improvements, but for the sake of scoping this issue, I believe we've made a decent leap.

**Comment by raggi** [comment]
https://github.com/google/gvisor/pull/14492
