### ISSUE TITLE
Mac client occasionally blocks all internet traffic when using an exit node

### ISSUE THREAD

**Issue by mpoindexter** [tailscale/tailscale#9875]
### What is the issue?

When using an exit node, my Mac device occasionally stops routing all traffic and DNS queries hang.

In all cases, the hang seems correlated with log entries indicating that DERP connections cannot be established, and connection timeouts showing attempted connections to DERP nodes over the tunnel. For example:

`magicsock: derp.Send(127.3.3.40:10): derphttp.Client.Send connect to region 10 (sea): context canceled: context canceled`
and later
`magicsock: derp.Send(127.3.3.40:10): derphttp.Client.Send connect to region 10 (sea): context deadline exceeded`
and
`open-conn-track: timeout opening (TCP 100.64.0.2:50279 => 192.73.252.134:443) to node [3fR7b]; online=yes, lastRecv=1m13s`
where `192.73.252.134` appears to be a DERP node (`derp2e.tailscale.com`)

dumping the goroutines of the daemon while the connection is hung reveals a large number of routines hung in connecting including a large number of DNS routines and these:

```
goroutine 197298 [select]:
tailscale.com/logtail/backoff.(*Backoff).BackOff(0x1400092dec8, {0x104ca5480, 0x140011dedc0}, {0x104c9b418?, 0x14001df7ea0?})
	tailscale.com@v1.50.1/logtail/backoff/backoff.go:76 +0x1f8
tailscale.com/wgengine/magicsock.(*Conn).runDerpReader(0x14000442000, {0x104ca5480, 0x140011dedc0}, {{{0x0?, 0xffff7f030328?}, 0x14000128000?}, 0x2?}, 0x14000f467e0, 0x1400079c3e0?, 0x140024d1b60)
	tailscale.com@v1.50.1/wgengine/magicsock/derp.go:502 +0xedc
created by tailscale.com/wgengine/magicsock.(*Conn).derpWriteChanOfAddr in goroutine 197186
	tailscale.com@v1.50.1/wgengine/magicsock/derp.go:380 +0xc64
```

```
goroutine 196127 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x140004eb268?, 0x60?, 0x8?)
	runtime/sema.go:77 +0x28
sync.(*Mutex).lockSlow(0x140005aa760)
	sync/mutex.go:171 +0x174
sync.(*Mutex).Lock(...)
	sync/mutex.go:90
tailscale.com/derp/derphttp.(*Client).connect(0x140005aa6c0, {0x104ca52f8, 0x105241120}, {0x1049243bc, 0x14})
	tailscale.com@v1.50.1/derp/derphttp/derphttp_client.go:285 +0xb4
tailscale.com/derp/derphttp.(*Client).RecvDetail(0x140004ebec8?)
	tailscale.com@v1.50.1/derp/derphttp/derphttp_client.go:1000 +0x3c
tailscale.com/wgengine/magicsock.(*Conn).runDerpReader(0x14000442000, {0x104ca5480, 0x1400174d5e0}, {{{0x0?, 0xffff7f030328?}, 0x14000128000?}, 0xa?}, 0x140005aa6c0, 0x14000d6d0b0?, 0x1400243e480)
	tailscale.com@v1.50.1/wgengine/magicsock/derp.go:474 +0x358
created by tailscale.com/wgengine/magicsock.(*Conn).derpWriteChanOfAddr in goroutine 193337
	tailscale.com@v1.50.1/wgengine/magicsock/derp.go:380 +0xc64
```

```
goroutine 196128 [select]:
tailscale.com/derp/derphttp.(*Client).dialNode(0x140005aa6c0, {0x104ca54f0, 0x14002630070}, 0x14000599710)
	tailscale.com@v1.50.1/derp/derphttp/derphttp_client.go:707 +0x354
tailscale.com/derp/derphttp.(*Client).dialRegion(0x104932937?, {0x104ca54f0, 0x14002630070}, 0x140002485f0)
	tailscale.com@v1.50.1/derp/derphttp/derphttp_client.go:558 +0x148
tailscale.com/derp/derphttp.(*Client).connect(0x140005aa6c0, {0x104ca52f8, 0x105241120}, {0x104924394, 0x14})
	tailscale.com@v1.50.1/derp/derphttp/derphttp_client.go:375 +0xbb8
tailscale.com/derp/derphttp.(*Client).Send(0x14000de86c8?, {{0xdd, 0xf4, 0x7b, 0x6c, 0xde, 0xb0, 0x5a, 0x94, 0x3a, ...}}, ...)
	tailscale.com@v1.50.1/derp/derphttp/derphttp_client.go:798 +0x48
tailscale.com/wgengine/magicsock.(*Conn).runDerpWriter(0x14000442000, {0x104ca5480, 0x1400174d5e0}, 0x104c9eb1a?, 0x14000e90cc0, 0xffff64400001?, 0x1400243e480)
	tailscale.com@v1.50.1/wgengine/magicsock/derp.go:606 +0x170
created by tailscale.com/wgengine/magicsock.(*Conn).derpWriteChanOfAddr in goroutine 193337
	tailscale.com@v1.50.1/wgengine/magicsock/derp.go:381 +0xd10
```

In some cases, disabling the exit node or exiting Tailscale fixes the problem, in others a machine reboot is required. My guess is that somehow there are cases in which traffic destined for DERP nodes is attempted to be sent over the tunnel, which fails because the existing connections are broken, but no new connections can be established because the traffic to DERP nodes is incorrectly being sent over the tunnel.

Interestingly, in this case it seems like remote nodes are still pingable via `tailscale ping 100.64.0.1`, but attempting to contact `100.64.0.1` via any IP level tools fails.

In some cases, the situation resolves itself after an extended period (10+ minutes), and in others it never does. When it does manage to recover on its own, it seems like lines line `magicsock: derp-2 connected; connGen=1` immediately precede recovery.

The following issues seem to describe similar symptoms that might be related.
https://github.com/tailscale/tailscale/issues/1134
https://github.com/tailscale/tailscale/issues/8223

### Steps to reproduce

There are a few ways to reproduce, all seem linked and produce similar log entries and goroutine dumps:
1. [Sometimes] Just use Tailscale while connected for a while. Approximately once every couple of days (seems unrelated to how long the VPN has been connected) all DNS and internet traffic will just hang.
2. [Sometimes] Let the machine sleep and wake while connected to WLAN and ethernet simultaneously
3. [Sometimes] Connect on WLAN, then plug in an ethernet connection
4. [Almost Always] Connect on ethernet with WLAN active, then unplug ethernet cable

### OS

macOS

### OS version

Ventura 13.6

### Tailscale version

1.50.1

### Other software

Bitdefender Antivirus

**Comment by mpoindexter** [comment]
For anyone trying to figure out similar behavior on mac, this was caused by Bitdefender AV. Bitdefender uses a Transparent Proxy network extension to intercept HTTPS traffic so it can be scanned. When the Bitdefender network extension intercepts a https connection, it MITM's it, and creates a new outbound connection to the original host. This new connection bypasses all the work Tailscale did to bind the connection to the correct interface, and so the connection is routed over the tunnel.

I was able to work around by excluding the Tailscale extension from being subject to such interception. It seems like if the Mac Tailscale client were to add DERP nodes and the control server to the set of routes excluded from being routed over the VPN it would prevent problems of this type in the future.
